### PR TITLE
[common/meta] refactor: move async-raft to datafuselabs/openraft

### PR DESCRIPTION
**Pull request by drmingdrmer**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Changelog

- Improvement

## Related Issues

### CODE REVIEW

**Review by ariesdevil — APPROVED** [review]
Nice shot

**Comment by BohuTANG** [comment]
The CI is broken, wait it work again :\

**Comment by BohuTANG** [comment]
Does the openraft will be published as crate in the future? (cc @drmingdrmer )

**Comment by drmingdrmer** [comment]
> Does the openraft will be published as crate in the future? (cc @drmingdrmer )

It's an option indeed.

**Comment by BohuTANG** [comment]
@mergify update

**Comment by BohuTANG** [comment]
@mergify update

**Comment by BohuTANG** [comment]
The ci failure is not related to this PR, let's merge :rocket:

**Pull request merged**
