### PR TITLE
refactor(meta): Cmd utilize XXXReq.

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

## Changelog

- Not for changelog (changelog entry is not required)

## Related Issues

Fixes https://github.com/datafuselabs/databend/issues/4834

### CODE REVIEW

**Comment by youngsofun** [comment]
why ci run only 3 checks ?

**Comment by BohuTANG** [comment]
Oops, not sure.
Here should ping the dad of the CI @Xuanwo

**Comment by Xuanwo** [comment]
> why ci run only 3 checks ?

I'm not sure, maybe something internal error happens so GHA missing our commit events.

Re-run all checks seems a useful workaround.

**Comment by youngsofun** [comment]
>  Re-run all checks seems a useful workaround.

yes, it return to normal after I push again

**Review by drmingdrmer — APPROVED** [review]
Oh my... I love nothing more than the reduction of LOC!!!

**Comment by drmingdrmer** [comment]
It seems the metactl test should be updated in accord.

**Comment by youngsofun** [comment]
@drmingdrmer 

It should be fixed by replace field name in meta.json.
I`m writing a simple python to do the translation.

but here we can stop a while to choose the better field name style:

from this file we can see the field name of `XXXCmd`  and `XXXReq`, which do you prefer:
https://github.com/datafuselabs/databend/blob/main/common/meta/types/src/cmd.rs

**Comment by drmingdrmer** [comment]
> `db` or `table` is used to represent a table instance, such as `Arc<dyn Table>`.
> In the files about `category`, there are some name conflict IMHO.
> Thus I prefer a suffix `_name` to let readers know it is more like a `String`.

But Indeed, naming is not a critical issue. Choose a style you feel comfortable with.:)

**Comment by youngsofun** [comment]
not `_meta*` dir, after `RUST_TEST_THREADS=2 cargo test --package databend-meta `.

and the following 2 always fail

```
    meta_node::meta_node_all::test_meta_node_snapshot_replication
    meta_node::meta_node_kv_api::test_meta_node_kv_api
```

**Comment by drmingdrmer** [comment]
Sorry my mistake. It should be `make stateless-cluster-test` to produce a `_meta*` dir.

Let have a look at the failure of the two case.

**Comment by youngsofun** [comment]
```


---- meta_node::meta_node_all::test_meta_node_snapshot_replication stdout ----
Error: timeout after 10s when non-voter replicated all logs .last_log_index -> Some(15) latest: Metrics{id:1,Learner, term:1, last_log:None, last_applied:None, leader:Some(0), membership:{log_id:0-0 membership:[{1}]}, snapshot:None, replication:
thread 'meta_node::meta_node_all::test_meta_node_snapshot_replication' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/test/src/lib.rs:186:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- meta_node::meta_node_all::test_meta_node_write_to_local_leader stdout ----
Error: timeout after 10s when add :2 .last_log_index -> Some(4) latest: Metrics{id:2,Learner, term:1, last_log:None, last_applied:None, leader:Some(0), membership:{log_id:0-0 membership:[{2}]}, snapshot:None, replication:
thread 'meta_node::meta_node_all::test_meta_node_write_to_local_leader' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/test/src/lib.rs:186:5

---- meta_node::meta_node_all::test_meta_node_add_database stdout ----
Error: timeout after 10s when  .last_applied -> Some(7) latest: Metrics{id:1,Follower, term:1, last_log:Some(7), last_applied:Some(LogId { term: 1, index: 6 }), leader:Some(0), membership:{log_id:1-7 membership:[{0, 1, 2}]}, snapshot:None, replication:
thread 'meta_node::meta_node_all::test_meta_node_add_database' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/test/src/lib.rs:186:5

---- grpc::metasrv_grpc_kv_api::test_metasrv_kv_api stdout ----
Error: raft stopped

Caused by:
    raft stopped
thread 'grpc::metasrv_grpc_kv_api::test_metasrv_kv_api' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/test/src/lib.rs:186:5

```

**Comment by drmingdrmer** [comment]
Right. These tests are somehow flaky...

**Comment by youngsofun** [comment]
@drmingdrmer  



```
pub struct TableMeta {
    pub schema: Arc<DataSchema>,
    pub engine: String,
    pub engine_options: HashMap<String, String>,
    pub options: HashMap<String, String>,
    pub created_on: DateTime<Utc>,
}
```

the order of  items in HashMap is random, should I change it to BTreeMap?

or  use this method: https://stackoverflow.com/questions/42723065/how-to-sort-hashmap-keys-when-serializing-with-serde


```
       "options": {
            "snapshot_location": "13/56/_ss/9bb26c300a1d4936a6d03de844938ece_v1.json",
            "database_id": "13"
          },
```

**Comment by drmingdrmer** [comment]
> @drmingdrmer
> 
> ```
> pub struct TableMeta {
>     pub schema: Arc<DataSchema>,
>     pub engine: String,
>     pub engine_options: HashMap<String, String>,
>     pub options: HashMap<String, String>,
>     pub created_on: DateTime<Utc>,
> }
> ```
> 
> the order of items in HashMap is random, should I change it to BTreeMap?
> 
> or use this method: https://stackoverflow.com/questions/42723065/how-to-sort-hashmap-keys-when-serializing-with-serde
> 
> or make the check not depend on it?
> 
> ```
>        "options": {
>             "snapshot_location": "13/56/_ss/9bb26c300a1d4936a6d03de844938ece_v1.json",
>             "database_id": "13"
>           },
> ```

I'll always prefer a `BTreeMap` to `HashMap` if the performance is not a concern. :)

It makes tests much easier to be done.

**Comment by Xuanwo** [comment]
> It makes tests much easier to be done.

I'm curious about why. Can you explain it in a bit more detail? Thanks.

**Comment by Xuanwo** [comment]
> or make the check not depend on it?

`HashMap` implements `Eq`. How about compare with a `HashMap` directly instead the raw content?

**Comment by drmingdrmer** [comment]
> > or make the check not depend on it?
> 
> `HashMap` implements `Eq`. How about comparing with a `HashMap` directly instead of the raw content?

In this case, the test is trying to compare two serialized strings :(

**Comment by youngsofun** [comment]
> HashMap implements Eq. How about comparing with a HashMap directly instead of the raw content?

`make metactl-test` compare dumped json log files

**Comment by youngsofun** [comment]
after change xxx_options from hashmap to btreemap.  
seems `make metactl-test` result in error in  log entry seqs

```
killall databend-meta 
killall databend-query
rm -rf _logs*
rm -rf _meta*
make stateless-cluster-test
killall databend-meta 
./target/debug/databend-metactl --export --raft-dir "_meta2" > tests/metactl/meta.json

```

```
make metactl-test

```

only sees Info logs

**Pull request merged**
