### PR TITLE
refactor(session): Remove `SessionRef`

### PR DESCRIPTION
**Pull request by ariesdevil**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Remove `SessionRef` for simplify codes.

Fixes #issue

### CODE REVIEW

**Comment by BohuTANG** [comment]
```
 cargo fmt --all -- --check
Diff in /workspace/query/tests/it/tests/context.rs at line 45:
     let dummy_session = sessions.create_session(SessionType::Dummy).await?;
 
     // Set user with all privileges
-    let mut user_info = UserInfo::new(
-        "root",
-        "127.0.0.1",
-        AuthInfo::Password {
-            hash_method: PasswordHashMethod::Sha256,
-            hash_value: Vec::from("pass"),
-        },
-    );
+    let mut user_info = UserInfo::new("root", "127.0.0.1", AuthInfo::Password {
+        hash_method: PasswordHashMethod::Sha256,
+        hash_value: Vec::from("pass"),
+    });
     user_info.grants.grant_privileges(
         &GrantObject::Global,
         UserPrivilegeSet::available_privileges_on_global(),
Diff in /workspace/query/tests/it/tests/context.rs at line 75:
     let sessions = SessionManagerBuilder::create_with_conf(config.clone()).build()?;
     let dummy_session = sessions.create_session(SessionType::Dummy).await?;
 
-    let mut user_info = UserInfo::new(
-        "root",
-        "127.0.0.1",
-        AuthInfo::Password {
-            hash_method: PasswordHashMethod::Sha256,
-            hash_value: Vec::from("pass"),
-        },
-    );
+    let mut user_info = UserInfo::new("root", "127.0.0.1", AuthInfo::Password {
+        hash_method: PasswordHashMethod::Sha256,
+        hash_value: Vec::from("pass"),
+    });
```

**Review by sundy-li — APPROVED** [review]

**Comment by BohuTANG** [comment]
Failed to execute. Collected info: Orig exception: The current accept connection has exceeded max_active_sessions config

**Comment by ariesdevil** [comment]
> Failed to execute. Collected info: Orig exception: The current accept connection has exceeded max_active_sessions config

I'm working on it

**Review by zhang2014 — APPROVED** [review]

**Comment by sundy-li** [comment]
` destory session` should be called in http/clickhouse handlers.

**Comment by ariesdevil** [comment]
@mergifyio update

**Pull request merged**
