### PR TITLE
ISSUE-5170 remove stale config items

### LINKED ISSUE #5170: remove config setting: table_engine_csv_enabled
**Summary**

CSV engine was deprecation or removed.  Please remove table_engine_csv_enabled config setting.

```
grep "table_engine_csv_enabled" * -r
docs/doc/30-reference/30-sql/70-system-tables/system-tracing.md:     msg: Config { config_file: "scripts/ci/deploy/config/databend-query-node-1.toml", query: QueryConfig { tenant_id: "test_tenant", cluster_id: "test_cluster", num_cpus: 10, mysql_handler_host: "0.0.0.0", mysql_handler_port: 3307, max_active_sessions: 256, clickhouse_handler_host: "0.0.0.0", clickhouse_handler_port: 9001, http_handler_host: "0.0.0.0", http_handler_port: 8001, http_handler_result_timeout_millis: 10000, flight_api_address: "0.0.0.0:9091", admin_api_address: "0.0.0.0:8081", metric_api_address: "0.0.0.0:7071", http_handler_tls_server_cert: "", http_handler_tls_server_key: "", http_handler_tls_server_root_ca_cert: "", api_tls_server_cert: "", api_tls_server_key: "", api_tls_server_root_ca_cert: "", rpc_tls_server_cert: "", rpc_tls_server_key: "", rpc_tls_query_server_root_ca_cert: "", rpc_tls_query_service_domain_name: "localhost", table_engine_csv_enabled: true, table_engine_parquet_enabled: true, table_engine_memory_enabled: true, database_engine_github_enabled: true, wait_timeout_mills: 5000, max_query_log_size: 10000, table_cache_enabled: true, table_cache_snapshot_count: 256, table_cache_segment_count: 10240, table_cache_block_meta_count: 102400, table_memory_cache_mb_size: 1024, table_disk_cache_root: "_cache", table_disk_cache_mb_size: 10240, management_mode: false, jwt_key_file: "" }, log: LogConfig { log_level: "INFO", log_dir: "./_logs", log_query_enabled: false }, meta: {meta_address: "0.0.0.0:9191", meta_user: "root", meta_password: "******"}, storage: StorageConfig { storage_type: "disk", storage_num_cpus: 0, disk: FsStorageConfig { data_path: "stateless_test_data", temp_data_path: "" }, s3: {s3.storage.region: "", s3.storage.endpoint_url: "https://s3.amazonaws.com", s3.storage.bucket: "", s3.storage.access_key_id: "", s3.storage.secret_access_key: "", }, azure_storage_blob: {Azure.storage.container: "", } } }
docs/doc/30-reference/30-sql/70-system-tables/system-configs.md:| table_engine_csv_enabled             | false            | query |             |
query/tests/it/storages/system/configs_table.rs:        "| query   | table_engine_csv_enabled             | false                    |             |",
query/tests/it/storages/system/configs_table.rs:        "| query   | table_engine_csv_enabled             | false                    |             |",
query/tests/it/configs.rs:table_engine_csv_enabled = false
query/tests/it/configs.rs:            assert!(configured.query.table_engine_csv_enabled);
query/tests/it/configs.rs:table_engine_csv_enabled = false
query/src/configs/config_query.rs:    pub table_engine_csv_enabled: bool,
query/src/configs/config_query.rs:            table_engine_csv_enabled: false,
scripts/ci/deploy/config/databend-query-node-1.toml:table_engine_csv_enabled = true
scripts/ci/deploy/config/databend-query-node-2.toml:table_engine_csv_enabled = true
scripts/ci/deploy/config/databend-query-embedded-meta.toml:table_engine_csv_enabled = true
scripts/ci/deploy/config/databend-query-node-3.toml:table_engine_csv_enabled = true
``

### PR DESCRIPTION
**Pull request by 5kbpers**
Signed-off-by: 5kbpers <hustmh@gmail.com>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Remove stale config items mentioned in #5170.

## Changelog

- Improvement
- Documentation
- Not for changelog (changelog entry is not required)

## Related Issues

Fixes #5170

### CODE REVIEW

**Comment by 5kbpers** [comment]
Found `query::tests::configs::test_env_config` and `query::tests::configs::test_override_config` try to read command line arguments, so cannot run them alone with like `cargo test --package databend-query --test it configs::test_env_config`.

Any suggestion to fix this? @BohuTANG

**Comment by BohuTANG** [comment]
Some places also have `table_engine_parquet_enabled`, for example `scripts/ci/deploy/config/databend-query-embedded-meta.Tom`, we can remove them all with grep to find.

**Comment by BohuTANG** [comment]
> Found `query::tests::configs::test_env_config` and `query::tests::configs::test_override_config` try to read command line arguments, so cannot run them alone with like `cargo test --package databend-query --test it configs::test_env_config`.
> 
> Any suggestion to fix this? @BohuTANG

Only removed them is ok :D

**Comment by 5kbpers** [comment]
> Some places also have `table_engine_parquet_enabled`, for example `scripts/ci/deploy/config/databend-query-embedded-meta.Tom`, we can remove them all with grep to find.

Fixed it. Very Strange that my code editor did not find them all the very first time.

**Review by Xuanwo — APPROVED** [review]
Thanks for contributing!

**Review by BohuTANG — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
