### PR TITLE
Push downs smallest column when no more columns

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

Push downs smallest column when no more columns

## Changelog

- Improvement

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by sundy-li** [comment]
After merge #3106

**Comment by BohuTANG** [comment]
> After merge #3106

LGTM, merged

**Comment by sundy-li** [comment]
Need merge main and modify the methods.

**Comment by BohuTANG** [comment]
> Need merge main and modify the methods.

Where does this patch depend on the main?

**Comment by BohuTANG** [comment]
> > Need merge main and modify the methods.
> 
> Where does this patch depend on the main?

Oh, i see `numeric_byte_size`

**Comment by BohuTANG** [comment]
@mergify update

**Review by zhyass — APPROVED** [review]

**Pull request merged**
