### PR TITLE
feat(query): Role/UserInfo add field create_on and udpate_on

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

Note:

In old version the time will be set to Utc::now().

e.g.

```sql
:) select * from system.users;

SELECT
  *
FROM
  system.users

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│     name     │ hostname │       auth_type      │  default_role │ is_configured │ disabled │     roles     │      created_on     │      update_on      │
│    String    │  String  │        String        │     String    │     String    │  Boolean │     String    │ Nullable(Timestamp) │ Nullable(Timestamp) │
├──────────────┼──────────┼──────────────────────┼───────────────┼───────────────┼──────────┼───────────────┼─────────────────────┼─────────────────────┤
│ 12345@qq.com │ %        │ double_sha1_password │               │ NO            │ false    │               │ 1970-01-01 00:00:00 │ 1970-01-01 00:00:00 │
│ a@xx         │ %        │ double_sha1_password │               │ NO            │ false    │               │ 1970-01-01 00:00:00 │ 1970-01-01 00:00:00 │
│ a            │ %        │ double_sha1_password │               │ NO            │ false    │               │ 1970-01-01 00:00:00 │ 1970-01-01 00:00:00 │
│ b            │ %        │ double_sha1_password │               │ NO            │ false    │               │ 1970-01-01 00:00:00 │ 1970-01-01 00:00:00 │
│ c            │ %        │ double_sha1_password │               │ NO            │ false    │               │ 1970-01-01 00:00:00 │ 1970-01-01 00:00:00 │
│ c2           │ %        │ double_sha1_password │               │ NO            │ false    │               │ 1970-01-01 00:00:00 │ 1970-01-01 00:00:00 │
│ test@qq.com  │ %        │ double_sha1_password │               │ NO            │ false    │ account_admin │ 1970-01-01 00:00:00 │ 1970-01-01 00:00:00 │
│ x@c          │ %        │ double_sha1_password │               │ NO            │ false    │               │ 1970-01-01 00:00:00 │ 1970-01-01 00:00:00 │
│ root         │ %        │ no_password          │ account_admin │ YES           │ false    │ account_admin │ NULL                │ NULL                │
│ default      │ %        │ no_password          │ account_admin │ YES           │ false    │ account_admin │ NULL                │ NULL                │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
10 rows read in 0.063 sec. Processed 10 rows, 1019 B (159.81 rows/s, 15.90 KiB/s)

:) select * from system.roles;

SELECT
  *
FROM
  system.roles

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│      name     │ inherited_roles │ inherited_roles_name │         created_on         │          update_on         │
│     String    │      UInt64     │        String        │          Timestamp         │          Timestamp         │
├───────────────┼─────────────────┼──────────────────────┼────────────────────────────┼────────────────────────────┤
│ account_admin │               0 │                      │ 2024-05-28 10:35:36.924398 │ 2024-05-28 10:35:36.924398 │
│ public        │               0 │                      │ 1970-01-01 00:00:00        │ 1970-01-01 00:00:00        │
│ test-role1    │               0 │                      │ 1970-01-01 00:00:00        │ 1970-01-01 00:00:00        │
│ test-role2    │               0 │                      │ 1970-01-01 00:00:00        │ 1970-01-01 00:00:00        │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
4 rows read in 0.056 sec. Processed 4 rows, 215 B (71.19 rows/s, 3.74 KiB/s)
```

- Fixes #[Link the issue here]

## Tests

- [x] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15661)

### CODE REVIEW

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 23 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15661)* status: 23 of 29 files reviewed, 5 unresolved discussions (waiting on @b41sh, @flaneur2020, and @TCeason)

___
*[`src/meta/proto-conv/src/ownership_from_to_protobuf_impl.rs` line 40 at r1](https://reviewable.io/reviews/datafuselabs/databend/15661#-Nyyonsq5A0RokcLcgUX:-Nyyonsq5A0RokcLcgUY:bpgz0k5) ([raw file](https://github.com/datafuselabs/databend/blob/41b4d0d2af59cbee3a4cfbe8b01b6fdb75c620e3/src/meta/proto-conv/src/ownership_from_to_protobuf_impl.rs#L40)):*
> ```XML
>             object: mt::principal::OwnershipObject::from_pb(p.object.ok_or_else(|| {
>                 Incompatible {
>                     reason: format!("ROLE {}: Object can not be None", p.role.clone()),
> ```

Needless clone. Using `&p.role` should be enough.
___
*[`src/meta/proto-conv/src/user_from_to_protobuf_impl.rs` line 325 at r1](https://reviewable.io/reviews/datafuselabs/databend/15661#-NyypGU89kwbPHPvhOlh:-NyypGU89kwbPHPvhOli:b-5e2lpm) ([raw file](https://github.com/datafuselabs/databend/blob/41b4d0d2af59cbee3a4cfbe8b01b6fdb75c620e3/src/meta/proto-conv/src/user_from_to_protobuf_impl.rs#L325)):*
> ```XML
>             auth_info: mt::principal::AuthInfo::from_pb(p.auth_info.ok_or_else(|| {
>                 Incompatible {
>                     reason: format!("USER {}: UserInfo.auth_info cannot be None", p.name.clone()),
> ```

Needless `clone()`
___
*[`src/meta/proto-conv/src/user_from_to_protobuf_impl.rs` line 330 at r1](https://reviewable.io/reviews/datafuselabs/databend/15661#-NyypJMq0wsUzjJEgvtn:-NyypJMq0wsUzjJEgvto:b-5e2lpm) ([raw file](https://github.com/datafuselabs/databend/blob/41b4d0d2af59cbee3a4cfbe8b01b6fdb75c620e3/src/meta/proto-conv/src/user_from_to_protobuf_impl.rs#L330)):*
> ```XML
>             grants: mt::principal::UserGrantSet::from_pb(p.grants.ok_or_else(|| {
>                 Incompatible {
>                     reason: format!("user {}: UserInfo.grants cannot be None", p.name.clone()),
> ```

Needless `clone()`
___
*[`src/meta/proto-conv/src/user_from_to_protobuf_impl.rs` line 334 at r1](https://reviewable.io/reviews/datafuselabs/databend/15661#-NyypJmr1X-UWR8h_8Co:-NyypJmr1X-UWR8h_8Cp:b-5e2lpm) ([raw file](https://github.com/datafuselabs/databend/blob/41b4d0d2af59cbee3a4cfbe8b01b6fdb75c620e3/src/meta/proto-conv/src/user_from_to_protobuf_impl.rs#L334)):*
> ```XML
>             })?)?,
>             quota: mt::principal::UserQuota::from_pb(p.quota.ok_or_else(|| Incompatible {
>                 reason: format!("user {}: UserInfo.quota cannot be None", p.name.clone()),
> ```

Needless `clone()`
___
*[`src/meta/proto-conv/src/user_from_to_protobuf_impl.rs` line 337 at r1](https://reviewable.io/reviews/datafuselabs/databend/15661#-NyypKD4Cig_jSfqBf-q:-NyypKD4Cig_jSfqBf-r:b-5e2lpm) ([raw file](https://github.com/datafuselabs/databend/blob/41b4d0d2af59cbee3a4cfbe8b01b6fdb75c620e3/src/meta/proto-conv/src/user_from_to_protobuf_impl.rs#L337)):*
> ```XML
>             })?)?,
>             option: mt::principal::UserOption::from_pb(p.option.ok_or_else(|| Incompatible {
>                 reason: format!("user {}: UserInfo.option cannot be None", p.name.clone()),
> ```

Needless `clone()`

**Comment by TCeason** [comment]
test in dev:

```sql
deploy@(system)/default> create warehouse 'user_time' warehouse_size='xsmall' with version='pr-15661-c3c2166';

deploy@(user_time)/default> select * from system.users where name='user_time';

SELECT
  *
FROM
  system.users
WHERE
  name = 'user_time'

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│    name   │ hostname │       auth_type      │ default_role │ is_configured │ disabled │  roles │         created_on         │          update_on         │
│   String  │  String  │        String        │    String    │     String    │  Boolean │ String │     Nullable(Timestamp)    │     Nullable(Timestamp)    │
├───────────┼──────────┼──────────────────────┼──────────────┼───────────────┼──────────┼────────┼────────────────────────────┼────────────────────────────┤
│ user_time │ %        │ double_sha1_password │              │ NO            │ false    │        │ 2024-05-29 04:02:45.232096 │ 2024-05-29 04:02:45.232096 │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
1 row read in 1.372 sec. Processed 95 row, 9.64 KiB (69.23 rows/s, 7.02 KiB/s)

deploy@(user_time)/default> use warehouse system;

USE warehouse system

deploy@(system)/default> select * from system.users where name='user_time';

SELECT
  *
FROM
  system.users
WHERE
  name = 'user_time'

┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│    name   │ hostname │       auth_type      │ default_role │ is_configured │ disabled │  roles │
│   String  │  String  │        String        │    String    │     String    │  Boolean │ String │
├───────────┼──────────┼──────────────────────┼──────────────┼───────────────┼──────────┼────────┤
│ user_time │ %        │ double_sha1_password │              │ NO            │ false    │        │
└────────────────────────────────────────────────────────────────────────────────────────────────┘
1 row read in 1.428 sec. Processed 95 row, 8.13 KiB (66.51 rows/s, 5.69 KiB/s)
```

Use new user 'user_time' login old warehouse `system`

```
user_time@(system)/default> select 1;

SELECT
  1

┌───────┐
│   1   │
│ UInt8 │
├───────┤
│     1 │
└───────┘

```

**Review by flaneur2020 — APPROVED** [review]
LGTM

**Comment by TCeason** [comment]
cc @BohuTANG @drmingdrmer  Please review this pr.

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 5 of 29 files at r1, 7 of 7 files at r2, 4 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15661)* status: all files reviewed, 2 unresolved discussions (waiting on @b41sh)

**Review by b41sh — APPROVED** [review]

**Pull request merged**
