### PR TITLE
fix(hive): may get wrong datablocks if not sorted by output schema

### PR DESCRIPTION
**Pull request by sandflee**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Closes #issue

### CODE REVIEW

**Comment by RinChanNOWWW** [comment]
If remain_reader is None, prewhere_reader's schema should be the same as output_schema.

**Review by RinChanNOWWW — APPROVED** [review]
LGTM. And in `do_deserialize`, `self.remain_reader` seems always be `Some(_)`, we can add ` Err(ErrorCode::Internal("It's a bug. No remain reader"))` there.

**Comment by sandflee** [comment]
> LGTM. And in `do_deserialize`, `self.remain_reader` seems always be `Some(_)`, we can add ` Err(ErrorCode::Internal("It's a bug. No remain reader"))` there.

will update the patch after test on our cluster.

**Comment by sundy-li** [comment]
@mergify update

**Comment by sandflee** [comment]
@mergify  update

**Comment by sandflee** [comment]
@mergify update

**Comment by sandflee** [comment]
@mergify update

**Comment by sandflee** [comment]
@mergify update

**Comment by sandflee** [comment]
OHH,  always see this error:
```
Error: '/Users/runner/work/_actions/_temp_debe1b19-4d5e-446b-9f69-8babf821fe4c/6dcc06e3-c8cb-4966-b1d0-bde205c00812.tar.gz' contains '0' directories
```

**Comment by RinChanNOWWW** [comment]
How about merge the latest main and repon this PR.

**Pull request merged**
