### PR TITLE
feat(iceberg): Implement Iceberg Table Read

### PR DESCRIPTION
**Pull request by Xuanwo**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

This PR will add the basic read support for iceberg table.

*basic* here means we still have a lot of work to do:

- not support filed metadata yet.
- not support schema changes.
- not support table time travel.
- we are reading data in io worker.

And we have a lot of bugs here:

- table instances are store in global iceberg context.
- we are loading all data into memory.

However, it's a good start for both [icelake](https://github.com/icelake-io/icelake) and databend! I think we should merge this PR first and than improve other parts.

### CODE REVIEW

**Comment by Xuanwo** [comment]
askbend:summary

**Comment by BohuTANG** [comment]
askbend:summary

**Comment by BohuTANG** [comment]
```
, result:

ERROR 1105 (HY000) at line 1: Code: 1006, Text = no such catalog iceberg_ctl(while in query flight).
```

**Comment by BohuTANG** [comment]
askbend:summary

**Comment by BohuTANG** [comment]
## PR Summary(By [llmchain.rs](https://github.com/shafishlabs/llmchain.rs)):
* **Changed S3 bucket path and dependencies**
Changed the S3 bucket path for copying data from tests/data/iceberg to s3://testbucket and added dependencies for arrow-array, arrow-schema, common-arrow, common-base, dashmap, and parquet. Also updated the version of icelake from 0.0.3 to 0.0.6, added the package parquet with version 40.0.0, and updated the version of thrift from 0.16.0 to 0.17.0.

* **Removed flatten field from IcebergCatalogOption**
Removed the field "flatten" from the struct IcebergCatalogOption in multiple files, including catalog.rs and catalog_manager.rs.

* **Added global context for Iceberg tables**
Added a context.rs file to the `src/query/storages/iceberg/src/` directory, which defines a global context for iceberg tables. This includes a lazy cell struct for thread-safe lazy initialization of a value and a global context struct for storing Iceberg tables.

* **Changed type of variable schema**
Changed the type of the variable "schema" from ArrowSchema to DataSchema in the file record_batch.rs.

* **Added IcebergTableSource struct**
Added a new file, table_source.rs, which contains the implementation of `IcebergTableSource` struct and its methods. The struct is used to read data from a Parquet file using the Iceberg engine.

* **Changed public API and parameter references**
Changed the public API and parameter references in multiple files, including lib.rs, reader.rs, mod.rs, and read.rs, to improve functionality and readability.

* **Added and deleted metadata and test files**
Added a new metadata file and test files, including 10_0000_create_and_show.sh, 10_0001_read.result, and 10_0001_read.sh. Also deleted an existing metadata file and a test file.

**Review by zhang2014 — APPROVED** [review]

**Comment by Xuanwo** [comment]
> ```
> , result:
> 
> ERROR 1105 (HY000) at line 1: Code: 1006, Text = no such catalog iceberg_ctl(while in query flight).
> ```

iceberg table read is not ready on cluster. I plan to get this PR merge first and than working on address that.

**Pull request merged**
