### PR TITLE
feat: twitter card test

### LINKED ISSUE #5658: website: Twitter card doesn't display correctly
As reported by @wey-gu, databend.rs 's page doesn't have a correct Twitter card.

image

I think https://docusaurus.io/ should already handle this.

Ping @Chasen-Zhang to take a look, thanks!

### PR DESCRIPTION
**Pull request by Chasen-Zhang**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Let me test it first.

## Changelog

- Improvement

## Related Issues

Fixes #5658

### CODE REVIEW

**Comment by Xuanwo** [comment]
image

Seems not work?

**Comment by Chasen-Zhang** [comment]
Let me see. It's weird

**Comment by Chasen-Zhang** [comment]
opps！ Path to the wrong

**Comment by Chasen-Zhang** [comment]
Just a moment, I'll adjust the picture again

**Comment by Xuanwo** [comment]
Current preview

image

**Review by BohuTANG — APPROVED** [review]

**Pull request merged**
