### PR TITLE
feat: FlightSQL support update (DDL and insert)

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

part of https://github.com/datafuselabs/databend/issues/10745.

-  ddl/insert work well with JDBC, see https://github.com/youngsofun/test_flight_sql/blob/main/src/main/java/Test.java.
    - but the official rs client has a bug (which is not used in production AFAIK),  so new unit test cases is commented out for now. however,  it uses a different interface of FlightSQL from JDBC(in JDBC, all statement is implemented as preparedStatement internally ).
- port change from 7000 to 8900 due to https://github.com/datafuselabs/databend/discussions/10741

- still only basic types are supported, I will go back to it after  impl meta related API  https://github.com/datafuselabs/databend/issues/10745.

Closes #issue

### CODE REVIEW

**Review by ariesdevil — APPROVED** [review]

**Comment by youngsofun** [comment]
Databend Query start failure, cause: Code: 1068, displayText = {127.0.0.1:4100} Address already in use (os error 98).
😭

**Comment by youngsofun** [comment]
both 8700 & 8600 failed in test_stateful_standalone_linux but suceed with test_stateful_cluster_linux

**Comment by BohuTANG** [comment]
Conflicting files
src/query/service/src/servers/mysql/mysql_interactive_worker.rs

**Comment by everpcpc** [comment]
> both 8700 & 8600 failed in test_stateful_standalone_linux but suceed with test_stateful_cluster_linux

There are two query instance in statefultest, another is a sharing instance: `scripts/ci/deploy/config/databend-query-node-shared.toml`, which would conflict if default port not changed in it.

**Comment by youngsofun** [comment]
> Conflicting files
> src/query/service/src/servers/mysql/mysql_interactive_worker.rs

rebased

**Review by TCeason — APPROVED** [review]

**Comment by youngsofun** [comment]
flightsql bug fixed

https://github.com/apache/arrow-rs/pull/3938

**Pull request merged**
