### PR TITLE
ISSUE-3906: Add partitions_scanned and partitions_total to planner statistics

### LINKED ISSUE #3906: Add `partitions_scanned` and `partitions_total` to Statistics
After https://github.com/datafuselabs/databend/pull/3903 checked in, we should add `partitions_scanned` and `partitions_total` to Statistics https://github.com/datafuselabs/databend/blob/d8cf752e80afc98ff173c38a2af4488601cc7cc8/common/planners/src/plan_statistics.rs#L16 and show them in the explain:

https://github.com/datafuselabs/databend/blob/d8cf752e80afc98ff173c38a2af4488601cc7cc8/common/planners/src/plan_display_indent.rs#L207-L213

### PR DESCRIPTION
**Pull request by BohuTANG**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

## Changelog

- Improvement

## Related Issues

Fixes #3906 

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Review by zhyass — APPROVED** [review]
LGTM

**Comment by zhyass** [comment]
```
/home/runner/work/databend/databend/tests/suites/0_stateless/02_0004_function_name_display_cluster.result
/home/runner/work/databend/databend/tests/suites/0_stateless/03_0004_select_order_by_cluster.result
/home/runner/work/databend/databend/tests/suites/0_stateless/03_0005_select_filter_cluster.result
/home/runner/work/databend/databend/tests/suites/0_stateless/08_0000_optimizer_cluster.result
/home/runner/work/databend/databend/tests/suites/0_stateless/09_0009_remote_explain.result
```

**Comment by BohuTANG** [comment]
> Failed cluster stateless tests
> 
> ```
> /home/runner/work/databend/databend/tests/suites/0_stateless/02_0004_function_name_display_cluster.result
> /home/runner/work/databend/databend/tests/suites/0_stateless/03_0004_select_order_by_cluster.result
> /home/runner/work/databend/databend/tests/suites/0_stateless/03_0005_select_filter_cluster.result
> /home/runner/work/databend/databend/tests/suites/0_stateless/08_0000_optimizer_cluster.result
> /home/runner/work/databend/databend/tests/suites/0_stateless/09_0009_remote_explain.result
> ```

Trying fixed

**Review by dantengsky — APPROVED** [review]
LGTM

**Pull request merged**
