### PR TITLE
chore: Bump z3 to remove build time warning

### PR DESCRIPTION
**Pull request by Xuanwo**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

chore: Bump z3 to remove build time warning

This PR will remove the warning during build time like the following:

```shell
warning: the following packages contain code that will be rejected by a future version of Rust: nom v5.1.2
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 2`
```

### CODE REVIEW

**Comment by Xuanwo** [comment]
Ooops, built faild on musl.

**Comment by Xuanwo** [comment]
reported to https://github.com/prove-rs/z3.rs/issues/245

**Review by sundy-li — APPROVED** [review]

**Review by andylokandy — APPROVED** [review]

**Comment by waywardmonkeys** [comment]
I've published `z3-sys` version `0.8.1` which should fix this. Please re-run this build and let's see.

**Comment by Xuanwo** [comment]
> I've published `z3-sys` version `0.8.1` which should fix this. Please re-run this build and let's see.

Thanks a lot!

**Comment by waywardmonkeys** [comment]
Sorry, I meant to publish z3 0.12.1, not z3-sys 0.8.1 ... one moment.

**Comment by waywardmonkeys** [comment]
z3 v0.12.1 published now.

**Comment by Xuanwo** [comment]
> z3 v0.12.1 published now.

Thanks, I will trigger again.

**Comment by Xuanwo** [comment]
Thank @waywardmonkeys a lot for the quick feedback, let's merge!

**Pull request merged**
