### PR TITLE
feat: add table least visible time

### PR DESCRIPTION
**Pull request by lichuang**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

feat: add table least visible time

- Closes https://github.com/datafuselabs/databend/issues/12643

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12644)

### CODE REVIEW

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 11 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12644)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @dantengsky and @lichuang)

___
*[`src/meta/api/src/schema_api_impl.rs` line 3570 at r1](https://reviewable.io/reviews/datafuselabs/databend/12644#-NdD8qm_0jvAc2QUzhpl:-NdD8qm_0jvAc2QUzhpm:bk36ga7) ([raw file](https://github.com/datafuselabs/databend/blob/9932cbe2dbc91799681ff4ecb93295d36be5c1ee/src/meta/api/src/schema_api_impl.rs#L3570)):*
> ```XML
>         let mut retry = 0;
>         while retry < TXN_MAX_RETRY_TIMES {
>             retry += 1;
> ```

Life would be a bit easier with `txn_trials()`:



_Suggestion:_
```XML
        let ctx = &func_name!();
        let mut trials = txn_trials(None, ctx);
        loop {
            trials.next().unwrap()?;
```

**Comment by drmingdrmer** [comment]
Least visible time should be identified by `TableId` instead of `(tenant, db_name, table_name)`

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12644)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @dantengsky)

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12644)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dantengsky)

**Review by dantengsky — APPROVED** [review]

**Pull request merged**
