### PR TITLE
feat(CSV): no longer accept trailing field_delimiter.

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

example:

```
a,b,c,
```

is invalid because the trailing comma.

Closes #issue

### CODE REVIEW

**Review by sundy-li — APPROVED** [review]

**Review by ariesdevil — APPROVED** [review]

**Comment by youngsofun** [comment]
https://repo.databend.rs/dataset/stateful/ontime_2006_200.csv has trailing `,` and is used in tests.
is it a mistake of us when transforming? @wubx

**Comment by BohuTANG** [comment]
> https://repo.databend.rs/dataset/stateful/ontime_2006_200.csv has trailing `,` and is used in tests. is it a mistake of us when transforming? @wubx

It needs to trim.

**Comment by BohuTANG** [comment]
[ontime_2006_200.csv](https://repo.databend.rs/dataset/stateful/ontime_2006_200.csv)(~92K) is a small test data, can we download and put it to `00_copy/testdata`? @youngsofun

**Comment by youngsofun** [comment]
http://repo.databend.rs/dataset/stateful/tpch.tar.gz

```
➜  data head customer.tbl
1|Customer#000000001|IVhzIApeRb ot,c,E|15|25-989-741-2988|711.56|BUILDING|to the even, regular platelets. regular, ironic epitaphs nag e|
2|Customer#000000002|XSTf4,NCwDVaWNe6tEgvwfmRchLXak|13|23-768-687-3665|121.65|AUTOMOBILE|l accounts. blithely ironic theodolites integrate boldly: caref|
...
```

**Comment by youngsofun** [comment]
> [ontime_2006_200.csv](https://repo.databend.rs/dataset/stateful/ontime_2006_200.csv)(~92K) is a small test data, can we download and put it to `00_copy/testdata`? @youngsofun

it is used in `00_0001_copy_from_http_location.sh`

**Comment by BohuTANG** [comment]
> http://repo.databend.rs/dataset/stateful/tpch.tar.gz end with `|`
> 
> ```
> ➜  data head customer.tbl
> 1|Customer#000000001|IVhzIApeRb ot,c,E|15|25-989-741-2988|711.56|BUILDING|to the even, regular platelets. regular, ironic epitaphs nag e|
> 2|Customer#000000002|XSTf4,NCwDVaWNe6tEgvwfmRchLXak|13|23-768-687-3665|121.65|AUTOMOBILE|l accounts. blithely ironic theodolites integrate boldly: caref|
> ...
> ```
> 
> it is 103M decompressed; 29M compressed

cc @xudong963

**Comment by youngsofun** [comment]
@xudong963 http://repo.databend.rs/dataset/stateful/tpch.tar.gz need to trim the ending `|` of each line.

**Comment by sundy-li** [comment]
> http://repo.databend.rs/dataset/stateful/tpch.tar.gz end with `|`
> 
> ```
> ➜  data head customer.tbl
> 1|Customer#000000001|IVhzIApeRb ot,c,E|15|25-989-741-2988|711.56|BUILDING|to the even, regular platelets. regular, ironic epitaphs nag e|
> 2|Customer#000000002|XSTf4,NCwDVaWNe6tEgvwfmRchLXak|13|23-768-687-3665|121.65|AUTOMOBILE|l accounts. blithely ironic theodolites integrate boldly: caref|
> ...
> ```
> 
> it is 103M decompressed; 29M compressed

This is generated by TPCH gen script.  What's the drawback that we support trailing field_delimiter ?

**Comment by BohuTANG** [comment]
Agree with @sundy-li .
Let's keep the non-standard compatibility now, otherwise many things may not work.

**Comment by sundy-li** [comment]
We can directly modify `**.tbl`, but it'll make others unable to do TPCH benchmark using the official tool.

Official:  https://github.com/electrum/tpch-dbgen

**Pull request closed without merging**
