### PR TITLE
feat: Remove the need of setting allow_anonymous

### PR DESCRIPTION
**Pull request by Xuanwo**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

This PR will remove the need to set allow_anonymous. Make it much simple to access public bucket.

## Tests

- [x] Unit Test
- [x] Logic Test
- [x] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14398)

### CODE REVIEW

**Comment by Xuanwo** [comment]
cc @soyeric128, we don't need to set `allow_anonymous` for public bucket anymore.

**Review by drmingdrmer — COMMENTED** [review]
A test should still be added to ensure future version of query can read protobuf message of this version.

> Reviewed 10 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14398#-:-Noiz7tU-A6PzDI7eqFF:b-exyjmq)* status: 10 of 12 files reviewed, all discussions resolved

**Review by drmingdrmer — APPROVED** [review]
LGTM!

> Reviewed 2 of 12 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14398#-:-Noj1aB7E9EbpCIlv7_f:b-85i648)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Xuanwo)

**Comment by BohuTANG** [comment]
Uni test failed:
`-| 'storage' | 's3.allow_anonymous'                       | 'false'                                                        | ''       |`

**Pull request merged**
