### PR TITLE
website: Add i18n support

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Part of https://github.com/datafuselabs/databend/issues/5542

## Changelog

- Documentation

### CODE REVIEW

**Comment by Xuanwo** [comment]
```shell

- On source page path = /doc/learn/analyze-ontime-with-databend-on-ec2-and-s3:
--
12:12:04.682 | -> linking to ../70-performance/03-ecs-oss-performance.md (resolved as: /doc/70-performance/03-ecs-oss-performance.md)
```

Seems this page should not be broken, I will fix it later

**Comment by Xuanwo** [comment]
image

**Comment by Xuanwo** [comment]
Vercel build with success, let's merge. We need to verify whether it works.

**Comment by BohuTANG** [comment]
image

The sidebar is gone?

**Comment by Xuanwo** [comment]
> The sidebar is gone?

Wired, I will fix it.

**Pull request merged**
