### PR TITLE
fix(cluster): stop tasks in cluster when select limit

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

fix(cluster): stop tasks in cluster when select limit

Fixes #issue

### CODE REVIEW

**Comment by sandflee** [comment]
I run a simple select query like 'select * from lineorder limit 100000',  totally it works fine with a litter minor problems, but we could trace it in another issues.
1.  it takes 1.2s in local mode, 1.4~.1.5s in cluster mode. a little expancive (starrocks takes 1.0 in local mode, 0.7 in cluster mode)
2. limit is not pushed down to the worker node,   worker node keeps reading and sending data.

**Comment by zhang2014** [comment]
> I run a simple select query like 'select * from lineorder limit 100000', totally it works fine with a litter minor problems, but we could trace it in another issues.
> 
> 1. it takes 1.2s in local mode, 1.4~.1.5s in cluster mode. a little expensive (for starrocks takes 1.0 in local mode, 0.7 in cluster mode)
> 2. limit is not pushed down to the worker node,   worker node keeps reading and sending data.

This may be related to our data block is too large, which requires more tests.

**Comment by BohuTANG** [comment]
@mergify update

**Review by BohuTANG — APPROVED** [review]

**Comment by BohuTANG** [comment]
test_sqllogic_base_cluster_linux always failed :)

**Comment by zhang2014** [comment]
> test_sqllogic_base_cluster_linux always failed :)

Sorry, it's a little late because of the holiday: (. I will continue this pr.

**Comment by sandflee** [comment]
I tried but failed to get the key point,  could you explain:

1.  what's the key problem and how to resolved it?
2. is any reason to  replace `Progress` and `PrecommitBlock` with  `FetchProgressAndPrecommit` and `ProgressAndPrecommit ` ?   is any relation with this  issues ?

**Comment by zhang2014** [comment]
> I tried but failed to get the key point, could you explain:
> 
> 1. what's the key problem and how to resolved it?
> 2. is any reason to  replace `Progress` and `PrecommitBlock` with  `FetchProgressAndPrecommit` and `ProgressAndPrecommit ` ?   is any relation with this  issues ?

When the limit processor finish, the corresponding executor will exit. Other nodes connected to them in the cluster will perceive this through the network and exit.

This is a bug. exchange progress blocked the executor exit.

**Comment by zhang2014** [comment]
@mergify update

**Comment by zhang2014** [comment]
```
Crate:         quick-xml
Version:       0.23.0
Warning:       yanked
Dependency tree: 
quick-xml 0.23.0
```

Opendal's dependency is yanked. CC: @Xuanwo

**Comment by Xuanwo** [comment]
> Opendal's dependency is yanked. CC: @Xuanwo

OpenDAL releases v0.16.0 yesterday, I will send a PR today.

**Pull request merged**
