### PR TITLE
feat: support `intdiv` operator `//`

### LINKED ISSUE #11516: Feature: Support `intdiv` operator `//`
**Summary**

Description for this feature.

```
select 3 / 2, 3//2;

--> 1.5, 1

```
Parser should add this `//` operator.
Operator `//`  should be resolved as `intdiv` function in [type_checker.rs](https://github.com/datafuselabs/databend/blob/e64908558f141d77a8b6bff93d8a6d4a99547a9f/src/query/sql/src/planner/semantic/type_check.rs)

### PR DESCRIPTION
**Pull request by gitccl**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Support `intdiv` operator `//`.

Closes #11516

### CODE REVIEW

**Comment by jun0315** [comment]
@gitccl Thanks for your contribution. There are some errors in workflow, please try fixing them first.It seems that there is no actual calculated code. 

Here are some links that may be helpful:
https://github.com/datafuselabs/databend/pull/10444
https://my.oschina.net/u/5489811/blog/7554715

**Comment by gitccl** [comment]
> It seems that there is no actual calculated code.

The `//` operator will be resolved as `intdiv` function in https://github.com/datafuselabs/databend/blob/e64908558f141d77a8b6bff93d8a6d4a99547a9f/src/query/sql/src/planner/semantic/type_check.rs#L1391-L1394
, so I think there is no extra calculate logic.

**Comment by jun0315** [comment]
> , so I think there is no extra calculate logic.

Yes, you're right, it's already registered as an alias, so there's no need to rewrite the calculation logic.
```rust
    registry.register_aliases("div", &["intdiv"]);
```

**Comment by sundy-li** [comment]
```
env REGENERATE_GOLDENFILES=1 cargo test
```

to regenerate the golden files.

**Review by sundy-li — APPROVED** [review]

**Review by RinChanNOWWW — APPROVED** [review]

**Pull request merged**
