### PR TITLE
feat: try replace the segment cache with new

### PR DESCRIPTION
**Pull request by BohuTANG**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Closes #issue

### CODE REVIEW

**Comment by BohuTANG** [comment]
This PR compile errors as following:
```
error: future cannot be sent between threads safely
   --> src/query/storages/fuse/src/pruning/pruning_executor.rs:148:14
    |
148 |             .try_spawn_batch_with_owned_semaphore(semaphore.clone(), tasks)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ future created by async block is not `Send`
    |
    = help: the trait `std::marker::Sync` is not implemented for `(dyn common_storages_cache::ObjectCacheProvider<common_storages_table_meta::meta::SegmentInfo> + 'static)`
note: future is not `Send` as this value is used across an await
   --> src/query/storages/fuse/src/pruning/pruning_executor.rs:181:65
    |
178 |         let segment_reader = SegmentReader::create(dal.clone());
    |             -------------- has type `std::sync::Arc<io::read::segment_reader::SegmentReader>` which is not `Send`
...
181 |         let segment_info = segment_reader.read(&path, None, ver).await?;
    |                                                                 ^^^^^^ await occurs here, with `segment_reader` maybe used later
```

The MemoryItemsCache defined:
https://github.com/datafuselabs/databend/blob/c79f9e81652839953690b88893361b3983833a39/src/query/storages/cache/src/providers/memory_items_cache.rs#L50-L52

Not sure:

1. how to remove the Sync+Send from:
` impl<T> ObjectCacheProvider<T> for MemoryItemsCache<T> 
 where T: CachedObject + Send + Sync`

2. how to fix the `try_spawn_batch_with_owned_semaphore` error

@dantengsky needs your help or suggestions.

**Comment by Xuanwo** [comment]
> 1. how to remove the Sync+Send from:
>    ` impl<T> ObjectCacheProvider<T> for MemoryItemsCache<T>   where T: CachedObject + Send + Sync`

Please try https://github.com/datafuselabs/opendal/commit/9ac3845f4f80e4cfc31c8dd62f9d019f795e79eb

OpenDAL now will make sure all returning `ObjectReader` have `Send + Sync`.

**Comment by BohuTANG** [comment]
@Xuanwo 

`Send+Sync` removed:

```diff
--- a/src/query/storages/cache/src/providers/memory_items_cache.rs
+++ b/src/query/storages/cache/src/providers/memory_items_cache.rs
@@ -49,7 +49,7 @@ impl<T> MemoryItemsCache<T> {

 #[async_trait::async_trait]
 impl<T> ObjectCacheProvider<T> for MemoryItemsCache<T>
-where T: CachedObject + Send + Sync
+where T: CachedObject
 {
     async fn read_object(&self, object: &Object, start: u64, end: u64) -> Result<Arc<T>> {
         let key = object.path().to_string();
```

Compiler error:
```
argo clippy --workspace --all-targets -- -D warnings
    Checking common-storages-cache v0.1.0 (/Users/bohu/github/datafuselabs/databend/src/query/storages/cache)
error: future cannot be sent between threads safely
  --> src/query/storages/cache/src/providers/memory_items_cache.rs:54:90
   |
54 |       async fn read_object(&self, object: &Object, start: u64, end: u64) -> Result<Arc<T>> {
   |  __________________________________________________________________________________________^
55 | |         let key = object.path().to_string();
56 | |         let try_get_val = self.get_cache(&key);
57 | |
...  |
68 | |         })
69 | |     }
   | |_____^ future created by async block is not `Send`
   |
note: captured value is not `Send` because `&` references cannot be sent unless their referent is `Sync`
  --> src/query/storages/cache/src/providers/memory_items_cache.rs:54:27
   |
54 |     async fn read_object(&self, object: &Object, start: u64, end: u64) -> Result<Arc<T>> {
   |                           ^^^^ has type `&providers::memory_items_cache::MemoryItemsCache<T>` which is not `Send`, because `providers::memory_items_cache::MemoryItemsCache<T>` is not `Sync`
   = note: required for the cast from `impl std::future::Future<Output = std::result::Result<std::sync::Arc<T>, common_exception::ErrorCode>>` to the object type `dyn std::future::Future<Output = std::result::Result<std::sync::Arc<T>, common_exception::ErrorCode>> + std::marker::Send`
help: consider further restricting this bound
   |
52 | where T: CachedObject + std::marker::Sync
   |                       +++++++++++++++++++

error: future cannot be sent between threads safely
  --> src/query/storages/cache/src/providers/memory_items_cache.rs:54:90
   |
54 |       async fn read_object(&self, object: &Object, start: u64, end: u64) -> Result<Arc<T>> {
   |  __________________________________________________________________________________________^
55 | |         let key = object.path().to_string();
56 | |         let try_get_val = self.get_cache(&key);
57 | |
...  |
68 | |         })
69 | |     }
   | |_____^ future created by async block is not `Send`
   |
note: captured value is not `Send` because `&` references cannot be sent unless their referent is `Sync`
  --> src/query/storages/cache/src/providers/memory_items_cache.rs:54:27
   |
54 |     async fn read_object(&self, object: &Object, start: u64, end: u64) -> Result<Arc<T>> {
   |                           ^^^^ has type `&providers::memory_items_cache::MemoryItemsCache<T>` which is not `Send`, because `providers::memory_items_cache::MemoryItemsCache<T>` is not `Sync`
   = note: required for the cast from `impl std::future::Future<Output = std::result::Result<std::sync::Arc<T>, common_exception::ErrorCode>>` to the object type `dyn std::future::Future<Output = std::result::Result<std::sync::Arc<T>, common_exception::ErrorCode>> + std::marker::Send`
help: consider further restricting this bound
   |
52 | where T: CachedObject + std::marker::Send
   |                       +++++++++++++++++++

error: future cannot be sent between threads safely
  --> src/query/storages/cache/src/providers/memory_items_cache.rs:71:76
   |
71 |       async fn write_object(&self, object: &Object, v: Arc<T>) -> Result<()> {
   |  ____________________________________________________________________________^
72 | |         if self.settings.cache_on_write {
73 | |             let key = object.path().to_string();
74 | |             self.lru.write().put(key, v.clone());
...  |
80 | |         Ok(())
81 | |     }
   | |_____^ future created by async block is not `Send`
   |
note: captured value is not `Send`
  --> src/query/storages/cache/src/providers/memory_items_cache.rs:71:51
   |
71 |     async fn write_object(&self, object: &Object, v: Arc<T>) -> Result<()> {
   |                                                   ^ has type `std::sync::Arc<T>` which is not `Send`
   = note: required for the cast from `impl std::future::Future<Output = std::result::Result<(), common_exception::ErrorCode>>` to the object type `dyn std::future::Future<Output = std::result::Result<(), common_exception::ErrorCode>> + std::marker::Send`
help: consider further restricting this bound
   |
52 | where T: CachedObject + std::marker::Sync
   |                       +++++++++++++++++++

error: future cannot be sent between threads safely
  --> src/query/storages/cache/src/providers/memory_items_cache.rs:71:76
   |
71 |       async fn write_object(&self, object: &Object, v: Arc<T>) -> Result<()> {
   |  ____________________________________________________________________________^
72 | |         if self.settings.cache_on_write {
73 | |             let key = object.path().to_string();
74 | |             self.lru.write().put(key, v.clone());
...  |
80 | |         Ok(())
81 | |     }
   | |_____^ future created by async block is not `Send`
   |
note: captured value is not `Send`
  --> src/query/storages/cache/src/providers/memory_items_cache.rs:71:51
   |
71 |     async fn write_object(&self, object: &Object, v: Arc<T>) -> Result<()> {
   |                                                   ^ has type `std::sync::Arc<T>` which is not `Send`
   = note: required for the cast from `impl std::future::Future<Output = std::result::Result<(), common_exception::ErrorCode>>` to the object type `dyn std::future::Future<Output = std::result::Result<(), common_exception::ErrorCode>> + std::marker::Send`
help: consider further restricting this bound
   |
52 | where T: CachedObject + std::marker::Send
   |                       +++++++++++++++++++

error: future cannot be sent between threads safely
  --> src/query/storages/cache/src/providers/memory_items_cache.rs:83:66
   |
83 |       async fn remove_object(&self, object: &Object) -> Result<()> {
   |  __________________________________________________________________^
84 | |         let key = object.path();
85 | |
86 | |         // Try to remove from the cache.
...  |
90 | |         Ok(())
91 | |     }
   | |_____^ future created by async block is not `Send`
   |
note: captured value is not `Send` because `&` references cannot be sent unless their referent is `Sync`
  --> src/query/storages/cache/src/providers/memory_items_cache.rs:83:29
   |
83 |     async fn remove_object(&self, object: &Object) -> Result<()> {
   |                             ^^^^ has type `&providers::memory_items_cache::MemoryItemsCache<T>` which is not `Send`, because `providers::memory_items_cache::MemoryItemsCache<T>` is
not `Sync`
   = note: required for the cast from `impl std::future::Future<Output = std::result::Result<(), common_exception::ErrorCode>>` to the object type `dyn std::future::Future<Output = std::result::Result<(), common_exception::ErrorCode>> + std::marker::Send`
help: consider further restricting this bound
   |
52 | where T: CachedObject + std::marker::Sync
   |                       +++++++++++++++++++

error: future cannot be sent between threads safely
  --> src/query/storages/cache/src/providers/memory_items_cache.rs:83:66
   |
83 |       async fn remove_object(&self, object: &Object) -> Result<()> {
   |  __________________________________________________________________^
84 | |         let key = object.path();
85 | |
86 | |         // Try to remove from the cache.
...  |
90 | |         Ok(())
91 | |     }
   | |_____^ future created by async block is not `Send`
   |
note: captured value is not `Send` because `&` references cannot be sent unless their referent is `Sync`
  --> src/query/storages/cache/src/providers/memory_items_cache.rs:83:29
   |
83 |     async fn remove_object(&self, object: &Object) -> Result<()> {
   |                             ^^^^ has type `&providers::memory_items_cache::MemoryItemsCache<T>` which is not `Send`, because `providers::memory_items_cache::MemoryItemsCache<T>` is
not `Sync`
   = note: required for the cast from `impl std::future::Future<Output = std::result::Result<(), common_exception::ErrorCode>>` to the object type `dyn std::future::Future<Output = std::result::Result<(), common_exception::ErrorCode>> + std::marker::Send`
help: consider further restricting this bound
   |
52 | where T: CachedObject + std::marker::Send
   |                       +++++++++++++++++++

error: could not compile `common-storages-cache` due to 6 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `common-storages-cache` due to 6 previous errors
```

**Comment by Xuanwo** [comment]
> `Send+Sync` removed:

Please keep `Send + Sync` and only upgrading opendal. The `Send + Sync` is required to implement `async_trait`.

To make `read_object` is `Send + Sync`, we need:

- `ObjectCacheProvider` is `Send + Sync`
- All implementations of `ObjectCacheProvider` (like `MemoryItemsCache`) is `Send + Sync`

**Comment by BohuTANG** [comment]
When opendal released the new tag? It seems there is a lot of change on databend side :)

**Comment by Xuanwo** [comment]
> When opendal released the new tag? It seems there is a lot of change on databend side :)

I will do this in next two days~

**Comment by BohuTANG** [comment]
Have a try with the new Version OpenDAL:
this PR `Sync+Send` is not related to the OpenDAL, it's the type of T, the error is same as above.

**Comment by BohuTANG** [comment]
@Xuanwo Fixed by @dantengsky  https://github.com/BohuTANG/databend/pull/39

**Comment by BohuTANG** [comment]
This experimental PR will be closed, @dantengsky  will continue to work on it 🚀

**Comment by dantengsky** [comment]
> This experimental PR will be closed, @dantengsky will continue to work on it rocket

:ok_hand:

**Pull request closed without merging**
