### PR TITLE
refactor: rename CreateOption to OnExist

### PR DESCRIPTION
**Pull request by drmingdrmer**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

##### refactor: rename CreateOption to OnExist

`CreateOption` should be explicit and specific on what action to take
when a record to add exists.

- `OnExist::Error`:   Return `Err` for an existing record.
- `OnExist::Keep`:    Keep the existing record and return `Ok(existing)`.
- `OnExist::Replace`: Overwrite the existing record and return `Ok(replaced)`.
## Tests

- [x] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [x] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

## Related Issues

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14949)

### CODE REVIEW

**Comment by andylokandy** [comment]
FYI https://github.com/datafuselabs/databend/pull/14941#pullrequestreview-1935814952

**Comment by sundy-li** [comment]
`CreateOption` is better than `OnExists`, the former is more closely to users and may cover other options other than OnExists.

**Comment by drmingdrmer** [comment]
> IMHO `CreateOption` is better than `OnExists`, the former is more closely to users and may cover options other than OnExists.

`CreateOption::Create` and `CreateOption::CreateIfNotExists` are still confusing terms:
With either option, the record will only be created **only if it does not exists**.

The difference between these two options is: `CreateOption::Create` returns an error to user, `CreateOption::CreateIfNotExists` silently ignores the error.

That's why this option should be explicit on this difference: ignore error or not.

**Comment by andylokandy** [comment]
`OnExist` is more likely a strategy on how to handle different kinds of CREATE statement, while `CreateOption`, being an AST, sticks closer to the SQL itself by imitating the term of SQL.

**Comment by drmingdrmer** [comment]
> `OnExist` is more likely a strategy on how to handle different kinds of CREATE statement, while `CreateOption`, being an AST, sticks closer to the SQL itself by imitating the term of SQL.

OK, I'm not a SQL expert. I'll gladly follow your lead on this.

**Pull request closed without merging**
