### PR TITLE
ci: migrate deprecating set-output commands

### LINKED ISSUE #8342: Migrate Deprecate save-state and set-output commands in CI
**Summary**

Ref: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Our workflow will print warnings like:

```shell
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

We should migrate them.

### PR DESCRIPTION
**Pull request by miles170**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Replace deprecating `set-output` command with `$GITHUB_OUTPUT`.

Closes #8342.

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]
Great! Thanks for your contribution~

**Comment by miles170** [comment]
It seems `$GITHUB_OUTPUT` doesn't play well with `composite runs`.

**Comment by miles170** [comment]
`Error: System.ArgumentException: Unexpected type 'NullToken' encountered while reading 'outputs'. The type 'MappingToken' was expected.`

I assume this error implies that we must fill `output_id`.

**Review by PsiACE — APPROVED** [review]
lgtm, thanks

**Pull request merged**
