### PR TITLE
Http handler refactor

### LINKED ISSUE #2407: [Query] long running query did not canceled in a right way in http server
**Summary**

when running some time consuming queries through http endpoint and directly shutdown client, the query still execute on query cluster rather than canceled, plus `show processlist` do not provide the information about the task.

**How to reproduce**
```bash
# send a long running query task on databend cluster, and CTRL C to cacnel it
echo "SELECT max(number) as max,sum(number) as sum FROM numbers_mt(10000000000000) GROUP BY number % 3, number % 4, number % 5" | curl -v 127.0.0.1:8000/v1/statement --data-binary @-
# show processlist
bendctl query "show processlist;" --databend_dir ./.databend
[ok] Query precheck passed!
[ok] Execute query show processlist; on mysql://root:root@127.0.0.1:3307
[ok] Connected with driver mysql (DatabendQuery v-0.1.0-7ac628f-simd(1.57.0-nightly-2021-10-23T16:18:51.253606598+00:00))
                  id                  | type  |      host       | state | database |    extra_info     | memory_usage 
--------------------------------------+-------+-----------------+-------+----------+-------------------+--------------
 57c615de-2b3e-44ec-b29e-d45e44bdc265 | MySQL | 127.0.0.1:34450 | Query | default  | show processlist; |            0 
(1 row)
```

query log
```bash
[2021-10-23T16:50:35Z INFO  databend_query] Config { config_file: "", query: QueryConfig { tenant: "test", namespace: "test_cluster", num_cpus: 8, mysql_handler_host: "127.0.0.1", mysql_handler_port: 3307, max_active_sessions: 256, clickhouse_handler_host: "127.0.0.1", clickhouse_handler_port: 9000, http_handler_host: "127.0.0.1", http_handler_port: 8000, flight_api_address: "127.0.0.1:9090", http_api_address: "127.0.0.1:8080", metric_api_address: "127.0.0.1:7070", api_tls_server_cert: "", api_tls_server_key: "", api_tls_server_root_ca_cert: "", rpc_tls_server_cert: "", rpc_tls_server_key: "key for rpc server cert", rpc_tls_query_server_root_ca_cert: "", rpc_tls_query_service_domain_name: "localhost" }, log: LogConfig { log_level: "INFO", log_dir: "./.databend/test/logs/local_query_log_0" }, meta: {meta_address: "127.0.0.1:9191", meta_user: "root", meta_password: "******"}, storage: StorageConfig { storage_type: "disk", disk: DiskStorageConfig { data_path: "/home/zhihanz/Documents/rust/src/zhihanz/zhihanz/databend/.databend/test/data" }, s3: {s3.storage.region: "", } } }
[2021-10-23T16:50:35Z INFO  databend_query] DatabendQuery v-0.1.0-7ac628f-simd(1.57.0-nightly-2021-10-23T16:18:51.253606598+00:00)
[2021-10-23T16:50:35Z INFO  databend_query] MySQL handler listening on 127.0.0.1:3307, Usage: mysql -h127.0.0.1 -P3307
[2021-10-23T16:50:35Z INFO  databend_query] ClickHouse handler listening on 127.0.0.1:9000, Usage: clickhouse-client --host 127.0.0.1 --port 9000
[2021-10-23T16:50:35Z INFO  databend_query] Http handler listening on 127.0.0.1:8000
[2021-10-23T16:50:35Z INFO  databend_query] Metric API server listening on 127.0.0.1:7070
[2021-10-23T16:50:35Z WARN  databend_query::api::http_service] Http API TLS not set
[2021-10-23T16:50:35Z INFO  databend_query] HTTP API server listening on 127.0.0.1:8080
[2021-10-23T16:50:35Z INFO  databend_query] RPC API server listening on 127.0.0.1:9090
[2021-10-23T16:50:35Z INFO  databend_query] Databend query has been registered to metastore.
[2021-10-23T16:50:35Z INFO  databend_query] Ready for connections.
[2021-10-23T16:53:10Z INFO  databend_query::sessions::context] Create DatabendQueryContext
[2021-10-23T16:54:22Z INFO  databend_query::sessions::context] Create DatabendQueryContext
[2021-10-23T16:54:22Z INFO  databend_query::sessions::context] Destroy DatabendQueryContext
[2021-10-23T16:55:48Z INFO  databend_query::servers::mysql::mysql_handler] MySQL connection coming: Ok(127.0.0.1:34450)
[2021-10-23T16:55:48Z INFO  databend_query::sessions::context] Create DatabendQueryContext
[2021-10-23T16:55:48Z INFO  databend_query::sessions::context] Destroy DatabendQueryContext
[2021-10-23T16:55:48Z INFO  databend_query::sessions::context] Create DatabendQueryContext
[2021-10-23T16:55:48Z INFO  databend_query::sessions::context] Destroy DatabendQueryContext
[2021-10-23T16:55:48Z INFO  databend_query::sessions::context] Create DatabendQueryContext
[2021-10-23T16:55:48Z INFO  databend_query::sessions::context] Destroy DatabendQueryContext
```
we could see that the http session do not destroyed

and cpu resource did not released
image

**Error message and/or stacktrace**

**Additional context**

### LINKED ISSUE #2557: http handler index route print the api usage
**Summary**

After `databend-query` starts, if we visit `http://127.0.0.1:8000/`, prints the REST api document:
```
API: /v1/statement/
Doc: the doc of this api
Example: curl --location --request POST '127.0.0.1:8001/v1/statement/' --header 'Content-Type: text/plain' --data-raw 'SELECT avg(number) FROM numbers(1000000000)'


[Others APIs]
```

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

rewrite /v1/statement, build on top of  /v1/query.

## Changelog

- Not for changelog (changelog entry is not required)

## Related Issues

Fixes #2557 
Fixes #2407

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by ZhiHanZ** [comment]
please take some doc test on cli query command to ensure the change does not affect normal usage in both interactive and non-interactive mode

**Comment by youngsofun** [comment]
@ZhiHanZ 

```
(datafuse) ➜  datafuse git:(http_handler_refactor) ✗ ./target/debug/bendctl query  --databend_dir .databend "select * from system.tables;" 
[ok] ✅ Query precheck passed!
+----------+----------------+----------------------+
| database | name           | engine               |
+----------+----------------+----------------------+
| "system" | "one"          | "SystemOne"          |
| "system" | "contributors" | "SystemContributors" |
| "system" | "databases"    | "SystemDatabases"    |
| "system" | "settings"     | "SystemSettings"     |
| "system" | "credits"      | "SystemCredits"      |
| "system" | "metrics"      | "SystemMetrics"      |
| "system" | "clusters"     | "SystemClusters"     |
| "system" | "processes"    | "SystemProcesses"    |
| "system" | "users"        | "SystemUsers"        |
| "system" | "columns"      | "SystemColumns"      |
| "system" | "functions"    | "SystemFunctions"    |
| "system" | "tables"       | "SystemTables"       |
| "system" | "tracing"      | "SystemTracing"      |
| "system" | "configs"      | "SystemConfigs"      |
+----------+----------------+----------------------+
[ok] ✅ read rows: 14, read bytes: 736 B, rows/sec: 64 (rows/sec), bytes/sec: 3.391 (KB/sec), time: 0.217 sec
```


```
(datafuse) ➜  datafuse git:(http_handler_refactor) ✗ ./target/debug/bendctl  --databend_dir .databend                                
[local] [sql]> select * from system.tables;
[ok] ✅ Query precheck passed!
+----------+----------------+----------------------+
| database | name           | engine               |
+----------+----------------+----------------------+
| "system" | "one"          | "SystemOne"          |
| "system" | "contributors" | "SystemContributors" |
| "system" | "databases"    | "SystemDatabases"    |
| "system" | "settings"     | "SystemSettings"     |
| "system" | "credits"      | "SystemCredits"      |
| "system" | "metrics"      | "SystemMetrics"      |
| "system" | "clusters"     | "SystemClusters"     |
| "system" | "processes"    | "SystemProcesses"    |
| "system" | "users"        | "SystemUsers"        |
| "system" | "columns"      | "SystemColumns"      |
| "system" | "functions"    | "SystemFunctions"    |
| "system" | "tables"       | "SystemTables"       |
| "system" | "tracing"      | "SystemTracing"      |
| "system" | "configs"      | "SystemConfigs"      |
+----------+----------------+----------------------+
[ok] ✅ read rows: 14, read bytes: 736 B, rows/sec: 1,400 (rows/sec), bytes/sec: 73.6 (KB/sec), time: 0.01 sec

```

**Review by ZhiHanZ — APPROVED** [review]

**Comment by BohuTANG** [comment]
Oops, conflicts need resolved

**Pull request merged**
