### PR TITLE
feat: change comparison result to u8

### PR DESCRIPTION
**Pull request by everpcpc**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

## Changelog

- Improvement

## Related Issues

Fixes https://github.com/datafuselabs/databend/issues/3383

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by sundy-li** [comment]
Should compare the performance of data block filter：

```
select sum(number) from numbers_mt(1000000000) where xxxx;
```

**Comment by sundy-li** [comment]
BTW, there are two approaches to make aggregate sum work with bool types.

1. Cast boolean column into u8 column before sum aggregate, this is the easy way to go.
2. Change comparison result to u8, this is the harder way:
   - Change comparison result to u8 column
   - Change function `if`
   - Change `datablock.filter`
   - Remove Boolean column and use u8 column instead.
   - ...

**Comment by everpcpc** [comment]
before:
```sql
mysql> select avg(number>10) from numbers(100);
ERROR 1105 (HY000): Code: 1010, displayText = AggregateAvgFunction does not support type 'Boolean' (while in select group by).
mysql> select sum(number) from numbers_mt(1000000000) where 2>1;
+--------------------+
| sum(number)        |
+--------------------+
| 499999999500000000 |
+--------------------+
1 row in set (4.05 sec)
Read 1000000000 rows, 8 GB in 4.030 sec., 248.16 million rows/sec., 1.99 GB/sec.

mysql> select sum(number) from numbers_mt(1000000000) where 2>1;
+--------------------+
| sum(number)        |
+--------------------+
| 499999999500000000 |
+--------------------+
1 row in set (4.04 sec)
Read 1000000000 rows, 8 GB in 4.024 sec., 248.5 million rows/sec., 1.99 GB/sec.
```

after:
```sql
mysql> select avg(number>10) from numbers(100);
+--------------------+
| avg((number > 10)) |
+--------------------+
|               0.89 |
+--------------------+
1 row in set (0.01 sec)
Read 100 rows, 800 B in 0.004 sec., 25.13 thousand rows/sec., 201.04 KB/sec.
mysql> select sum(number) from numbers_mt(1000000000) where 2>1;
+--------------------+
| sum(number)        |
+--------------------+
| 499999999500000000 |
+--------------------+
1 row in set (4.05 sec)
Read 1000000000 rows, 8 GB in 4.032 sec., 248.03 million rows/sec., 1.98 GB/sec.

mysql> select sum(number) from numbers_mt(1000000000) where 2>1;
+--------------------+
| sum(number)        |
+--------------------+
| 499999999500000000 |
+--------------------+
1 row in set (4.04 sec)
Read 1000000000 rows, 8 GB in 4.031 sec., 248.06 million rows/sec., 1.98 GB/sec.
```

**Comment by sundy-li** [comment]
`where 2>1` meets the constant folding case in:

https://github.com/datafuselabs/databend/blob/dc058c9d22baa9e61763661f77cd10ec62c87c48/common/datablocks/src/kernels/data_block_filter.rs

**Comment by everpcpc** [comment]
> 

benchmark result updated

**Comment by everpcpc** [comment]
> `where 2>1` meets the constant folding case in:
> 
> https://github.com/datafuselabs/databend/blob/dc058c9d22baa9e61763661f77cd10ec62c87c48/common/datablocks/src/kernels/data_block_filter.rs

benchmark result updated

**Comment by sundy-li** [comment]
`34.07 MB/sec.`

Should use release binary to bench, `./target/release/databend-query`

**Comment by everpcpc** [comment]
> `34.07 MB/sec.`
> 
> Should use release binary to bench, `./target/release/databend-query`

updated with release build

**Pull request closed without merging**
