### PR TITLE
fix(docker): fix certificates dependencies

### LINKED ISSUE #6134: bug: creating database using `GITHUB` engine always fails
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

databend-query v0.7.93-nightly-d6c8161-simd(rust-1.63.0-nightly-2022-06-20T16:16:37.326208256Z)

### What's Wrong?

creating database using `GITHUB` engine always fails with the following message:

```
ERROR 1105 (HY000) at line 1: Code: 1073, displayText = octocrab error, cause: HTTP Error: error sending request for url (https://api.github.com/orgs/datafuselabs/repos?type=sources&sort=pushed&direction=desc&per_page=100): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1919: (unable to get local issuer certificate)

Found at  0 <snafu::backtrace_shim::Backtrace as snafu::GenerateImplicitData>::generate::hb7ae1c076656ae1e
   /opt/rust/cargo/registry
```

### How to Reproduce?

1. Start databend using docker:
```
$ docker run --net=host --rm --name databend datafuselabs/databend
```

2. Create a database using `GITHUB` engine by mysql client:

```
$ mysql -h127.0.0.1 -uroot -P3307 -e 'CREATE DATABASE datafuselabs ENGINE=GITHUB'
ERROR 1105 (HY000) at line 1: Code: 1073, displayText = octocrab error, cause: HTTP Error: error sending request for url (https://api.github.com/orgs/datafuselabs/repos?type=sources&sort=pushed&direction=desc&per_page=100): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1919: (unable to get local issuer certificate)

Found at  0 <snafu::backtrace_shim::Backtrace as snafu::GenerateImplicitData>::generate::hb7ae1c076656ae1e
   /opt/rust/cargo/registry
```

3. Check tables in the created database:
```
$ mysql -h127.0.0.1 -uroot -P3307 -e 'SHOW TABLES FROM datafuselabs' # no tables created

```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by wfxr**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Add missing certificates dependencies to Dockerfile

## Changelog

- Bug Fix

## Related Issues

Fixes #6134

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]
LGTM, requiring @everpcpc for extra confirmation.

**Comment by Xuanwo** [comment]
@wfxr Happy to see you again!

**Review by everpcpc — APPROVED** [review]

**Comment by wfxr** [comment]
@Xuanwo Happy to see you too :)

**Comment by Xuanwo** [comment]
This PR will get merged automatically after all required checks are passed.

**Pull request merged**
