### PR TITLE
chore(http): fix query num in v1/status

### LINKED ISSUE #8895: bug:  running_queries_count in databend status is not correct
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

xxx

### What's Wrong?

we using `running_queries_count`  in http `v1/status` to know the pressure of databend, if running query is close to max settings, we stop send queries to databend.   Found that this num is not correct,  for example there are only  serval processes but `running_queries_count`  is much more bigger,  68 in our cluster.

### How to Reproduce?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by sandflee**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Closes #8895

### CODE REVIEW

**Review by BohuTANG — APPROVED** [review]

**Comment by BohuTANG** [comment]
Dev Linux / test_unit :
```
test api::http::status::test_status ... FAILED
```
https://github.com/datafuselabs/databend/actions/runs/3553269289/jobs/5968909129#step:4:2417

**Comment by sandflee** [comment]
@mergify update

**Comment by sandflee** [comment]
> Dev Linux / test_unit :
> 
> ```
> test api::http::status::test_status ... FAILED
> ```
> 
> https://github.com/datafuselabs/databend/actions/runs/3553269289/jobs/5968909129#step:4:2417

fixed.   `create_query_context_with_type` creates a active session, leading to the failure. use a DUMY session instead.

**Review by BohuTANG — APPROVED** [review]

**Comment by BohuTANG** [comment]
```
Conflicting files
src/query/service/src/sessions/session_mgr.rs
```

**Review by zhang2014 — APPROVED** [review]

**Pull request merged**
