### PR TITLE
feat: Adopt OpenDAL's batch delete support

### PR DESCRIPTION
**Pull request by Xuanwo**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Adopt OpenDAL's batch delete support for delete performance.

Closes https://github.com/datafuselabs/databend/issues/10148

### CODE REVIEW

**Comment by Xuanwo** [comment]
cc @BohuTANG, can you take a bench on it?

**Comment by Xuanwo** [comment]
Test failed, I am invetisgating.

**Comment by Xuanwo** [comment]
Also related to https://github.com/datafuselabs/opendal/issues/1396

**Comment by BohuTANG** [comment]
@mergify update

**Review by BohuTANG — APPROVED** [review]

**Pull request merged**
