### PR TITLE
chore(logging): disabled debug log to stderr for sled

### PR DESCRIPTION
**Pull request by drmingdrmer**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Related Issues

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]

**Comment by Xuanwo** [comment]
image

Seems not affected. I remember metasrv has its own logging settings.

**Comment by drmingdrmer** [comment]
> Seems not affected. I remember metasrv has its own logging settings.

Logging level in env variable should also be updated too.

**Comment by BohuTANG** [comment]
@drmingdrmer Can we change the unit test log level from DEBUG to INFO? 
DEBUG still has many logs(most are meta srv) but is not helpful most time.

**Comment by drmingdrmer** [comment]
> @drmingdrmer Can we change the unit test log level from DEBUG to INFO? DEBUG still has many logs(most are meta srv) but is not helpful most time.

Should we just stop writing debug-level logs to stderr, and instead only write debug-level logs to log-file?

**Pull request merged**
