### PR TITLE
ISSUE-3646: fix `stdout` appender not working 

### LINKED ISSUE #3646: bug: $ ./target/debug/databend-query can't print logs
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

$ ./target/debug/databend-query canot print logs

### What You Expected?

Print the INFO level logs

### How to Reproduce?

make build-debug
$ ./target/debug/databend-query

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by dantengsky**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

use `init_tracing_with`_file to initialize loggers

## Changelog

- Bug Fix
- Not for changelog (changelog entry is not required)

## Related Issues

Fixes #3646

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
Hi, this patch does not work for jager.
The workable patch please see (a review comments need fixed by @drmingdrmer )https://github.com/datafuselabs/databend/pull/3647

**Comment by dantengsky** [comment]
> Hi, this patch does not work for jager.

forget to export the `LOG_LEVEL` as well in `scripts/deploy/env_trace.sh`. After applying this modification, stdout appender, and jager do work together now.

BUT,  PR #3647 is preferred for this,  merging all the log initialization routines into one is better. This PR will be transformed to draft and close manually after #3647 is merged.

**Comment by BohuTANG** [comment]
I add LOG_LEVEL in PR #3647

**Comment by dantengsky** [comment]
closing this PR as #3647 merged

**Pull request closed without merging**
