### PR TITLE
Feature: add metrics doc, remove independent metric service from metasrv, use http service instead

### PR DESCRIPTION
**Pull request by lichuang**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

1. add metrics doc.
2. remove independent metric service from metasrv, use http service instead

## Changelog

- Improvement
- Documentation

## Related Issues

Fixes https://github.com/datafuselabs/databend/issues/5601

### CODE REVIEW

**Review by drmingdrmer — APPROVED** [review]
Looks good to me. And nice docs!

**Comment by drmingdrmer** [comment]
Need @ZhiHanZ to confirm it's OK to remove the metrics service.:)

**Comment by ZhiHanZ** [comment]
> Need @ZhiHanZ to confirm it's OK to remove the metrics service.:)

LGTM, it would simplify the meta service monitor infra

**Review by ZhiHanZ — APPROVED** [review]

**Review by drmingdrmer — APPROVED** [review]
Happy deleting codes:D

**Pull request merged**
