### PR TITLE
fix the deprecated of postcss.plugin

### LINKED ISSUE #3587: docs: postcss-px-to-viewport: postcss.plugin was deprecated
Warning during the website build.

https://vercel.com/databend/databend/5b7MmmN6AiSYU7uq22ctpX8hMVfR

```
postcss-px-to-viewport: postcss.plugin was deprecated. Migration guide:
--
<span>https://evilmartians.com/chronicles/postcss-8-plugin-migration</span>
```

---

ping @Chasen-Zhang for a look.

### PR DESCRIPTION
**Pull request by Chasen-Zhang**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

fix the deprecated of postcss.plugin

## Changelog

- Other

## Related Issues

Fixes #3587

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]
Mostly LGTM, please resolve the conflicts before merging.

**Comment by Xuanwo** [comment]
BTW, the upstream project of `postcss-px-to-viewport` is not updated since 2020-04, do we have a better choice?

**Comment by BohuTANG** [comment]
`website/databend/yarn.lock`  has confilicts need resolved

**Comment by Chasen-Zhang** [comment]
> BTW, the upstream project of `postcss-px-to-viewport` is not updated since 2020-04, do we have a better choice?

I'm going to keep an eye on this library, but for now, I'm going to use a library based on postcss-px-to-viewport.  It is OK, don't worry about it😊

**Pull request merged**
