### PR TITLE
chore(metactl): move to tools/metactl

### PR DESCRIPTION
**Pull request by PsiACE**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

chore(metactl): move to tools/metactl

It's just a simple move that doesn't look like it will break anything.

## Changelog

- Not for changelog (changelog entry is not required)

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]

**Comment by BohuTANG** [comment]
Does the `metactl` is build and in our release package?

**Comment by PsiACE** [comment]
> Does the `metactl` is build and in our release package?

It is currently not built with the `make` cmd and is not in our release.

**Comment by BohuTANG** [comment]
> > Does the `metactl` is build and in our release package?
> 
> It is currently not built with the `make` cmd and is not in our release.

I think we should built metactl to our release, could you do it in this PR? @PsiACE 
Thank you.

**Comment by PsiACE** [comment]
> I think we should built metactl to our release, could you do it in this PR?

ok

**Comment by PsiACE** [comment]
@BohuTANG @Xuanwo PTAL, I tried to add an asset called databend-tools, including metactl and benchmark.

**Pull request merged**
