### PR TITLE
feat(cluster): auto discover ip when ip is unspecified or loop back

### LINKED ISSUE #7510: Feature:  remove the host conf from flight_api_address  to simple deploy databend
**Summary**
now we must specify the host ip to flight_api_address, which means we could't simple spread the config file to multi machines.

databend master could parse the real ip from the connection,  it may not works for private networks, but maybe we could add a config option?

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

feat(cluster): auto discover ip when ip is unspecified or loop back

Fixes #7510

### CODE REVIEW

**Review by drmingdrmer — APPROVED** [review]

**Comment by sandflee** [comment]
LGTM，  except some checks failed,  `ERROR taplo: the file is not properly formatted path="/workspace/src/query/management/Cargo.toml"
`

**Review by sandflee — APPROVED** [review]

**Review by drmingdrmer — APPROVED** [review]

**Comment by BohuTANG** [comment]
@mergify update

**Comment by drmingdrmer** [comment]
@mergify update

**Comment by BohuTANG** [comment]
@mergify update

**Review by BohuTANG — APPROVED** [review]
+1

**Pull request merged**
