### PR TITLE
feat(expression): support Vector data type

### LINKED ISSUE #10769: Introduce a new data type `VECTOR` (alias of `ARRAY<Float32>`) (@b41sh )

### PR DESCRIPTION
**Pull request by b41sh**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Support the `Vector` data type, as alias of `Array<Float32>`

Closes #10769

### CODE REVIEW

**Comment by sundy-li** [comment]
Why not do it in AST Level ?

**Review by BohuTANG — APPROVED** [review]

**Comment by sundy-li** [comment]
@BohuTANG 
Subjectively adding some types by mind may make our code difficult to maintain, because it's hard to change and be compatible with the previous type version.

1. What if we want to change this to `Array<Float64>` in the future ?
2. Vector type is only used for `cosine distance calculations`, we may need a detailed RFC to determine whether and how to make DataBend a vector database.

**Comment by sundy-li** [comment]
> If we can create a index like 'create table XX(v Array(float32) index ivf_pq)' is ok, here only to do the special index.

I do prefer this.  A dynamic index is hard to maintain, considering the old version of the bloom filter index.

**Comment by BohuTANG** [comment]
@b41sh Convert this PR to draft, it's low-prority and need some proposal ok n the future, thanks.

**Review by drmingdrmer — APPROVED** [review]

**Comment by b41sh** [comment]
We don't need the `Vector` data type for now, so close this PR. We can reopen it later if needed.

**Pull request closed without merging**
