### PR TITLE
chore: updated `displayText` to `Text` in error string

### LINKED ISSUE #10253: Better `displayText` name when error
**Summary**

```
ERROR 1105 (HY000): Code: 1065, displayText = Unsupported literal value: 58750003716598352816469.
```

It would be better to:
```
ERROR 1105 (HY000): Code: 1065, Text = Unsupported literal value: 58750003716598352816469.
```

### PR DESCRIPTION
**Pull request by rkmdCodes**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Updated the error string as per required in raised issue , still working on locating the tests that need to be reconfigured.

Summary about this PR

Closes #10253

### CODE REVIEW

**Comment by BohuTANG** [comment]
Hi @rkmdCodes 

It would be helpful to run `make lint` in your locally, this will make the `Dev Linux / check` happy.
Before running it we can `make setup` to install the toolchain.

**Comment by rkmdCodes** [comment]
hi @BohuTANG , I  tried to build from source using `make setup` and `make build release`. After that I tried to run `make lint` but I got the `cargo machete` error I installed it and still got a few errors like command not found 
image

**Comment by BohuTANG** [comment]
@rkmdCodes 

`cargo machete` is not affecting the cargo format, the style it's ok now. 

The check CI failed due to the `*.yml` file, I have deleted it, it's not necessary to add it to this PR.

**Comment by BohuTANG** [comment]
Run `cargo fmt --all` on local will same as `make lint` :)

**Comment by BohuTANG** [comment]
@mergify update

**Comment by BohuTANG** [comment]
@mergify update

**Comment by BohuTANG** [comment]
@rkmdCodes 

Please rebase this PR with the main branch, the CI will be happy :)

**Comment by BohuTANG** [comment]
Hello, I was wondering if there have been any recent updates regarding this PR? If not, I would like to offer my assistance in continuing the work.

**Comment by BohuTANG** [comment]
@mergify update

**Comment by rkmdCodes** [comment]
hi @BohuTANG  sir , thanks for offering assistance I was actually stuck at this point  ,

**Comment by BohuTANG** [comment]
```
git checkout main
git pull -ap
git reset --hard origin/main

git checkout <your branch>
git merge main
```

https://github.com/datafuselabs/databend/pull/10597

**Comment by BohuTANG** [comment]
@mergify update

**Comment by BohuTANG** [comment]
@rkmdCodes Thanks for your contribution.

**Pull request merged**
