### PR TITLE
website: Upgrade depencences of website

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

website: Upgrade depencences of website

### CODE REVIEW

**Review by BohuTANG — APPROVED** [review]

**Comment by BohuTANG** [comment]
image
@Xuanwo

**Comment by Xuanwo** [comment]
> image @Xuanwo

Already addressed.

**Comment by BohuTANG** [comment]
From my preview, there are two `Guides` to show:
image

**Comment by Xuanwo** [comment]
> From my preview, there are two `Guides` to show:

Fixed.

**Comment by Xuanwo** [comment]
The links are broken, I'm working on a fix.

> At least we know the CI failed as expected (

**Comment by Xuanwo** [comment]
> The links are broken, I'm working on a fix.

Fixed.

**Pull request merged**
