### PR TITLE
clean up deps

### PR DESCRIPTION
**Pull request by light4**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Clean up deps, I wonder if it's useful.

## Changelog

- Improvement
- Build/Testing/CI
- Other 
- Not for changelog (changelog entry is not required)

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by sundy-li** [comment]
BTW， how to detect unused deps?

**Comment by light4** [comment]
https://github.com/est31/cargo-udeps
https://github.com/light4/cargo-inner, caution: this tool is unpolished.

**Comment by sundy-li** [comment]
> [est31/cargo-udeps](https://github.com/est31/cargo-udeps) [light4/cargo-inner](https://github.com/light4/cargo-inner), caution: this tool is unpolished.

So we can introduce it as a Linter in github ci workflow?

**Comment by light4** [comment]
`cargo-udeps` cannot detect indirect deps, see https://github.com/est31/cargo-udeps/issues/84
`cargo-inner` cannot find crates used by features or macros
So for now, maybe we can introduce `cargo-udeps` as a lint.

**Comment by light4** [comment]
I find the binary size reduced a little.
`585M -> 584M`

**Review by PsiACE — APPROVED** [review]
lgtm

**Pull request merged**
