### PR TITLE
refactor(geo): Refine geo base functions

### PR DESCRIPTION
**Pull request by ariesdevil**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Refine geo base functions.

Closes #issue

### CODE REVIEW

**Review by TCeason — APPROVED** [review]

**Review by Xuanwo — APPROVED** [review]
Mostly LGTM! Do we need a sqllogic test for this?

**Comment by ariesdevil** [comment]
sqllogic tests were added in the previous PR, but yes we can add more about these functions.

**Comment by BohuTANG** [comment]
/workspace/tests/suites/0_stateless/13_tpch/13_0009_q9.sql
[267](https://github.com/datafuselabs/databend/actions/runs/3941098711/jobs/6743285981#step:4:278)
 cc @leiysky @xudong963

**Comment by BohuTANG** [comment]
@soyeric128 looking forward the new geo function documents, thanks.

**Pull request merged**
