### PR TITLE
ci: Add file size watcher in CI

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

ci: Add file szie watcher in CI

### CODE REVIEW

**Review by BohuTANG — APPROVED** [review]
:100:

**Comment by Xuanwo** [comment]
Node.js sucks...

**Comment by Xuanwo** [comment]
Cc @everpcpc, `npx` will install binaries to `tmp` and than link back to `$PATH` which can't run based on current setup. Any ideas to fix this?

**Comment by everpcpc** [comment]
> Cc @everpcpc, `npx` will install binaries to `tmp` and than link back to `$PATH` which can't work based on current setup. Any ideas to fix this?

Maybe It's related to self-hosted runner, maybe we can separate this check in a new workflow?

**Comment by Xuanwo** [comment]
This PR doesn't work as expected.

**Pull request closed without merging**
