### PR TITLE
fix(mysql): fix databend float64 to mysql double

### PR DESCRIPTION
**Pull request by sandflee**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Closes #issue

### CODE REVIEW

**Comment by sandflee** [comment]
cc @sundy-li

**Review by xudong963 — APPROVED** [review]

**Review by Xuanwo — APPROVED** [review]

**Review by sundy-li — APPROVED** [review]

**Comment by sandflee** [comment]
@mergify update

**Comment by sandflee** [comment]
BTW,  all of databend integers are converted to MYSQL_TYPE_LONG, is this the  expected behavior?
```rust
                TypeID::Int8 => Ok(ColumnType::MYSQL_TYPE_LONG),
                TypeID::Int16 => Ok(ColumnType::MYSQL_TYPE_LONG),
                TypeID::Int32 => Ok(ColumnType::MYSQL_TYPE_LONG),
                TypeID::Int64 => Ok(ColumnType::MYSQL_TYPE_LONG),
                TypeID::UInt8 => Ok(ColumnType::MYSQL_TYPE_LONG),
                TypeID::UInt16 => Ok(ColumnType::MYSQL_TYPE_LONG),
                TypeID::UInt32 => Ok(ColumnType::MYSQL_TYPE_LONG),
                TypeID::UInt64 => Ok(ColumnType::MYSQL_TYPE_LONG),
```

**Comment by xudong963** [comment]
> BTW, all of databend integers are converted to MYSQL_TYPE_LONG, is this the expected behavior?
> 
> ```rust
>                 TypeID::Int8 => Ok(ColumnType::MYSQL_TYPE_LONG),
>                 TypeID::Int16 => Ok(ColumnType::MYSQL_TYPE_LONG),
>                 TypeID::Int32 => Ok(ColumnType::MYSQL_TYPE_LONG),
>                 TypeID::Int64 => Ok(ColumnType::MYSQL_TYPE_LONG),
>                 TypeID::UInt8 => Ok(ColumnType::MYSQL_TYPE_LONG),
>                 TypeID::UInt16 => Ok(ColumnType::MYSQL_TYPE_LONG),
>                 TypeID::UInt32 => Ok(ColumnType::MYSQL_TYPE_LONG),
>                 TypeID::UInt64 => Ok(ColumnType::MYSQL_TYPE_LONG),
> ```

I think it doesn't matter(no loss of precision).

**Comment by sandflee** [comment]
`MYSQL_TYPE_LONG` is 32bit not 64, seems we should use 'MYSQL_LONGLONG'  for TypeID::Int64&uint64

**Comment by sandflee** [comment]
> I think it doesn't matter(no loss of precision).

for me， I shoud pass databend data to hive， if I get query a small int column, databend produces long while hive expected small int,  there maybe some problems. so I prefer to correct it like https://dev.mysql.com/doc/c-api/8.0/en/c-api-prepared-statement-type-codes.html.

**Pull request merged**
