### PR TITLE
chore(planner): Refine stack usage of type check

### PR DESCRIPTION
**Pull request by leiysky**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Reduce stack memory usage to support deeper expression.

Before this PR, it can only support binary expression with depth 15 on my macbook pro.

After this PR, the depth is increased to 31.
image

Related to #6430

### CODE REVIEW

**Review by xudong963 — APPROVED** [review]

**Comment by Xuanwo** [comment]
```shell
  --- stderr
  error occurred: Failed to find tool. Is `musl-gcc` installed?
error: failed to run custom build command for `lz4-sys v1.9.3`
Caused by:
  process didn't exit successfully: `/workspace/target/debug/build/lz4-sys-af3f644e019d95d9/build-script-build` (exit status: 1)
```

@everpcpc PTAL

**Comment by leiysky** [comment]
@mergify update

**Comment by BohuTANG** [comment]
The CI failures are not related to this PR, please ignore.

**Comment by BohuTANG** [comment]
@mergify update

**Review by sundy-li — APPROVED** [review]

**Comment by sundy-li** [comment]
Maybe we can use RPN to replace the recursion.

**Comment by leiysky** [comment]
> Maybe we can use RPN to replace the recursion.

I was considering about that, but we have to introduce a new IR. This is not necessary for now, we can leverage with it in the future.

**Pull request merged**
