### PR TITLE
feat: support recursive cte

### PR DESCRIPTION
**Pull request by xudong963**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

Basic support recursive cte.

- Fixes https://github.com/datafuselabs/databend/issues/15228

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15675)

### CODE REVIEW

**Comment by xudong963** [comment]
ready for review

**Comment by sundy-li** [comment]
can you add a test to solve the sudo with recursive cte?

https://www.percona.com/blog/sudoku-recursive-common-table-expression-solver/

**Comment by xudong963** [comment]
> can you add a test to solve the sudoku with recursive cte?
> 
> https://www.percona.com/blog/sudoku-recursive-common-table-expression-solver/ https://siderite.dev/blog/using-cte-to-solve-sudoku-in-sql#at2254754596

Currently, we only support recursive cte referenced by one place, sudoku solver is more complex and the `digits` cte is used by multiple places.

**Review by sundy-li — APPROVED** [review]

**Comment by xudong963** [comment]
cc @soyeric128 for doc

**Comment by l1t1** [comment]
could you add a benchmark of
```sql
with recursive t as(select 1 a union all select a+1 from t where a<10000)select count(a),sum(a) from t
```

**Pull request merged**
