### PR TITLE
improve `#[serde(default)]` attr usage for some types

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

improve `#[serde(default)]` attr usage for some types

## Changelog

- Improvement

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by sundy-li** [comment]
Great~

What about `FileFormat` in 

https://github.com/datafuselabs/databend/blob/38f49251439691f76b51bedecb49f156fe7640f0/common/meta/types/src/user_stage.rs  ?

Can we use

```
#[serde(default)]
pub struct FileFormat {
    #[serde(default)]
    pub format: Format,
    pub record_delimiter: String, 
    pub field_delimiter: String, 
    pub csv_header: bool, 
    pub compression: Compression,
}
``` 

?

**Comment by koushiro** [comment]
@sundy-li what your meaning?  Add `#[serde(default)]` attribute for the `format` field?

**Comment by sundy-li** [comment]
> @sundy-li what's your meaning? Add `#[serde(default)]` attribute for the `format` field?

It seems we do not need `#[serde(default)]` in the fields attribute anymore if we introduce `#[serde(default)]` to the `FileFormat ` struct .

**Comment by koushiro** [comment]
> > @sundy-li what's your meaning? Add `#[serde(default)]` attribute for the `format` field?
> 
> It seems we do not need `#[serde(default)]` in the fields attribute anymore if we introduce `#[serde(default)]` to the `FileFormat ` struct .

Yes

**Comment by BohuTANG** [comment]
Good job!
Thank you @koushiro

**Review by PsiACE — APPROVED** [review]

**Pull request merged**
