### PR TITLE
chore(query): make copy into table support auto cast schema

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

make copy into table support auto cast schema

Closes #issue

### CODE REVIEW

**Comment by BohuTANG** [comment]
UT failed https://github.com/datafuselabs/databend/actions/runs/4453349139/jobs/7822223067?pr=10630

**Review by youngsofun — APPROVED** [review]

**Comment by youngsofun** [comment]
> UT failed https://github.com/datafuselabs/databend/actions/runs/4453349139/jobs/7822223067?pr=10630

only need to regenerate results of test_statement

**Comment by sundy-li** [comment]
> > UT failed [datafuselabs/databend/actions/runs/4453349139/jobs/7822223067?pr=10630](https://github.com/datafuselabs/databend/actions/runs/4453349139/jobs/7822223067?pr=10630)
> 
> only need to regenerate results of test_statement

I did that, I don't know why it failed in ci.

**Comment by BohuTANG** [comment]
@mergify update

**Comment by sundy-li** [comment]
Maybe a bug in ci, let's merge.

**Pull request merged**
