### PR TITLE
docs(official site): simplify command uploading file

### PR DESCRIPTION
**Pull request by doki23**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Simplify the command format.

## Changelog

simplify the command uploading files

### CODE REVIEW

**Comment by BohuTANG** [comment]
> When I copied the command to my terminal, it became
> 
> ```
> echo curl -H \"insert_sql:insert into book_db.books format CSV\" -H \"skip_header:0\" -H \"field_delimiter:','\" -H \"record_delimiter:'\n'\" -F  \"upload=@./books.csv\" -XPUT http://127.0.0.1:8081/v1/streaming_load\|bash
> ```
> 
> The `\|bash` made it failed to run, so remove the `echo ... | bash` can help avoid the problem.

Hello, what's your os?

**Comment by doki23** [comment]
macOS

**Comment by BohuTANG** [comment]
Thank you for the feedback, I will check it out tomorrow this is working on ubuntu.
Good night!

**Review by BohuTANG — APPROVED** [review]
Thank you!

**Comment by xudong963** [comment]
Nice to see you in the databend community too! @doki23

**Pull request merged**
