### PR TITLE
chore(planner): Improve join reorder algorithm

### PR DESCRIPTION
**Pull request by leiysky**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Introduce exchange rules to extend search space.

Also, introduce `AppliedRules` for `Memo` to reduce duplicated rule applications.

After this PR, the optimizer will generate bushy join trees.

### CODE REVIEW

**Comment by leiysky** [comment]
@mergify update

**Comment by BohuTANG** [comment]
test_sqllogic_base_cluster_linux and test_sqllogic_ydb_cluster_linux timeout after 30m.

**Comment by xudong963** [comment]
@mergify update

**Comment by xudong963** [comment]
> test_sqllogic_base_cluster_linux and test_sqllogic_ydb_cluster_linux timeout after 30m.

Seems related to https://github.com/datafuselabs/databend/issues/9558

**Review by xudong963 — APPROVED** [review]

**Comment by leiysky** [comment]
@mergify update

**Comment by leiysky** [comment]
@mergify requeue

**Pull request merged**
