### PR TITLE
feat(observability): replace metrics-rs with prometheus-client

### LINKED ISSUE #12688: observability: switch to prometheus-client in query execution

### LINKED ISSUE #12870: observability: replace the metrics_table with prometheus-client, and removes metrics-rs

### PR DESCRIPTION
**Pull request by flaneur2020**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

This PR migrated all the metrics into prometheus-client, and:

- [x] change the /metrics endpoint to promtheus-client
- [x] unit test about the metrics endpoint
- [x] change the metrics-table to prometheus-client
- [x] remove metric-rs's recorder
- ~support reset metrics~ (in another PR)

Closes #12688
Closes #12870

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12787)

### CODE REVIEW

**Review by Xuanwo — COMMENTED** [review]
Please enable opendal's prometheus layer and disable it's metrics layer  to make it work with databend.

**Comment by flaneur2020** [comment]
> Please enable opendal's prometheus layer and disable it's metrics layer to make it work with databend.

I tried upgrade opendal but failed due to the api seems changed a lot, I choose to only disable the MetricsLayer in this PR yet, and enable the prometheus client layer later after opendal upgraded.

It seems that currently there's a StorageMetricsAccessor which also covers the metrics on accessing opendal, I suppose that StorageMetricsAccessor could be removed after the opendal upgraded with PrometheusClientLayer enabled.

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 39 of 40 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12787)* status: 40 of 42 files reviewed, all discussions resolved (waiting on @Xuanwo)

**Comment by Xuanwo** [comment]
Hi, this PR contains breaking changes introduced in OpenDAL v0.40.0, please read our upgrade note carefully to make sure nothing is broken: https://opendal.apache.org/docs/rust/opendal/docs/upgrade/index.html#upgrade-to-v040

**Comment by Xuanwo** [comment]
> Hi, this PR contains breaking changes introduced in OpenDAL v0.40.0, please read our upgrade note carefully to make sure nothing is broken: https://opendal.apache.org/docs/rust/opendal/docs/upgrade/index.html#upgrade-to-v040

Oh, please ignore this comment. Seems opendal not upgraded yet.

**Review by Xuanwo — APPROVED** [review]

**Pull request merged**
