### PR TITLE
docs: Update streaming load docs and tests

### PR DESCRIPTION
**Pull request by ariesdevil**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Streaming load using the new syntax, so update streaming load docs and tests.

Closes #issue

### CODE REVIEW

**Comment by ariesdevil** [comment]
The stateful CI seems not running, how to force run it?

**Comment by everpcpc** [comment]
Try rebase and force push?

**Review by TCeason — APPROVED** [review]
LGTM. cc @soyeric128

**Comment by youngsofun** [comment]
@PsiACE  this will be a breaking change, can we advance notice it in change log and Databend Weekly？
https://github.com/datafuselabs/databend/pull/9063

**Pull request merged**
