### PR TITLE
feat(expr): add `DataType::Map(T)`

### PR DESCRIPTION
**Pull request by andylokandy**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

- Add a static typed `Map(T)` which is an alias of `Array(Tuple(String, T))`.

Tracked in https://github.com/datafuselabs/databend/issues/6547

### CODE REVIEW

**Comment by sundy-li** [comment]
`DataType::Map<T>` is different to `DataType::Variant` in the datavalues.

**Comment by b41sh** [comment]
> `DataType::Map<T>` is different to `DataType::Variant` in the datavalues.

We can use `Map<T>` instead of `VariantObject`, just like `Array<T>` instead of `VariantArray`. Because both `VariantArray` and `VariantObject` are actually a special type of `Variant`, keeping too many types at the same time can lead to confusion for users.

**Comment by sundy-li** [comment]
> We can use Map<T> instead of VariantObject

`Map<T>` is similar to `Map<K,V>` of ClickHouse , https://clickhouse.com/docs/en/sql-reference/data-types/map.

But its key is Fixed to String type, it can not be used instead of `VariantObject` because `T` is a fixed type but `VariantObject`  is a variant type.

**Comment by andylokandy** [comment]
@sundy-li 

> Map<T> is similar to Map<K,V> of ClickHouse , https://clickhouse.com/docs/en/sql-reference/data-types/map.

We can free the `K` from the String type if we want to.

> But its key is Fixed to String type, it can not be used instead of VariantObject because T is a fixed type but VariantObject is a variant type.

`VariantMap` is semantically equal to `Map<Variant>`.

> I don't think it's ok to have Map<T> because we have to care about the behavior of duplicated keys inside the tuple.

The uniqueness of keys is invariant and should be checked on constructing a map.

**Comment by sundy-li** [comment]
> We can free the K from the String type if we want to.

Yes, better to have K instead of String.

I was thinking that whether should we have a new datatype named `Map`.  Since we will have `Variant` type which could cover:  

1. `1`
2. `'1'`
3.  `{"x" : "y"}`
4. `{"x" :   {"a" : 3 }    }`
5. ..

**Comment by andylokandy** [comment]
> Yes, better to have K instead of String.

I'm worried about whether the user will use other types as keys. cc @BohuTANG 

> I was thinking that whether should we have a new datatype named Map. Since we will have Variant type which could cover:

Once we have static `Map`, the `Map` will become one of the variants of `Variant`. See more in https://github.com/datafuselabs/databend/issues/6634#issuecomment-1195768310

**Comment by sundy-li** [comment]
Oh, I get it now.

**Review by sundy-li — APPROVED** [review]

**Review by BohuTANG — APPROVED** [review]

**Pull request merged**
