### PR TITLE
[test]: test: filter stdout to let result matching easier

### PR DESCRIPTION
**Pull request by drmingdrmer**
This is not meant for merge but to solve a testing issue in  @GanZiheng 's  PR
- fix: #3319
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

### CODE REVIEW

**Comment by sundy-li** [comment]
I think it's too redundant, we can write shell/python scripts.

https://github.com/datafuselabs/databend/blob/main/tests/suites/0_stateless/00_0000_dummy_select_sh.sh

**Comment by drmingdrmer** [comment]
> I think it's too redundant, we can write shell/python scripts.
> 
> https://github.com/datafuselabs/databend/blob/main/tests/suites/0_stateless/00_0000_dummy_select_sh.sh
> 
> shell pipeline grep should fix this case.

IMHO, we should avoid using shell script and provide a way that is easier than writing a script for developers to transform the unstable result(such as date/time):

- Handling string literal is a disaster in shell, e.g. there is no way to escape a single quote in a string quoted with single quote.
- python `re` has less surprises than grep or sed.
- shell scripts are less portable than python. E.g. On mac `gsed` is the gnu compatible `sed` and  that `sed` and `gsed` on mac have different meanings for option `-i`.

**Comment by sundy-li** [comment]
So how about using python scripts, we support all executable scripts (python,shell,golang,perl ..) , all we need to do is make the file executable.

python: https://github.com/datafuselabs/databend/blob/ac5a59358873347495b8b14456279d3938d829c5/tests/suites/0_stateless/12_0000_insert_into_select2.py

**Comment by BohuTANG** [comment]
I perfer using python script for the special test, it is programable.

We would choose a option, this is blocked https://github.com/datafuselabs/databend/pull/3319/files#diff-887f7231188d935f381b467a8a38898e98bb09ac489678fdb692c9fa115a8482R80

Or we merged #3319 first and then change the test to python script.
@drmingdrmer @sundy-li what do you think? :thinking:

**Comment by drmingdrmer** [comment]
> I perfer using python script for the special test, it is programable.
> 
> We would choose a option, this is blocked https://github.com/datafuselabs/databend/pull/3319/files#diff-887f7231188d935f381b467a8a38898e98bb09ac489678fdb692c9fa115a8482R80
> 
> Or we merged #3319 first and then change the test to python script. @drmingdrmer @sundy-li what do you think? 🤔

@sundy-li 
@BohuTANG 

There are two problems around this issue:
- dynamic input: the input sql for a test is not static or the test has to setup supporting resources such as s3.
- dynamic output: the output of a test varies depending on the environment, even with the same input sql. I.e., `select now()`

pyhon/shell script is meant to solve the first problem.
Something like a result filter in my sub-PR is to solve the second one.

**Pull request merged**
