### PR TITLE
refactor(query): rename some array functions add array_ prefix

### PR DESCRIPTION
**Pull request by b41sh**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

rename some array functions add `array_` prefix
```
remove_first -> array_remove_first
remove_last -> array_remove_last
concat -> array_concat
prepend -> array_prepend
append -> array_append
indexof -> array_indexof
```

Closes #issue

### CODE REVIEW

**Review by BohuTANG — APPROVED** [review]

**Comment by BohuTANG** [comment]
@soyeric128 it's time to add ARRAY to https://databend.rs/doc/reference/functions/semi-structured-functions

**Comment by b41sh** [comment]
> @soyeric128 it's time to add ARRAY functions to https://databend.rs/doc/reference/functions/semi-structured-functions

@BohuTANG How about adding a new category, `Nested` functions or `Array` functions? since the `Array` type is not `semi-structured`.

**Comment by BohuTANG** [comment]
@b41sh 

Categories:
[Semi-structured Data Functions](https://docs.snowflake.com/en/sql-reference/functions-semistructured.html) (Array/Object)

**Comment by andylokandy** [comment]
Snowflake's Array is indeed semi-structured, while databend's Array is strongly typed. Anyway, it'll be nice to follow to the convention.

**Pull request merged**
