### PR TITLE
feat: initial support of TOP k syntax

### PR DESCRIPTION
**Pull request by ZhengLin-Li**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

Hi, I am new to this project and found the following issue interesting. I plan to submit this PR to address the issue. This is my initial implementation, not sure if it will work. Any comments or guidance are more than welcome! Thanks!

- Fixes https://github.com/datafuselabs/databend/issues/14972

## Tests

- [ ] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [x] No Test  - Just a initial support, not sure if on the right track, will add tests after reviewing

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14998)

### CODE REVIEW

**Comment by sundy-li** [comment]
@ZhengLin-Li thanks for your contribution.

@b41sh can give you some guides about how to add this feature.

**Comment by b41sh** [comment]
Hi, @ZhengLin-Li Thanks for your interest in Databend and your willingness to contribute code.
The top n syntax is used in the select statement, so we'd be better off adding an Option `top_n` field to `SelectStmt`, similar to the `distinct` and `hints` fields.
You'll also need to test the code locally before committing it to make sure the ci test can pass.

**Comment by b41sh** [comment]
Hi @ZhengLin-Li Any progress this week? If you have questions you can just ask and I'll try to answer them

**Comment by TCeason** [comment]
Hi @ZhengLin-Li  don't know if you have spare time to complete this task, if you don't have time or no reply, I will take over this task next week

**Comment by TCeason** [comment]
Thanks for your contribute. Now this task link to https://github.com/datafuselabs/databend/pull/15318

**Pull request closed without merging**
