### PR TITLE
*: Adopting the new format macro

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

This PR adopts the new format macro from `format!("{}", e)` to `format!("{e}")`. Make our code more readable.

## Changelog

- Improvement

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
Magic.
Is there any documentation about this format style?

**Comment by Xuanwo** [comment]
> Magic. Is there any documentation about this format style?

The `format!` not updated so far, we have to read the RFC: https://rust-lang.github.io/rfcs/2795-format-args-implicit-identifiers.html

**Review by PsiACE — APPROVED** [review]
I absolutely love it!

**Pull request merged**
