### PR TITLE
chore(query): add debug assert that reproduces meta inconsistent bug of ALTER

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Closes #issue

### CODE REVIEW

**Comment by sundy-li** [comment]
There must be a terrible bug in alter table statement.

It will make column meta inconsistent and cause process panic.

**Review by lichuang — APPROVED** [review]

**Comment by sundy-li** [comment]
@lichuang  This is not for merge, it proves that DDL had bugs.

**Comment by lichuang** [comment]
Test DDL:
```
DROP TABLE IF EXISTS `05_0028_at_t3`;
CREATE TABLE `05_0028_at_t3`(a Array(UInt8));
INSERT INTO TABLE `05_0028_at_t3` values([101,2]);
```

after insert `Array` type values, the `total_rows` of array return `num_values`, which in there case is 2, so assert failed.But for a nested data type, it is OK.

**Comment by sundy-li** [comment]
@lichuang  got that, maybe you can add more debug_assert for untested types. This could detect bugs in ci.

**Pull request closed without merging**
