### PR TITLE
ci: improve logictest output

### LINKED ISSUE #6696: Improve the SQL Logic Test Output
Can we improve the output?

```shell
    results: [(<re.Match object; span=(0, 4), match='----'>, 215, '1680 222 1 112.0 674\n1826 222 1 122.0 738\n1902 222 4 127.0 760\n1985 333 4 132.0 793\n2046 222 2 137.0 827\n2202 444 2 147.0 880\n2281 333 1 152.0 905\n2432 444 1 162.0 966\n2501 333 1 167.0 1000\n2654 444 1 177.0 1057\n2728 333 3 182.0 1096\n3175 333 3 212.0 1277\n3331 222 1 222.0 1338\n3473 333 1 232.0 1391\n3553 444 1 237.0 1416\n3706 111 2 247.0 1484')],
    runs_on: {'clickhouse', 'mysql', 'http'},
```

I expect to read:

```shell
Expected:

xxx

Actual:

xxx
```

It could be better in diff-style.

_Originally posted by @Xuanwo in https://github.com/datafuselabs/databend/issues/6681#issuecomment-1188626717_

### PR DESCRIPTION
**Pull request by ZeaLoVe**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

1. Add runner info in failed statement message
2. Every error will return statement message and some message about error type
3. Use left aligned in query result compare message 
4. Add some doc about writing logictest case file

Fixes #6696

### CODE REVIEW

**Comment by ZeaLoVe** [comment]
error message like:

image

**Review by sundy-li — APPROVED** [review]

**Review by BohuTANG — APPROVED** [review]

**Comment by ZeaLoVe** [comment]
cc @leiysky  test failed by a explain statement

EPhihpNCh2

**Review by leiysky — APPROVED** [review]

**Comment by leiysky** [comment]
> cc @leiysky test failed by a explain statement
> 
> EPhihpNCh2

@dantengsky PTAL

**Comment by dantengsky** [comment]
> > cc @leiysky test failed by a explain statement
> > EPhihpNCh2
> 
> @dantengsky PTAL

@ZeaLoVe @leiysky 
that seems to be caused by false positive pruning.  please ignore it.  let me try fix it.

**Pull request merged**
