### PR TITLE
feat(query): support h3_to_center_child/h3_exact_edge_length_m/... function

### PR DESCRIPTION
**Pull request by nange**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

1. Support `h3_to_center_child`, `h3_exact_edge_length_m`, `h3_exact_edge_length_km`,  `h3_exact_edge_length_rads`, `h3_num_hexagons`, `h3_line`, `h3_distance`, `h3_hex_ring`, `h3_get_unidirectional_edge`.
2. Fix a bug in  `h3_k_ring` function.

- Related #6390

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12386)

### CODE REVIEW

**Comment by ariesdevil** [comment]
@nange you can add `order by` to force the output ordered.

**Comment by nange** [comment]
Hi @ariesdevil . There's another issue: we can't ordered the output if it is an `ArrayType`. 
The error message is:
`ERROR 1105 (HY000): Unimplemented. Code: 1002, Text = Row format is not yet support for [SortField { data_type: Array(Number(UInt64)), asc: true, nulls_first: false }].`

**Comment by ariesdevil** [comment]
order by not supporting array type, apply order by to primitive type or return single value in SQL logic test's result.

**Comment by nange** [comment]
All fixed. @ariesdevil PTAL.

**Review by ariesdevil — APPROVED** [review]

**Pull request merged**
