### PR TITLE
ci: Move check to self-hosted runners

### PR DESCRIPTION
**Pull request by everpcpc**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

## Changelog

- Not for changelog (changelog entry is not required)

## Related Issues

Fixes #issue

### CODE REVIEW

**Comment by Xuanwo** [comment]
https://github.com/datafuselabs/databend/pull/5759 is trying to fix this issue in another way.

Move `check` and `unit_test` to our self-host runners. (fix the one who raises the problem!)

**Comment by Xuanwo** [comment]
Our self-hosted runner has 1min quicker than github's.

**Comment by Xuanwo** [comment]
unit tests can move to self-hosted runners too.

**Comment by Xuanwo** [comment]
Before：

image


This PR：

image

**Comment by Xuanwo** [comment]
image

Seems the runner is OOM. Maybe we need to increase the memory limit.

**Comment by everpcpc** [comment]
We need a Kubernetes feature in 1.23 (https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes) for better handling ephemeral volumes, which is not currently available in EKS.
EKS seems to release 1.23 by  the end of the month, we will migrate unit test then.

**Review by Xuanwo — APPROVED** [review]

**Review by PsiACE — APPROVED** [review]

**Pull request merged**
