### PR TITLE
[metasrv] remove old MetaApi related code

### PR DESCRIPTION
**Pull request by drmingdrmer**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

##### [metasrv] remove old MetaApi related code
Share related codes are removed in this commit.

- Fix: #5207

## Related Issues

### CODE REVIEW

**Comment by drmingdrmer** [comment]
@youngsofun `Share` related codes are removed in this commit.
You may want to backup these codes:)

**Review by BohuTANG — APPROVED** [review]
Deleting code is more fun than writing it, hahah

**Comment by Xuanwo** [comment]
Oh, I love removing code!

**Comment by BohuTANG** [comment]
xp has written more code in order to remove these codes

> Oh, I love removing code!

image
In order to remove these codes, xp has written more codes :crying_cat_face:

**Comment by drmingdrmer** [comment]
> In order to remove these codes, xp has written more codes 😿

Sounds like a rebirth 🤔 
image

**Pull request merged**
