### PR TITLE
feat: data time travel "select at"

### LINKED ISSUE #5516: Feature: support basic `select at` statement
**Summary:**
  
  Enhance the select query, so that a time point can be specified, sth like this
  
  `select * from t at(offset => -2) as t where ...`
  
  https://docs.snowflake.com/en/sql-reference/constructs/at-before.html
  
  A basic idea of impl (not a strict requirement, any other functionality equivalent impls are ok)
  - enhance the corresponding parser components
     encode the timepoint specification (the `at(offset...)` parts) into `DfQueryStatement`
  - carries the timepoint spec all the way to `ToReadDataSourcePlan::read_plan_with_catalog`   
     - detects if the underlying table instance support time travel.
     - if it does, navigate there, and construct the `ReadDataSourcePlan` accordingly
     
     also see https://github.com/datafuselabs/databend/issues/5514

### PR DESCRIPTION
**Pull request by dantengsky**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Basic `select at` syntax supports, **Legacy Parser ONLY**

`select * from t12_0004 at (snapshot => "98ec833d7806463ba71cfb6a13fa12c3");`

~~~
mysql> create table t12_0004(c int);
Query OK, 0 rows affected (0.09 sec)
Read 0 rows, 0.00 B in 0.045 sec., 0 rows/sec., 0.00 B/sec.

mysql> insert into t12_0004 values(1),(2);
Query OK, 0 rows affected (0.04 sec)
Read 2 rows, 8.00 B in 0.028 sec., 71.33 rows/sec., 285.32 B/sec.

mysql> insert into t12_0004 values(3);
Query OK, 0 rows affected (0.06 sec)
Read 1 rows, 4.00 B in 0.029 sec., 34.72 rows/sec., 138.89 B/sec.

mysql> select * from t12_0004;
+------+
| c    |
+------+
|    1 |
|    2 |
|    3 |
+------+
3 rows in set (0.04 sec)
Read 3 rows, 12.00 B in 0.006 sec., 486.07 rows/sec., 1.90 KiB/sec.

mysql> select * from fuse_snapshot('default', 't12_0004');
+----------------------------------+-----------------------------------------------------+----------------+----------------------------------+---------------+-------------+-----------+--------------------+------------------+
| snapshot_id                      | snapshot_location                                   | format_version | previous_snapshot_id             | segment_count | block_count | row_count | bytes_uncompressed | bytes_compressed |
+----------------------------------+-----------------------------------------------------+----------------+----------------------------------+---------------+-------------+-----------+--------------------+------------------+
| 1e046191e45848b5b59e414811930d95 | 1/1583/_ss/1e046191e45848b5b59e414811930d95_v1.json |              1 | 98ec833d7806463ba71cfb6a13fa12c3 |             2 |           2 |         3 |                 12 |              372 |
| 98ec833d7806463ba71cfb6a13fa12c3 | 1/1583/_ss/98ec833d7806463ba71cfb6a13fa12c3_v1.json |              1 | NULL                             |             1 |           1 |         2 |                  8 |              188 |
+----------------------------------+-----------------------------------------------------+----------------+----------------------------------+---------------+-------------+-----------+--------------------+------------------+
2 rows in set (0.03 sec)
Read 2 rows, 366.00 B in 0.007 sec., 305.18 rows/sec., 54.54 KiB/sec.

mysql> select * from t12_0004 at (snapshot => "98ec833d7806463ba71cfb6a13fa12c3");
+------+
| c    |
+------+
|    1 |
|    2 |
+------+
2 rows in set (0.03 sec)
Read 2 rows, 8.00 B in 0.005 sec., 427.27 rows/sec., 1.67 KiB/sec.
~~~

## Changelog

- New Feature
- Documentation
- Not for changelog (changelog entry is not required)

## Related Issues

Fixes #5516

### CODE REVIEW

**Comment by BohuTANG** [comment]
Do we plan to support
 `SELECT ...
FROM ...
  {
   AT (TIMESTAMP|)
  }
`
?

**Comment by dantengsky** [comment]
> Do we plan to support `SELECT ... FROM ... { AT (TIMESTAMP|) } ` ?

yes,  storage layer is ready. 

https://github.com/datafuselabs/databend/blob/e164aa23933781abb757b0666b655461481dcdbb/query/src/storages/fuse/operations/navigate.rs#L32-L36

in this pr, syntax that is most easily to be implemented  and tested is chose :)

**Comment by Xuanwo** [comment]
@dantengsky 's fork name (`fuse-query`) represent a history :1st_place_medal:

**Comment by BohuTANG** [comment]
How about run this statement in the new planner?  If it not working we should adapter it in the new planner.

**Comment by dantengsky** [comment]
> How about run this statement in the new planner? If it not working we should adapter it in the new planner.

How about trying it in another PR? seems it is much more involved than simple syntax adaption like `drop all`

**Review by BohuTANG — APPROVED** [review]

**Pull request merged**
