### PR TITLE
[common/meta] refactor: rename get_tables to list_tables

### PR DESCRIPTION
**Pull request by drmingdrmer**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Changelog

- Improvement

## Related Issues

### CODE REVIEW

**Comment by BohuTANG** [comment]
/lgtm

Ask a question here:
how can i add a `engine` filed to the `DatabaseInfo` and deal it internal the metasrv:
https://github.com/datafuselabs/databend/blob/9ed709b8e7791074a56678d3d6f8fa5615ce9e0f/common/meta/types/src/database.rs#L18-L22

It  will need at this PR:
https://github.com/datafuselabs/databend/pull/2930/files#diff-a74f09da3b101f6ef49dfbf4c675c0999b28c7d518eeaa57137a22639d90f83cR58

**Comment by BohuTANG** [comment]
Oh, I edited my last approve comments, it merged by the bot :sad

**Comment by drmingdrmer** [comment]
> /lgtm
> 
> Ask a question here: how can i add a `engine` filed to the `DatabaseInfo` and deal it internal the metasrv:
> 
> https://github.com/datafuselabs/databend/blob/9ed709b8e7791074a56678d3d6f8fa5615ce9e0f/common/meta/types/src/database.rs#L18-L22
> 
> It will need at this PR: https://github.com/datafuselabs/databend/pull/2930/files#diff-a74f09da3b101f6ef49dfbf4c675c0999b28c7d518eeaa57137a22639d90f83cR103-R118

As I recalled we had decided to remove db.engine and leave only one database type: the `default` one.
And variant data sources are meant to be implemented at `table` level, i.e., by introducing new `table.engine`s.

Thus `db.engine` is removed.

It can be added back. Not a big deal. 🤔

**Comment by BohuTANG** [comment]
The `engine` here is just used to mark this database type for special scenarios, for the most part we can leave it empty, which I've almost done in #2930 , but this logic is completely different from the previous one we removed.

**Comment by drmingdrmer** [comment]
> The `engine` here is just used to mark this database type for special scenarios, for the most part we can leave it empty, which I've almost done in #2930 , but this logic is completely different from the previous one we removed.

Got it. And we need to save db.engine into metasrv.

**Pull request merged**
