### PR TITLE
chore: Update ignored CVE reported by cargo-audit

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

chore: Update ignored CVE reported by cargo-audit

This PR will fix CI check failure.

### CODE REVIEW

**Review by PsiACE — COMMENTED** [review]
lgtm, but for RUSTSEC-2022-0032

https://github.com/datafuselabs/databend/pull/6067/commits/a2bde3e61d23efa7136c0db873b73bc5a8c920b0

**Comment by Xuanwo** [comment]
> lgtm, but for RUSTSEC-2022-0032
> 
> [a2bde3e](https://github.com/datafuselabs/databend/commit/a2bde3e61d23efa7136c0db873b73bc5a8c920b0)

`openssl-src` is used everywhere, update version in query can't fix this:

```txt
openssl-src 111.21.0+1.1.1p
└── openssl-sys 0.9.74
    ├── openssl 0.10.40
    │   ├── native-tls 0.2.10
    │   │   ├── tokio-native-tls 0.3.0
    │   │   │   ├── reqwest 0.11.11
    │   │   │   │   ├── sentry 0.27.0
    │   │   │   │   │   ├── databend-query 0.1.0
    │   │   │   │   │   │   └── databend-fuzz 0.1.0
    │   │   │   │   │   └── databend-meta 0.1.0
    │   │   │   │   │       ├── databend-metactl 0.1.0
    │   │   │   │   │       └── databend-metabench 0.1.0
    │   │   │   │   ├── octocrab 0.16.0
    │   │   │   │   │   ├── databend-query 0.1.0
    │   │   │   │   │   └── common-exception 0.1.0
    │   │   │   │   │       ├── databend-query 0.1.0
    │   │   │   │   │       ├── databend-meta 0.1.0
    │   │   │   │   │       ├── common-streams 0.1.0
    │   │   │   │   │       │   └── databend-query 0.1.0
    │   │   │   │   │       ├── common-planners 0.1.0
    │   │   │   │   │       │   └── databend-query 0.1.0
    │   │   │   │   │       ├── common-metrics 0.1.0
    │   │   │   │   │       │   ├── databend-query 0.1.0
    │   │   │   │   │       │   └── common-meta-grpc 0.1.0
    │   │   │   │   │       │       ├── databend-query 0.1.0
    │   │   │   │   │       │       ├── databend-metactl 0.1.0
    │   │   │   │   │       │       ├── databend-metabench 0.1.0
    │   │   │   │   │       │       ├── databend-meta 0.1.0
    │   │   │   │   │       │       └── common-meta-store 0.1.0
    │   │   │   │   │       │           └── databend-query 0.1.0
    │   │   │   │   │       ├── common-meta-types 0.1.0
    │   │   │   │   │       │   ├── databend-query 0.1.0
    │   │   │   │   │       │   ├── databend-metactl 0.1.0
    │   │   │   │   │       │   ├── databend-metabench 0.1.0
    │   │   │   │   │       │   ├── databend-meta 0.1.0
    │   │   │   │   │       │   ├── common-proto-conv 0.1.0
    │   │   │   │   │       │   │   ├── common-meta-grpc 0.1.0
    │   │   │   │   │       │   │   ├── common-meta-api 0.1.0
    │   │   │   │   │       │   │   │   ├── databend-query 0.1.0
    │   │   │   │   │       │   │   │   ├── databend-metactl 0.1.0
    │   │   │   │   │       │   │   │   ├── databend-metabench 0.1.0
    │   │   │   │   │       │   │   │   ├── databend-meta 0.1.0
    │   │   │   │   │       │   │   │   ├── common-meta-store 0.1.0
    │   │   │   │   │       │   │   │   ├── common-meta-raft-store 0.1.0
    │   │   │   │   │       │   │   │   │   ├── databend-query 0.1.0
    │   │   │   │   │       │   │   │   │   ├── databend-metactl 0.1.0
    │   │   │   │   │       │   │   │   │   ├── databend-meta 0.1.0
    │   │   │   │   │       │   │   │   │   └── common-meta-embedded 0.1.0
    │   │   │   │   │       │   │   │   │       ├── databend-query 0.1.0
    │   │   │   │   │       │   │   │   │       ├── common-meta-store 0.1.0
    │   │   │   │   │       │   │   │   │       └── common-management 0.1.0
    │   │   │   │   │       │   │   │   │           └── databend-query 0.1.0
    │   │   │   │   │       │   │   │   ├── common-meta-grpc 0.1.0
    │   │   │   │   │       │   │   │   ├── common-meta-embedded 0.1.0
    │   │   │   │   │       │   │   │   └── common-management 0.1.0
    │   │   │   │   │       │   │   └── common-management 0.1.0
    │   │   │   │   │       │   ├── common-planners 0.1.0
    │   │   │   │   │       │   ├── common-meta-store 0.1.0
    │   │   │   │   │       │   ├── common-meta-sled-store 0.1.0
    │   │   │   │   │       │   │   ├── databend-query 0.1.0
    │   │   │   │   │       │   │   ├── databend-metactl 0.1.0
    │   │   │   │   │       │   │   ├── databend-meta 0.1.0
    │   │   │   │   │       │   │   ├── common-meta-raft-store 0.1.0
    │   │   │   │   │       │   │   └── common-meta-embedded 0.1.0
    │   │   │   │   │       │   ├── common-meta-raft-store 0.1.0
    │   │   │   │   │       │   ├── common-meta-grpc 0.1.0
    │   │   │   │   │       │   ├── common-meta-embedded 0.1.0
    │   │   │   │   │       │   ├── common-meta-app 0.1.0
    │   │   │   │   │       │   │   ├── databend-query 0.1.0
    │   │   │   │   │       │   │   ├── databend-metabench 0.1.0
    │   │   │   │   │       │   │   ├── common-proto-conv 0.1.0
    │   │   │   │   │       │   │   ├── common-planners 0.1.0
    │   │   │   │   │       │   │   ├── common-meta-grpc 0.1.0
    │   │   │   │   │       │   │   └── common-meta-api 0.1.0
    │   │   │   │   │       │   ├── common-meta-api 0.1.0
    │   │   │   │   │       │   ├── common-management 0.1.0
    │   │   │   │   │       │   └── common-ast 0.1.0
    │   │   │   │   │       │       ├── databend-query 0.1.0
    │   │   │   │   │       │       └── common-management 0.1.0
    │   │   │   │   │       ├── common-meta-store 0.1.0
    │   │   │   │   │       ├── common-meta-raft-store 0.1.0
    │   │   │   │   │       ├── common-meta-grpc 0.1.0
    │   │   │   │   │       ├── common-meta-embedded 0.1.0
    │   │   │   │   │       ├── common-meta-app 0.1.0
    │   │   │   │   │       ├── common-meta-api 0.1.0
    │   │   │   │   │       ├── common-management 0.1.0
    │   │   │   │   │       ├── common-io 0.1.0
    │   │   │   │   │       │   ├── databend-query 0.1.0
    │   │   │   │   │       │   ├── common-streams 0.1.0
    │   │   │   │   │       │   ├── common-proto-conv 0.1.0
    │   │   │   │   │       │   ├── common-meta-types 0.1.0
    │   │   │   │   │       │   ├── common-meta-raft-store 0.1.0
    │   │   │   │   │       │   ├── common-meta-app 0.1.0
    │   │   │   │   │       │   ├── common-management 0.1.0
    │   │   │   │   │       │   ├── common-functions 0.1.0
    │   │   │   │   │       │   │   ├── databend-query 0.1.0
    │   │   │   │   │       │   │   ├── common-streams 0.1.0
    │   │   │   │   │       │   │   ├── common-planners 0.1.0
    │   │   │   │   │       │   │   ├── common-management 0.1.0
    │   │   │   │   │       │   │   └── common-ast 0.1.0
    │   │   │   │   │       │   ├── common-formats 0.1.0
    │   │   │   │   │       │   │   └── databend-query 0.1.0
    │   │   │   │   │       │   ├── common-datavalues 0.1.0
    │   │   │   │   │       │   │   ├── databend-query 0.1.0
    │   │   │   │   │       │   │   ├── common-streams 0.1.0
    │   │   │   │   │       │   │   ├── common-proto-conv 0.1.0
    │   │   │   │   │       │   │   ├── common-planners 0.1.0
    │   │   │   │   │       │   │   ├── common-meta-types 0.1.0
    │   │   │   │   │       │   │   ├── common-meta-app 0.1.0
    │   │   │   │   │       │   │   ├── common-meta-api 0.1.0
    │   │   │   │   │       │   │   ├── common-management 0.1.0
    │   │   │   │   │       │   │   ├── common-functions 0.1.0
    │   │   │   │   │       │   │   ├── common-formats 0.1.0
    │   │   │   │   │       │   │   ├── common-datablocks 0.1.0
    │   │   │   │   │       │   │   │   ├── databend-query 0.1.0
    │   │   │   │   │       │   │   │   ├── common-streams 0.1.0
    │   │   │   │   │       │   │   │   ├── common-planners 0.1.0
    │   │   │   │   │       │   │   │   ├── common-functions 0.1.0
    │   │   │   │   │       │   │   │   └── common-formats 0.1.0
    │   │   │   │   │       │   │   ├── common-ast 0.1.0
    │   │   │   │   │       │   │   └── codegen 0.1.0
    │   │   │   │   │       │   └── common-datablocks 0.1.0
    │   │   │   │   │       ├── common-grpc 0.1.0
    │   │   │   │   │       │   ├── databend-query 0.1.0
    │   │   │   │   │       │   ├── databend-meta 0.1.0
    │   │   │   │   │       │   ├── common-meta-store 0.1.0
    │   │   │   │   │       │   ├── common-meta-raft-store 0.1.0
    │   │   │   │   │       │   └── common-meta-grpc 0.1.0
    │   │   │   │   │       ├── common-functions 0.1.0
    │   │   │   │   │       ├── common-formats 0.1.0
    │   │   │   │   │       ├── common-datavalues 0.1.0
    │   │   │   │   │       ├── common-datablocks 0.1.0
    │   │   │   │   │       ├── common-cache 0.1.0
    │   │   │   │   │       │   └── databend-query 0.1.0
    │   │   │   │   │       ├── common-base 0.1.0
    │   │   │   │   │       │   ├── databend-query 0.1.0
    │   │   │   │   │       │   ├── databend-metactl 0.1.0
    │   │   │   │   │       │   ├── databend-metabench 0.1.0
    │   │   │   │   │       │   ├── databend-meta 0.1.0
    │   │   │   │   │       │   ├── common-streams 0.1.0
    │   │   │   │   │       │   ├── common-metrics 0.1.0
    │   │   │   │   │       │   ├── common-meta-sled-store 0.1.0
    │   │   │   │   │       │   ├── common-meta-raft-store 0.1.0
    │   │   │   │   │       │   ├── common-meta-grpc 0.1.0
    │   │   │   │   │       │   ├── common-meta-embedded 0.1.0
    │   │   │   │   │       │   ├── common-meta-api 0.1.0
    │   │   │   │   │       │   ├── common-management 0.1.0
    │   │   │   │   │       │   ├── common-grpc 0.1.0
    │   │   │   │   │       │   ├── common-datavalues 0.1.0
    │   │   │   │   │       │   ├── common-datablocks 0.1.0
    │   │   │   │   │       │   ├── common-contexts 0.1.0
    │   │   │   │   │       │   │   └── databend-query 0.1.0
    │   │   │   │   │       │   └── common-ast 0.1.0
    │   │   │   │   │       └── common-ast 0.1.0
    │   │   │   │   ├── jwtk 0.2.4
    │   │   │   │   │   └── databend-query 0.1.0
    │   │   │   │   ├── databend-query 0.1.0
    │   │   │   │   └── databend-meta 0.1.0
    │   │   │   ├── mysql_async 0.30.0
    │   │   │   │   └── databend-query 0.1.0
    │   │   │   └── hyper-tls 0.5.0
    │   │   │       ├── reqwest 0.11.11
    │   │   │       └── opendal 0.9.1
    │   │   │           ├── databend-query 0.1.0
    │   │   │           ├── common-streams 0.1.0
    │   │   │           ├── common-io 0.1.0
    │   │   │           └── common-contexts 0.1.0
    │   │   ├── reqwest 0.11.11
    │   │   ├── mysql_async 0.30.0
    │   │   └── hyper-tls 0.5.0
    │   ├── jwtk 0.2.4
    │   └── databend-query 0.1.0
    ├── native-tls 0.2.10
    ├── jwtk 0.2.4
    ├── curl-sys 0.4.55+curl-7.83.1
    │   ├── isahc 1.7.2
    │   │   └── reqsign 0.1.1
    │   │       └── opendal 0.9.1
    │   └── curl 0.4.43
    │       └── isahc 1.7.2
    └── curl 0.4.43
```

**Comment by PsiACE** [comment]
> `openssl-src` is used everywhere, update version in query can't fix this:

I don't think so, because it's updated in `Cargo.lock`. Normally, I would avoid changes in `Cargo.toml` and just keep the changes to `Cargo.lock`.

**Comment by Xuanwo** [comment]
> I don't think so, because it's updated in `Cargo.lock`

Oh, yeah. You are correct! I will cherry-pick this change.

**Comment by dantengsky** [comment]
> > `openssl-src` is used everywhere, update version in query can't fix this:
> 
> I don't think so, because it's updated in `Cargo.lock`. Normally, I would avoid changes in `Cargo.toml` and just keep the changes to `Cargo.lock`.

tried “cargo audit fix”，but failed. after that the caogo.toml is tweaked mannually，and local cargo audit passed. but as @PsiACE  said modifications of cargo.lock themself should be enough

**Comment by Xuanwo** [comment]
> Normally, I would avoid changes in `Cargo.toml` and just keep the changes to `Cargo.lock`.

Can you explain how this could happen? I mean, `Cargo.lock` is not intended to be updated manully.

**Comment by Xuanwo** [comment]
> but as @PsiACE said modifications of cargo.lock themself should be enough

No LGTM to me, we should avoid change `Cargo.lock` by hand as it can be regenerated at any time which could overwrite our changes.

**Review by PsiACE — APPROVED** [review]

**Review by zhang2014 — APPROVED** [review]

**Comment by dantengsky** [comment]
> > Normally, I would avoid changes in `Cargo.toml` and just keep the changes to `Cargo.lock`.
> 
> Can you explain how this could happen? I mean, `Cargo.lock` is not intended to be updated manully.

cargo update？ https://doc.rust-lang.org/cargo/commands/cargo-update.html

**Comment by Xuanwo** [comment]
> cargo update？ https://doc.rust-lang.org/cargo/commands/cargo-update.html

The point is we should use cargo instead of change by hand.

**Comment by dantengsky** [comment]
> > but as @PsiACE said modifications of cargo.lock themself should be enough
> 
> No LGTM to me, we should avoid change `Cargo.lock` by hand as it can be regenerated at any time which could overwrite our changes.

the cargo.lock is not changed by hand，at least not directly

**Comment by Xuanwo** [comment]
@PsiACE @dantengsky I camp up a better idea, PTAL: https://github.com/datafuselabs/databend/pull/6483/commits/4993da9a5e19bc6d49ec872157c9ea407b6d8f2e

**Comment by Xuanwo** [comment]
> the cargo.lock is not changed by hand，at least not directly

I got it, thanks for explaining :laughing:

**Comment by PsiACE** [comment]
> Can you explain how this could happen? I mean, Cargo.lock is not intended to be updated manully.

`cargo update` or `cargo upgrade` (cargo-edit) should support some automated work, and if memory serves `upgrade` can be done only for a particular crate. 

But in fact, I may occasionally hack manually, as we `Cargo.lock` is released with the source and the dependencies rarely change during the build.

**Comment by PsiACE** [comment]
> I camp up a better idea, PTAL: [4993da9](https://github.com/datafuselabs/databend/commit/4993da9a5e19bc6d49ec872157c9ea407b6d8f2e)

hakari in databend way, :tada: it looks like we can go a little further

**Comment by Xuanwo** [comment]
After `check` passed, we can merge this PR directly. (There is a known ci failure for musl build)

**Comment by BohuTANG** [comment]
```
unused dependencies:
`common-dep-hack v0.1.0 (/workspace/common/dep-hack)`
└─── dependencies
     └─── "openssl-src"
Note: These dependencies might be used by other targets.
      To find dependencies that are not used by any target, enable `--all-targets`.
Note: They might be false-positive.
      For example, `cargo-udeps` cannot detect usage of crates that are only used in doc-tests.
      To ignore some dependencies, write `package.metadata.cargo-udeps.ignore` in Cargo.toml.
Error: Process completed with exit code 1.
```

**Comment by Xuanwo** [comment]
> ```
> unused dependencies:
> `common-dep-hack v0.1.0 (/workspace/common/dep-hack)`
> └─── dependencies
>      └─── "openssl-src"
> Note: These dependencies might be used by other targets.
>       To find dependencies that are not used by any target, enable `--all-targets`.
> Note: They might be false-positive.
>       For example, `cargo-udeps` cannot detect usage of crates that are only used in doc-tests.
>       To ignore some dependencies, write `package.metadata.cargo-udeps.ignore` in Cargo.toml.
> Error: Process completed with exit code 1.
> ```

Addressed.

**Pull request merged**
