### PR TITLE
refactor: refector ShareMeta struct

### PR DESCRIPTION
**Pull request by lichuang**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

refactor: refector ShareMeta struct

introduce `ShareMetaV2` as main `ShareMeta`, rename old `ShareMeta` as `ShareMetaV1`, main difference of two version share meta is:

* use `ShareTable` \ `ShareDatabase` instead of `ShareGrantObject`, make data struct more clearly;
* add `reference_database` and `reference_table` in ShareMetaV2, which is used in share view;

also, change `ShareId` kvapi prefix as `__fd_share_id_v2` instead of `__fd_share_id`, value of prefix `__fd_share_id` will access `ShareMetaV1`, when prefix `__fd_share_id_v2` will access `ShareMetaV2`.

## Tests

- [x] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [x] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16100)

### CODE REVIEW

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 2 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16100)* status: 2 of 31 files reviewed, 1 unresolved discussion (waiting on @lichuang)

___
*[`src/meta/api/src/schema_api_impl.rs` line 674 at r1](https://reviewable.io/reviews/datafuselabs/databend/16100#-O36kqHi3PW2mAHsQvAt:-O36kqHi3PW2mAHsQvAu:boaj2r0) ([raw file](https://github.com/datafuselabs/databend/blob/bea1ba70e6093a6ab76b877853afb09f0d474075/src/meta/api/src/schema_api_impl.rs#L674)):*
> ```XML
>                     old_db_id,
>                     db_meta.clone(),
>                 );
> ```

Why does `ShareGrantObjectSeqAndId` has a `db_name`? Will such a record be affected by database rename?

And it looks like `db_name` is not used yet in our codebase. Since a database is uniquely identified by `db_id, db_meta_seq`, I'd recommend removing `db_name` if possible.

```
pub enum ShareGrantObjectSeqAndId {
    // db_name, db_meta_seq, db_id, DatabaseMeta
    Database(String, u64, u64, DatabaseMeta),
```



_Code quote:_
```XML
                let seq_and_id = ShareGrantObjectSeqAndId::Database(
                    tenant_dbname.database_name().to_string(),
                    db_meta_seq,
                    old_db_id,
                    db_meta.clone(),
                );
```

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 22 of 31 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16100)* status: 27 of 31 files reviewed, 10 unresolved discussions (waiting on @lichuang)

___
*[`src/meta/app/src/share/share.rs` line 555 at r2](https://reviewable.io/reviews/datafuselabs/databend/16100#-O375H497pQkXM_drU7g:-O375H497pQkXM_drU7h:bxkjz9x) ([raw file](https://github.com/datafuselabs/databend/blob/5b5c603ffacc31b0ba578cbf48bb56da0a211a7d/src/meta/app/src/share/share.rs#L555)):*
> ```XML
> 
> #[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Eq)]
> pub enum ShareGrantObject {
> ```

Add  some doc comment explaining its purpose?
___
*[`src/meta/app/src/share/share_meta_v1.rs` line 32 at r2](https://reviewable.io/reviews/datafuselabs/databend/16100#-O375Q-kEC0LuZkuVofT:-O375Q-kEC0LuZkuVofU:bxkjz9x) ([raw file](https://github.com/datafuselabs/databend/blob/5b5c603ffacc31b0ba578cbf48bb56da0a211a7d/src/meta/app/src/share/share_meta_v1.rs#L32)):*
> ```XML
> 
> #[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Eq)]
> pub struct ShareGrantEntry {
> ```

Add  some doc comment explaining its purpose?
___
*[`src/meta/app/src/share/share_meta_v2.rs` line 30 at r2](https://reviewable.io/reviews/datafuselabs/databend/16100#-O37FzUQBr1ihN7Vq2DK:-O37FzUQBr1ihN7Vq2DL:b5yl3jz) ([raw file](https://github.com/datafuselabs/databend/blob/5b5c603ffacc31b0ba578cbf48bb56da0a211a7d/src/meta/app/src/share/share_meta_v2.rs#L30)):*
> ```XML
> pub struct ShareDatabase {
>     pub privileges: BitFlags<ShareGrantObjectPrivilege>,
>     pub name: String,
> ```

what's the name for? Make it `share_name`, `database_name` to make it clear.
___
*[`src/meta/app/src/share/share_meta_v2.rs` line 32 at r2](https://reviewable.io/reviews/datafuselabs/databend/16100#-O37G08m0pY0IGYwz1_q:-O37G08m0pY0IGYwz1_r:b-m35xwe) ([raw file](https://github.com/datafuselabs/databend/blob/5b5c603ffacc31b0ba578cbf48bb56da0a211a7d/src/meta/app/src/share/share_meta_v2.rs#L32)):*
> ```XML
>     pub name: String,
>     pub db_id: u64,
>     pub grant_on: DateTime<Utc>,
> ```

I'd recommended to use a unified name: `updated_on` or `created_on`, instead of using specific term `grant`. 
Because here `grant` is not clear on whether it is updated time or created time.
___
*[`src/meta/app/src/share/share_meta_v2.rs` line 58 at r2](https://reviewable.io/reviews/datafuselabs/databend/16100#-O379ZgvCPJzoJinzavX:-O379ZgvCPJzoJinzavY:b5yl3jz) ([raw file](https://github.com/datafuselabs/databend/blob/5b5c603ffacc31b0ba578cbf48bb56da0a211a7d/src/meta/app/src/share/share_meta_v2.rs#L58)):*
> ```XML
> pub struct ShareTable {
>     pub privileges: BitFlags<ShareGrantObjectPrivilege>,
>     pub name: String,
> ```

what's the name for? Make it `share_name`, `database_name` to make it clear.
___
*[`src/meta/app/src/share/share_meta_v2.rs` line 61 at r2](https://reviewable.io/reviews/datafuselabs/databend/16100#-O379lOG1YAXE5V2omso:-O379lOG1YAXE5V2omsp:b-m35xwe) ([raw file](https://github.com/datafuselabs/databend/blob/5b5c603ffacc31b0ba578cbf48bb56da0a211a7d/src/meta/app/src/share/share_meta_v2.rs#L61)):*
> ```XML
>     pub db_id: u64,
>     pub table_id: u64,
>     pub grant_on: DateTime<Utc>,
> ```

I'd recommended to use a unified name: `updated_on` or `created_on`, instead of using specific term `grant`. 
Because here `grant` is not clear on whether it is updated time or created time.
___
*[`src/meta/app/src/share/share_meta_v2.rs` line 65 at r2](https://reviewable.io/reviews/datafuselabs/databend/16100#-O37ArtE7p1lsYCJvvrT:-O37ArtE7p1lsYCJvvrU:undefined) ([raw file](https://github.com/datafuselabs/databend/blob/5b5c603ffacc31b0ba578cbf48bb56da0a211a7d/src/meta/app/src/share/share_meta_v2.rs#L65)):*
> ```XML
>     pub engine: String,
>     // if table is a view, save all the reference table ids
>     pub reference_table: BTreeSet<u64>,
> ```





_Suggestion:_
```XML
    pub view_reference_tables: BTreeSet<u64>,
```
___
*[`src/meta/app/src/share/share_meta_v2.rs` line 91 at r2](https://reviewable.io/reviews/datafuselabs/databend/16100#-O37GqPQ1PytVsto_9U4:-O37GqPQ1PytVsto_9U5:bgrn4ca) ([raw file](https://github.com/datafuselabs/databend/blob/5b5c603ffacc31b0ba578cbf48bb56da0a211a7d/src/meta/app/src/share/share_meta_v2.rs#L91)):*
> ```XML
> pub struct ShareReferenceTable {
>     pub privileges: BitFlags<ShareGrantObjectPrivilege>,
>     pub name: String,
> ```

Add specific qualifier to the name such as `table_name` or `database_name`
___
*[`src/meta/app/src/share/share_meta_v2.rs` line 143 at r2](https://reviewable.io/reviews/datafuselabs/databend/16100#-O37B2082pdU63GWY0Dq:-O37B2082pdU63GWY0Dr:b-mou2vx) ([raw file](https://github.com/datafuselabs/databend/blob/5b5c603ffacc31b0ba578cbf48bb56da0a211a7d/src/meta/app/src/share/share_meta_v2.rs#L143)):*
> ```XML
>     // (table name, db_id, table id)
>     Table(String, u64, u64),
> }
> ```

Why does it need to store db name and table name? what if the object is renamed?



_Code quote:_
```XML
pub enum ShareObject {
    // (db name, db id)
    Database(String, u64),
    // (table name, db_id, table id)
    Table(String, u64, u64),
}
```

**Comment by lichuang** [comment]
*[`src/meta/app/src/share/share_meta_v2.rs` line 61 at r2](https://reviewable.io/reviews/datafuselabs/databend/16100#-O379lOG1YAXE5V2omso:-O3Ar-g0696dFGClZlWp:bxt8cng) ([raw file](https://github.com/datafuselabs/databend/blob/5b5c603ffacc31b0ba578cbf48bb56da0a211a7d/src/meta/app/src/share/share_meta_v2.rs#L61)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

I'd recommended to use a unified name: `updated_on` or `created_on`, instead of using specific term `grant`. 
Because here `grant` is not clear on whether it is updated time or created time.
</blockquote></details>

grant_on means `grant xxx to share` time, not update or create time.

**Comment by lichuang** [comment]
*[`src/meta/api/src/schema_api_impl.rs` line 674 at r1](https://reviewable.io/reviews/datafuselabs/databend/16100#-O36kqHi3PW2mAHsQvAt:-O3Arv--1vC9vDxmm_Ji:bxqx20t) ([raw file](https://github.com/datafuselabs/databend/blob/bea1ba70e6093a6ab76b877853afb09f0d474075/src/meta/api/src/schema_api_impl.rs#L674)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

Why does `ShareGrantObjectSeqAndId` has a `db_name`? Will such a record be affected by database rename?

And it looks like `db_name` is not used yet in our codebase. Since a database is uniquely identified by `db_id, db_meta_seq`, I'd recommend removing `db_name` if possible.

```
pub enum ShareGrantObjectSeqAndId {
    // db_name, db_meta_seq, db_id, DatabaseMeta
    Database(String, u64, u64, DatabaseMeta),
```
</blockquote></details>

rename a share table / database will make previous `grant xxx to share` lose efficacy

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 1 of 31 files at r1, 11 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16100)* status: 30 of 34 files reviewed, all discussions resolved

**Pull request merged**
