### PR TITLE
feat: KVApi: add new method list_kv()->BoxStream

### PR DESCRIPTION
**Pull request by drmingdrmer**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

##### feat: KVApi: add new method list_kv()->BoxStream

**Compatibility change**:
This committee does not change the compatibility of databend-query. It
remains compatible with 1.1.32 and onwards. The Stream API will be used
only when databend-meta 1.2.163 is detected.

- Add new method `KVApi::list_kv()` returns a stream of key-value record,
  while `KVApi::prefix_list_kv()` returns a `Vec`.

  `prefix_list_kv()` will be deprecated soon.
  For now, it has a default implementation that collects result from
  `list_kv()` into a `Vec`, to minimize application modification.

- KVApi implementation for meta-grpc client uses stream api to retrieve
  key-values from remote meta-service. This makes it possible to fetch
  large data set without trouble.

- Server version detection: when a connection is made to a meta-server,
  it returns a server-version to the caller.

  If server-version is 1.2.63 or newer, list-kvs uses the stream api
  `kv_read_v1()`, otherwise, it reverts to old `kv_api()`.

- The return type of the Stream API has been alerted to `BoxStream`. This is
  constructed from an iterator when it reverts to using `kv_api()`.

- Fix: #13304

## Changelog

- New Feature

## Related Issues

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13348)

### CODE REVIEW

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13348)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lichuang)

**Review by lichuang — APPROVED** [review]

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13348)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @drmingdrmer)

**Comment by drmingdrmer** [comment]
Let's figure out how to maximize compatibility by letting new query access a new meta-server

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13348)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @drmingdrmer)

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13348)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lichuang)

**Review by lichuang — APPROVED** [review]

**Pull request merged**
