### PR TITLE
feat(query): show drop table support filter and limit

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

add some show commands logic test

fix: fix read_timestamp_text bug when .ms len is not equal with 3, 6, 9

- Closes #issue

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13658)

### CODE REVIEW

**Comment by TCeason** [comment]
ci test_stateless_cluster failed. https://github.com/datafuselabs/databend/actions/runs/6810163393/job/18518346739?pr=13658

But it doesn't seem to have anything to do with my changes. So I will rerun it.

```
17_0005_alter_table_modify_column_type:                                 [ FAIL ] - result differs with:
--- /runner/_work/databend/databend/tests/suites/0_stateless/17_altertable/17_0005_alter_table_modify_column_type.result	2023-11-09 10:12:12.164932617 +0000
+++ /runner/_work/databend/databend/tests/suites/0_stateless/17_altertable/17_0005_alter_table_modify_column_type.stdout	2023-11-09 10:15:20.376926991 +0000
@@ -6,7 +6,7 @@
 a	FLOAT	NO	0	
 b	VARCHAR	NO	''	
 c	INT	NO	0	
-Error: APIError: ResponseError with 1006: invalid float literal while evaluating function `to_float32('a')`
+Error: APIError: PageError with 1006: invalid float literal while evaluating function `to_float32('a')`
 Error: APIError: ResponseError with 1058: Cannot find column b
 0	1
 Error: APIError: ResponseError with 1006: invalid float literal while evaluating function `to_float32('a')`

```

**Comment by TCeason** [comment]
> ci test_stateless_cluster failed. https://github.com/datafuselabs/databend/actions/runs/6810163393/job/18518346739?pr=13658
> 
> But it doesn't seem to have anything to do with my changes. So I will rerun it.
> 
> ```
> 17_0005_alter_table_modify_column_type:                                 [ FAIL ] - result differs with:
> --- /runner/_work/databend/databend/tests/suites/0_stateless/17_altertable/17_0005_alter_table_modify_column_type.result	2023-11-09 10:12:12.164932617 +0000
> +++ /runner/_work/databend/databend/tests/suites/0_stateless/17_altertable/17_0005_alter_table_modify_column_type.stdout	2023-11-09 10:15:20.376926991 +0000
> @@ -6,7 +6,7 @@
>  a	FLOAT	NO	0	
>  b	VARCHAR	NO	''	
>  c	INT	NO	0	
> -Error: APIError: ResponseError with 1006: invalid float literal while evaluating function `to_float32('a')`
> +Error: APIError: PageError with 1006: invalid float literal while evaluating function `to_float32('a')`
>  Error: APIError: ResponseError with 1058: Cannot find column b
>  0	1
>  Error: APIError: ResponseError with 1006: invalid float literal while evaluating function `to_float32('a')`
> ```

It seems to relate to [it](https://github.com/datafuselabs/bendsql/blob/8aae0c966b4dda09478daa57851000bffaaabb29/core/src/client.rs#L273).

**Review by sundy-li — APPROVED** [review]

**Comment by everpcpc** [comment]
There seems something wrong with sqllogic test on macOS:
https://github.com/datafuselabs/databend/actions/runs/6811525621/job/18526141523

**Comment by TCeason** [comment]
> There seems something wrong with sqllogic test on macOS: https://github.com/datafuselabs/databend/actions/runs/6811525621/job/18526141523

Running Clickhouse test for file: tests/sqllogictests/suites/base/07_use/07_0000_use_database.test ...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', tests/sqllogictests/src/client/clickhouse_client.rs:101:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Process completed with exit code 101.

**Comment by TCeason** [comment]
> value: Error("expected value", line: 1, column: 1)

value: Error("expected value", line: 1, column: 1)

**Pull request merged**
