### PR TITLE
[metasrv] refactor grpc client

### PR DESCRIPTION
**Pull request by ariesdevil**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Remove unused `token` lock.
Always assign to `current_endpoint` even if `make_channel` return error.

## Changelog

- Improvement

## Related Issues

Fixes #issue

### CODE REVIEW

**Comment by Xuanwo** [comment]
@mergify update

**Review by lichuang — APPROVED** [review]

**Comment by Xuanwo** [comment]
Weird, no tests triggered. I'm investigating.

**Comment by Xuanwo** [comment]
> Weird, no tests triggered. I'm investigating.

Oh, I got it. The commit in the main branch is ignored.

**Comment by Xuanwo** [comment]
yamllint failed for

```shell
yamllint -f auto .
make: yamllint: No such file or directory
make: *** [Makefile:30: lint-yaml] Error 127
```

@everpcpc PTAL

**Comment by Xuanwo** [comment]
Thanks for the quick fix from @everpcpc, let's try again.

@mergify update

**Comment by ariesdevil** [comment]
> yamllint failed for
> 
> ```shell
> yamllint -f auto .
> make: yamllint: No such file or directory
> make: *** [Makefile:30: lint-yaml] Error 127
> ```
> 
> @everpcpc PTAL
> 
> Seems we are using the wrong image?

Still failed

**Comment by Xuanwo** [comment]
> Still failed

Image not updated, they work now!

image

**Pull request merged**
