### PR TITLE
feat(datatype): datatype timestamp with precision

### LINKED ISSUE #4994: What will the datetime data type
@sundy-li @Veeupup 

What's the databend final datetime data type is？
In some database systems(snow, [bigquery](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#timestamp_type), [duckdb](https://duckdb.org/docs/sql/data_types/timestamp), [cockroachdb](https://www.cockroachlabs.com/docs/stable/timestamp.html)), they are introduce only one type: timestamp(datetime may be a aliases name in some of them), and the range:
```
0001-01-01 00:00:00 to 9999-12-31 23:59:59.999999 UTC
```
Supports precision levels from 0 (seconds) to 6 (microseconds) .

I suggest the default is TIMESTAMP(6), what do you think?

_Originally posted by @BohuTANG in https://github.com/datafuselabs/databend/pull/4982#issuecomment-1105896600_

### PR DESCRIPTION
**Pull request by Veeupup**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

* alias datatype `timestamp` alias to `datetime` and `timestamp(n)` can have precision like `datetime(n)`
* default `timestamp` precision is `6`.

## Changelog

- New Feature

## Related Issues

Fixes #4994

### CODE REVIEW

**Comment by BohuTANG** [comment]
Cool.
It would be great to add some datetime cast or bound check in the file(it's empty now):
https://github.com/datafuselabs/databend/blob/main/tests/suites/0_stateless/11_data_type/11_0001_data_type_date_time.sql

**Review by sundy-li — APPROVED** [review]

**Comment by Veeupup** [comment]
> Cool.
> It would be great to add some datetime cast or bound check in the file(it's empty now):
> https://github.com/datafuselabs/databend/blob/main/tests/suites/0_stateless/11_data_type/[11_0001_data_type_date_time.sql
](https://github.com/datafuselabs/databend/issues/4874)
Maybe this can be fixed with this

**Comment by BohuTANG** [comment]
> > Cool.
> > It would be great to add some datetime cast or bound check in the file(it's empty now):
> 
> [https://github.com/datafuselabs/databend/blob/main/tests/suites/0_stateless/11_data_type/[11_0001_data_type_date_time.sql](https://github.com/datafuselabs/databend/blob/main/tests/suites/0_stateless/11_data_type/%5B11_0001_data_type_date_time.sql) ]
> 
> (#4874) Maybe this can be fixed with this issue

Ok, let's merge :D

**Comment by b41sh** [comment]
@Veeupup  The default precision of `datetime` has changed, so the documentation also needs to be modified.
https://github.com/datafuselabs/databend/blob/main/docs/doc/30-reference/10-data-types/20-data-type-time-date-types.md

**Comment by BohuTANG** [comment]
> @Veeupup The default precision of `datetime` has changed, so the documentation also needs to be modified. https://github.com/datafuselabs/databend/blob/main/docs/doc/30-reference/10-data-types/20-data-type-time-date-types.md

I will do that, not only the datatype also some examples.

**Comment by BohuTANG** [comment]
DATETIME should be an alias for TIMESTAMP, now databend TIMESTAMP is an alias for DATETIME.
See:
https://docs.snowflake.com/en/sql-reference/data-types-datetime.html#datetime
https://duckdb.org/docs/sql/data_types/timestamp
https://www.cockroachlabs.com/docs/stable/timestamp.html (CRDB has no DATETIME type)

cc @Veeupup @sundy-li

**Pull request merged**
