### PR TITLE
polish wall_time_ms in http handler

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

1. return wall_time_ms only after execute finished, before that it is None/nil
2. use float instead of int
3. include parse and analyze time

## Changelog

- Not for changelog (changelog entry is not required)

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by youngsofun** [comment]
\review @Chasen-Zhang

**Comment by ZhiHanZ** [comment]
overall LGTM, could you clarify the wall time in the documentation and add examples with instructions for checking on query logs for profiling time such as planner time etc

**Review by ZhiHanZ — APPROVED** [review]

**Comment by youngsofun** [comment]
> overall LGTM, could you clarify the wall time in the documentation and add examples with instructions for checking on query logs for profiling time such as planner time etc

ok

**Pull request merged**
