### PR TITLE
fix(query): fix insert default value datatype

### LINKED ISSUE #9806: bug: segment pruning failure, task 355254 panicked.
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.9.19

### What's Wrong?

segment pruning failure, task 355254 panicked.

### How to Reproduce?

```sql
DROP DATABASE IF EXISTS databend2;
CREATE DATABASE databend2;
USE databend2;
CREATE TABLE t0(c0INT INT16 NULL DEFAULT(-872582066), c1VARCHAR VARCHAR NULL, c2VARCHAR VARCHAR NULL);
CREATE TABLE t1(c0INT INT8 NULL, c1BOOLEAN BOOL NULL);
CREATE TABLE t39(c0VARCHAR VARCHAR NULL DEFAULT('cs1VaDp'));
CREATE TABLE t2(c0FLOAT FLOAT NULL, c1VARCHAR VARCHAR NULL DEFAULT('4hbF'));
INSERT INTO t2(c1varchar) VALUES ('');
INSERT INTO t1(c0int, c1boolean) VALUES (170989606, true), (-872582066, true);
INSERT INTO t2(c1varchar, c0float) VALUES ('x7cm', 0.07512109726667404);
INSERT INTO t2(c1varchar, c0float) VALUES ('tS', 0.07512109726667404), ('', 0.8786426782608032);
INSERT INTO t39(c0varchar) VALUES ('d6ImqT6xp');
INSERT INTO t1(c0int, c1boolean) VALUES (-361154226, false);
INSERT INTO t1(c1boolean, c0int) VALUES (false, -361154226);
INSERT INTO t0(c2varchar, c1varchar) VALUES ('diu7Pk', '');
INSERT INTO t1(c1boolean) VALUES (true);
INSERT INTO t39(c0varchar) VALUES ('zEgfS99S');
INSERT INTO t2(c0float) VALUES (0.08835110068321228);
SELECT * FROM (SELECT t0.c0int AS t0c0int, t0.c1varchar AS t0c1varchar, t0.c2varchar AS t0c2varchar FROM t0 WHERE (NOT (NOT (+ ((t0.c0int)+(t0.c0int))))) GROUP BY t0.c0int, t0.c1varchar, t0.c2varchar ORDER BY t0.c0int DESC, t0.c1varchar ASC LIMIT 2147483647 OFFSET 0) as result WHERE result.t0c0int = 29774 AND result.t0c1varchar = '' AND result.t0c2varchar = 'diu7Pk';
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Closes #9806

### CODE REVIEW

**Comment by RinChanNOWWW** [comment]
```sql
create table t_insert_default(a int null, b int default 2, c float, d varchar default 'd', e smallint null default -872582066);
```

What will happen if `e` is not nullable?

```
create table t_insert_default(a int null, b int default 2, c float, d varchar default 'd', e smallint default -872582066);
```

**Comment by RinChanNOWWW** [comment]
```
MySQL [(none)]> create table a (a smallint default -872582066);
Query OK, 0 rows affected (0.056 sec)

MySQL [(none)]> insert into a values(default);
ERROR 1105 (HY000): Code: 1001, displayText = number overflowed while evaluating function `to_int16(-872582066_i64)`.
```

Should we check the default value is valid when creating table?

**Review by youngsofun — APPROVED** [review]

**Comment by BohuTANG** [comment]
> ```
> MySQL [(none)]> create table a (a smallint default -872582066);
> Query OK, 0 rows affected (0.056 sec)
> 
> MySQL [(none)]> insert into a values(default);
> ERROR 1105 (HY000): Code: 1001, displayText = number overflowed while evaluating function `to_int16(-872582066_i64)`.
> ```
> 
> Should we check if the default value is valid when creating table?

MySQL:
```
create table a (a tinyint default -872582066);
Schema Error: Error: ER_INVALID_DEFAULT: Invalid default value for 'a'
```

**Comment by sundy-li** [comment]
If we don't need the default expression with other column feature (which is not enabled in MySQL), we can use constant folding and check the errors in the bind stage. 

E.g
```
a tinyint default  (b + 3) /4
```

**Comment by sundy-li** [comment]
@mergify update

**Pull request merged**
