### PR TITLE
feat: new table option `data_retention_period_in_hours`

### PR DESCRIPTION
**Pull request by dantengsky**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

Introduces new table option `data_retention_period_in_hours`, which has a higher priority to session/global level setting of `data_retention_period_in_days`, if it is set.

The min value of table `data_retention_period_in_hours` is 1 (hour), the max values of it is`config.data_retention_time_in_days_max` is specified ( or 90 days if not specified in config)

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16266)

### CODE REVIEW

**Review by SkyFan2002 — APPROVED** [review]

**Comment by sundy-li** [comment]
> which has a higher priority to session/global level setting of data_retention_period_in_days

Let's just keep config & table option.

**Comment by dantengsky** [comment]
> Let's just keep config & table option. I think maybe we don't need the setting.

do you mean we no longer need session level retention period settings?

**Comment by sundy-li** [comment]
Yes， I think keep three with priority confuse lot.

**Comment by wubx** [comment]
@soyeric128  This feature need doc.

**Pull request merged**
