### PR TITLE
chore: move range filter test to right dir

### PR DESCRIPTION
**Pull request by xudong963**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Closes #issue

### CODE REVIEW

**Comment by BohuTANG** [comment]
```
MySQL client starts to run...
Test finished, Total 1 records failed to run
0: query result mismatch:
[SQL] explain select * from t where a in (1, 2, 3, 4) order by a
[Diff] (-excepted|+actual)
    Sort
    ├── sort keys: [a ASC NULLS LAST]
    ├── estimated rows: 1.33
-   └── Filter
-       ├── filters: [contains(array(1_u8, 2_u8, 3_u8, 4_u8), t.a (#0))]
-       ├── estimated rows: 1.33
-       └── TableScan
-           ├── table: default.db_09_0009.t
-           ├── read rows: 2
-           ├── read bytes: 72
-           ├── partitions total: 3
-           ├── partitions scanned: 1
-           ├── push downs: [filters: [contains([1_u64, 2_u64, 3_u64, 4_u64], a)], limit: NONE]
-           └── estimated rows: 4.00
+   └── Exchange
+       ├── exchange type: Merge
+       └── Filter
+           ├── filters: [contains(array(1_u8, 2_u8, 3_u8, 4_u8), t.a (#0))]
+           ├── estimated rows: 1.33
+           └── TableScan
+               ├── table: default.db_09_0009.t
+               ├── read rows: 2
+               ├── read bytes: 72
+               ├── partitions total: 3
+               ├── partitions scanned: 1
+               ├── push downs: [filters: [contains([1_u64, 2_u64, 3_u64, 4_u64], a)], limit: NONE]
+               └── estimated rows: 4.00
at tests/sqllogictests/suites/base/09_fuse_engine/09_0009_range_filter:28
```

**Comment by xudong963** [comment]
> ```
> MySQL client starts to run...
> Test finished, Total 1 records failed to run
> 0: query result mismatch:
> [SQL] explain select * from t where a in (1, 2, 3, 4) order by a
> [Diff] (-excepted|+actual)
>     Sort
>     ├── sort keys: [a ASC NULLS LAST]
>     ├── estimated rows: 1.33
> -   └── Filter
> -       ├── filters: [contains(array(1_u8, 2_u8, 3_u8, 4_u8), t.a (#0))]
> -       ├── estimated rows: 1.33
> -       └── TableScan
> -           ├── table: default.db_09_0009.t
> -           ├── read rows: 2
> -           ├── read bytes: 72
> -           ├── partitions total: 3
> -           ├── partitions scanned: 1
> -           ├── push downs: [filters: [contains([1_u64, 2_u64, 3_u64, 4_u64], a)], limit: NONE]
> -           └── estimated rows: 4.00
> +   └── Exchange
> +       ├── exchange type: Merge
> +       └── Filter
> +           ├── filters: [contains(array(1_u8, 2_u8, 3_u8, 4_u8), t.a (#0))]
> +           ├── estimated rows: 1.33
> +           └── TableScan
> +               ├── table: default.db_09_0009.t
> +               ├── read rows: 2
> +               ├── read bytes: 72
> +               ├── partitions total: 3
> +               ├── partitions scanned: 1
> +               ├── push downs: [filters: [contains([1_u64, 2_u64, 3_u64, 4_u64], a)], limit: NONE]
> +               └── estimated rows: 4.00
> at tests/sqllogictests/suites/base/09_fuse_engine/09_0009_range_filter:28
> ```

The explain test is meaningless, I'll remove it.

**Comment by xudong963** [comment]
```
20_0005_mysql_auth:                                                     [ FAIL ] - Timeout!
20_0008_mysql_client_command:                                           [ OK ]
20_0010_distinct_aggr:                                                  [ OK ]
20_0011_purge_before:                                                   [ OK ]

Having 1 errors! 50 tests passed.                     0 tests skipped.
The failure tests:
    /workspace/tests/suites/0_stateless/20+_others/20_0005_mysql_auth.py
Error: Process completed with exit code 1.
```

**Pull request merged**
