### PR TITLE
create table validation

### PR DESCRIPTION
**Pull request by chienguo**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Add new feature that avoid unkown engine names at the stage of `InterpreterCreateTable`.

## Changelog

- New Feature

## Related Issues

Fixes issue https://github.com/datafuselabs/databend/issues/4441

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
```
[ FAIL ] - result differs with:
--- /Users/runner/work/databend/databend/tests/suites/0_stateless/05_ddl/05_0000_ddl_create_tables.result	2022-03-18 13:07:46.000000000 +0000
+++ /Users/runner/work/databend/databend/tests/suites/0_stateless/05_ddl/05_0000_ddl_create_tables.stdout	2022-03-18 13:10:35.000000000 +0000
@@ -1,6 +1,8 @@
 1
 2
 4
+ERROR 1105 (HY000) at line 14: Code: 2702, displayText = Expected server error code: 2302 but got: 2702.
+Unknown table engine NotExists.
 ====BEGIN TEST CREATE TABLE LIKE STATEMENT====
 8
 a	Int32	NO

```

**Comment by chienguo** [comment]
when dealing with the following sql from `tests/suites/0_stateless/05_ddl/05_0000_ddl_create_tables.sql` :
```
create table t2(a int,b int) engine=Memory;
insert into t2 values(1,1),(2,2);
select a+b from t2;
create table t2(a int,b int) engine=NotExists; -- {ErrorCode 2302}
```
what errorcode should be return? `TableAlreadyExists` or `UnknowTableEngine`?

**Comment by sundy-li** [comment]
> create table t2(a int,b int) engine=NotExists; -- {ErrorCode 2302}

Let's update the test cast to ` create table t2(a int,b int) engine=Memory; ` to cover the `TableAlreadyExists ` error.

**Review by BohuTANG — APPROVED** [review]
LGTM

Thank you @chienguo :rocket:

**Comment by chienguo** [comment]
Thank you guys!

**Pull request merged**
