### PR TITLE
TEST-3859: Refine interpreter unit test

### LINKED ISSUE #3859: Refine the interpreter unit test
Get the interpreter from the factory instead of creating them from the determinism plan :

old:
https://github.com/datafuselabs/databend/blob/9bfd5ff7ddd65aaea1c70e6c8b1d5bfeff3bfc9f/query/tests/it/interpreters/interpreter_stage_drop.rs#L38-L56

good:
https://github.com/datafuselabs/databend/blob/9bfd5ff7ddd65aaea1c70e6c8b1d5bfeff3bfc9f/query/tests/it/interpreters/interpreter_stage_create.rs#L33-L35

### PR DESCRIPTION
**Pull request by BohuTANG**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR:
1. Refine the interpreter unit test, get all the interpreter from `InterpreterFactory::get`
2. Remove` tests::parser_query`, let the dev prefer use the `PlanParser::parser`

## Changelog

- Build/Testing/CI

## Related Issues

Fixes #3859 

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by Xuanwo** [comment]
The GPG signature seems invalid.

image

**Comment by BohuTANG** [comment]
> The GPG signature seems invalid.
> 
> image

Thanks for reminding me that, i will take a look.

**Comment by BohuTANG** [comment]
GPG sig ok :D

**Review by PsiACE — APPROVED** [review]
LGTM

**Pull request merged**
