### PR TITLE
feat: add home page and other plugins

### PR DESCRIPTION
**Pull request by Chasen-Zhang**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary
add home page and other plugins
Summary about this PR #3410

## Changelog

- Documentation

### CODE REVIEW

**Review by PsiACE — APPROVED** [review]
LGTM

**Comment by BohuTANG** [comment]
Maybe we should remove the secondary page: How it work.
Give a link to our whitepaper instead of `performance` in the first page :D

**Comment by BohuTANG** [comment]
The website title also need addressed, now it's: `Hello from Databend`

**Comment by Chasen-Zhang** [comment]
> The website title also need addressed, now it's: `Hello from Databend`

How about the "Databend - A Modern Real-Time Data Processing&Analytics DBMS with Cloud-Native Architecture" instead?

**Comment by Chasen-Zhang** [comment]
> Maybe we should remove the secondary page: How it work. Give a link to our whitepaper instead of `performance` in the first page :D

Personally, I think it's a good idea to include architecture diagrams.  Can we add a whitepapers menu?

**Pull request merged**
