### PR TITLE
docs: Fixed some styling issues the Blog contacted us with

### PR DESCRIPTION
**Pull request by Carlosfengv**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Closes #issue

### CODE REVIEW

**Comment by BohuTANG** [comment]
`The Deployment has been canceled as a result of running the command defined in the "Ignored Build Step" setting.`? @PsiACE

**Comment by PsiACE** [comment]
> `The Deployment has been canceled as a result of running the command defined in the "Ignored Build Step" setting.`? 

We previously only checked if the documentation had changed and I will fix it.

**Comment by Xuanwo** [comment]
@mergify squash

**Comment by Xuanwo** [comment]
cc @Carlosfengv, please squash your PR to make the recent commit reflects the change

**Comment by BohuTANG** [comment]
@mergify update

**Pull request merged**
