### PR TITLE
ISSUE-3627: adding distributed tracing instrumentation to query

### LINKED ISSUE #3627: consider adding distributed tracing instrumentation to query
like meta-service does, by using `opentelemetry_jaeger`. It should be helpful, at least for diagnostics

### PR DESCRIPTION
**Pull request by dantengsky**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

- enable opentelemetry_jaeger for databend-query
- add instruments

**how to play:**

- bring up jaeger
   `docker run -d -p6831:6831/udp -p6832:6832/udp -p16686:16686 jaegertracing/all-in-one:latest`
-  set up env vars
   under project root path
   ~~~
   > # set up env vars: RUST_LOG, DATABEND_JAEGER, and OTEL_BSP_MAX_EXPORT_BATCH_SIZE
   > source ./scripts/deploy/env_trace.sh

   > # kick off ur favorite deploy script, e.g.
   > ./scripts/deploy/databend-query-cluster-3-nodes.sh

   > # run some sqls
   > # visit http://127.0.0.1:16686/
    
   ~~~
  

**NOTE**:

  - for transformers that implements `Processor::execute`, the name of span has been tweaked a little bit
   
     like this
     ~~~rust
      impl Processor for ProjectionTransform { 
       ...
      #[tracing::instrument(level = "info", name = "projection_execute", skip(self))]
      async fn execute(&self) -> Result<SendableDataBlockStream> {
       ... 
     ~~~
     hope it will be helpful in browsing the jaeger report
  - service-name is encoded as **databend_query-${cluster_id}@${mysql_host}:${mysql_port}**  
  - by default
    - almost all the transformers's `execute` method are traced at `INFO` level
    - distributed RPC are traced at `DEBUG` level   
  - some spawned task and stream has been instrumented manually, to make the span sensible
  
 **A sample span diagram** :

  - global tracing level INFO
  - query flight rpc's tracing level DEBUG
  - parquet-source tracing level DEBUG
     
127 0 0 1_16686_trace_382b579d57865d4dca57ac30f765c711 (1)

## Changelog

- Improvement
- Not for changelog (changelog entry is not required)

## Related Issues

Fixes #3627

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by ZhiHanZ** [comment]
can we configure on jaeger tracing address similar to metrics api server?

**Comment by dantengsky** [comment]
> can we configure on jaeger tracing address similar to metrics api server?

sure!

**Comment by BohuTANG** [comment]
> > can we configure on jaeger tracing address similar to metrics api server?
> 
> sure!

This feature will be addressed in this PR or later?

**Comment by dantengsky** [comment]
> This feature will be addressed in this PR or later?

will be addressed later,  corresponding issue is
-  https://github.com/datafuselabs/databend/issues/3633

**Pull request merged**
