### PR TITLE
refactor: reorg workspace, a basic structure

### PR DESCRIPTION
**Pull request by PsiACE**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

In this PR

-  Splitting binary targets and shared libraries. 
    - move fuzz to query/ast
    - move metabench, metactl to cmds
-  A clean root dir structure, all crates in src dir. 
    - move databend-query to query/service
    - move databend-meta to meta/service
-  Almost all meta-related crates are categorised
    - move common/meta, common/protos, common/proto-conv to meta.
    - add a `README.md` to meta dir
- edit makefile, codeowner and docs

Related #7050

### CODE REVIEW

**Comment by Xuanwo** [comment]
`targets` have different meanings in rust, and it seems we don't need to add an extra layer.

How about renaming `cmds` to `bianries`?

```
binaries
  - query
  - meta
  - metabench
  - metactl
```

**Comment by Xuanwo** [comment]
Rename `common` to `components`? Or we will do this in the next parts?

**Comment by PsiACE** [comment]
> Rename `common` to `components`? Or we will do this in the next parts?

we will do this in the next parts

**Comment by Xuanwo** [comment]
> `cargo install databend-bianries` ?

I guess we should only upload libs to `crates.io`. Binaries are so large that not suitable for users to `cargo install` them directly.

**Comment by BohuTANG** [comment]
This is a monster PR!
Can we split into more than one PR? The layout change will block many other PRs, and other PRs will block this PR too.

**Review by Xuanwo — APPROVED** [review]
Nice work!

**Comment by PsiACE** [comment]
> I guess we should only upload libs to `crates.io`. Binaries are so large that not suitable for users to `cargo install` them directly.

It has now been renamed, but I still think it can be published to crates.io, which just means that users will need to compile it themselves.

**Comment by Xuanwo** [comment]
> This is a monster PR! Can we split into more than one PR? The layout change will block many other PRs, and other PRs will block this PR too.

Most works are just renaming. git is smart enough to merge them without conflicts.

**Comment by PsiACE** [comment]
> > This is a monster PR! Can we split into more than one PR? The layout change will block many other PRs, and other PRs will block this PR too.
> 
> Most works are just renaming. git is smart enough to merge them without conflicts (I guess).

Yes, most of the time it is easy to avoid file conflicts by simply running `git pull` once. 

As we plan to introduce layout changes, I think it will be difficult to avoid blocking each other.

**Comment by BohuTANG** [comment]
Almost LGTM.
I suggest merging this PR on the weekend or when PR numbers are low, not blocking other PRs which is working.

**Review by drmingdrmer — APPROVED** [review]

**Comment by Xuanwo** [comment]
Ooops, there are many conflicts. Git is not smart enough :cry:

**Comment by PsiACE** [comment]
> I suggest merging this PR on the weekend or when PR numbers are low, not blocking other PRs which is working.

I marked it as a draft to avoid merging at an unexpected time.

> Ooops, there are many conflicts. Git is not smart enough

emmm, It requires manual confirmation of the merge. But the fact is that hardly anything has to be modified.

**Comment by Xuanwo** [comment]
This PR shows how frequently we changing our code...

**Comment by Xuanwo** [comment]
cc @PsiACE, Let's try merge this PR today!

**Comment by Xuanwo** [comment]
Github is more stupid than Git.

`git merge` works excellent, but GitHub marks it as conflicts.

**Pull request merged**
