### PR TITLE
refactor: Move configs to common so we can reuse it

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

refactor: Move configs to common so we can reuse it

For example:

- Use configs in `common_grpc`
- Use configs in `common_meta_grpc`
- TODO: Use configs in stage storage, so we don't need to declare `S3StorageConfig` twice.

## Changelog

- Improvement

### CODE REVIEW

**Comment by Xuanwo** [comment]
> * TODO: Use configs in stage storage, so we don't need to declare `S3StorageConfig` twice.

@sundy-li Is it a good idea for you?

**Comment by BohuTANG** [comment]
This is a good idea, but `query.rs` and `config.rs` are only used by the query, it's not common, preferred to keep them in `query/src/configs`.

**Comment by Xuanwo** [comment]
> but `query.rs` and `config.rs` are only used by the query, it's not common, preferred to keep them in `query/src/configs`.

`common_grpc` and `common_meta` will also depend on them to build their own conf struct.

Comparing `cfg.query.to_grpc_client_config()`, maybe it's better to use `impl From<&MetaConfig> for MetaGrpcClientConf`?

**Comment by BohuTANG** [comment]
> > but `query.rs` and `config.rs` are only used by the query, it's not common, preferred to keep them in `query/src/configs`.
> 
> `common_grpc` and `common_meta` will also depend on `config` to build their own conf struct.
> 
> Comparing `cfg.query.to_grpc_client_config()`, maybe it's better to use `impl From<&MetaConfig> for MetaGrpcClientConf`?

Ok, `config.rs` can be kept in `query/src/configs`?

**Comment by Xuanwo** [comment]
> Ok, `config.rs` can be kept in `query/src/configs`?

LGTM, I will address that.

**Review by drmingdrmer — APPROVED** [review]
LGTM:DDD

**Review by BohuTANG — APPROVED** [review]

**Pull request merged**
