### PR TITLE
refactor: system clustering_information

### PR DESCRIPTION
**Pull request by zhyass**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Add unclustered_block_count in clustering_information result.

Batch read segments, avoid oom.

- Closes #issue

### CODE REVIEW

**Comment by zhyass** [comment]
askbend:summary

**Comment by BohuTANG** [comment]
askbend:summary

**Review by sundy-li — APPROVED** [review]

**Comment by BohuTANG** [comment]
askbend:summary

**Comment by BohuTANG** [comment]
askbend:summary

**Comment by BohuTANG** [comment]
askbend:summary

**Comment by BohuTANG** [comment]
askbend:summary

**Pull request merged**
