### PR TITLE
refactor: split common-users

### PR DESCRIPTION
**Pull request by PsiACE**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

After this split:
- [x] query/users will be available as a common crate named common-users
- [x] refactor, replace query/users with common-users
  - [x] `users/auth/auth_mgr` -> `query/auth`, because of `QueryContext`

Related #6180

### CODE REVIEW

**Comment by Xuanwo** [comment]
How about moving user-related structs out of meta-types?

**Comment by PsiACE** [comment]
> How about moving user-related structs out of meta-types?

I will investigate it after replacing `query/users`.

**Review by drmingdrmer — APPROVED** [review]
looks great to me!

**Comment by BohuTANG** [comment]
looks great to me!

**Pull request merged**
