### PR TITLE
Replace AppendOperationLogEntry  vec[] with stream

### PR DESCRIPTION
**Pull request by junli1026**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

Currently AppendOperationLogEntry is returned as array, the PR is to replace with stream.

## Changelog

- Improvement

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by junli1026** [comment]
@dantengsky any interest to adopt the PR?  It changes the return type to a stream, instead of vec[].

**Comment by dantengsky** [comment]
@junli1026  

> any interest to adopt the PR? It changes the return type to a stream, instead of vec[].
 
Sure! `stream` IS preferred to `vec[]` here. 

there even was a TODO item for replacing the array with a stream, which was removed (by me, I think:) accidentally.

thanks for the contribution!

**Review by dantengsky — APPROVED** [review]
LGTM

**Review by PsiACE — APPROVED** [review]

**Pull request merged**
