### PR TITLE
chore: update rust toolchain to nightly-2024-07-02

### PR DESCRIPTION
**Pull request by andylokandy**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Tests

- [x] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [x] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16026)

### CODE REVIEW

**Comment by andylokandy** [comment]
> manifest for datafuselabs/build-tool:debian-nightly-2024-07-02 not found: manifest unknown: manifest unknown

How to resolve this error?

**Comment by andylokandy** [comment]
seems not working

**Comment by Xuanwo** [comment]
> seems not working

Let me help you do this.

**Comment by Xuanwo** [comment]
Hi, @andylokandy, please review and merge https://github.com/datafuselabs/databend/pull/16033 first.

**Review by Xuanwo — APPROVED** [review]

**Comment by Xuanwo** [comment]
Seems we can remove 

```
==> build-tool using image runner/build-tool:dev-nightly-2024-07-02
Analyzing dependencies of crates in this directory...
cargo-machete found the following unused dependencies in /workspace:
databend-common-storages-stage -- /workspace/src/query/storages/stage/Cargo.toml:
	dashmap

If you believe cargo-machete has detected an unused dependency incorrectly,
you can add the dependency to the list of dependencies to ignore in the
`[package.metadata.cargo-machete]` section of the appropriate Cargo.toml.
For example:

[package.metadata.cargo-machete]
ignored = ["prost"]

You can also try running it with the `--with-metadata` flag for better accuracy,
though this may modify your Cargo.lock files.
```

**Comment by andylokandy** [comment]
unsafe violation is detected by the new std. I'm trying to figure it out...

**Comment by andylokandy** [comment]
@ariesdevil I've disabled sanitizer check because it's not compatible with the latest toolchain.

**Comment by BohuTANG** [comment]
@andylokandy  I'll run a benchmark CI to ensure there's no regression.

**Comment by andylokandy** [comment]
benchmark seems ok

**Comment by Xuanwo** [comment]
Let's merge! This PR is waiting for so long.

**Pull request merged**
