### PR TITLE
fix: fix sub-column of added-tuple column return default 0 bug

### PR DESCRIPTION
**Pull request by lichuang**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

fix: fix sub-column of added-tuple column return default 0 bug

Closes https://github.com/datafuselabs/databend/issues/9972

### CODE REVIEW

**Comment by BohuTANG** [comment]
There's no perf comments, cc @everpcpc

**Comment by BohuTANG** [comment]
@everpcpc `ms ` should be `sec` in the perf result

**Comment by BohuTANG** [comment]
From the result of the perf bot above, it seems there is no perf issue.

**Review by b41sh — APPROVED** [review]

**Review by BohuTANG — APPROVED** [review]

**Pull request merged**
