### PR TITLE
use jwtk for es512

### PR DESCRIPTION
**Pull request by junnplus**
Signed-off-by: Ye Sijun <junnplus@gmail.com>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

`jwt-simple` does not support `ES512` algorithm, see https://github.com/jedisct1/rust-jwt-simple#jwt-simple

So I found [jwtk](https://github.com/sopium/jwtk), supports almost all JWS algorithms, both JWT and JWKS are supported. 

## Changelog

- New Feature

## Related Issues

Fixes https://github.com/datafuselabs/databend/issues/4928

### CODE REVIEW

**Review by ZhiHanZ — APPROVED** [review]

**Review by flaneur2020 — APPROVED** [review]
LGTM

**Comment by BohuTANG** [comment]
This PR can not build in MacOS from CI:
```
 cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  run pkg_config fail: "pkg-config has not been configured to support cross-compilation.\n\nInstall a sysroot for the target platform and configure it via\nPKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a\ncross-compiling wrapper for pkg-config and set it via\nPKG_CONFIG environment variable."
```

Not sure where caused it.

**Review by youngsofun — APPROVED** [review]

**Comment by youngsofun** [comment]
@junnplus is there any other choice that does not depend on openssl (like jwt-simple) ?

**Comment by youngsofun** [comment]
is this strongly required？since jwt-simple already support Ed25519 mentioned in https://github.com/datafuselabs/databend/issues/4928#issuecomment-1102755820

**Comment by junnplus** [comment]
> giving jwt-simple already support Ed25519

It seems that kms of AWS do not support the Ed25519 algorithm, we need to use kms to generate JWT token

**Comment by junnplus** [comment]
> @junnplus is there any other choice that does not depend on openssl (like jwt-simple) ?

jwt-simple does not support ES512 algorithm.

In addition, the API design of jwt-simple is not good, like [ES256PublicKey](https://docs.rs/jwt-simple/0.11.0/jwt_simple/algorithms/struct.ES256PublicKey.html), it lacks the api to convert from JWK to public key.

**Comment by Xuanwo** [comment]
[reqsign](https://github.com/Xuanwo/reqsign) uses [jsonwebtoken](https://crates.io/crates/jsonwebtoken) for JWT, does it looks good to you?

**Comment by Xuanwo** [comment]
> [reqsign](https://github.com/Xuanwo/reqsign) uses [jsonwebtoken](https://crates.io/crates/jsonwebtoken) for JWT, does it looks good to you?

Ooops, jsonwebtoken seems to lack `ES512`. Does it has anything special? It looks like we just need to add a new enum?

**Pull request merged**
