### PR TITLE
Add cluster_by field in system.tables

### PR DESCRIPTION
**Pull request by zhyass**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Add cluster_by field in system.tables

## Changelog

- Improvement

## Related Issues

Fixes #issue

### CODE REVIEW

**Comment by dantengsky** [comment]
cc @flaneur2020, please take a look & thanks

a new field `cluster_by` has been added to `system.tables`, hope this will not break things

**Review by dantengsky — APPROVED** [review]
LGTM

**Comment by flaneur2020** [comment]
> cc @flaneur2020, please take a look & thanks
> 
> a new field `cluster_by` has been added to `system.tables`, hope this will not break things

thank you for notify, I believe adding fields is safe in our systems, however we'd take care about renaming or deleting fields.

**Comment by dantengsky** [comment]
> thank you for notify, I believe adding fields is safe in our systems, however we'd take care about renaming or deleting fields.

roger

**Review by BohuTANG — APPROVED** [review]

**Pull request merged**
