### PR TITLE
refactor: use GlobalIORuntime::instance() for reading file in copy.

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Closes #issue

### CODE REVIEW

**Comment by zhang2014** [comment]
Maybe hang? CC: @dantengsky 

ref: https://github.com/datafuselabs/databend/pull/9615/files

**Comment by dantengsky** [comment]
> Maybe hang? CC: @dantengsky
> 
> ref: https://github.com/datafuselabs/databend/pull/9615/files

not sure : (  *seems* to me that it will not re-introduce the bug of https://github.com/datafuselabs/databend/issues/9576 which fixed in pr #9615

**Comment by BohuTANG** [comment]
Does this patch good to have?

**Comment by dantengsky** [comment]
@youngsofun hi, 

2023-03-15-194245_749x241_scrot

If the only concern here is to guarantee that the async closure beginning at line 204 will be executed in the thread pool of `GlobalIORuntime`,  then `tokio::spawn` should do the same job as well, since while spawning, the "current runtime" in the context, is the `GlobalIORuntime`. 

@zhang2014  Am I getting right about the behavior of  `tokio::spawn`?

**Pull request closed without merging**
