### PR TITLE
feat(query): add function NULLIF

### LINKED ISSUE #5769: NULLIF function
**Summary**

Category: Conditional Functions

The `NULLIF()` function compares two expressions and returns NULL if they are equal. Otherwise, the first expression is returned.
Syntax:
```
NULLIF( <expr1> , <expr2> )
```

Reference:
https://docs.snowflake.com/en/sql-reference/functions/nullif.html

### PR DESCRIPTION
**Pull request by RinChanNOWWW**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Add new function `NULLIF`

The NULLIF() function compares two expressions and returns NULL if they are equal. Otherwise, the first expression is returned.
Syntax:

```sql
NULLIF( <expr1> , <expr2> )
```

## Changelog

- New Feature

## Related Issues

Fixes #5769

## TODO

- [x] Add tests.
- [x] Add docs.

### CODE REVIEW

**Comment by wubx** [comment]
add a synonym： ifnull?

**Comment by RinChanNOWWW** [comment]
> add a synonym： ifnull?

The behavior is the same as `NULLIF`?

**Comment by wubx** [comment]
> > add a synonym： ifnull?
> 
> The behavior is the same as `NULLIF`?

Yes.

**Comment by wubx** [comment]
> > add a synonym： ifnull?
> 
> The behavior is the same as `NULLIF`?

Sorry, the behavior is not same. 

ifnull like : https://docs.snowflake.com/en/sql-reference/functions/ifnull.html

**Comment by BohuTANG** [comment]
> > > add a synonym： ifnull?
> > 
> > 
> > The behavior is the same as `NULLIF`?
> 
> Sorry, the behavior is not same.
> 
> ifnull like : https://docs.snowflake.com/en/sql-reference/functions/ifnull.html

We should add a new issue for it.

**Comment by sundy-li** [comment]
LGTM, Let's hold this pr after #4544 is merged

**Comment by RinChanNOWWW** [comment]
Let's merge first.

**Pull request merged**
