### PR TITLE
chore(planner): Deprecate `Project` operator

### PR DESCRIPTION
**Pull request by leiysky**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

We no longer need `Project` operator.

### CODE REVIEW

**Comment by BohuTANG** [comment]
@leiysky , 

Please rebase :), I have moved some codes from mod.rs to a single file in this PR https://github.com/datafuselabs/databend/pull/7773

**Review by xudong963 — APPROVED** [review]
The ticket will solve the issue?https://github.com/datafuselabs/databend/issues/7463

**Comment by leiysky** [comment]
> The ticket will solve the issue?#7463

Not yet, this is the prerequisite.

**Comment by leiysky** [comment]
@mergify update

**Pull request merged**
