### PR TITLE
Improve insert into select

### PR DESCRIPTION
**Pull request by BohuTANG**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

Summary about this PR:
https://github.com/datafuselabs/databend/pull/2765#discussion_r751289300

## Changelog

- Improvement

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
cc @ygf11 , since you worked in it, you might also be interested in this PR :D

**Comment by ygf11** [comment]
> cc @ygf11 , since you worked on it, you might also be interested in this PR :D

Nice, It make code cleaner.
https://github.com/datafuselabs/databend/blob/9c2e1d606688bbac5134eaaee33dfb3b798dfb8d/query/src/interpreters/interprerer_insert_into_select_test.rs#L62-L63

We can using InsertIntoInterpreter::try_create() instead of InterpreterFactory::get() here too:)

**Comment by BohuTANG** [comment]
> > cc @ygf11 , since you worked on it, you might also be interested in this PR :D
> 
> Nice, It make code cleaner.
> 
> https://github.com/datafuselabs/databend/blob/9c2e1d606688bbac5134eaaee33dfb3b798dfb8d/query/src/interpreters/interprerer_insert_into_select_test.rs#L62-L63
> 
> We can use InsertIntoInterpreter::try_create() instead of InterpreterFactory::get() here too:)

This is ok, it will test the InterpreterFactory

**Review by sundy-li — APPROVED** [review]

**Comment by BohuTANG** [comment]
Thank you @ygf11 @sundy-li

**Pull request merged**
