### PR TITLE
chore(settings): remove unused UserSettings from meta/types

### PR DESCRIPTION
**Pull request by BohuTANG**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

* Remove unused UserSettings from meta/types
* Disable macos stateless test

## Changelog

- Improvement
- Not for changelog (changelog entry is not required)

## Related Issues

Fixes #issue

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]
Any timeline to re-enable macos?

**Comment by BohuTANG** [comment]
> Any timeline to re-enable macos?

@sundy-li  is working on it, https://github.com/datafuselabs/databend/pull/5294

**Comment by fkuner** [comment]
@BohuTANG 

I am working on global setting and have a question about Why the `setting_api` and `setting_mgr` are removed in this pr?

I think we can reuse it.

**Comment by BohuTANG** [comment]
> @BohuTANG
> 
> I am working on global setting and have a question about why the `setting_api` and `setting_mgr` are removed in this pr?
> 
> I think we can reuse it.

Hmm, because no crate used them,  we can re-use them back.

**Pull request merged**
