### PR TITLE
refactor: SHOW GRANTS should not display drop on table/database

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

database/name is store with id. But different id can has same name.

e.g. 

```sql
create database a; -- id is 1
grant all on a.* to role role1;
drop database a;
create database a; -- id is 2
grant all on a.* to role role1;
```

Then show grants for role role1 will display `grant all on a.* to role role1` twice.

So show grants will not display dropped table/database.

- Part of #15052

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [x] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14931)

### CODE REVIEW

**Comment by TCeason** [comment]
After merge this pr, I think we should support two operator:

1. revoke privilege support this:

```sql
revoke <privilege_type> from db_id.* from [ user | role ];
revoke <privilege_type> from db_id.table_id from [ user | role ];
```

2. Support show grants to [ user | role ]

It will display a table format. Like this:

show grants to a;
|privilege_type|table_id|table_name|user|
|--|--|--|--|
|select|1|t|u1|

**Comment by TCeason** [comment]
In this pr, modify mget_tables and mget_databases;

bendsql --query='show grants for role role1' --time                                                                                                                                                                                       
2.272

**Comment by TCeason** [comment]
> After merge this pr, I think we should support two operator:
> 
> 1. revoke privilege support this:
> 
> ```sql
> revoke <privilege_type> from db_id.* from [ user | role ];
> revoke <privilege_type> from db_id.table_id from [ user | role ];
> ```
> 
> 2. Support show grants to [ user | role ]
> 
> It will display a table format. Like this:
> 
> show grants to a;
> 
> privilege_type	table_id	table_name	user
> select	1	t	u1

How about add revoke id from obj? cc @sundy-li

**Comment by TCeason** [comment]
Three tasks:

- [ ] show grants for <> all?
- [ ] show grants for <> as table?
- [ ] vacuum privilege

In pr https://github.com/datafuselabs/databend/pull/14931 we finish task 1.

**Review by flaneur2020 — APPROVED** [review]
LGTM

**Review by flaneur2020 — APPROVED** [review]
LGTM

**Pull request merged**
