### PR TITLE
chore(query): make agg batch mode

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

1. If aggregation with group set query has `distinct` states, we will use parallel aggregation to speed up the query. (enabled)
2. If aggregation without group set and the state support parallel merge, will use parallel merge to speed up the query. (currently disabled need future improvement to make it enable)

Closes #issue

### CODE REVIEW

**Comment by BohuTANG** [comment]
> If aggregation with group set query has distinct states, we will use parallel aggregation to speed up the query. (enabled)

Whats the performance improved?

**Comment by sundy-li** [comment]
> > If aggregation with group set query has distinct states, we will use parallel aggregation to speed up the query. (enabled)
> 
> Whats the performance improved?

In query:
```
SELECT RegionID, COUNT(DISTINCT UserID) AS u FROM hits GROUP BY RegionID ORDER BY u DESC LIMIT 10;
```
From 3 sec to 1.4 sec.

Depends on the distinct value of `RegionID`

**Review by PsiACE — APPROVED** [review]

**Comment by BohuTANG** [comment]
tpch 13_0016_q16 is affected by this PR? cc @xudong963 

```
--- /workspace/tests/suites/0_stateless/13_tpch/13_0016_q16.result	2022-11-27 09:20:11.499137767 +0000
+++ /workspace/tests/suites/0_stateless/13_tpch/13_0016_q16.stdout	2022-11-27 09:24:04.927875718 +0000
@@ -1,20 +1,20 @@
-Brand#14	SMALL ANODIZED NICKEL	45	12
-Brand#22	SMALL BURNISHED BRASS	19	12
-Brand#25	PROMO POLISHED COPPER	14	12
-Brand#35	LARGE ANODIZED STEEL	45	12
-Brand#35	PROMO BRUSHED COPPER	9	12
-Brand#51	ECONOMY ANODIZED STEEL	9	12
-Brand#53	LARGE BRUSHED NICKEL	45	12
-Brand#11	ECONOMY POLISHED COPPER	14	8
-Brand#11	LARGE PLATED STEEL	23	8
-Brand#11	PROMO POLISHED STEEL	23	8
-Brand#11	STANDARD ANODIZED COPPER	9	8
-Brand#12	ECONOMY BURNISHED BRASS	9	8
-Brand#12	LARGE ANODIZED BRASS	14	8
-Brand#12	SMALL ANODIZED TIN	23	8
-Brand#12	SMALL BRUSHED NICKEL	23	8
-Brand#12	STANDARD ANODIZED BRASS	3	8
-Brand#12	STANDARD BURNISHED TIN	23	8
-Brand#13	ECONOMY POLISHED BRASS	9	8
-Brand#13	LARGE BURNISHED COPPER	45	8
-Brand#13	MEDIUM ANODIZED STEEL	23	8
+Brand#14	SMALL ANODIZED NICKEL	45	8
+Brand#53	LARGE BRUSHED NICKEL	45	7
+Brand#21	PROMO POLISHED TIN	49	6
+Brand#25	MEDIUM BURNISHED TIN	3	6
+Brand#34	SMALL BRUSHED TIN	3	6
+Brand#42	MEDIUM PLATED COPPER	45	6
+Brand#43	PROMO BRUSHED BRASS	36	6
+Brand#51	SMALL ANODIZED COPPER	45	6
+Brand#51	SMALL BRUSHED COPPER	45	6
+Brand#52	ECONOMY PLATED TIN	19	6
+Brand#52	LARGE PLATED TIN	3	6
+Brand#53	SMALL BRUSHED COPPER	14	6
+Brand#11	PROMO POLISHED STEEL	23	5
+Brand#12	LARGE ANODIZED BRASS	14	5
+Brand#12	SMALL ANODIZED TIN	23	5
+Brand#12	SMALL BRUSHED NICKEL	23	5
+Brand#13	ECONOMY POLISHED BRASS	9	5
+Brand#13	PROMO POLISHED TIN	36	5
+Brand#14	PROMO BRUSHED STEEL	9	5
+Brand#15	ECONOMY PLATED TIN	9	5
```

**Comment by sundy-li** [comment]
> tpch 13_0016_q16 is affected by this PR? cc @xudong963
> 
> ```
> --- /workspace/tests/suites/0_stateless/13_tpch/13_0016_q16.result	2022-11-27 09:20:11.499137767 +0000
> +++ /workspace/tests/suites/0_stateless/13_tpch/13_0016_q16.stdout	2022-11-27 09:24:04.927875718 +0000
> ```

Related to Parallel aggregation merge with shuffle, I'm still looking into it.

**Pull request merged**
