### PR TITLE
[Store] support defaulting in store

### PR DESCRIPTION
**Pull request by ZhiHanZ**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

Similar to https://github.com/datafuselabs/databend/blob/master/query/src/configs/config.rs

## Changelog

- Improvement

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by drmingdrmer** [comment]
Does it build something different from `Config::empty()`?

`StructOptToml` provides an impl of `trait Default`. But it should not be used in unittest. Because it reads the CLI arguments that should be passed to `cargo test`.

That's why `Config::empty()` is introduced for building a default `Config`.

**Comment by BohuTANG** [comment]
Sorry, there is `empty`(haven't hear that before) there:
```
 <Self as StructOpt>::from_iter(&Vec::<&'static str>::new())
```
 @drmingdrmer Does it same as the `default`? If so query config can be use it too, it's simple and clear.

**Comment by drmingdrmer** [comment]
> Sorry, there is `empty`(haven't hear that before) there:
> 
> ```
>  <Self as StructOpt>::from_iter(&Vec::<&'static str>::new())
> ```
> 
> @drmingdrmer Does it same as the `default`? If so query config can be use it too, it's simple and clear.

Yes it is meant to do the same as `::default()`.

**Comment by BohuTANG** [comment]
Cool, thank you @drmingdrmer

**Pull request merged**
