### PR TITLE
store password hash instead of plaintext.

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

store password hash instead of plaintext.

## Changelog

- Not for changelog (changelog entry is not required)

## Related Issues

https://github.com/datafuselabs/databend/issues/3476

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]
Mostly LGTM, althougth I think we should not support storing plain text in any case (`PasswordHashMethod::PlainText` should not exist)

**Comment by youngsofun** [comment]
@xuanwo clickhouse support it， we introduced it at first，I will try to find a reason later，otherwise remove it.

**Comment by BohuTANG** [comment]
```
failures:

---- storages::system::users_table::test_users_table stdout ----
thread 'storages::system::users_table::test_users_table' panicked at 'assertion failed: `(left == right)`
  left: `["+-------+-----------+--------------------+------------------------------------------------------------------+", "| name  | hostname  | auth_type          | auth_string                                                      |", "+-------+-----------+--------------------+------------------------------------------------------------------+", "| test  | localhost | no_password        |                                                                  |", "| test1 | %         | plaintext_password | 123456789                                                        |", "| test1 | %         | sha256_password    | 15e2b0d3c33891ebb0f1ef609ec419420c20e320ce94c65fbc8c3312448eb225 |", "+-------+-----------+--------------------+------------------------------------------------------------------+"]`,
 right: `["+-------+-----------+--------------------+------------------------------------------------------------------+", "| name  | hostname  | auth_type          | auth_string                                                      |", "+-------+-----------+--------------------+------------------------------------------------------------------+", "| test  | localhost | no_password        |                                                                  |", "| test1 | %         | plaintext_password | 123456789                                                        |", "| test2 | %         | sha256_password    | 15e2b0d3c33891ebb0f1ef609ec419420c20e320ce94c65fbc8c3312448eb225 |", "+-------+-----------+--------------------+------------------------------------------------------------------+"]`: ""

expected:

[
    "+-------+-----------+--------------------+------------------------------------------------------------------+",
    "| name  | hostname  | auth_type          | auth_string                                                      |",
    "+-------+-----------+--------------------+------------------------------------------------------------------+",
    "| test  | localhost | no_password        |                                                                  |",
    "| test1 | %         | plaintext_password | 123456789                                                        |",
    "| test1 | %         | sha256_password    | 15e2b0d3c33891ebb0f1ef609ec419420c20e320ce94c65fbc8c3312448eb225 |",
    "+-------+-----------+--------------------+------------------------------------------------------------------+",
]
actual:

[
    "+-------+-----------+--------------------+------------------------------------------------------------------+",
    "| name  | hostname  | auth_type          | auth_string                                                      |",
    "+-------+-----------+--------------------+------------------------------------------------------------------+",
    "| test  | localhost | no_password        |                                                                  |",
    "| test1 | %         | plaintext_password | 123456789                                                        |",
    "| test2 | %         | sha256_password    | 15e2b0d3c33891ebb0f1ef609ec419420c20e320ce94c65fbc8c3312448eb225 |",
    "+-------+-----------+--------------------+------------------------------------------------------------------+",
]

```

**Pull request merged**
