### PR TITLE
fix(executor): fix dead loop for tasks

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

fix(executor): fix dead loop for tasks

## Changelog

- Bug Fix

## Related Issues

Fixes #issue

### CODE REVIEW

**Review by sundy-li — APPROVED** [review]

**Review by Xuanwo — APPROVED** [review]

**Comment by BohuTANG** [comment]
@mergify update

**Comment by BohuTANG** [comment]
Under this patch, some test failures that can be reproduced, need to check. cc @zhang2014

**Comment by sundy-li** [comment]
middle_img_v2_48b7b119-814c-4de9-86a1-2e632b94822g

Performance drawback

**Comment by zhang2014** [comment]
@sundy-li Let's look at the next day's performance test.

**Pull request merged**
