### PR TITLE
add system.stages table and show stages

### PR DESCRIPTION
**Pull request by junnplus**
Signed-off-by: Ye Sijun <junnplus@gmail.com>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

- add system.stages table 
- support show stages

```
MySQL [(none)]> show stages;
+-------+------------+---------+
| name  | stage_type | comment |
+-------+------------+---------+
| test  | Internal   |         |
| test1 | Internal   |         |
| test2 | Internal   |         |
+-------+------------+---------+
3 rows in set (0.044 sec)

MySQL [(none)]> desc stage test1;
+-------+------------+----------------------------------------------------------------+-----------------------------------------------+--------------------------------------------------------------------------------------------------------------------+---------+
| name  | stage_type | stage_params                                                   | copy_options                                  | file_format_options                                                                                                | comment |
+-------+------------+----------------------------------------------------------------+-----------------------------------------------+--------------------------------------------------------------------------------------------------------------------+---------+
| test1 | Internal   | StageParams { storage: Fs(StorageFsConfig { root: "_data" }) } | CopyOptions { on_error: None, size_limit: 0 } | FileFormatOptions { format: Csv, skip_header: 0, field_delimiter: ",", record_delimiter: "\n", compression: None } |         |
+-------+------------+----------------------------------------------------------------+-----------------------------------------------+--------------------------------------------------------------------------------------------------------------------+---------+
1 row in set (0.041 sec)

MySQL [(none)]> select * from system.stages;
+-------+------------+----------------------------------------------------------------+-----------------------------------------------+--------------------------------------------------------------------------------------------------------------------+---------+
| name  | stage_type | stage_params                                                   | copy_options                                  | file_format_options                                                                                                | comment |
+-------+------------+----------------------------------------------------------------+-----------------------------------------------+--------------------------------------------------------------------------------------------------------------------+---------+
| test  | Internal   | StageParams { storage: Fs(StorageFsConfig { root: "_data" }) } | CopyOptions { on_error: None, size_limit: 0 } | FileFormatOptions { format: Csv, skip_header: 0, field_delimiter: ",", record_delimiter: "\n", compression: None } |         |
| test1 | Internal   | StageParams { storage: Fs(StorageFsConfig { root: "_data" }) } | CopyOptions { on_error: None, size_limit: 0 } | FileFormatOptions { format: Csv, skip_header: 0, field_delimiter: ",", record_delimiter: "\n", compression: None } |         |
| test2 | Internal   | StageParams { storage: Fs(StorageFsConfig { root: "_data" }) } | CopyOptions { on_error: None, size_limit: 0 } | FileFormatOptions { format: Csv, skip_header: 0, field_delimiter: ",", record_delimiter: "\n", compression: None } |         |
+-------+------------+----------------------------------------------------------------+-----------------------------------------------+--------------------------------------------------------------------------------------------------------------------+---------+
3 rows in set (0.040 sec)
```
## Changelog

- New Feature

## Related Issues

Fixes https://github.com/datafuselabs/databend/issues/5550

### CODE REVIEW

**Comment by LiuYuHui** [comment]
> Hi, #5496 is working on the same feature too.
> 
> @LiuYuHui Are you still working on this? Let's make sure we don't have a conflict here.

Yes, I am still working on this, that's awkward, my PR is fixing issue #4488, although it has a different issue number with #5550, it contains the same content as #4488.

**Comment by BohuTANG** [comment]
Oops, Conflicting needs resolved.

**Comment by junnplus** [comment]
@LiuYuHui I'm sorry I missed #5496, thanks for your contribution!

**Comment by BohuTANG** [comment]
Hi @junnplus 

I prefer to add a stateless test for `show stages`, so we can keep moving, `unit test` can not do that.

**Review by sundy-li — APPROVED** [review]

**Review by BohuTANG — APPROVED** [review]
💯

**Pull request merged**
