### PR TITLE
fix(query): window function out of bounds access panic

### PR DESCRIPTION
**Pull request by shamb0**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

- Fixes https://github.com/datafuselabs/databend/issues/14487

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15860)

### CODE REVIEW

**Comment by shamb0** [comment]
The out-of-bounds error was caused by an underflow in the index calculation when using the default `self.peer_group_start` value.

I updated the `are_peers()` method to only use `self.peer_group_start` when `self.is_ranking` is `true`. This prevents the underflow.

I confirmed the fix resolves the reported test case failure.

```
root@localhost:8000/default> SELECT DISTINCT lead((861, FALSE, FALSE), 9, (849, TRUE, TRUE)) OVER (PARTITION BY 15560425903542832284, 965871850213131579 ORDER BY 13746504519650342222, 5897530378272856518 ASC NULLS FIRST) from range(100, 120000000, 467);

SELECT
  DISTINCT lead((861, FALSE, FALSE), 9, (849, TRUE, TRUE)) OVER (
    PARTITION BY 15560425903542832284,
    965871850213131579
    ORDER BY
      13746504519650342222,
      5897530378272856518 ASC NULLS FIRST
  )
FROM
  RANGE(100, 120000000, 467)

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ lead((861, false, false), 9, (849, true, true)) over ( partition by 15560425903542832284, 965871850213131579 order by 13746504519650342222, 5897530378272856518 asc nulls first ) │
│                                                                          Tuple(UInt16, Boolean, Boolean)                                                                          │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ (861,false,false)                                                                                                                                                                 │
│ (849,true,true)                                                                                                                                                                   │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
2 rows read in 4.064 sec. Processed 256.96 thousand rows, 1.96 MiB (63.22 thousand rows/s, 493.94 KiB/s)
```

**Comment by sundy-li** [comment]
Can you add test case as logicaltest file?

**Comment by shamb0** [comment]
> Can you add test case as logicaltest file?

Done, @sundy-li

**Comment by b41sh** [comment]
@shamb0 thanks for your contribution, but some test failed, this modification seem not correct.
https://github.com/datafuselabs/databend/actions/runs/9626684558/job/26553089343?pr=15860

**Comment by shamb0** [comment]
> @shamb0 thanks for your contribution, but some test failed, this modification seem not correct. https://github.com/datafuselabs/databend/actions/runs/9626684558/job/26553089343?pr=15860

Thanks @b41sh, for highlighting this test-case, I will pick-it up today

**Comment by b41sh** [comment]
Hi, @shamb0 This bug is caused by sorting constant value. We can determine whether the value of the order by is `ConstantExpr` or not at the binder stage, and ignore it if it is, and the code in `TransformWindow` does not need to be changed.
You can add the following code at this file.
```rust
if matches!(order, ScalarExpr::ConstantExpr(_)) {
    continue;
}
```
https://github.com/datafuselabs/databend/blob/main/src/query/sql/src/planner/semantic/type_check.rs#L1152

**Comment by shamb0** [comment]
> Hi, @shamb0 This bug is caused by sorting constant value. We can determine whether the value of the order by is `ConstantExpr` or not at the binder stage, and ignore it if it is, and the code in `TransformWindow` does not need to be changed. You can add the following code at this file.
> 
> ```rust
> if matches!(order, ScalarExpr::ConstantExpr(_)) {
>     continue;
> }
> ```
> 
> https://github.com/datafuselabs/databend/blob/main/src/query/sql/src/planner/semantic/type_check.rs#L1152

Thanks @b41sh. The proposed solution is effective and addresses the issue. All logical test suites in `window_function` now pass. I appreciate the insights provided by this solution.

**Review by b41sh — APPROVED** [review]
LGTM, cc @sundy-li

**Pull request merged**
