### PR TITLE
feat: add feature "raft-store-defensive" to enable defensive check

### PR DESCRIPTION
**Pull request by drmingdrmer**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

##### feat: add feature "raft-store-defensive" to enable defensive check

This feature enables defensive check when accessing the raft store, e.g,
it check if the next log is at index of last index plus one, when
appending logs.

For optimal performance, this feature is disabled by default.

## Changelog

- New Feature

## Related Issues

### CODE REVIEW

**Comment by Xuanwo** [comment]
> This feature enables defensive check when accessing the raft store, e.g,
> it check if the next log is at index of last index plus one, when
> appending logs.

Do you think it's a good idea to hide them under `#[cfg(debug_assertions)]` instead of features?

**Comment by drmingdrmer** [comment]
> > This feature enables defensive check when accessing the raft store, e.g,
> > it check if the next log is at index of last index plus one, when
> > appending logs.
> 
> Do you think it's a good idea to hide them under `#[cfg(debug_assertions)]` instead of features?

Sounds a good idea! I am not quite sure if it is possible to enable debug-assertions for just one crate `databend-meta`? AFAIK, enabling debug-assertions is a workspace level config. Having to enable debug-assertions for all the crates in our project feels a little bit inconvenient.

**Comment by Xuanwo** [comment]
> AFAIK, enabling debug-assertions is a workspace level config. Having to enable debug-assertions for all the crates in our project feels a little bit inconvenient.

Oh, `#[cfg(debug_assertions)]` can be added on block level. Take opendal's code for example:

```rust
pub fn to_flat_pager<A: Accessor, P>(acc: A, path: &str, size: usize) -> ToFlatPager<A, P> {
    #[cfg(debug_assertions)]
    {
        let meta = acc.info();
        debug_assert!(
            !meta.capabilities().contains(AccessorCapability::Scan),
            "service already supports scan, call to_flat_pager must be a mistake"
        );
        debug_assert!(
            meta.capabilities().contains(AccessorCapability::List),
            "service doesn't support list hierarchy, it must be a bug"
        );
    }

    <real work>
}
```

**Comment by Xuanwo** [comment]
> Having to enable debug-assertions for all the crates in our project feels a little bit inconvenient.

Ok, I got it!

**Review by Xuanwo — APPROVED** [review]

**Review by PsiACE — APPROVED** [review]

**Comment by Xuanwo** [comment]
@mergify update

**Pull request merged**
