### PR TITLE
feat: introduce system.tables_with_history

### LINKED ISSUE #5858: improve `show tables` performance.
improve `show tables` performance

middle_img_v2_4db868f0-2665-4ba4-8905-1526f48ad43g

### LINKED ISSUE #6352: `system.tables` switch between `list_tables` and `list_tables_history` on-demand
How about let `system.tables` respects predicate pushdowns, and dynamically switch between `list_tables` and `list_tables_history` according to the related predicate?  At least, this can mitigate the situation of common case.

_Originally posted by @dantengsky in https://github.com/datafuselabs/databend/issues/6285#issuecomment-1170788082_

### PR DESCRIPTION
**Pull request by dantengsky**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

- Introduce `system.tables_with_history` which contains dropped tables, and statement like `show tables history ..` depends on it
- `system.tables` no longer contains dropped tables, so that for common statements like `show tables` (without history), `call system$search_table`, no longer accesse meta data of dropped tables (which might be rather slow)
  **To be backward compatible**:
  - **schema of `system.tables` still contains the `dropped_on` column**
  **If it is not necessary, please let me know**

NOTE:

 **Columns that not contained in the result set of `show full tables …`, will no longer be valid to be used in the `where clause` of `show tables`**

 e.g.

 - **`show tables where table_name = “t”` no longer valid**
 - **pls use `show tables like` or `show tables where Tables_in_$db = “t”`**
   For example:
   https://github.com/dantengsky/fuse-query/blob/e3730f242f36facf5a15897c735058a169cb49a2/tests/suites/0_stateless/06_show/06_0004_show_tables.sql#L17

 **Hope this make sense, but if any concerns, please let me know.**
 

Fixes #6352 
Fixes #5858 

————————

For @flaneur2020, hope the followings will not bring too much troubles, if anything is not acceptable or should be adjusted, pls let me know.

- A new system table `system.tables_with_history` is added
  Its schema is the same of `system.tables`
- `show tables where table_name = …` no longer works

### CODE REVIEW

**Comment by Xuanwo** [comment]
This is a space in the start of title~

**Comment by dantengsky** [comment]
> There is a space at the start of the title, so our PR check always failed.

Roger & thanks!

**Comment by BohuTANG** [comment]
Please confirm that if `show tables where table_name = “t” no longer valid` affects the cloud platform, cc @Chasen-Zhang @flaneur2020

**Comment by BohuTANG** [comment]
This CI failure is due to #6418 , it's in fixing, please ignore it :)

**Comment by Chasen-Zhang** [comment]
I haven't used `show tables where table_name = …` yet,  But I did use `show full tables from ${database};`  will affect?
I'm using the `call system$search_table` search tables, This is ok in the test environment

**Review by BohuTANG — APPROVED** [review]

**Comment by BohuTANG** [comment]
Does this patch also fix https://github.com/datafuselabs/databend/issues/5858?

**Comment by dantengsky** [comment]
> `show full tables from ${database};` will affect?

no effects for this statement

**Pull request merged**
