### PR TITLE
Add dal_metrics and scan_progress in processlist

### LINKED ISSUE #3598: Add session context progress to `show processlist`
**Summary**

Now:
```
mysql> show processlist;
+--------------------------------------+----------------+-----------------+------+-------+----------+-------------------------------+--------------+
| id                                   | type           | host            | user | state | database | extra_info                    | memory_usage |
+--------------------------------------+----------------+-----------------+------+-------+----------+-------------------------------+--------------+
| 7b8b38ee-95e8-4cba-9145-c1064d126734 | Streaming load | NULL            | root | Query | default  | insert into ontime format CSV |            0 |
| 482841dc-3c8c-49ab-b107-bbde6725b0e1 | MySQL          | 127.0.0.1:36006 | root | Query | default  | show processlist              |            0 |
+--------------------------------------+----------------+-----------------+------+-------+----------+-------------------------------+--------------+
```

Expect:
Add some extra infos to trace the progress values:
1. self.ctx.get_dal_metrics()
2.  self.ctx.get_scan_progress_value()

### PR DESCRIPTION
**Pull request by GrapeBaBa**
Signed-off-by: grapebaba <281165273@qq.com>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Add dal_metrics and scan_progress in processlist

## Changelog

- New Feature

## Related Issues

Fixes #3598 

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
/lgtm

Cool, thank you @GrapeBaBa

**Comment by GrapeBaBa** [comment]
how can retry the ci build? I don't get any error in my local build and test

**Comment by BohuTANG** [comment]
> how can retry the ci build? I don't get any error in my local build and test

There is no way do that yet except you are the repo admin :D

**Comment by BohuTANG** [comment]
Thank you @GrapeBaBa

**Pull request merged**
