### PR TITLE
ci: move iceberg stateful tests

### PR DESCRIPTION
**Pull request by ClSlaid**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

This PR adjusted the folder and patched the test of Iceberg feature.

### CODE REVIEW

**Comment by ClSlaid** [comment]
Looks like the `test-compat` test will have to wait for the next release of Databend.

**Comment by BohuTANG** [comment]
It's strange:
```
0: statement failed: mysql client error: Server error: `ERROR HY000 (1105): Code: 1005, displayText = error: 
  --> SQL:1:25
  |
1 | CREATE CATALOG ctl TYPE=ICEBERG CONNECTION=( URL='fs://tmp' );
  | ------                  ^^^^^^^ expected `DEFAULT` or `HIVE`
  | |                        
  | while parsing `CREATE CATALOG [IF NOT EXISTS] <catalog> TYPE=<catalog_type> CONNECTION=<catalog_options>`

.'
[SQL] CREATE CATALOG ctl TYPE=ICEBERG CONNECTION=( URL='fs://tmp' );
at tests/sqllogictests/suites/base/05_ddl/05_0029_ddl_create_catalog:9

Error: SelfError("sqllogictest failed")
```

https://github.com/datafuselabs/databend/actions/runs/4231623156/jobs/7350571020#step:4:898

**Comment by BohuTANG** [comment]
@mergify update

**Comment by BohuTANG** [comment]
Ok, let's merge.

**Review by BohuTANG — APPROVED** [review]

**Comment by drmingdrmer** [comment]
meta-compat test is fixed in:
- #10153

**Pull request merged**
