### PR TITLE
feat(query): create drop inverted index

### PR DESCRIPTION
**Pull request by b41sh**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

* Parser support create/drop inverted index
* TableMeta adds indexes field
* Add `create_table_index` and `drop_table_index` api

- part of #14825

## Tests

- [x] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14859)

### CODE REVIEW

**Review by ariesdevil — APPROVED** [review]

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 14 of 43 files at r1.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14859)* status: 14 of 44 files reviewed, 1 unresolved discussion (waiting on @b41sh and @sundy-li)

___
*[`src/meta/api/src/schema_api_impl.rs` line 4013 at r1](https://reviewable.io/reviews/datafuselabs/databend/14859#-NsIIj-MDohOWNO5I24J:-NsIIj-MDohOWNO5I24K:bvh4fqe) ([raw file](https://github.com/datafuselabs/databend/blob/b9ac163c9ee7d4364185a3f0ae3f928f7bc216a5/src/meta/api/src/schema_api_impl.rs#L4013)):*
> ```XML
>             UnknownIndex::new(&tenant_index.index_name, "drop index with different type"),
>         )));
>     }
> ```

An `index` is uniquely identified by `index_type` at line 3985, does it have to check `index_type`?



_Code quote:_
```XML
    if index_type != &index_meta.index_type {
        return Err(KVAppError::AppError(AppError::UnknownIndex(
            UnknownIndex::new(&tenant_index.index_name, "drop index with different type"),
        )));
    }
```

**Comment by b41sh** [comment]
> > Reviewed 14 of 43 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14859)_ status: 14 of 44 files reviewed, 1 unresolved discussion (waiting on @b41sh and @sundy-li)
> 
> _[`src/meta/api/src/schema_api_impl.rs` line 4013 at r1](https://reviewable.io/reviews/datafuselabs/databend/14859#-NsIIj-MDohOWNO5I24J:-NsIIj-MDohOWNO5I24K:bvh4fqe) ([raw file](https://github.com/datafuselabs/databend/blob/b9ac163c9ee7d4364185a3f0ae3f928f7bc216a5/src/meta/api/src/schema_api_impl.rs#L4013)):_
> 
> > ```
> >             UnknownIndex::new(&tenant_index.index_name, "drop index with different type"),
> >         )));
> >     }
> > ```
> 
> An `index` is uniquely identified by `index_type` at line 3985, does it have to check `index_type`?
> 
> _Code quote:_
> 
> ```
>     if index_type != &index_meta.index_type {
>         return Err(KVAppError::AppError(AppError::UnknownIndex(
>             UnknownIndex::new(&tenant_index.index_name, "drop index with different type"),
>         )));
>     }
> ```

The aggregating index and the inverted index have different drop syntaxes, 
```sql
DROP AGGREGATING INDEX idx1;
DROP INVERTED INDEX idx1;
```
The main reason for checking the index type here is to avoid using the wrong drop syntax, for example:
```sql
CREATE AGGREGATING INDEX my_agg_index AS SELECT MIN(a), MAX(c) FROM agg;
DROP INVERTED INDEX my_agg_index;
```

**Comment by drmingdrmer** [comment]
> The aggregating index and the inverted index have different drop syntaxes,
> 
> ```sql
> DROP AGGREGATING INDEX idx1;
> DROP INVERTED INDEX idx1;
> ```
> 
> The main reason for checking the index type here is to avoid using the wrong drop syntax, for example:
> 
> ```sql
> CREATE AGGREGATING INDEX my_agg_index AS SELECT MIN(a), MAX(c) FROM agg;
> DROP INVERTED INDEX my_agg_index;
> ```

Is it allowed for an aggregating index and an inverted index to have same index name? For example:
```sql
CREATE AGGREGATING INDEX aaa ...;
```

**Comment by b41sh** [comment]
> > The aggregating index and the inverted index have different drop syntaxes,
> > ```sql
> > DROP AGGREGATING INDEX idx1;
> > DROP INVERTED INDEX idx1;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The main reason for checking the index type here is to avoid using the wrong drop syntax, for example:
> > ```sql
> > CREATE AGGREGATING INDEX my_agg_index AS SELECT MIN(a), MAX(c) FROM agg;
> > DROP INVERTED INDEX my_agg_index;
> > ```
> 
> Is it allowed for an aggregating index and an inverted index to have same index name? For example:
> 
> ```sql
> CREATE AGGREGATING INDEX aaa ...;
> CREATE INVERTED INDEX aaa ...;
> ```

Same name is not allowed.

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14859)* status: 14 of 45 files reviewed, 2 unresolved discussions (waiting on @b41sh and @sundy-li)

___
*[`src/meta/app/src/schema/index.rs` line 96 at r3](https://reviewable.io/reviews/datafuselabs/databend/14859#-NsJSqSG4lOQ1YL4FqhB:-NsJSqSG4lOQ1YL4FqhC:b3fm7db) ([raw file](https://github.com/datafuselabs/databend/blob/9a3fd6bfcde7f9211289cfa70bb2cc83652e088f/src/meta/app/src/schema/index.rs#L96)):*
> ```XML
>     AGGREGATING = 1,
>     JOIN = 2,
>     INVERTED = 3,
> ```

Adding a variant is a incompatible change. In a cluster of new-query and old-query running together, the old-query that  can not read `INVERTED`  will return an error

**Comment by sundy-li** [comment]
> Adding a variant is a incompatible change. In a cluster of new-query and old-query running together, the old-query that can not read INVERTED will return an error

Seems reasonable, new-query should remove this new meta to downgrade.

**Comment by drmingdrmer** [comment]
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14859)_ status: 14 of 45 files reviewed, 2 unresolved discussions (waiting on @b41sh and @sundy-li)
> 
> _[`src/meta/app/src/schema/index.rs` line 96 at r3](https://reviewable.io/reviews/datafuselabs/databend/14859#-NsJSqSG4lOQ1YL4FqhB:-NsJSqSG4lOQ1YL4FqhC:b3fm7db) ([raw file](https://github.com/datafuselabs/databend/blob/9a3fd6bfcde7f9211289cfa70bb2cc83652e088f/src/meta/app/src/schema/index.rs#L96)):_
> 
> > ```
> >     AGGREGATING = 1,
> >     JOIN = 2,
> >     INVERTED = 3,
> > ```
> 
> Adding a variant is a incompatible change. In a cluster of new-query and old-query running together, the old-query that can not read `INVERTED` will return an error

@TCeason had solved a similar compatibility issue like this. What's the correct way for adding a enum variant?

**Comment by b41sh** [comment]
> > Adding a variant is a incompatible change. In a cluster of new-query and old-query running together, the old-query that can not read `INVERTED` will return an error
> 
> @TCeason had solved a similar compatibility issue like this. What's the correct way for adding a enum variant?
We can store the data for the inverted index separately, but this will bring some duplicate code, is there a better way to solve this problem?

**Comment by TCeason** [comment]
> We can store the data for the inverted index separately, but this will bring some duplicate code, is there a better way to solve this problem?

PriviligeType is bitflag. Use  from_bits_truncate.
```rust
let privileges =
            BitFlags::<mt::principal::UserPrivilegeType, u64>::from_bits_truncate(p.privileges);
```

**Comment by TCeason** [comment]
> > > Reviewed all commit messages.
> > > _[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14859)_ status: 14 of 45 files reviewed, 2 unresolved discussions (waiting on @b41sh and @sundy-li)
> > 
> > 
> > _[`src/meta/app/src/schema/index.rs` line 96 at r3](https://reviewable.io/reviews/datafuselabs/databend/14859#-NsJSqSG4lOQ1YL4FqhB:-NsJSqSG4lOQ1YL4FqhC:b3fm7db) ([raw file](https://github.com/datafuselabs/databend/blob/9a3fd6bfcde7f9211289cfa70bb2cc83652e088f/src/meta/app/src/schema/index.rs#L96)):_
> > > ```
> > >     AGGREGATING = 1,
> > >     JOIN = 2,
> > >     INVERTED = 3,
> > > ```
> > 
> > 
> > Adding a variant is a incompatible change. In a cluster of new-query and old-query running together, the old-query that can not read `INVERTED` will return an error
> 
> @TCeason had solved a similar compatibility issue like this. What's the correct way for adding a enum variant?

```
index_type: FromPrimitive::from_i32(p.index_type).ok_or_else(|| Incompatible {
                reason: format!("invalid IndexType: {}", p.index_type),
            })?,

```

Now index type uses from i32. So we can add a compat test for it? like this:

1. in new query: add inverted index; add AGGREGATING index
2. revert version to main without the inverted index
3. try to query the inverted index; try to query the agg index.

**Comment by drmingdrmer** [comment]
If there is an incompatible variant, `from_pb` will return an Error. Is it acceptable? @b41sh 


https://github.com/datafuselabs/databend/blob/f9e0e1c7ded521980a1c531cde7dfb7dbd3fd242/src/meta/proto-conv/src/index_from_to_protobuf_impl.rs#L77

image

**Comment by b41sh** [comment]
> If there is an incompatible variant, `from_pb` will return an Error. Is it acceptable? @b41sh

Returning an error makes the index unusable, which is unacceptable.

Inverted indexes are for a single table, whereas aggregating indexes are for multiple tables, so it seems better to define them separately. Can we define a new inverted index and put it in TableMeta?

**Comment by ariesdevil** [comment]
> > If there is an incompatible variant, `from_pb` will return an Error. Is it acceptable? @b41sh
> 
> Returning an error makes the index unusable, which is unacceptable.
> 
> Inverted indexes are for a single table, whereas aggregating indexes are for multiple tables, so it seems better to define them separately. Can we define a new inverted index and put it in TableMeta?↳

Aggregating index also for single table, but one table can have multiple aggregating indexes.

**Comment by drmingdrmer** [comment]
> Can we define a new inverted index and put it in TableMeta?

It would be more clear and neat.

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 6 of 72 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14859)* status: 7 of 78 files reviewed, 3 unresolved discussions (waiting on @ariesdevil, @b41sh, and @sundy-li)

___
*[`src/meta/app/src/schema/table.rs` line 258 at r4](https://reviewable.io/reviews/datafuselabs/databend/14859#-NsTC9Nw1quSrcSWJXDS:-NsTC9Nw1quSrcSWJXDT:b-5lhnmb) ([raw file](https://github.com/datafuselabs/databend/blob/750cb48c33b9c611f589159887c9f18d9f5911f0/src/meta/app/src/schema/table.rs#L258)):*
> ```XML
> pub struct TableIndex {
>     pub name: String,
>     pub columns: Vec<String>,
> ```

If a column is renamed, `columns` becomes invalid.
The `column_id` should be used instead of `String`. `column_id` are unique.

Refer to:
https://github.com/datafuselabs/databend/blob/97e7a31aeaaa8ac9e4e30625b54fc31192081ccd/src/query/expression/src/schema.rs#L156

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 1 of 72 files at r4, 3 of 15 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14859)* status: 9 of 78 files reviewed, 4 unresolved discussions (waiting on @ariesdevil, @b41sh, and @sundy-li)

___
*[`src/meta/api/src/schema_api_impl.rs` line 3186 at r5](https://reviewable.io/reviews/datafuselabs/databend/14859#-NsTh0lBCID97D8RPA4w:-NsTh0lBCID97D8RPA4x:b-8wxe6t) ([raw file](https://github.com/datafuselabs/databend/blob/89f654196cce25ab5052b2d770c897631eb06469/src/meta/api/src/schema_api_impl.rs#L3186)):*
> ```XML
>                 column_ids: req.column_ids.clone(),
>             };
>             indexes.insert(req.name.clone(), index);
> ```

The `column_ids` is passed in via the `CreateTableIndexReq`,  the column ids may have changed in the `TableMeta` fetched at line 3115.

There are two options to address this issue:
- Confirm that the column ids from `CreateTableIndexReq` present in the `TableMeta`'
- Specify column by names in the `CreateTableIdnexReq`, and translate them to column-id in this method.

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 30 of 72 files at r4, 3 of 15 files at r5, 3 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14859)* status: 42 of 78 files reviewed, 2 unresolved discussions (waiting on @ariesdevil, @b41sh, and @sundy-li)

**Pull request merged**
