### PR TITLE
fix(build-tool): add symlink for musl-gcc

### PR DESCRIPTION
**Pull request by everpcpc**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Fixes #issue

### CODE REVIEW

**Comment by Xuanwo** [comment]
How about using https://musl.cc/x86_64-linux-musl-cross.tgz?

**Comment by Xuanwo** [comment]
We can unarchive this package to `/usr/local/x86_64-linux-musl-cross` and add `/usr/local/x86_64-linux-musl-cross/bin` in `PATH`?

**Comment by Xuanwo** [comment]
This PR is LGTM so far, we can get this PR merge first if you prefer to do so.

**Review by Xuanwo — APPROVED** [review]

**Comment by everpcpc** [comment]
> This PR is LGTM so far, we can get this PR merge first if you prefer to do so.

Yes, this is a temporary fix. I will check other solutions later.

**Review by PsiACE — APPROVED** [review]

**Pull request merged**
