### PR TITLE
doc(deploy): add scaleway os deploy

### PR DESCRIPTION
**Pull request by mrhamburg**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

add scaleway os deploy

## Changelog

- Documentation

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Review by BohuTANG — APPROVED** [review]
LGTM, Thank you!

**Comment by BohuTANG** [comment]
Hi @mrhamburg ,

Thank you for the contribution!
I have check the performance result, may i have your:
```
call system$fuse_history('default', 'ontime');
```

Result likes https://databend.rs/doc/performance/ecs-oss-performance#block-statistics
```
+----------------------------------+------------------+---------------+-------------+-----------+--------------------+------------------+
| snapshot_id                      | prev_snapshot_id | segment_count | block_count | row_count | bytes_uncompressed | bytes_compressed |
+----------------------------------+------------------+---------------+-------------+-----------+--------------------+------------------+
| 550cb965554349d981476ea5cb86ebc0 | NULL             |             1 |         203 | 202687655 |       146705866574 |       8891053905 |
+----------------------------------+------------------+---------------+-------------+-----------+--------------------+------------------+
```

**Comment by mrhamburg** [comment]
Hi @BohuTANG,

I removed all instances just a minute ago. I can get you those figures, but it will take some time.

**Comment by BohuTANG** [comment]
Well, how do you load the ontime data into databend?
The difference loading may affect the performance.
Loading ontime csv year by year is the preferred way :)

**Comment by mrhamburg** [comment]
Yeah I noticed that partitioning wise it wasn't that efficient hence the scanning of all files. I was lazy and just applied the following instructions: https://databend.rs/doc/learn/analyze-ontime-with-databend-on-ec2-and-s3

You happen to have a script to load and thereby partition the data by year? I can run the ingestion year by year and also update the docs based on that (will improve the figures, I hope)

**Comment by BohuTANG** [comment]
Hi @mrhamburg ,
Thank you for the information.
We have updated the t_ontime.csv file which data organizated year by year, you can re-load it again follow the same step:
https://databend.rs/doc/learn/analyze-ontime-with-databend-on-ec2-and-s3

By the way, the md5:
```
1b2dbd5116cba3e5bddcc2b473cdf6c9  t_ontime.csv.zip
267fe3a7edf9727d4a46786d01f72649  t_ontime.csv
```

**Pull request merged**
