### PR TITLE
Split databend-query to multiple crates

### LINKED ISSUE #4382: Feature: split databend-query to multiple crates
**Summary**

Split databend-query to multiple crates has two main benefits:
1. reduce build time
2. easier to maintain

Example: https://github.com/bytecodealliance/wasmtime/tree/main/cranelift

Thoughts?

### PR DESCRIPTION
**Pull request by light4**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Split databend-query to multiple crates

## Changelog

- Improvement
- Build/Testing/CI
- Other 
- Not for changelog (changelog entry is not required)

## Related Issues

Fixes #4382

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by PsiACE** [comment]
What a big change! I'm glad to see that you are willing to do this. However, on my computer, the release compilation time has increased by about 2 minutes. :sob:

**Comment by light4** [comment]
It's still a work in progress. :)

**Comment by PsiACE** [comment]
> It's still a work in progress. :)

Oh, yes. Maybe this will improve after removing unnecessary dependencies, looking forward to when it's ready.

**Comment by BohuTANG** [comment]
Nice work, I have seen that the time cost is less than before.
Is it possible we move the crates one by one instead the all of query?

**Comment by light4** [comment]
Do you mean move one crate one pr at a time?
The `users`, `common` and `config` mods are easy to move out. But don't have a positive effect on improving build time.
Mods like `sessions`, `storages`, `pipelines`, `catalogs` depend on each other, moving out one by one will cause cyclic dependency.

**Comment by Xuanwo** [comment]
Is this PR still going on? I'm afraid it's impossible to do such refactor in the project with such heavy traffic.

Can we find a way to do them in a progressive way?

**Comment by light4** [comment]
Sorry, don't have time to do this anymore. Just close it.

**Pull request closed without merging**
