### PR TITLE
feat: default file format to Parquet.

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

https://github.com/datafuselabs/databend/issues/9946

there are multi place in doc need to update/ refactor.
doc in another pr https://github.com/datafuselabs/databend/pull/9957

### CODE REVIEW

**Comment by youngsofun** [comment]
@drmingdrmer  can you help with https://github.com/datafuselabs/databend/actions/runs/4140672596/jobs/7159636152, can not find useful error message.

**Comment by youngsofun** [comment]
I am trying `sh ./tests/metactl/update-metactl-test.sh`

**Comment by youngsofun** [comment]
passed after rerun for the 3ed time

**Review by BohuTANG — APPROVED** [review]

**Comment by drmingdrmer** [comment]
> @drmingdrmer can you help with https://github.com/datafuselabs/databend/actions/runs/4140672596/jobs/7159636152, can not find useful error message.

Oh I did not notice that the output json map keys are not sorted. Surprised it passed before.

Let me fix it.

**Pull request merged**
