### PR TITLE
chore: update logcall

### PR DESCRIPTION
**Pull request by andylokandy**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Tests

- [x] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [x] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15831)

### CODE REVIEW

**Review by andylokandy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15831)* status: all files reviewed, 1 unresolved discussion (waiting on @drmingdrmer)

___
*[`src/meta/api/src/schema_api_impl.rs` line 269 at r1](https://reviewable.io/reviews/datafuselabs/databend/15831#-O-kdk7d2tkGeezcgN78:-O-ksKJ67u1e7wv2Kz3b:b-ilndxa) ([raw file](https://github.com/datafuselabs/databend/blob/4024618e5cbaea03f9588d520cd22b96a5bca2c8/src/meta/api/src/schema_api_impl.rs#L269)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

Is it able to keep the struct name `SchemaApi` in the debug log?
</blockquote></details>

It's not possible in current logcall. But it's possible to upgrade.

**Review by drmingdrmer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15831)* status: all files reviewed, 1 unresolved discussion (waiting on @andylokandy)

___
*[`src/meta/api/src/schema_api_impl.rs` line 269 at r1](https://reviewable.io/reviews/datafuselabs/databend/15831#-O-kdk7d2tkGeezcgN78:-O-kuRjKAMwteoo2bfSb:b-1ih2ji) ([raw file](https://github.com/datafuselabs/databend/blob/4024618e5cbaea03f9588d520cd22b96a5bca2c8/src/meta/api/src/schema_api_impl.rs#L269)):*
<details><summary><i>Previously, andylokandy (Andy Lok) wrote…</i></summary><blockquote>

It's not possible in current logcall. But it's possible to upgrade.
</blockquote></details>

In that case, retaining the manual debug statements is a sensible choice. Given that there are several structures with nearly identical method sets, such as `catalog.create_table` invoking `SchemaApi::create_table`.

And having debug statements at the start of each method can be useful. This approach allows for better traceability and understanding of the workflow, especially when diagnosing issues, as opposed to only logging when a method completes.

**Comment by andylokandy** [comment]
> having debug statements at the start of each method can be useful. This approach allows for better traceability and understanding of the workflow, especially when diagnosing issues, as opposed to only logging when a method completes.

For such aspect, I recommend enabling structlog for meta, which will arrange the log in the way functions is call in hierarchy, and is already setup for query

**Comment by andylokandy** [comment]
The new patch will log the function in full path: https://github.com/andylokandy/logcall/pull/5

**Comment by drmingdrmer** [comment]
Can you keep the original debug log statement so that I can still get enough information while evaluating the new logging?

**Comment by andylokandy** [comment]
updated

**Review by drmingdrmer — APPROVED** [review]
Thank you

> Reviewed 2 of 2 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15831#-:-O03_R5n32XB-ZoU4NUa:bvs55d0)* status: all files reviewed, 1 unresolved discussion (waiting on @andylokandy)

**Pull request merged**
