### PR TITLE
[Issue-3367] Using serde to ser/de Aggregate function states in binary format

### LINKED ISSUE #3367: Using serde to se/deserialize aggregate function states.
**Summary**

Description for this improvement.

https://serde.rs/

Serde the Aggregate function state in binary format should be very efficient and have low memory overhead.

Sample trait from @sunli829 

```
use serde::de::DeserializeOwned;
use serde::Serialize;
use std::fmt::Debug;

trait GenericFunction: Debug {
    type State: Serialize + DeserializeOwned + 'static;

    fn state(&self) -> &Self::State;

    fn load_state(&mut self, state: Self::State);

    fn call(&mut self);
}

trait Function: Debug {
    fn save_state(&self, buf: &mut Vec<u8>);

    fn load_state(&mut self, state: &[u8]);

    fn call(&mut self);
}

impl<T: GenericFunction> Function for T {
    fn save_state(&self, buf: &mut Vec<u8>) {
        bincode::serialize_into(buf, T::state(self)).unwrap();
    }

    fn load_state(&mut self, mut state: &[u8]) {
        T::load_state(self, bincode::deserialize_from(&mut state).unwrap());
    }

    fn call(&mut self) {
        T::call(self)
    }
}

#[derive(Debug)]
struct CounterFunction {
    count: usize,
}

impl GenericFunction for CounterFunction {
    type State = usize;

    fn state(&self) -> &Self::State {
        &self.count
    }

    fn load_state(&mut self, state: Self::State) {
        self.count = state;
    }

    fn call(&mut self) {
        self.count += 1;
    }
}

fn main() {
    let mut f: Box<dyn Function> = Box::new(CounterFunction { count: 0 });

    f.call();
    f.call();

    let mut state = Vec::new();
    f.save_state(&mut state);

    println!("{:?}", f);

    f.call();
    f.call();

    println!("{:?}", f);

    f.load_state(&state);

    println!("{:?}", f);

    f.call();
    f.call();

    println!("{:?}", f);
}

```

### PR DESCRIPTION
**Pull request by ygf11**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

1. Using serde to ser/de Aggregate function states in binary format.
2. Clean up non used BinarySer/BinaryDe code.

## Changelog

- Improvement
- Performance Improvement

## Related Issues

Fixes #3367

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
Benchmark test in my local PC(Without performance degradation :+1: ):

This patch:
```
databend :) SELECT sum(number) FROM numbers_mt(100000000000);

┌────────sum(number)─┐
│ 932355974711512064 │
└────────────────────┘

1 rows in set. Elapsed: 4.830 sec. Processed 100.00 billion rows, 800.00 GB (20.70 billion rows/s., 165.62 GB/s.)

databend :) SELECT min(number) FROM numbers_mt(100000000000);

┌─min(number)─┐
│           0 │
└─────────────┘

1 rows in set. Elapsed: 9.606 sec. Processed 100.00 billion rows, 800.00 GB (10.41 billion rows/s., 83.28 GB/s.)

databend :) SELECT max(number), sum(number) FROM numbers_mt(1000000000) GROUP BY number % 3, number % 4, number % 5 LIMIT 10;

┌─max(number)─┬──────sum(number)─┐
│   999999992 │ 8333333700000004 │
│   999999957 │ 8333333116666662 │
│   999999983 │ 8333333550000001 │
│   999999986 │ 8333333600000002 │
│   999999981 │ 8333333516666667 │
│   999999993 │ 8333333716666671 │
│   999999949 │ 8333332983333334 │
│   999999958 │ 8333333133333328 │
│   999999945 │ 8333332916666670 │
│   999999973 │ 8333333383333331 │
└─────────────┴──────────────────┘

10 rows in set. Elapsed: 1.654 sec. Processed 1.00 billion rows, 8.00 GB (604.69 million rows/s., 4.84 GB/s.)

```


main branch:
```
databend :) SELECT sum(number) FROM numbers_mt(100000000000);


┌────────sum(number)─┐
│ 932355974711512064 │
└────────────────────┘

1 rows in set. Elapsed: 5.126 sec. Processed 100.00 billion rows, 800.00 GB (19.51 billion rows/s., 156.08 GB/s.)

databend :) SELECT min(number) FROM numbers_mt(100000000000);


┌─min(number)─┐
│           0 │
└─────────────┘

1 rows in set. Elapsed: 9.509 sec. 

databend :) SELECT max(number), sum(number) FROM numbers_mt(1000000000) GROUP BY number % 3, number % 4, number % 5 LIMIT 10;


┌─max(number)─┬──────sum(number)─┐
│   999999940 │ 8333332833333340 │
│   999999965 │ 8333333249999995 │
│   999999973 │ 8333333383333331 │
│   999999981 │ 8333333516666667 │
│   999999997 │ 8333333783333339 │
│   999999955 │ 8333333083333330 │
│   999999960 │ 8333333166666660 │
│   999999967 │ 8333333283333329 │
│   999999977 │ 8333333449999999 │
│   999999948 │ 8333332966666668 │
└─────────────┴──────────────────┘

10 rows in set. Elapsed: 1.656 sec. Processed 1.00 billion rows, 8.00 GB (603.97 million rows/s., 4.83 GB/s.)
```

**Comment by sundy-li** [comment]
Can we optimize the length encoding to variant encoding?

 https://github.com/bincode-org/bincode/blob/trunk/src/enc/mod.rs#L68-L70

**Comment by ygf11** [comment]
> Can we optimize the length encoding to variant encoding?

Yes, it supports this option. Let me do it.

https://github.com/bincode-org/bincode/blob/c44b5e364e7084cdbabf9f94b63a3c7f32b8fb68/src/config/mod.rs#L156-L159

**Comment by sundy-li** [comment]
Yes, but I don't want it to be a global setting.

Could it be possible to just write the `offsets`/ `length`   of (vectors,  byte arrays ) in variant encoding?
For other integers, we just use native encoding.

This is because we always know that the vector state has small size ranges, so it benefits a lot to use variant encoding. But for other integers, the range may be random, it's better to use native encoding.

**Comment by ygf11** [comment]
> Yes, but I don't want it to be a global setting.

We can serialize every field in state one by one, like:
```
struct State {
   v1: Vec<u8>,
   v2: u8,
   v3: u16   
}

fn serialize(&self, writer: &mut ByteMut) -> Result<()> {
   let writer: std::io::Writer = BufMut::writer(writer);

   bincode_serialize_variant_encoding(writer, self.v1);
   bincode_serialize_fixed_encoding(writer, self.v2);
   bincode_serialize_fixed_encoding(writer, self.v3);
   Ok(())
}
```


the problem is that `serialize_into` method need the ownership of the `writer`, so we can not write one by one here.

**Comment by ygf11** [comment]
I also find the `2.0.0-alpha.1` of `bincode` crate support passing `&mut [u8]` as writer, but it is still in developing.

**Comment by sundy-li** [comment]
How about using a forked `bincode` crate ?

**Comment by ygf11** [comment]
> How about using a forked bincode crate ?

Current `bincode` is enough, I misunderstand the meaning of api :sweat:

**Review by sundy-li — APPROVED** [review]
LGTM

**Comment by BohuTANG** [comment]
Thank you @ygf11 !

**Pull request merged**
