### PR TITLE
ci: run benchmark for clickbench result format

### PR DESCRIPTION
**Pull request by everpcpc**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Closes #issue

### CODE REVIEW

**Comment by BohuTANG** [comment]
Need a teardown like 'drop table hits all' to clean the data.

**Comment by everpcpc** [comment]
> Need a teardown like 'drop table hits all' to clean the data.

Test data exists in the `databend-ci` bucket and will be auto cleaned in 7 days.

**Comment by everpcpc** [comment]
[clickbench-report.zip](https://github.com/datafuselabs/databend/files/10729372/clickbench-report.zip)

**Comment by BohuTANG** [comment]
> clickbench-report.zip

Can we give s3 link URL view instead of the download?

**Comment by everpcpc** [comment]
platform
**Benchmark Results**: https://repo.databend.rs/benchmark/clickbench/pr/7220305151.html

**Comment by everpcpc** [comment]
Added a lifecycle rule, results under `/benchmark/clickbench/pr/` will expire in 30 days.

**Review by sundy-li — APPROVED** [review]

**Review by BohuTANG — APPROVED** [review]

**Review by Xuanwo — APPROVED** [review]

**Pull request merged**
