### PR TITLE
refactor: Bump OpenDAL to 0.48.0

### PR DESCRIPTION
**Pull request by Xuanwo**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

This PR will bump opendal t0 0.48.0

## Tests

- [x] Unit Test
- [x] Logic Test
- [x] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [x] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16147)

### CODE REVIEW

**Comment by Xuanwo** [comment]
Local Load test failed for

```
from system.functions ignore_result;
select name from system.tables where name='t_1';
select name from system.tables where name in ('t_1', 't_2'');
3
Error: APIError: ResponseError with 1005: error: 
  --> SQL:1:54
  |
1 | select name from system.tables where name in ('t_1', 't_2'')
  |                                                      ^^^^^^^ unable to recognize the rest tokens
```

**Comment by BohuTANG** [comment]
> Local Load test failed for
> 
> ```
> from system.functions ignore_result;
> select name from system.tables where name='t_1';
> select name from system.tables where name in ('t_1', 't_2'');
> 3
> Error: APIError: ResponseError with 1005: error: 
>   --> SQL:1:54
>   |
> 1 | select name from system.tables where name in ('t_1', 't_2'')
>   |                                                      ^^^^^^^ unable to recognize the rest tokens
> ```

I think this is a wrong test, we can modify in this PR. cc @TCeason

**Comment by TCeason** [comment]
> select name from system.tables where name in ('t_1', 't_2'')

Yes, `select name from system.tables where name in ('t_1', 't_2')`

**Comment by BohuTANG** [comment]
Fixed and re-run the benchmark.

**Comment by Xuanwo** [comment]
> Fixed and re-run the benchmark.

Thanks!

**Review by andylokandy — APPROVED** [review]

**Pull request merged**
