### PR TITLE
Add panic hook for dataquery and datastore

### LINKED ISSUE #792: [observability] add custom panic hook to common/tracing
**Summary**

Query/Store can install a custom panic hook, error the custom log when panic.
It can:
1. catch the panic info
2. send the log to tracing

Reference:
https://github.com/tokio-rs/tracing/blob/master/examples/examples/panic_hook.rs

### PR DESCRIPTION
**Pull request by jyz0309**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

Summary about this PR

## Changelog

- New Feature

## Related Issues

Fixes #792 

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
Hi,

Cool.
This pr looks ready for review? I see it title has `WIP`

**Comment by jyz0309** [comment]
> Hi,
> 
> Cool.
> This pr looks ready for review? I see it title has `WIP`

I think we can review it first to make sure this implement meets the issue.:)

**Comment by BohuTANG** [comment]
Meets the issue very well :+1:

**Comment by jyz0309** [comment]
> Meets the issue very well 👍

Ready for review🙈

**Pull request merged**
