### PR TITLE
refactor: Rename to data operator to make space for cache

### PR DESCRIPTION
**Pull request by Xuanwo**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Part of https://github.com/datafuselabs/databend/issues/6803

### CODE REVIEW

**Review by PsiACE — APPROVED** [review]

**Comment by BohuTANG** [comment]
Why change the `storage` name to `persist`? `persist` is not easy to understand at a glance.

**Comment by Xuanwo** [comment]
> Why change the `storage` name to `persist`? `persist` is not easy to understand at a glance.

`persist`, `cache`, and `temporary` will same the same storage config. Change `StorageOperator` to `PersistOperator` can make it easier to distinguish with `StorageConfig`.

After this change, all `StorageXxx` will apply for all operator types.

**Comment by BohuTANG** [comment]
How about DataOperator?

**Review by zhang2014 — APPROVED** [review]

**Comment by Xuanwo** [comment]
> How about DataOperator?

Updated.

**Pull request merged**
