### PR TITLE
improvement(function): simplify in function

### LINKED ISSUE #4995: Feature:  Function In support other datatypes
**Summary**

Description for this feature.

https://github.com/datafuselabs/databend/blob/0768992f646a1ddb834caec1f789420486556ed9/common/functions/src/scalars/conditionals/in_basic.rs

### PR DESCRIPTION
**Pull request by fkuner**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Simplify `in` function

## Changelog

- Improvement

## Related Issues

Fixes #4995

### CODE REVIEW

**Comment by BohuTANG** [comment]
> /ci rerun

Hmm, there is no CI commands for the bot.
I have re-run it from the ci panel.

**Review by sundy-li — APPROVED** [review]

**Comment by fkuner** [comment]
> > /ci rerun
> 
> Hmm, there is no CI commands for the bot. I have re-run it from the ci panel.

Thanks. But can I rerun it? Sometimes the ci can't passed and I want to try it again to see whether ci failed by accident.

**Comment by BohuTANG** [comment]
I think you can re-run now, try it next time.

**Pull request merged**
