### PR TITLE
refactor(copy): rewrite copy into table for parquet.

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

tracked in https://github.com/datafuselabs/databend/issues/11158

### CODE REVIEW

**Comment by youngsofun** [comment]
1_stateful/00_copy/00_0000_copy_from_s3_location passed on my mac, but failed in ci.

seems the minio  crashed for some reason.

```
+ERROR 1105 (HY000) at line 1: Code: 4000, Text = Unexpected (persistent) at read, context: { called: http_util::Client::send_async, service: s3, path: ontime_200_v1.parquet, range: 2727-2858 } => send async request, source: error sending request for url (http://127.0.0.1:9900/testbucket/admin/data/ontime_200_v1.parquet): error trying to connect: tcp connect error: Connection refused (os error 111).
+ERROR 1105 (HY000) at line 1: Code: 4000, Text = Unexpected (persistent) at read, context: { called: http_util::Client::send_async, service: s3, path: 1/11/_ss/f982ef04a485466689c3e3d4636e949e_v3.bincode, range: 0- } => send async request, source: error sending request for url (http://127.0.0.1:9900/testbucket/admin/1/11/_ss/f982ef04a485466689c3e3d4636e949e_v3.bincode): error trying to connect: tcp connect error: Connection refused (os error 111).
+ERROR 1105 (HY000) at line 1: Code: 4000, Text = Unexpected (persistent) at read, context: { called: http_util::Client::send_async, service: s3, path: 1/11/_ss/f982ef04a485466689c3e3d4636e949e_v3.bincode, range: 0- } => send async request, source: error sending request for url (
```

**Comment by youngsofun** [comment]
seems minio crashed when running stateful test https://github.com/datafuselabs/databend/actions/runs/4775784805/jobs/8490413882

cc @Xuanwo  @everpcpc any thoughts on this?

**Comment by Xuanwo** [comment]
> seems minio crashed when running stateful test https://github.com/datafuselabs/databend/actions/runs/4775784805/jobs/8490413882
> 
> cc @Xuanwo @everpcpc any thoughts on this?

Weird...

Can we got the minio's log? @everpcpc

**Comment by Xuanwo** [comment]
Tests timeout. Maybe we should exit job if test failed?

**Comment by youngsofun** [comment]
> Tests timeout. Maybe we should exit job if test failed?

most of the time,  it is helpful to keep on running.
I will let it fail fast in the pr temperately and for debugging only.

**Comment by Xuanwo** [comment]
Hi, there many connection reset happened in minio. It often happened when users trying to read more bytes than server expected.

If it possible that the schema for parquet is wrong that lead to underlying storage trying to wrong range or size?

**Comment by Xuanwo** [comment]
https://github.com/datafuselabs/databend/pull/11173/commits/ffad777dcedcaf25209937a1470d413b8155afbc this commit will try to read data via host network.

**Comment by Xuanwo** [comment]
```
872e37c8cd49f9bb5d7370075d5df4cc700f1104a3ab43c24b98648fbf4feb46
make_bucket failed: s3://testbucket Could not connect to the endpoint URL: "http://127.0.0.1:9900/testbucket"
Error: Process completed with exit code 1.
```

:scream:

**Comment by youngsofun** [comment]
```
(venv) ➜  databend git:(parquet) ls -l tests/data/ontime_200.parquet
-rw-r--r--  1 yangxiufeng  staff  28087 Nov 15 10:13 tests/data/ontime_200.parquet
```
so   range: 16297-16335 is valid.

**Comment by Xuanwo** [comment]
Issue fixed after migrating to host network. The root cause is still unknown.

**Review by Xuanwo — APPROVED** [review]
Great, thanks!

**Review by BohuTANG — APPROVED** [review]

**Review by sundy-li — APPROVED** [review]

**Pull request merged**
