### PR TITLE
feat(query): migrate window function to new pipeline

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

migrate window function to new pipeline

Fixes #issue

### CODE REVIEW

**Review by zhang2014 — APPROVED** [review]

**Comment by BohuTANG** [comment]
window function test failed \:
https://github.com/datafuselabs/databend/runs/7211563161?check_suite_focus=true#step:3:340

**Comment by BohuTANG** [comment]
@mergify update

**Comment by sundy-li** [comment]
@zhang2014   results is missed in https://github.com/datafuselabs/databend/runs/7226876258?check_suite_focus=true

**Comment by BohuTANG** [comment]
The test failure `03_0018_insert_into_variant` is not related to this pr, let's merge.

**Pull request merged**
