### PR TITLE
feat(planner): support `alter view` in new planner

### PR DESCRIPTION
**Pull request by b41sh**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

support `alter view` in new planner

## Changelog

- New Feature

## Related Issues

#5779

### CODE REVIEW

**Review by leiysky — APPROVED** [review]

**Comment by sundy-li** [comment]
@ZeaLoVe  @youngsofun   Seems this is a flaky test on macOS HTTP handler.

**Comment by youngsofun** [comment]
@sundy-li I see 3 cases
fail test_sqllogic_standalone_macos
pass test_sqllogic_standalone_linux

    suite_name: gen/03_dml/03_0008_select_aggregator_combinator,
    text:
        select sum_distinct(number) /  count_distinct(number) = avg_distinct(number) from ( select number % 100 as number from numbers(100000));

**Comment by youngsofun** [comment]
@sundy-li  @ZeaLoVe  @leiysky  the flaky test It`s my fault, fixing it

**Comment by youngsofun** [comment]
@mergify update

**Comment by BohuTANG** [comment]
```
error[E0560]: struct `common_planners::AlterViewPlan` has no field named `db`
--> query/src/sql/planner/binder/ddl/view.rs:67:13
|
67|             db,
| ^^`common_planners::AlterViewPlan` does not have this field
|
= note: available fields are: `tenant`, `catalog`, `database`, `viewname`, `subquery`
For more information about this error, try `rustc --explain E0560`.
error: could not compile `databend-query` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `databend-query` due to previous error
Error: Process completed with exit code 101.
```

https://github.com/datafuselabs/databend/runs/6824991342?check_suite_focus=true#step:3:1465

**Comment by Xuanwo** [comment]
@mergify update

**Comment by b41sh** [comment]
```
Parsed Statement
    at_line: 31,
    s_type: Statement: query, type: IT, query_type: IT, retry: False,
    suite_name: gen/03_dml/03_0003_select_group_by,
    text:
        SELECT count(*), name FROM system.credits WHERE name='ahash' GROUP BY name;
    results: [(<re.Match object; span=(0, 4), match='----'>, 36, '1 ahash')],
```
@youngsofun  failed in `test_sqllogic_standalone_linux`, how to fix this error?

**Comment by ZeaLoVe** [comment]
> ```
> 2022-06-10T08:24:43.003367Z  INFO databend_query::servers::mysql::mysql_interactive_worker: Normal query: SELECT count(*), name FROM system.credits WHERE name='ahash' GROUP BY name;
> 2022-06-10T08:24:43.012044Z  WARN databend_query::pipelines::new::executor::pipeline_pulling_executor: Send finish event error SendError { .. }
> Traceback (most recent call last):
>   File "/home/runner/work/databend/databend/tests/logictest/logictest.py", line 218, in safe_execute
>     return method()
>   File "/home/runner/work/databend/databend/tests/logictest/logictest.py", line 308, in <lambda>
>     actual = safe_execute(lambda: self.execute_query(statement), statement)
>   File "/home/runner/work/databend/databend/tests/logictest/mysql_runner.py", line 48, in execute_query
>     r = cursor.fetchall()
>   File "/home/runner/.local/lib/python3.8/site-packages/mysql/connector/cursor.py", line 985, in fetchall
>     raise errors.InterfaceError("No result set to fetch from.")
> mysql.connector.errors.InterfaceError: No result set to fetch from.
> ```
> 
> cc @ZeaLoVe

Looks like a failure， original stateless test failed too.

**Pull request merged**
