### PR TITLE
chore: use cargo workspace inheritance

### PR DESCRIPTION
**Pull request by TennyZhuang**
Signed-off-by: TennyZhuang <zty0826@gmail.com>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

A new cargo feature stabilized in Rust 1.64, see https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace

It works well on the recent toolchain and have nice editor support on VSCode.

### CODE REVIEW

**Comment by TennyZhuang** [comment]
Announced in Rust 1.64. https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html

**Comment by TennyZhuang** [comment]
It seems that we can hold the PR after a bump.

**Comment by TennyZhuang** [comment]
It seems that we may also have to bump the cargo-udeps.

**Comment by Xuanwo** [comment]
> Announced in Rust 1.64. https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html

We are using 1.66 (nightly) now. This feature should be available.

> It seems that we may also have to bump the cargo-udeps.

Let me take a look.

**Comment by Xuanwo** [comment]
Can you help upgrade `cargo-udeps` to the latest version? thanks!

https://github.com/datafuselabs/databend/blob/e03366fa68babb0da237eb5609e13e04e287c3b4/scripts/setup/rust-tools.txt#L2

**Comment by Xuanwo** [comment]
Wait for https://github.com/datafuselabs/databend/pull/7815

**Comment by TennyZhuang** [comment]
The latest cargo-udeps still requires a feature flag.

**Review by PsiACE — APPROVED** [review]

**Review by Xuanwo — APPROVED** [review]

**Pull request merged**
