### PR TITLE
feat(query): batch insert values

### LINKED ISSUE #8988: Feature: Split insert values by row batch and insert in parallel
**Summary**

as comment https://github.com/datafuselabs/databend/pull/8966#issuecomment-1328225415

### PR DESCRIPTION
**Pull request by b41sh**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

use [aho-corasick](https://github.com/BurntSushi/aho-corasick) to split values and then batch insert values.

Closes #8988

### CODE REVIEW

**Comment by BohuTANG** [comment]
@mergify update

**Comment by b41sh** [comment]
The batch insert optimization effect of this PR is not good, the main problem lies in the processing of the MySQL protocol, so close this PR.

**Comment by BohuTANG** [comment]
@b41sh 
After https://github.com/datafuselabs/opensrv/pull/37 merged, we can retest whether this patch：https://github.com/datafuselabs/databend/pull/8966 is needed and how much performance is affected.

**Comment by b41sh** [comment]
> @b41sh After [datafuselabs/opensrv#37](https://github.com/datafuselabs/opensrv/pull/37) merged, we can retest whether this patch：#8966 is needed and how much performance is affected.

ok

**Comment by b41sh** [comment]
@BohuTANG The performance of inserting data using `AsyncSource` and `SyncSource` in https://github.com/datafuselabs/databend/pull/8966 is almost the same, we can keep this feature, it may be useful in the future.

**Comment by BohuTANG** [comment]
@b41sh 
Great if the performance is the same, it's a useless feature.
Suggest removing them not someday we perhaps use them. Let's keep the databend clean and usable.

**Pull request closed without merging**
