### PR TITLE
chore(http): both accept stage_name and stage-name as args on upload_to_stage

### PR DESCRIPTION
**Pull request by flaneur2020**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

having underscore in the http header seems to be not HTTP standard, and easy to get troubles on various HTTP proxies like nginx.

this PR makes `upload_to_stage` also accepts `stage-name` and `x-databend-stage-name` as arguments, and adjusted the related docs to encourage using `stage-name` instead of `stage_name`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12656)

### CODE REVIEW

**Review by BohuTANG — APPROVED** [review]

**Comment by BohuTANG** [comment]
Need a test to check the new header works and not braked by other PR in the future.

**Comment by flaneur2020** [comment]
> Need a test to check the new header works and not braked by other PR in the future.

let me add one in this pr before getting merge

**Comment by flaneur2020** [comment]
added tests in https://github.com/datafuselabs/databend/pull/12656/files#diff-0b123a2c66dc6caef99f4d85f948a085079fd897efda785cd1505f72858068b4R11

**Comment by sundy-li** [comment]
The headers in databend should always be `x-databend-xxxx` (or upper case).

Let's just add `x-databend-stage-name` for this pr.

Later we will bump the clients just send `x-databend-stage-name`.

**Comment by flaneur2020** [comment]
headers are case insensitive, so we can have `x-databend-stage-name` for suggested and keep `stage_name` for backward compatibility for a while

**Comment by flaneur2020** [comment]
@sundy-li PTAL

**Pull request merged**
