### PR TITLE
fix(test): rm the tailling comma of ontime.csv.

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Fixes https://github.com/datafuselabs/databend/issues/8531

### CODE REVIEW

**Comment by youngsofun** [comment]
The downloaded dataset has been corrupted, please remove and fetch it again.

**Review by Xuanwo — APPROVED** [review]

**Comment by sundy-li** [comment]
The last field is an empty string. Maybe we should change into  `,""` ?

**Comment by youngsofun** [comment]
@sundy-li 
one more column then the schema

**Review by BohuTANG — APPROVED** [review]

**Review by sundy-li — APPROVED** [review]

**Comment by BohuTANG** [comment]
Please enable the merge , don't believe the mergify like this PR @Xuanwo

**Comment by BohuTANG** [comment]
@mergify update

**Comment by BohuTANG** [comment]
@youngsofun This PR has some conflicts, but they are not shown here. Please merge with the latest main and push again.

**Comment by youngsofun** [comment]
@BohuTANG  already merged?  https://github.com/datafuselabs/databend/commits/main

**Comment by Xuanwo** [comment]
> @BohuTANG already merged? https://github.com/datafuselabs/databend/commits/main

Maybe a bug of github(

**Pull request closed without merging**
