### PR TITLE
Update bincode version

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary
Update bincode version

cc @ygf11 

Summary about this PR

## Changelog

- Not for changelog (changelog entry is not required)

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by ygf11** [comment]
Looks good to me.

**Comment by BohuTANG** [comment]
Why we maintain bincode crate in datafuselabs-extras?

**Comment by sundy-li** [comment]
> Why we maintain bincode crate in datafuselabs-extras?

This is because we always know that the vector state has small size ranges, so it benefits a lot to use variant encoding. But for other integers, the range may be random, it's better to use native encoding.

From PR #3465

**Pull request merged**
