### PR TITLE
[Release] fix release patch

### PR DESCRIPTION
**Pull request by ZhiHanZ**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary
If change OUT_DIR environment variable to other paths, it would introduce error during cross compile.

https://github.com/datafuselabs/databend/runs/4149080720?check_suite_focus=true
## Changelog

- Bug Fix

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
Related to #2725 ?

**Comment by drmingdrmer** [comment]
> Related to #2725 ?

It must be. 🤔

**Review by PsiACE — APPROVED** [review]

**Pull request merged**
