### PR TITLE
refactor: use `Binaryfuse16` and disable feature `uniform-random`

### PR DESCRIPTION
**Pull request by xudong963**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

- `Binaryfuse16` will reduce fp rate

- disabling feature `uniform-random` can reduce the cost of building bloom filter: https://github.com/ayazhafiz/xorf?tab=readme-ov-file#uniform-random

## Tests

- [ ] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [x] No Test  - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [x] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14187)

### CODE REVIEW

**Comment by xudong963** [comment]
Btw, [xorf](https://github.com/ayazhafiz/xorf) is better than the xorf that we are using

```rust
// bench construct bloom filter
fn bench_u64_using_new_bloom_from(c: &mut Criterion) {
    let column = rand_i64_column(1_000_000);
    let func_ctx = FunctionContext::default();
    let col = BloomIndex::calculate_column_digest(
        &func_ctx,
        &column,
        &DataType::Number(NumberDataType::Int64),
        &DataType::Boolean,
    )
    .unwrap();
    let digests = UInt64Type::try_downcast_column(&col).unwrap();
    c.bench_with_input(
        criterion::BenchmarkId::new("new_bloom_from", "u64"),
        &digests,
        |b, digests| b.iter(|| BinaryFuse16::try_from(digests.deref()).unwrap()),
    );
}

// old xorf
fn bench_u64_using_digests_from(c: &mut Criterion) {
    let column = rand_i64_column(1_000_000);
    let func_ctx = FunctionContext::default();
    let col = BloomIndex::calculate_column_digest(
        &func_ctx,
        &column,
        &DataType::Number(NumberDataType::Int64),
        &DataType::Boolean,
    )
    .unwrap();
    let digests = UInt64Type::try_downcast_column(&col).unwrap();
    c.bench_with_input(
        criterion::BenchmarkId::new("old_bloom_from", "u64"),
        &digests,
        |b, digests| {
            b.iter(|| {
                let mut builder = Xor8Builder::create();
                builder.add_digests(digests.deref());
                builder.build().unwrap()
            })
        },
    );
}

// bench contain in bloom filter
fn bench_u64_using_new_bloom_contain(c: &mut Criterion) {
    let column = rand_i64_column(1_000_000);
    let func_ctx = FunctionContext::default();
    let col = BloomIndex::calculate_column_digest(
        &func_ctx,
        &column,
        &DataType::Number(NumberDataType::Int64),
        &DataType::Boolean,
    )
    .unwrap();
    let digests = UInt64Type::try_downcast_column(&col).unwrap();
    let filter = BinaryFuse16::try_from(digests.deref()).unwrap();
    c.bench_function("new_bloom_contain", |b| {
        let key = thread_rng().gen();
        b.iter(||filter.contains(&key))
    });
}

// old xorf
fn bench_u64_using_digests_contain(c: &mut Criterion) {
    let column = rand_i64_column(1_000_000);
    let func_ctx = FunctionContext::default();
    let col = BloomIndex::calculate_column_digest(
        &func_ctx,
        &column,
        &DataType::Number(NumberDataType::Int64),
        &DataType::Boolean,
    )
    .unwrap();
    let digests = UInt64Type::try_downcast_column(&col).unwrap();
    let mut builder = Xor8Builder::create();
    builder.add_digests(digests.deref());
    let filter = builder.build().unwrap();
    c.bench_function("old_bloom_contain", |b| {
        let key = thread_rng().gen();
        b.iter(|| {
            filter.contains_digest(key);
        })
    });
}
```

```
old_bloom_from/u64      time:   [91.956 ms 92.400 ms 92.913 ms]
                        change: [+11.156% +11.911% +12.647%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high severe

new_bloom_from/u64      time:   [34.853 ms 35.015 ms 35.187 ms]
                        change: [-5.3573% -3.3763% -1.4135%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 2 outliers among 100 measurements (2.00%)
  1 (1.00%) high mild
  1 (1.00%) high severe

new_bloom_contain       time:   [2.5608 ns 2.5642 ns 2.5680 ns]
Found 6 outliers among 100 measurements (6.00%)
  4 (4.00%) low mild
  1 (1.00%) high mild
  1 (1.00%) high severe

old_bloom_contain       time:   [2.9524 ns 2.9605 ns 2.9758 ns]
Found 7 outliers among 100 measurements (7.00%)
  1 (1.00%) low mild
  2 (2.00%) high mild
  4 (4.00%) high severe
```
Maybe we can replace old xorf with it. cc @drmingdrmer

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 11 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14187)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @dantengsky)

**Comment by BohuTANG** [comment]
If we use BinaryFuse16, will it be compatible with the current Bloom filter file already in the s3?

**Comment by xudong963** [comment]
> If we use BinaryFuse16, will it be compatible with the current Bloom filter file already in the s3?

I think it's not compatible. They are different bloom filter crate, [old](https://github.com/datafuse-extras/xorfilter) and [new](https://github.com/ayazhafiz/xorf).

The PR won't influence current bloom filter file already in the s3, it only changed bloom filter used by runtime filter.

**Pull request merged**
