### PR TITLE
refactor: spead up csv reader.

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

I mistakenly create new reader for each batch when refactoring（it is one reader for each split in the origin imply）

- Fixes #[Link the issue here]

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [x] Performance Improvement
- [ ] Other (please describe):

### CODE REVIEW

**Comment by youngsofun** [comment]
@BohuTANG 

Query Duration:
9m 19.3s

**Review by Xuanwo — APPROVED** [review]
Thanks!

**Comment by BohuTANG** [comment]
👍 

image

**Comment by BohuTANG** [comment]
@dantengsky @youngsofun It seems this PR also faster ndjson read:
image

The old is slower as csv.

**Pull request merged**
