### PR TITLE
refactor(query): add config enable_meta_data_upgrade_json_to_pb_from_v307

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

enable_meta_data_upgrade_json_to_pb_from_v307 default disable.

Old version upgrade to new version, not auto upgrade json to pb.

## Tests

- [x] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [x] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16306)

### CODE REVIEW

**Review by drmingdrmer — CHANGES_REQUESTED** [review]
> Reviewed 3 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16306)* status: 3 of 17 files reviewed, 1 unresolved discussion (waiting on @TCeason)

___
*[`src/query/management/src/quota/quota_mgr.rs` line 57 at r1](https://reviewable.io/reviews/datafuselabs/databend/16306#-O4sOW58CynDzpFKdbQg:-O4sOW58CynDzpFKdbQh:b-xjlm6w) ([raw file](https://github.com/datafuselabs/databend/blob/4e257df34e31f8864120f819192e6115d9d98ab3/src/query/management/src/quota/quota_mgr.rs#L57)):*
> ```XML
> 
> #[async_trait::async_trait]
> impl<const WRITE_PB: bool> QuotaApi for QuotaMgr<WRITE_PB> {
> ```

It looks like `QuotaMgr` already have this flag in this generic const parameter `WRITE_PB`.
Set this const with the value of `enable_upgrade_meta_data_to_pb` would be just enough for your need IMHO.

**Review by drmingdrmer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16306)* status: 3 of 17 files reviewed, 2 unresolved discussions (waiting on @TCeason)

___
*[`src/query/users/src/user_api.rs` line 116 at r1](https://reviewable.io/reviews/datafuselabs/databend/16306#-O4sPKo67BUKSAuNn6gs:-O4sPKo67BUKSAuNn6gt:b-m8erd0) ([raw file](https://github.com/datafuselabs/databend/blob/4e257df34e31f8864120f819192e6115d9d98ab3/src/query/users/src/user_api.rs#L116)):*
> ```XML
>         conf: RpcClientConf,
>         tenant: &Tenant,
>         enable_upgrade_meta_data_to_pb: bool,
> ```

This flag should not be a flag for `UserApiProvider`, which is a container of various `API` managers .

The flag should only be added to the `role_api` method below.

Unless `enable_upgrade_meta_data_to_pb` will affect the behavior of all of the API managers in `UserApiProvider`.

Or introduce a dedicated `Config` instance as the third argument, which then defines configurations for each API manager.

**Comment by TCeason** [comment]
> 
> 
> > *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16306)* status: 3 of 17 files reviewed, 2 unresolved discussions (waiting on @TCeason)
> 
> ___
> *[`src/query/users/src/user_api.rs` line 116 at r1](https://reviewable.io/reviews/datafuselabs/databend/16306#-O4sPKo67BUKSAuNn6gs:-O4sPKo67BUKSAuNn6gt:b-m8erd0) ([raw file](https://github.com/datafuselabs/databend/blob/4e257df34e31f8864120f819192e6115d9d98ab3/src/query/users/src/user_api.rs#L116)):*
> > ```XML
> >         conf: RpcClientConf,
> >         tenant: &Tenant,
> >         enable_upgrade_meta_data_to_pb: bool,
> > ```
> 
> This flag should not be a flag for `UserApiProvider`, which is a container of various `API` managers .
> 
> The flag should only be added to the `role_api` method below.
> 
> Unless `enable_upgrade_meta_data_to_pb` will affect the behavior of all of the API managers in `UserApiProvider`.
> 
> Or introduce a dedicated `Config` instance as the third argument, which then defines configurations for each API manager.
> 
> 
> 
> 

Maybe Quota not support deserialize json? So I don't let this config control quota.

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 20 of 20 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16306)* status: all files reviewed, 3 unresolved discussions (waiting on @BohuTANG, @dantengsky, and @TCeason)

___
*[`src/query/management/src/role/role_mgr.rs` line 62 at r3](https://reviewable.io/reviews/datafuselabs/databend/16306#-O4u1p4D22z-I-MfzGI7:-O4u1p4D22z-I-MfzGI8:b-hgxivx) ([raw file](https://github.com/datafuselabs/databend/blob/5681e8a2ef42bccd1bf09204104be624393bc186/src/query/management/src/role/role_mgr.rs#L62)):*
> ```XML
>     kv_api: Arc<dyn kvapi::KVApi<Error = MetaError> + Send + Sync>,
>     tenant: Tenant,
>     enable_meta_data_upgrade_json_to_pb_from_v307: bool,
> ```

This flag does not have to be business specific at this level. It just `upgrade_to_pb` to `RoleMgr`.
___
*[`src/query/management/src/role/role_mgr.rs` line 534 at r3](https://reviewable.io/reviews/datafuselabs/databend/16306#-O4u2XuWDViL3ZrNEQH3:-O4u2XuWDViL3ZrNEQH4:b-yort4d) ([raw file](https://github.com/datafuselabs/databend/blob/5681e8a2ef42bccd1bf09204104be624393bc186/src/query/management/src/role/role_mgr.rs#L534)):*
> ```XML
> 
> fn quota(target: impl ToString, enable_meta_data_upgrade_json_to_pb_from_v307: bool) -> Quota {
>     if enable_meta_data_upgrade_json_to_pb_from_v307 {
> ```

simplify the flag to `enable_upgrade_to_pb`.



_Code quote:_
```XML
fn quota(target: impl ToString, enable_meta_data_upgrade_json_to_pb_from_v307: bool) -> Quota {
    if enable_meta_data_upgrade_json_to_pb_from_v307 {
```
___
*[`src/query/users/src/user_api.rs` line 134 at r3](https://reviewable.io/reviews/datafuselabs/databend/16306#-O4u33qn6P6ab6XomxoD:-O4u33qn6P6ab6XomxoE:bv0u0jw) ([raw file](https://github.com/datafuselabs/databend/blob/5681e8a2ef42bccd1bf09204104be624393bc186/src/query/users/src/user_api.rs#L134)):*
> ```XML
>             GlobalConfig::instance()
>                 .query
>                 .enable_meta_data_upgrade_json_to_pb_from_v307,
> ```

This flag just specifies if to upgrade json to pb, although it is used for v307.

The name should reflect the purpose `upgrade_to_pb`, `for from v307` could be part of its comment.

**Comment by TCeason** [comment]
> ```
> enable_meta_data_upgrade_json_to_pb_from_v307
> ```

Done

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16306)* status: all files reviewed, 3 unresolved discussions (waiting on @BohuTANG, @dantengsky, and @TCeason)

**Pull request merged**
