### PR TITLE
[DON'T-MERGE] Try to build databend into Wasm

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

Summary about this PR

## Changelog

- New Feature
 

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by sundy-li** [comment]
Current issue:
```
  Compiling socket2 v0.4.2
error[E0432]: unresolved import `crate::sys`
 --> /home/sundy/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/socket2-0.4.2/src/sockaddr.rs:5:12
  |
5 | use crate::sys::{
  |            ^^^ could not find `sys` in the crate root

error[E0432]: unresolved imports `crate::sys`, `crate::sys`
  --> /home/sundy/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/socket2-0.4.2/src/socket.rs:21:12
   |
21 | use crate::sys::{self, c_int, getsockopt, setsockopt, Bool};
   |            ^^^   ^^^^ no `sys` in the root
```

**Comment by Xuanwo** [comment]
It's cool!

**Comment by sundy-li** [comment]
> It's cool!

Actually, I have no idea to finish this pr..

**Comment by Xuanwo** [comment]
For wasm,  maybe we need to support no-std?

**Pull request closed without merging**
