### PR TITLE
chore(tokio): remove unused enable_all

### PR DESCRIPTION
**Pull request by BohuTANG**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Closes #issue

### CODE REVIEW

**Comment by drmingdrmer** [comment]
It enables io and timer. Don't we relies on them?:

```
  pub fn enable_all(&mut self) -> &mut Self {
        #[cfg(feature = "io-driver")]
        self.enable_io();
        #[cfg(feature = "time")]
        self.enable_time();

        self
    }
```

**Comment by drmingdrmer** [comment]
@BohuTANG unit test fails with:
thread 'Inner' panicked at 'A Tokio 1.x context was found, but timers are disabled. Call `enable_time` on the runtime builder to enable timers.', src/common/base/tests/it/runtime_tracker.rs:36:13

**Comment by BohuTANG** [comment]
> @BohuTANG unit test fails with: thread 'Inner' panicked at 'A Tokio 1.x context was found, but timers are disabled. Call `enable_time` on the runtime builder to enable timers.', src/common/base/tests/it/runtime_tracker.rs:36:13

`enable_io` will panic miri, so i removed it and added `enable_time`.

**Review by drmingdrmer — APPROVED** [review]

**Comment by BohuTANG** [comment]
Now we can run miri on some unit test, for example:
```
MIRIFLAGS='-Zmiri-disable-isolation' cargo miri test --test it pipelines::processors::port_test::test_port_drop
```

But we don't have many unit tests related to `unsafe`, FYI @zhang2014 @sundy-li

**Comment by BohuTANG** [comment]
oops:
```
ailures:

---- grpc_client::test_grpc_client_action_timeout stdout ----
thread 'meta-client-rt' panicked at 'A Tokio 1.x context was found, but IO is disabled. Call `enable_io` on the runtime builder to enable IO.', /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.23.1/src/net/tcp/stream.rs:161:18
```

**Comment by BohuTANG** [comment]
It seems we can't disable IO in Databend, wait for https://github.com/rust-lang/miri/issues/602

**Pull request closed without merging**
