### PR TITLE
ISSUE-3257: Add created_on to TableMeta

### LINKED ISSUE #3257: Add `created_on` to TableMeta
**Summary**

Add `created_on` to TableMeta:
https://github.com/datafuselabs/databend/blob/8c3ef25e153855ebbf9adbb2380ef6ef034ef902/common/meta/types/src/table.rs#L97-L101

```show tables;```

|created_on	| name 
| --------- | -------------- | 
2021-12-05 16:41:07.651 -0800|	T1

### PR DESCRIPTION
**Pull request by GanZiheng**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

Summary about this PR

## Changelog

- Improvement

## Related Issues

Fixes #3257 

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by GanZiheng** [comment]
Current Issue:
I found it is a little hard to pass some tests if we store `created_on` in `system.tables` because they select every thing from `system.tables`. I tried to modify test script to support regex but it will fail other tests. 
@BohuTANG could you please give me some suggestions for this problem? Should I modify test script or just don't store `created_on` in `system.tables`? Thanks.

**Comment by GanZiheng** [comment]
@drmingdrmer thank you for your review. I just update my pr with rebase and there are still 3 stateless tests failed.

**Review by drmingdrmer — APPROVED** [review]
Nice shot~

**Comment by GanZiheng** [comment]
@drmingdrmer Sorry to bother you. I'd like to know how to go on with this pr, since there are some checks not successful due to the issue below.

> Current Issue: I found it is a little hard to pass some tests if we store `created_on` in `system.tables` because they select every thing from `system.tables`. I tried to modify test script to support regex but it will fail other tests. @BohuTANG could you please give me some suggestions for this problem? Should I modify test script or just don't store `created_on` in `system.tables`? Thanks.

**Comment by drmingdrmer** [comment]
> @drmingdrmer Sorry to bother you. I'd like to know how to go on with this pr, since there are some checks not successful due to the issue below.
> 
> > Current Issue: I found it is a little hard to pass some tests if we store `created_on` in `system.tables` because they select every thing from `system.tables`. I tried to modify test script to support regex but it will fail other tests. @BohuTANG could you please give me some suggestions for this problem? Should I modify test script or just don't store `created_on` in `system.tables`? Thanks.

A first thought is to filter the stdout by regex. Let me take a shot.

**Comment by drmingdrmer** [comment]
@GanZiheng 
have a look at this~ 
https://github.com/datafuselabs/databend/pull/3475

**Comment by drmingdrmer** [comment]
@GanZiheng 
Merge my pr into your branch then you should have no trouble get your PR passed

**Comment by drmingdrmer** [comment]
@GanZiheng 
Let's merge.
The discussion about how to write tests in such cases is still in progress.

Let's refine it later

**Pull request merged**
