### PR TITLE
feat(query): efficiently memory two level group by in standalone mode 

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

feat(query): support external group by for standalone mode

- Release unused memory in advance.
- Streaming merges multiple aggregate states.

Closes #issue

### CODE REVIEW

**Comment by sundy-li** [comment]
how is the performance results?

**Comment by BohuTANG** [comment]
I will test&check the memory usage later :)

**Comment by BohuTANG** [comment]
@mergify update

**Comment by BohuTANG** [comment]
Before:
```
select count() from hits_expr group by url ignore_result;
Peak 23G mem
```

This(half memory of peak):
```
select count() from hits_expr group by url ignore_result;
Peak 15G mem
```

**Review by BohuTANG — APPROVED** [review]

**Comment by BohuTANG** [comment]
Let's merge.

**Pull request merged**
