### PR TITLE
feat(test): support mysql-connector-python 8.0.30

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

The mysql-connector-python refactor the function name 

_DATETIME_to_python -> _datetime_to_python
_STRING_to_python -> _string_to_python

So if docker's driver upgrade to 8.0.30 the test https://github.com/datafuselabs/databend/actions/runs/3028367354/jobs/4873334306 will err.

Now we pin the mysql-connector-python version with 8.0.28, so the test can pass.

Fixes #i7569

### CODE REVIEW

**Comment by TCeason** [comment]
If we want to pass test, need drop the pin in tests/logictest/Dockerfile

**Comment by TCeason** [comment]
test can pass on my local:

```shell
$ pip3 list|grep mysql                                     
mysql-connector        2.2.9               
mysql-connector-python 8.0.30              
mysqlclient            2.1.0       
$ python3 main.py 02_0012_function_datetimes
INFO:log:run_sql_suite for mysql with suites dir /home/taichong/database/source-code/datafuse/tests/logictest/suites
INFO:log:Suite file:suites/base/02_function/02_0012_function_datetimes pass!
INFO:log:Suite file:suites/base/02_function/02_0012_function_datetimes_tz pass!
INFO:log:run_sql_suite for http with suites dir /home/taichong/database/source-code/datafuse/tests/logictest/suites
INFO:log:Suite file:suites/base/02_function/02_0012_function_datetimes pass!
INFO:log:Suite file:suites/base/02_function/02_0012_function_datetimes_tz pass!
INFO:log:run_sql_suite for clickhouse with suites dir /home/taichong/database/source-code/datafuse/tests/logictest/suites
INFO:log:Suite file:suites/base/02_function/02_0012_function_datetimes pass!
INFO:log:Suite file:suites/base/02_function/02_0012_function_datetimes_tz pass!
Logic Test Summary
Runner mysql test 2 suites, avg time cost of suites is 4845.14 ms
Runner mysql test 236 statements, avg time cost of statements is 41.06 ms
Runner http test 2 suites, avg time cost of suites is 2868.23 ms
Runner http test 236 statements, avg time cost of statements is 24.31 ms
Runner clickhouse test 2 suites, avg time cost of suites is 2730.55 ms
Runner clickhouse test 235 statements, avg time cost of statements is 23.24 ms

All tests pass! Logic test success!

```

**Review by everpcpc — APPROVED** [review]

**Comment by TCeason** [comment]
wait https://github.com/datafuselabs/databend/pull/7610 merge

**Review by Xuanwo — APPROVED** [review]
Oh, Python!

**Comment by TCeason** [comment]
@Mergify update

**Pull request merged**
