### PR TITLE
feature(query): copy into stage support

### LINKED ISSUE #4498: Unloading data into stage
**Summary**

* Unloading into a Databend Internal Stage
* Unloading into a Databend External Stage

```
COPY INTO { internalStage | externalStage | externalLocation }
     FROM { [<database_name>.]<table_name> | ( <query> ) }
[ FILE_FORMAT = ( { TYPE = { CSV | JSON | PARQUET } [ formatTypeOptions ] } ) ]
[ copyOptions ]
[ VALIDATION_MODE = RETURN_ROWS ]
```

Reference:
https://docs.snowflake.com/en/user-guide-data-unload.html

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

## Changelog

- New Feature
 

## Related Issues

Fixes #4498

### CODE REVIEW

**Comment by BohuTANG** [comment]
We add a new feature: unloading data into s3. 
There is a demo https://github.com/datafuselabs/databend/pull/5579/files#diff-7c8278d52ae4ed2008a0098db05b1f085394cab7c01888a7fb71435d7b2e354f
 cc @soyeric128

**Comment by soyeric128** [comment]
> We add a new feature: unloading data into s3.
> There is a demo https://github.com/datafuselabs/databend/pull/5579/files#diff-7c8278d52ae4ed2008a0098db05b1f085394cab7c01888a7fb71435d7b2e354f
> cc @soyeric128

Hi @BohuTANG,

Do we support unloading into all of the three places, internalStage | externalStage | externalLocation as the syntax shows in #4498 ? Or the external stage only as indicated in the demo above?

**Comment by BohuTANG** [comment]
Hi @soyeric128 
Yes, we support three.

**Comment by soyeric128** [comment]
> Hi @soyeric128
> Yes, we support three.

Thanks for the reply. I just created a PR to add a file describing the command "COPY INTO _location_". 

- Most of the parameter description is from [the "COPY INTO _table_" page](https://databend.rs/doc/reference/sql/dml/dml-copy).
- I used the test script in the demo you provided as the example. 

Please help review the page and let me know if any comments, thanks.

**Pull request merged**
