### PR TITLE
refactor: remove all share related functions

### PR DESCRIPTION
**Pull request by drmingdrmer**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Tests

- [x] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [x] Other

## Related Issues

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16383)

### CODE REVIEW

**Comment by drmingdrmer** [comment]
@TCeason Please have a look at the statement tests changes, make sure no sql statements are removed except SHARE related sqls.
Because some of the statement such as role and share both use `grant xxx` for privilege management.

**Comment by TCeason** [comment]
> @TCeason Please have a look at the statement tests changes, make sure no sql statements are removed except SHARE related sqls.
> 
> Because some of the statement such as role and share both use `grant xxx` for privilege management.

Ok

**Comment by TCeason** [comment]
> @TCeason Please have a look at the statement tests changes, make sure no sql statements are removed except SHARE related sqls.
> 
> Because some of the statement such as role and share both use `grant xxx` for privilege management.

This pr not related to user role privilege.

**Review by BohuTANG — APPROVED** [review]

**Comment by BohuTANG** [comment]
@soyeric128 We can remove the `SHARE` part from the documention now, thanks.

**Comment by drmingdrmer** [comment]
**The backup of these removed codes is at: https://github.com/datafuselabs/databend/tree/share-bkp
Merge this branch to restore the removed codes.**

**Pull request merged**
