### PR TITLE
chore: make error msg of parquet schema miss match easier to read.

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

when table schema and parquet schema not match,  for example in https://github.com/datafuselabs/databend/issues/10171:  

```
➜  ~ curl -u root: -H "insert_sql:insert into nt_info file_format=(type=parquet)"  -F "upload=@./demo.parquet" -XPUT http://localhost:8000/v1/streaming_load
```

message before:

```
{"error":{"code":"400","message":"execute fail: parquet schema mismatch, differ: Differences (-expected_field|+infer_field):\n-TableField {\n+Field {\n     name: \"time_at\",\n-    default_expr: None,\n-    data_type: Timestamp,\n-    column_id: 6,\n+    data_type: Utf8,\n+    is_nullable: true,\n+    metadata: {},\n }\n"}}%
➜  ~ curl -u root: -H "insert_sql:insert into nt_info file_format=(type=parquet)"  -F "upload=@./demo.parquet" -XPUT http://localhost:8000/v1/streaming_load
```

after:

```
{"error":{"code":"400","message":"execute fail: parquet schema mismatch for field 6(start from 0), expect: TableField { name: \"time_at\", default_expr: None, data_type: Timestamp, column_id: 6 }, got TableField { name: \"time_at\", default_expr: None, data_type: Nullable(String), column_id: 0 }"}}%
```

Closes #issue

### CODE REVIEW

**Comment by youngsofun** [comment]
cc @wubx

**Comment by wubx** [comment]
Good job!
Clear error reporting will make it easier to use.

**Review by BohuTANG — APPROVED** [review]
Like the idea 👍

**Comment by BohuTANG** [comment]
Sorry for the conflict in another PR:
```
Conflicting files
docs/doc/15-sql-functions/112-table-functions/stage_table_funtion.md
```

**Pull request merged**
