### PR TITLE
refactor(query/config): Adapt RFC Config Backward Compatibility

### PR DESCRIPTION
**Pull request by Xuanwo**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Part of https://github.com/datafuselabs/databend/issues/5297

Followup of https://github.com/datafuselabs/databend/pull/5399

After this PR, `databend-query` will maintain config backward compatibility.

## Changelog

- Improvement

### CODE REVIEW

**Review by BohuTANG — APPROVED** [review]

**Review by sundy-li — APPROVED** [review]

**Comment by Xuanwo** [comment]
After merging with main branch, our unit tests will failed at:

```shell
---- servers::http::http_query_handlers::test_pagination stdout ----
thread 'servers::http::http_query_handlers::test_pagination' panicked at 'assertion failed: `(left == right)`: QueryResponse { id: "80643c6a-7441-4b72-b7f9-760308b38648", session_id: Some("ae898b2f-f5fc-4691-8d88-3bd8c079b291"), schema: Some(DataSchema { fields: [DataField { name: "number", data_type: UInt64, nullable: false }], metadata: {} }), data: [[Number(0)], [Number(1)]], state: Running, error: None, stats: QueryStats { scan_progress: Some(ProgressValues { rows: 10, bytes: 80 }), running_time_ms: 19.835854 }, stats_uri: Some("/v1/query/80643c6a-7441-4b72-b7f9-760308b38648"), final_uri: Some("/v1/query/80643c6a-7441-4b72-b7f9-760308b38648/final"), next_uri: Some("/v1/query/80643c6a-7441-4b72-b7f9-760308b38648/page/1"), kill_uri: Some("/v1/query/80643c6a-7441-4b72-b7f9-760308b38648/kill") }

Diff < left / right > :
<Running
>Succeeded

', query/tests/it/servers/http/http_query_handlers.rs:238:5
```

I can't reproduce it locally, any ideas about that?

**Comment by youngsofun** [comment]
@Xuanwo  I will fix it soon.

**Comment by Xuanwo** [comment]
@mergify requeue

**Comment by BohuTANG** [comment]
@mergify update

**Comment by Xuanwo** [comment]
Cool!

We have an ICE here...

```shell
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.
```

**Comment by Xuanwo** [comment]
Asking @everpcpc for help. What we should do while meeting ICE?

**Comment by Xuanwo** [comment]
@mergify update

**Comment by everpcpc** [comment]
> Asking @everpcpc for help. What we should do while meeting ICE?

It seems reproducible, maybe we could:
1. try upgrade the rust cache version to get a clean rebuild:
    https://github.com/datafuselabs/databend/blob/main/.github/actions/build_debug/action.yml#L39
3. try upgrade toolchain

**Comment by Xuanwo** [comment]
> 1. try upgrade the rust cache version to get a clean rebuild:

Let's try upgrade cache version first.

**Pull request merged**
