### PR TITLE
ci: migration stateless test 05_ddl and 06_show

### PR DESCRIPTION
**Pull request by ZeaLoVe**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

1. Migration stateless test 05_ddl and 06_show to logic test
2. Fix gen_suites.py an end-line empty space problem

Fixes #issue

### CODE REVIEW

**Comment by ZeaLoVe** [comment]
`SHOW SETTINGS LIKE 'enable%';`
http handler with planner_v2 get an error, I just skip it. cc @youngsofun 
` <1005: errno:1005,msg:sql parser error: Expected end of statement, found: LIKE>`

**Comment by ZeaLoVe** [comment]
ci failed https://github.com/datafuselabs/databend/runs/7496671712?check_suite_focus=true , because I delete stateless test 05_ddl dir. I see https://github.com/datafuselabs/databend/blob/main/tests/compat/test-compat.sh#L187-L198  meta will run 05_ddl test, It is redundant? cc @drmingdrmer

**Comment by drmingdrmer** [comment]
> ci failed https://github.com/datafuselabs/databend/runs/7496671712?check_suite_focus=true , because I delete stateless test 05_ddl dir. I see https://github.com/datafuselabs/databend/blob/main/tests/compat/test-compat.sh#L187-L198 meta will run 05_ddl test, It is redundant? cc @drmingdrmer

Hmmm... It's not redundant. It is meant to test if different versions of databend-query and databend-meta work smoothly. E.g., query-0.5 and meta-0.6

Since only `ddl` operations are related to query-meta operation, only these tests are run.

What's the command if I'd like to run the new 05_ddl tests?

**Comment by ZeaLoVe** [comment]
OK, I see, let me get this done.

**Comment by drmingdrmer** [comment]
> OK, I see, let me get this done.

Ok. If you got trouble with it. Let me do it.

**Review by drmingdrmer — APPROVED** [review]
Great!

**Comment by ZeaLoVe** [comment]
> Great!

**Comment by ZeaLoVe** [comment]
> Great!

Still something wrong with logic test pattern.. I will fix it.

**Review by sundy-li — APPROVED** [review]

**Comment by ZeaLoVe** [comment]
Seems old logictest in v0.7.57  has some issue with python3.9, I just use some commands to make it run. If test-compact failed again, we should not merge it util all problem solved.

**Pull request merged**
