### PR TITLE
[metasrv] temporarily disable connection pool to avoid connection hang

### PR DESCRIPTION
**Pull request by ariesdevil**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Temporarily disable connection pool to avoid connection hang. As [tonic doc said](https://docs.rs/tower-service/0.3.1/tower_service/trait.Service.html#tymethod.poll_ready) if `poll_ready` return `Poll::Ready(Ok(()))` that service is able to process requests. But if metasrv is force killed, that TCP connection remains half-open and the `poll_ready` still return `Poll::Ready(Ok(()))`.

### how to reproduce
0. add some debug info to [check function](https://github.com/datafuselabs/databend/blob/7385f416059bc7d5bc4eaa9c77c5d01cf659c197/common/meta/grpc/src/grpc_client.rs#L114)
1. deploy databend-query and databend-meta manually
2. using MySQL cli connect to databend and do some create table and insert oprations.
3. kill databend-meta and perform some operation with MySQL cli, then you can find it hang on...
4. using `strace` on the hanged process see it stuck on [`recvfrom`](https://linux.die.net/man/3/recvfrom)

## Changelog

- Improvement

## Related Issues

Fixes #issue

### CODE REVIEW

**Comment by drmingdrmer** [comment]
I'm afraid it is not the fault of the persistent connection pool.

It is caused by the `query` that does not handle errors correctly.

I can reproduce it and when it hangs, an error is returned to meta-client:
```
2022-06-02T01:38:19.380815Z DEBUG Some("meta-client-rt") ThreadId(17) worker_loop#8000000001: MetaGrpcClient send response to the handle resp=Err(MetaNetworkError(ConnectionError(ConnectionError { msg: "", source: tonic::status::Status: status: Unavailable, message: "error trying to connect: tcp connect error: Connection refused (os error 61)", details: [], metadata: MetadataMap { headers: {} } source: transport error source: error trying to connect: tcp connect error: Connection refused (os error 61) source: tcp connect error: Connection refused (os error 61) source: Connection refused (os error 61) })))
2022-06-02T01:38:19.380908Z  INFO Some("meta-client-rt") ThreadId(17) worker_loop#8000000001: exit
2022-06-02T01:38:19.380966Z DEBUG Some("mysql-query-executor") ThreadId(32) Destroy session 6b4d147c-397a-45a2-891c-48ca0ba2494a
2022-06-02T01:38:19.381712Z TRACE Some("mysql-query-executor") ThreadId(32) deregistering event source from poller    

```

It looks like query does not deal with such an error.

**Comment by ariesdevil** [comment]
> I'm afraid it is not the fault of the persistent connection pool.
> 
> It is caused by the `query` that does not handle errors correctly.
> 
> I can reproduce it and when it hangs, an error is returned to meta-client:
> 
> ```
> 2022-06-02T01:38:19.380815Z DEBUG Some("meta-client-rt") ThreadId(17) worker_loop#8000000001: MetaGrpcClient send response to the handle resp=Err(MetaNetworkError(ConnectionError(ConnectionError { msg: "", source: tonic::status::Status: status: Unavailable, message: "error trying to connect: tcp connect error: Connection refused (os error 61)", details: [], metadata: MetadataMap { headers: {} } source: transport error source: error trying to connect: tcp connect error: Connection refused (os error 61) source: tcp connect error: Connection refused (os error 61) source: Connection refused (os error 61) })))
> 2022-06-02T01:38:19.380908Z  INFO Some("meta-client-rt") ThreadId(17) worker_loop#8000000001: exit
> 2022-06-02T01:38:19.380966Z DEBUG Some("mysql-query-executor") ThreadId(32) Destroy session 6b4d147c-397a-45a2-891c-48ca0ba2494a
> 2022-06-02T01:38:19.381712Z TRACE Some("mysql-query-executor") ThreadId(32) deregistering event source from poller    
> ```
> 
> It looks like query does not deal with such an error. But instead, it just closed a query-session.

That's another question, but the Service::poll_ready should return error when service is killed.

**Comment by drmingdrmer** [comment]
> > I'm afraid it is not the fault of the persistent connection pool.
> > It is caused by the `query` that does not handle errors correctly.
> > I can reproduce it and when it hangs, an error is returned to meta-client:
> > ```
> > 2022-06-02T01:38:19.380815Z DEBUG Some("meta-client-rt") ThreadId(17) worker_loop#8000000001: MetaGrpcClient send response to the handle resp=Err(MetaNetworkError(ConnectionError(ConnectionError { msg: "", source: tonic::status::Status: status: Unavailable, message: "error trying to connect: tcp connect error: Connection refused (os error 61)", details: [], metadata: MetadataMap { headers: {} } source: transport error source: error trying to connect: tcp connect error: Connection refused (os error 61) source: tcp connect error: Connection refused (os error 61) source: Connection refused (os error 61) })))
> > 2022-06-02T01:38:19.380908Z  INFO Some("meta-client-rt") ThreadId(17) worker_loop#8000000001: exit
> > 2022-06-02T01:38:19.380966Z DEBUG Some("mysql-query-executor") ThreadId(32) Destroy session 6b4d147c-397a-45a2-891c-48ca0ba2494a
> > 2022-06-02T01:38:19.381712Z TRACE Some("mysql-query-executor") ThreadId(32) deregistering event source from poller    
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It looks like query does not deal with such an error. But instead, it just closed a query-session.
> 
> That's another question, but the Service::poll_ready should return error when service is killed.

I think it's by design the behavior of tower: it only checks the channel to the worker task, not the real connection.

**Review by lichuang — APPROVED** [review]

**Comment by drmingdrmer** [comment]
@mergify update

**Comment by drmingdrmer** [comment]
> > 
> 
> yep, it's our duty to check the connection

Is it possible to be done?

BTW, a connection that returned OK from `is_ready()` is still possible to get an error when handling the actual network request. Which will still hang the server. I do not think checking the readiness would eventually solve this issue.

It should be dealt with correctly by the caller of the client IMHO.

**Comment by ariesdevil** [comment]
> > yep, it's our duty to check the connection
> 
> Is it possible to be done?
> 
> BTW, a connection that returned OK from `is_ready()` is still possible to get an error when handling the actual network request. Which will still hang the server. I do not think checking the readiness would eventually solve this issue.
> 
> It should be dealt with correctly by the caller of the client IMHO.

Let me rethink it

**Pull request closed without merging**
