### PR TITLE
fix(httphandler): req should return as soon as results is exhausted.

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

1.  carry `bool done` aside block when `pop()` 
2.  notify when `stop_push()`
3.  not return data and next_url when error.

## Changelog

- Bug Fix

## Related Issues

Fixes https://github.com/datafuselabs/databend/issues/5456

### CODE REVIEW

**Review by junnplus — APPROVED** [review]

**Comment by BohuTANG** [comment]
failures:
    servers::http::http_query_handlers::test_pagination always failed.

https://github.com/datafuselabs/databend/runs/6505375747?check_suite_focus=true#step:3:3320

**Comment by youngsofun** [comment]
@BohuTANG should have been fixed. took a while to debug.

**Comment by youngsofun** [comment]
@TCeason 
```
02_0000_kill_query:                                                     2022-05-19T12:23:26.361052Z ERROR databend_query::pipelines::processors::processor_merge: Merge processor cannot push data: channel closed
[ FAIL ] - return code 1
, result:

Traceback (most recent call last):
  File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 178, in read
    data += self.queue.get(timeout=timeleft)
  File "/usr/lib/python3.8/queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 152, in expect
    data = self.read(timeout=timeleft, raise_exception=True)
  File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 186, in read
    raise TimeoutError(timeout)
uexpect.TimeoutError: Timeout 60.000s

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/databend/databend/tests/suites/1_stateful/02_query/02_0000_kill_query.py", line 25, in <module>
    with NativeClient(name='client2>') as client2:
  File "/home/runner/work/databend/databend/tests/suites/1_stateful/02_query/../../../helpers/native_client.py", line 38, in __init__
    self.client.expect('[#\$] ', timeout=60)
  File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 159, in expect
    raise exception
uexpect.ExpectTimeoutError: Timeout 60.000s for '[#\\$] ' 

```

**Comment by TCeason** [comment]
> @TCeason need your help
> 
> ```
> 02_0000_kill_query:                                                     2022-05-19T12:23:26.361052Z ERROR databend_query::pipelines::processors::processor_merge: Merge processor cannot push data: channel closed
> [ FAIL ] - return code 1
> , result:
> 
> Traceback (most recent call last):
>   File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 178, in read
>     data += self.queue.get(timeout=timeleft)
>   File "/usr/lib/python3.8/queue.py", line 178, in get
>     raise Empty
> _queue.Empty
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 152, in expect
>     data = self.read(timeout=timeleft, raise_exception=True)
>   File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 186, in read
>     raise TimeoutError(timeout)
> uexpect.TimeoutError: Timeout 60.000s
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/runner/work/databend/databend/tests/suites/1_stateful/02_query/02_0000_kill_query.py", line 25, in <module>
>     with NativeClient(name='client2>') as client2:
>   File "/home/runner/work/databend/databend/tests/suites/1_stateful/02_query/../../../helpers/native_client.py", line 38, in __init__
>     self.client.expect('[#\$] ', timeout=60)
>   File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 159, in expect
>     raise exception
> uexpect.ExpectTimeoutError: Timeout 60.000s for '[#\\$] ' 
> ```

Yes that a flaky test, needs a rerun.

**Comment by BohuTANG** [comment]
> > @TCeason need your help
> > ```
> > 02_0000_kill_query:                                                     2022-05-19T12:23:26.361052Z ERROR databend_query::pipelines::processors::processor_merge: Merge processor cannot push data: channel closed
> > [ FAIL ] - return code 1
> > , result:
> > 
> > Traceback (most recent call last):
> >   File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 178, in read
> >     data += self.queue.get(timeout=timeleft)
> >   File "/usr/lib/python3.8/queue.py", line 178, in get
> >     raise Empty
> > _queue.Empty
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 152, in expect
> >     data = self.read(timeout=timeleft, raise_exception=True)
> >   File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 186, in read
> >     raise TimeoutError(timeout)
> > uexpect.TimeoutError: Timeout 60.000s
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/home/runner/work/databend/databend/tests/suites/1_stateful/02_query/02_0000_kill_query.py", line 25, in <module>
> >     with NativeClient(name='client2>') as client2:
> >   File "/home/runner/work/databend/databend/tests/suites/1_stateful/02_query/../../../helpers/native_client.py", line 38, in __init__
> >     self.client.expect('[#\$] ', timeout=60)
> >   File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 159, in expect
> >     raise exception
> > uexpect.ExpectTimeoutError: Timeout 60.000s for '[#\\$] ' 
> > ```
> 
> Yes that a flaky test, needs a rerun.

Re-run can't save it. It seems to fail every time, needs improvement, or skip this test.

**Comment by youngsofun** [comment]
a unit test seems to be blocked,  I am working on it.

**Comment by TCeason** [comment]
> > > @TCeason need your help
> > > ```
> > > 02_0000_kill_query:                                                     2022-05-19T12:23:26.361052Z ERROR databend_query::pipelines::processors::processor_merge: Merge processor cannot push data: channel closed
> > > [ FAIL ] - return code 1
> > > , result:
> > > 
> > > Traceback (most recent call last):
> > >   File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 178, in read
> > >     data += self.queue.get(timeout=timeleft)
> > >   File "/usr/lib/python3.8/queue.py", line 178, in get
> > >     raise Empty
> > > _queue.Empty
> > > 
> > > During handling of the above exception, another exception occurred:
> > > 
> > > Traceback (most recent call last):
> > >   File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 152, in expect
> > >     data = self.read(timeout=timeleft, raise_exception=True)
> > >   File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 186, in read
> > >     raise TimeoutError(timeout)
> > > uexpect.TimeoutError: Timeout 60.000s
> > > 
> > > During handling of the above exception, another exception occurred:
> > > 
> > > Traceback (most recent call last):
> > >   File "/home/runner/work/databend/databend/tests/suites/1_stateful/02_query/02_0000_kill_query.py", line 25, in <module>
> > >     with NativeClient(name='client2>') as client2:
> > >   File "/home/runner/work/databend/databend/tests/suites/1_stateful/02_query/../../../helpers/native_client.py", line 38, in __init__
> > >     self.client.expect('[#\$] ', timeout=60)
> > >   File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 159, in expect
> > >     raise exception
> > > uexpect.ExpectTimeoutError: Timeout 60.000s for '[#\\$] ' 
> > > ```
> > 
> > 
> > Yes that a flaky test, needs a rerun.
> 
> Re-run can't save it. It seems to fail every time, needs improvement, or skip this test.

Got and doing

**Comment by TCeason** [comment]
And I think you can skip this test tmp. @youngsofun 

remove file : 02_0000_kill_query.result in your pr.

**Comment by youngsofun** [comment]
> And I think you can skip this test tmp. @youngsofun
> 
> remove file : 02_0000_kill_query.result in your pr.

@TCeason 
removed

**Comment by youngsofun** [comment]
find another flaky test...

**Pull request merged**
