### PR TITLE
refactor: append transform and mutation log

### PR DESCRIPTION
**Pull request by zhyass**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary
split from pr #11850

1. split `AppendTransform` to `TransformSerializeBlock` and `TransformSerializeSegment`
2. refactor `MutationLogEntry`

- Closes #issue

### CODE REVIEW

**Comment by JackTan25** [comment]
askbend:summary

**Comment by JackTan25** [comment]
I think the MutationLogEntry's refactor is great for me, no problem. As to split of the AppendTransform, I'm not very sure, but I can't find out some bad corner cases. (not very familiar with this very much for now). @dantengsky please confirm
it.

**Review by JackTan25 — APPROVED** [review]
I think the MutationLogEntry's refactor is great for me, no problem. As to split of the AppendTransform, I'm not very sure, but I can't find out some bad corner cases. (not very familiar with this very much for now). @dantengsky please confirm
it.

**Comment by dantengsky** [comment]
> I think the MutationLogEntry's refactor is great for me, no problem. As to split of the AppendTransform, I'm not very sure, but I can't find out some bad corner cases. (not very familiar with this very much for now). @dantengsky please confirm it.

:ok_hand:

**Review by dantengsky — APPROVED** [review]

**Pull request merged**
