### PR TITLE
ci: fix logictest dockerfile

### PR DESCRIPTION
**Pull request by ZeaLoVe**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Dockerfile Copy *  behave unexpected. We need copy suites to /suites, but actually it copy suites/ydb/* suites/base/*  to /suites.
So use copy suites /suites instead.

Fixes #issue

### CODE REVIEW

**Review by everpcpc — APPROVED** [review]

**Comment by Xuanwo** [comment]
Please...

Remove container image for the logic test. It doesn't make sense at all...

**Comment by ZeaLoVe** [comment]
> Please...
> 
> Remove container image for the logic test. It doesn't make sense at all...

hmmm, this is a medium size refactor, maybe an issue for later action?

**Review by Xuanwo — APPROVED** [review]

**Comment by Xuanwo** [comment]
> hmmm, this is a medium size refactor, maybe an issue for later action?

Nice idea, I have raised an issue: https://github.com/datafuselabs/databend/issues/7002

**Comment by Xuanwo** [comment]
@mergify update

**Pull request merged**
