### PR TITLE
feat(format): fix TSV file format and tests

### LINKED ISSUE #9733: bug: copy XML file format into stage panic
**Summary**

client:
```
create table test(a int);
insert into test select * from numbers(10);
create stage stagexml;
COPY INTO @stagexml FROM test FILE_FORMAT=(type=XML)
ERROR 1105 (HY000): Code: 1068, displayText = Cannot join handle from context's runtime, cause: task 11520 panicked.
```

server log:
```
{
   "fn":"tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/runtime/scheduler/multi_thread/worker.rs",
   "line":406
},
{
   "fn":"tokio::macros::scoped_tls::ScopedKey<T>::set",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/macros/scoped_tls.rs",
   "line":61
},
{
   "fn":"tokio::runtime::scheduler::multi_thread::worker::run",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/runtime/scheduler/multi_thread/worker.rs",
   "line":403
},
{
   "fn":"tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/runtime/scheduler/multi_thread/worker.rs",
   "line":365
},
{
   "fn":"<tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/runtime/blocking/task.rs",
   "line":42
},
{
   "fn":"tokio::runtime::task::core::Core<T,S>::poll::{{closure}}",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/runtime/task/core.rs",
   "line":223
},
{
   "fn":"tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/loom/std/unsafe_cell.rs",
   "line":14
},
{
   "fn":"tokio::runtime::task::core::Core<T,S>::poll",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/runtime/task/core.rs",
   "line":212
},
{
   "fn":"tokio::runtime::task::harness::poll_future::{{closure}}",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/runtime/task/harness.rs",
   "line":481
},
{
   "fn":"<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once",
   "file":"/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/core/src/panic/unwind_safe.rs",
   "line":271
},
{
   "fn":"std::panicking::try::do_call",
   "file":"/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs",
   "line":483
},
{
   "fn":"___rust_try"
},
{
   "fn":"std::panicking::try",
   "file":"/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs",
   "line":447
},
{
   "fn":"std::panic::catch_unwind",
   "file":"/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panic.rs",
   "line":137
},
{
   "fn":"tokio::runtime::task::harness::poll_future",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/runtime/task/harness.rs",
   "line":469
},
{
   "fn":"tokio::runtime::task::harness::Harness<T,S>::poll_inner",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/runtime/task/harness.rs",
   "line":198
},
{
   "fn":"tokio::runtime::task::harness::Harness<T,S>::poll",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/runtime/task/harness.rs",
   "line":152
},
{
   "fn":"tokio::runtime::task::raw::poll",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/runtime/task/raw.rs",
   "line":255
},
{
   "fn":"tokio::runtime::task::raw::RawTask::poll",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/runtime/task/raw.rs",
   "line":200
},
{
   "fn":"tokio::runtime::task::UnownedTask<S>::run",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/runtime/task/mod.rs",
   "line":496
},
{
   "fn":"tokio::runtime::blocking::pool::Task::run",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/runtime/blocking/pool.rs",
   "line":159
},
{
   "fn":"tokio::runtime::blocking::pool::Inner::run",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/runtime/blocking/pool.rs",
   "line":510
},
{
   "fn":"tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}",
   "file":"/Users/bohu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.23.1/src/runtime/blocking/pool.rs",
   "line":468
},
{
   "fn":"std::sys_common::backtrace::__rust_begin_short_backtrace",
   "file":"/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys_common/backtrace.rs",
   "line":121
},
{
   "fn":"std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}",
   "file":"/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/thread/mod.rs",
   "line":550
},
{
   "fn":"<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once",
   "file":"/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/core/src/panic/unwind_safe.rs",
   "line":271
},
{
   "fn":"std::panicking::try::do_call",
   "file":"/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs",
   "line":483
},
{
   "fn":"___rust_try"
},
{
   "fn":"std::panicking::try",
   "file":"/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs",
   "line":447
},
{
   "fn":"std::panic::catch_unwind",
   "file":"/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panic.rs",
   "line":137
},
{
   "fn":"std::thread::Builder::spawn_unchecked_::{{closure}}",
   "file":"/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/thread/mod.rs",
   "line":549
},
{
   "fn":"core::ops::function::FnOnce::call_once{{vtable.shim}}",
   "file":"/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/core/src/ops/function.rs",
   "line":507
},
{
   "fn":"<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once",
   "file":"/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/alloc/src/boxed.rs",
   "line":2000
},
{
   "fn":"<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once",
   "file":"/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/alloc/src/boxed.rs",
   "line":2000
},
{
   "fn":"std::sys::unix::thread::Thread::new::thread_start",
   "file":"/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys/unix/thread.rs",
   "line":108
},
{
   "fn":"__pthread_deallocate"
}
],
"panic.file":"src/query/formats/src/file_format_type.rs",
"panic.line":198,
"panic.column":17
```

### PR DESCRIPTION
**Pull request by BohuTANG**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

* add TSV file format back
* refine the file format
* add a logic test for the file format

Closes #9733, #9731

### CODE REVIEW

**Comment by BohuTANG** [comment]
The `ON_ERROR` display will ignore if the `ON_ERROR` is empty, cc @ariesdevil

**Comment by ariesdevil** [comment]
> The `ON_ERROR` display will ignore if the `ON_ERROR` is empty, cc @ariesdevil↳

I wonder if we should make `ON_ERROR` display to `abort` when the `ON_ERROR` is empty, we don't have `None` as an option right now.

**Comment by BohuTANG** [comment]
> > The `ON_ERROR` display will ignore if the `ON_ERROR` is empty, cc @ariesdevil↳
> 
> I wonder if we should make `ON_ERROR` display to `abort` when the `ON_ERROR` is empty, we don't have `None` as an option right now.

Make sense. `ON_ERROR` default is `abort`, prefer to make it from string to enum, like (type = CSV).

**Comment by ariesdevil** [comment]
I'll do this tomorrow, just returned to Beijing :)

**Pull request merged**
