### PR TITLE
refactor: migrate from tokio-tracing to minitrace

### PR DESCRIPTION
**Pull request by andylokandy**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

This PR proposes replacing tokio-tracing with [minitrace](https://github.com/tikv/minitrace-rust/) for a 100x performance boost in tracing. Although we previously utilized numerous utilities from tokio-tracing, such as logging macros and function return value inspectors, all similar features can now be achieved using minitrace in conjunction with [log](https://crates.io/crates/log) and [logcall](https://crates.io/crates/logcall).

The refactoring process includes:

1. Reimplementing within the common_tracing crate.

2. Substituting `#[tracing::instrument]` with `#[minitrace::trace]` and `#[logcall::logcall("info")]`.

3. Switching from `tracing::{warn, info, error,...}` to `log::{warn, info, error,...}`.

However, since [tokio-console](https://github.com/tokio-rs/console) is built on top of 'tokio-tracing', it remains an optional dependency of 'common_tracing', controlled by a feature flag.

There are still significant tasks ahead:

1. Implementing sentry support.
   
2. Migrating openraft.
   
3. Conducting A/B testing on logging and tracing output to ensure no unexpected issues arise.

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12169)

### CODE REVIEW

**Comment by drmingdrmer** [comment]
From my observation, tracing is not our performance bottleneck, so a 100x increase in tracing might not lead to a noticeable improvement in our overall performance. Implementing this change requires extensive modifications to our existing codebase and dependencies.

If tracing overhead isn't the primary constraint on our performance, it seems preferable to avoid substantial rewrites of our codebase.

**Comment by andylokandy** [comment]
> From my observation, tracing is not our performance bottleneck, so a 100x increase in tracing might not lead to a noticeable improvement in our overall performance.

It's not about to improve performance, but providing a way to add trace everywhere with no hesitate. Our plan is to add minitrace to planner or maybe deep down into interpreter later.

> it seems preferable to avoid substantial rewrites of our codebase.

This PR is merely a showcase and prove-of-concept, later on we could break it down and merge it as smaller PRs for easier integration.

**Comment by drmingdrmer** [comment]
> > From my observation, tracing is not our performance bottleneck, so a 100x increase in tracing might not lead to a noticeable improvement in our overall performance.
> 
> It's not about improving performance, but providing a way to add trace everywhere with no hesitate. Our plan is to add minitrace to planner or maybe deep down into interpreter later.
> 
> > it seems preferable to avoid substantial rewrites of our codebase.
> 
> This PR is merely a showcase and prove-of-concept, later on we could break it down and merge it as smaller PRs for easier integration.

Make sense.

**Comment by andylokandy** [comment]
Seems ok comparing to https://github.com/datafuselabs/databend/pull/12220

**Review by drmingdrmer — CHANGES_REQUESTED** [review]
Is it possible to output tracing spans like the following to a file? I used to debug meta-service issues with these tracing log. Or is there a replacement of it?
```
2023-07-20T15:32:56.118678Z DEBUG Some("meta-client-rt") ThreadId(15) worker_loop#14000000001:watch#14000000002:make_client#14000000003:make_channel#14000000004{addr=Some("127.0.0.1:29001")}:get#14000000005{self=Pool { initial_retry_interval: 50ms, items: Mutex { data: {}, poisoned: false, .. }, manager: MetaChannelManager { timeout: None, conf: None }, err_type: PhantomData<common_meta_types::errors::meta_network_errors::MetaNetworkError>, n_retries: 3 } key="127.0.0.1:29001"}:build#14000000006{self=MetaChannelManager { timeout: None, conf: None } addr="127.0.0.1:29001"}:Connection#14000000007{peer=Client}: enter
```

> Reviewed 6 of 296 files at r1, 4 of 109 files at r4, 4 of 16 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12169#-:-NaKS1a8BMlELTeVp98V:bu16tge)* status: 14 of 310 files reviewed, 1 unresolved discussion (waiting on @andylokandy)

___
*[`src/common/tracing/src/minitrace.rs` line 187 at r5](https://reviewable.io/reviews/datafuselabs/databend/12169#-NaKRW1m9-nHDZShoSCc:-NaKRW1n39exKz7lOTCq:bosjkwk) ([raw file](https://github.com/datafuselabs/databend/blob/b488f103d21a70faa3ca6b8d6d5e3b7ba6e6ac55/src/common/tracing/src/minitrace.rs#L187)):*
> ```XML
> }
> 
> fn formmater(
> ```

I think it should be `formatter` :)

**Comment by drmingdrmer** [comment]
> > I think it should be formatter :)
> 
> the name `format` comes from the configuration item:
> 
> https://github.com/datafuselabs/databend/blob/b488f103d21a70faa3ca6b8d6d5e3b7ba6e6ac55/src/common/tracing/src/config.rs#L35
> 
> to my understanding, this `formatter` function inputs a `format` config item and then returns a formatter.

I mean...is it a typo: `formmater -> formatter`?

**Comment by BohuTANG** [comment]
This PR is ready to merge this weekend? @andylokandy @drmingdrmer

**Comment by andylokandy** [comment]
it's pending for review

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 1 of 109 files at r4, 4 of 8 files at r8, 12 of 16 files at r9, 4 of 7 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12169)* status: 310 of 313 files reviewed, 1 unresolved discussion (waiting on @andylokandy)

**Comment by drmingdrmer** [comment]
Since tracing is also heavily used by storage, it would be better if @dantengsky ensures these changes won't affect tracing requirements on storage.

**Review by dantengsky — APPROVED** [review]

**Comment by niebayes** [comment]
Have you ever considered the portability issue related to minitrace?
See: https://github.com/risingwavelabs/risingwave/issues/10236

**Comment by drmingdrmer** [comment]
> Have you ever considered the portability issue related to minitrace? See: [risingwavelabs/risingwave#10236](https://github.com/risingwavelabs/risingwave/issues/10236)

@andylokandy

**Comment by andylokandy** [comment]
@niebayes thank you! never knows about the protability limitation. But I think as long as minitace allows to replace minstant with https://github.com/metrics-rs/quanta using a feature flag, everything will be fine.

**Comment by niebayes** [comment]
@andylokandy `quanta` also states only x86 arch is supported. The performance improvement gained from TSC support will degrade whatsoever.
image

**Comment by andylokandy** [comment]
> @andylokandy `quanta` also states only x86 arch is supported. The performance improvement gained from TSC support will degrade whatsoever. image

yes, tsc is a x86-specific feature. anyway, the fallback timer, aka coerse, does not have drawback in performance but in accuracy only.

**Pull request merged**
