### PR TITLE
refactor: Use OpenDAL API to avoid extra seek call

### PR DESCRIPTION
**Pull request by Xuanwo**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

This PR will refactor the read metadata implement by adopting OpenDAL's native API instead of seek on reader.

Benchmark:

Test upon a 100MiB parquet file hosted on minio.

```rust
old/old                 time:   [4.5618 ms 4.6360 ms 4.7137 ms]
new/new                 time:   [1.4413 ms 1.5201 ms 1.6057 ms]
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12524)

### CODE REVIEW

**Comment by Xuanwo** [comment]
image

Tpch looks good, but hits seems OOM, let's try again.

**Comment by Xuanwo** [comment]
Q0 is 186x slower, seems related to cache changes, let's try again.

**Comment by dantengsky** [comment]
Untitled

regression of q19 looks weird, this query should benefit from the improvement of this PR

**Comment by Xuanwo** [comment]
This PR's performance is not as my expected, I will figure out what happened.

**Comment by Xuanwo** [comment]
I conducted a test in the development environment and found that this PR does not have a significant impact on real use cases. I recommend merging this PR initially to determine if it resolves the issue of unexpected query hang.

**Comment by dantengsky** [comment]
> I conducted a test in the development environment and found that this PR does not have a significant impact on real use cases. I recommend merging this PR initially to determine if it resolves the issue of unexpected query hang.
> 
> cc @BohuTANG @dantengsky

confirm. 

Tested with a table consisting of 19900 blocks, point queries that hit 6 blocks show no regression.

**Review by dantengsky — APPROVED** [review]

**Pull request merged**
