### PR TITLE
feat: add create or replace stage support

### LINKED ISSUE #14547: feat: add create or replace stage support
**Summary**

feat: add create or replace stage support

### PR DESCRIPTION
**Pull request by lichuang**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

feat: add create or replace stage support

- Fixes #14547

## Tests

- [x] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [x] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14548)

### CODE REVIEW

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 2 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14548)* status: 2 of 13 files reviewed, 1 unresolved discussion (waiting on @lichuang)

___
*[`src/query/management/src/stage/stage_mgr.rs` line 107 at r1](https://reviewable.io/reviews/datafuselabs/databend/14548#-NpYv-TY0lrZ78EKrQq5:-NpYv-TZDNZ_Kd_kIrDK:bnmelch) ([raw file](https://github.com/datafuselabs/databend/blob/20aed88a1e3f7921b8f16169e319030a3d415c33/src/query/management/src/stage/stage_mgr.rs#L107)):*
> ```XML
>                 &key,
>                 serialize_struct(&info, ErrorCode::IllegalUserStageFormat, || "")?,
>             )];
> ```

Why is it written as a transaction here? Wouldn't a simple upsert be enough? For CreateIfNotExists, it would be `MatchSeq::Exact(0)`; and for CreateOrReplace, it would be `MatchSeq::GE(0)`.

**Review by drmingdrmer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14548)* status: 2 of 13 files reviewed, 1 unresolved discussion (waiting on @lichuang)

___
*[`src/query/management/src/stage/stage_mgr.rs` line 106 at r2](https://reviewable.io/reviews/datafuselabs/databend/14548#-NpZ2ci9B2NkC-MWOxoE:-NpZ2ci9B2NkC-MWOxoF:bgae9q1) ([raw file](https://github.com/datafuselabs/databend/blob/bcbdb65f247177115f7becaef45b69d66ce33f4b/src/query/management/src/stage/stage_mgr.rs#L106)):*
> ```XML
>         self.kv_api
>             .upsert_kv(UpsertKVReq::new(&key, seq, val, None))
>             .await?;
> ```

The result of the upsert must be checked to see if it succeeded.
And the `get()` before `upsert` is unnecessary.



_Suggestion:_
```XML
let seq = match create_option {
    CreateOption::CreateIfNotExists(_) => MatchSeq::Exact(0),
    CreateOption::CreateOrReplace => MatchSeq::GE(0),
};

let res = self.kv_api
    .upsert_kv(UpsertKVReq::new(&key, seq, val, None))
    .await?;

match create_option {
    CreateOption::CreateIfNotExists(false) => {
        if res.prev.is_some() {
            return Err(ErrorCode::StageAlreadyExists(format!(
                "Stage '{}' already exists.",
                info.stage_name
            )));
        }
    },
    _ => {}
}
```

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 7 of 13 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14548)* status: 10 of 13 files reviewed, all discussions resolved

**Review by drmingdrmer — APPROVED** [review]

**Comment by lichuang** [comment]
@soyeric128

**Pull request merged**
