### PR TITLE
chore(query): turn on new agg hashtable

### PR DESCRIPTION
**Pull request by Freejww**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

In the previous PR, we implemented a new aggregation hash table. Now, it supports both singleton and cluster environments, and we have also added support for spill. This PR includes performance tests and try to enable the new aggregation hash table.

- Fixes #[Link the issue here]

## Tests

- [x] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [x] Performance Improvement
- [ ] Other (please describe):

### CODE REVIEW

**Comment by Freejww** [comment]
# Performance test on ClickBench/hits

### Note: We use `hits` as a benchmark because there are many group by tests.

### Local machine configuration: 32GB memory, 12-core CPU.
1. The new aggregation hash table has completely outperformed the old method.
2. In some high-cardinality or string grouping , the new method outperforms the old one.
3. More details will be introduced in a later blog.
hits-perf

**Comment by sundy-li** [comment]
There are explain tests that need to be fixed.

**Comment by sundy-li** [comment]
We use random and fixed SQL queries to cover the correctness tests.

Test Codes in https://github.com/sundy-li/mmbend/tree/master/examples

**Comment by BohuTANG** [comment]
Great 👍 

Wizard [SELECTS] tests **passed**. SQL selects script here: https://github.com/datafuselabs/wizard/blob/main/checksb/sql/selects/check.sql

**Review by sundy-li — APPROVED** [review]

**Comment by compasses** [comment]
May I know the test carried on memory limited ?

> # Performance test on ClickBench/hits

**Comment by sundy-li** [comment]
> May I know the test carried on memory limited ?

No major difference when blocks are spilled, because the bottleneck is io issue.

**Comment by compasses** [comment]
got thanks
So I think this kind of implementation may not efficient than general-purpose hash table like Clickhouse did.

**Comment by sundy-li** [comment]
> So I think this kind of implementation may not efficient than general-purpose hash table like Clickhouse did.

I disagree with that. The older one is the general-purpose hashtable you indicate.

**Comment by Freejww** [comment]
> Oh, OK, I mean without IO effect. Since most of agg workloads are memory-bound. And the way of implementation above seems need indirection access? Or maybe I missed something, but memory bandwidth is important for high cardinality keys.

Indirect access is that we only compare the high 16 bits of the hash. If they match, then we proceed to compare the actual data. General-purpose hashtable compares the entire hash value before proceeding to compare the actual data.

**Comment by compasses** [comment]
OK got you thanks. Since the general-purpose hashtable will compare hash values if they saved the hash, if not just use it for probing, but any way the memory layout is more cache-friendly.

**Pull request merged**
