### PR TITLE
AUTO RUN `test_management_mode` IN CI AND release after the test passed.

### LINKED ISSUE #4134: test_management_mode test actually not running
**Summary**

There are 2 issues for test_management_mode:
1. `test_management_mode test` actually not running, the CI pass is in wrong status:
https://github.com/datafuselabs/databend/runs/5172713388?check_suite_focus=true

2. Add `test_management_mode test` to production(now only run in Developing)
https://github.com/datafuselabs/databend/blob/9b004e0bc2969c42ee1658e2c3a11552cb9fead9/.github/workflows/developing.yml#L97-L106

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

> **Summary**
> 
> There are 2 issues for test_management_mode:
> 
> 1. `test_management_mode test` actually not running, the CI pass is in wrong status:
>    https://github.com/datafuselabs/databend/runs/5172713388?check_suite_focus=true
> 2. Add `test_management_mode test` to production(now only run in Developing)
>    https://github.com/datafuselabs/databend/blob/9b004e0bc2969c42ee1658e2c3a11552cb9fead9/.github/workflows/developing.yml#L97-L106

For Q1:
   [this yml](https://github.com/datafuselabs/databend/blob/e293ca21f9c6d6d6dd0f57265c19e87e1056db2a/.github/actions/test_management_mode/action.yml#L46) means just `matrix.config.os != 'ubuntu-latest'`, run the management mode test, but in the [dev yml](https://github.com/datafuselabs/databend/blob/93b70b3392f3fa506e2fb08cf7c844dbb9c5246a/.github/workflows/developing.yml#L114) the matrix.config.os is `ubuntu-latest`. So the test not run.

For Q2:

 Should add to [produce yml](https://github.com/datafuselabs/databend/blob/e20fd1561099fd097a273dbbcda6b705adb2e490/.github/workflows/production.yml#L119) and add publish_image.need.

## Changelog

- Improvement
- Build/Testing/CI

## Related Issues

Fixes #4134 

## Test Plan

Stateless Tests

### CODE REVIEW

**Comment by TCeason** [comment]
I will keep an eye on the PR to see if it has passed the management test.

**Comment by TCeason** [comment]
The test failed, but I try to run it on my local, it successed.

```
➜  ~/database/source-code/datafuse👆 git:(ISSUE-4134/test_management_mode)  bash -x scripts/ci/ci-run-stateless-tests-management-mode.sh 
+ echo 'Starting DatabendQuery management mode(debug)'
Starting DatabendQuery management mode(debug)
+ ./scripts/ci/deploy/databend-query-management-mode.sh
databend-query(2386844): 不允许的操作
databend-query: 未找到进程
databend-meta(2386666): 不允许的操作
databend-meta: 未找到进程
The databend-query is not killed. force killing.
databend-query(2386844): 不允许的操作
databend-query: 未找到进程
The databend-meta is not killed. force killing.
databend-meta(2386666): 不允许的操作
databend-meta: 未找到进程
Start databend-meta...
Waiting on databend-meta 10 seconds...
nohup: 把输出追加到 'nohup.out'
not connected to :9191
OK :9191 is listening
Start databend-query...
Waiting on databend-query 10 seconds...
nohup: 把输出追加到 'nohup.out'
not connected to :3307
OK :3307 is listening
+++ dirname scripts/ci/ci-run-stateless-tests-management-mode.sh
++ cd scripts/ci
++ pwd
+ SCRIPT_PATH=/home/taichong/database/source-code/datafuse/scripts/ci
+ cd /home/taichong/database/source-code/datafuse/scripts/ci/../../tests
+ echo 'Starting databend-test for management mode'
Starting databend-test for management mode
+ ./databend-test --mode standalone --run-dir 2_management_mode

Running 5 management_mode tests.

00_0001_management_mode_database:                                       [ OK ]
00_0002_management_mode_table:                                          [ OK ]
00_0003_management_mode_user:                                           [ OK ]
00_0004_management_mode_function:                                       [ OK ]
00_0005_management_mode_stage:                                          [ OK ]

5 tests passed. 0 tests skipped.

```

**Comment by BohuTANG** [comment]
`00_0005_management_mode_stage.sql` should be deleted, stage command have reverted.

**Comment by BohuTANG** [comment]
@mergify update

**Pull request merged**
