### PR TITLE
refactor(storages): move fuse&hive to single folder

### PR DESCRIPTION
**Pull request by BohuTANG**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

* `fuse`&`fuse-meta` to `fuse/`
* `hive`&`hive-meta-store` to `hive/`

Fixes #issue

### CODE REVIEW

**Comment by BohuTANG** [comment]
@sandflee @dantengsky @zhyass 
This PR adjusts the directory structure to make it more organized, please comments let me know if this PR breaks your WIP PR.

**Review by dantengsky — APPROVED** [review]
LGTM

**Review by Xuanwo — APPROVED** [review]

**Review by sandflee — APPROVED** [review]

**Comment by sandflee** [comment]
BTW,  hive use some components from fuse, like `range filter` and 'cache' etc. maybe sometimes we could do another refactor to seperate the common components from fuse.

**Comment by BohuTANG** [comment]
@sandflee 

`cache` and `index` are the single crates under the `storages`.
image

I think you are mean `common-storages-fuse-meta = { path = "../../fuse/fuse-meta" }`, which is used by hive/cargo.toml

**Comment by sandflee** [comment]
> cache and index are the single crates under the storages.
have not noticed there are moved from fuse :)

**Pull request merged**
