### PR TITLE
feat: add endpoint /v1/session/logout and record client session ID in meta.

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

1.  support temp table: https://github.com/datafuselabs/databend/pull/16250
    1. set client session id to Session so temp table use it as dbname
    1. meta add `/<tenant>/<client_session_id> -> {user_name:String}` to marking a session is alive, and objects like 
tmptable that lives in the session should not be recycled.
    1. rename global TokenManager to ClientSessionManager
3.  add `/v1/session/logout` so token and session_id  can be remove faster from both mem and meta.
4.  http query polling and final check session_id, otherwise any one knowing the query id and authed can op on and  inspect the result that should be private to the session. 

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16281)

### CODE REVIEW

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16281)* status: all files reviewed, 1 unresolved discussion (waiting on @youngsofun)

___
*[`src/query/management/src/client_session.rs` line 115 at r1](https://reviewable.io/reviews/datafuselabs/databend/16281#-O4firEy6_9iVcp55tfW:-O4firEy6_9iVcp55tfX:b3thxmg) ([raw file](https://github.com/datafuselabs/databend/blob/e528908ebf26b86eeacd7b2f50cb088e83adbf2a/src/query/management/src/client_session.rs#L115)):*
> ```XML
>         let upsert = UpsertPB::update(ident, value)
>             .with(seq)
>             .with_ttl(Duration::from_secs(ttl.as_secs()));
> ```

ttl is already a Duration



_Suggestion:_
```XML
            .with_ttl(ttl);
```

**Review by youngsofun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16281)* status: 26 of 28 files reviewed, 1 unresolved discussion (waiting on @drmingdrmer)

___
*[`src/query/management/src/client_session.rs` line 115 at r1](https://reviewable.io/reviews/datafuselabs/databend/16281#-O4firEy6_9iVcp55tfW:-O4h1U8_EaByJmNT0fV0:b-896fix) ([raw file](https://github.com/datafuselabs/databend/blob/e528908ebf26b86eeacd7b2f50cb088e83adbf2a/src/query/management/src/client_session.rs#L115)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

ttl is already a Duration
</blockquote></details>

Done.

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16281)* status: all files reviewed, 1 unresolved discussion (waiting on @dantengsky, @flaneur2020, and @SkyFan2002)

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16281)* status: all files reviewed, 1 unresolved discussion (waiting on @dantengsky, @flaneur2020, @SkyFan2002, and @sundy-li)

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16281)* status: all files reviewed, 1 unresolved discussion (waiting on @dantengsky, @flaneur2020, @SkyFan2002, and @sundy-li)

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16281)* status: all files reviewed, 1 unresolved discussion (waiting on @dantengsky, @flaneur2020, @SkyFan2002, and @sundy-li)

**Review by SkyFan2002 — APPROVED** [review]

**Pull request merged**
