### PR TITLE
fix: fix share db bug, create DatabaseIdToName if need

### PR DESCRIPTION
**Pull request by lichuang**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

fix: Some database has been created before share, so they has no `DatabaseIdToName` for share, create DatabaseIdToName if need.

Closes #issue

### CODE REVIEW

**Comment by BohuTANG** [comment]
Can we add some tests(ut or stateless test) for this PR?

**Comment by lichuang** [comment]
> Can we add some tests(ut or stateless test) for this PR?

Because the case is occur if the shared database is created before share feature implement,  these database leak `DatabaseIdToName` info. After share feature implement, every time create a new database, it will create `DatabaseIdToName ` info.

So it cannot build a test case that create a database leak `DatabaseIdToName`.

**Comment by BohuTANG** [comment]
> > Can we add some tests(ut or stateless test) for this PR?
> 
> Because the case is occur if the shared database is created before share feature implement, these database leak `DatabaseIdToName` info. After share feature implement, every time create a new database, it will create `DatabaseIdToName ` info.
> 
> So it cannot build a test case that create a database leak `DatabaseIdToName`.

How about some stateless tests? 
Likely we don't have any stateless test for share?

**Comment by lichuang** [comment]
> How about some stateless tests? Likely we don't have any stateless test for share?

https://github.com/datafuselabs/databend/blob/main/tests/logictest/suites/base/06_show/06_0009_show_shares

**Comment by BohuTANG** [comment]
I found this stateless test but it only a show function test, can we add a full share function test for it? For example:
1, create a share from A for B
2, B can read from A'share
3, B can not write the A'share
4, A drop the share what's the B will happen?

**Review by drmingdrmer — APPROVED** [review]

**Pull request merged**
