### PR TITLE
STORAGE-3098:  Catalog refactor

### LINKED ISSUE #3098: Consider refactory catalog trait
**Summary**

catalog trait is not clear, for example in `catalog` trait it has a `build_table` to return a `dyn Table` by table info and used by many places:
```
fn build_table(&self, table_info: &TableInfo) -> Result<Arc<dyn Table>>;
```

In database trait, it has `get_table` to return `dyn Table` by db_name and table_name and used by many places other:
```
async fn get_table(&self, db_name: &str, table_name: &str) -> Result<Arc<dyn Table>>;
```

Goal:
1. Provide a unitfied trait api
2. User can easily implement their own datasource under the api

### PR DESCRIPTION
**Pull request by BohuTANG**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

**This patch cannot be split into many small PRs, it is easy to cause conflicts:<**
Summary about this PR:
1. Rename `datasources` to `storages` 
2. Put all db/table schema operation to catalog trait

In `storages` dir, the table engine defines:
How and where data is stored, where to write it and where read from.
```
storages
├── csv
├── memory
├── null
├── parquet
├── github
├── system
└── fuse
```

TODO(in another PR):
1. Add database init operation to database trait for github engine @Veeupup 

## Changelog

- Improvement

## Related Issues

Fixes #3098 

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by drmingdrmer** [comment]
Wow~

**Comment by drmingdrmer** [comment]
/lgtm

Much more clear and obvious~

**Comment by Veeupup** [comment]
/LGTM
learn a lot from it ...

**Pull request merged**
