### PR TITLE
fix(cluster): try fix cluster hang in bench

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

fix(cluster): try fix cluster hang in bench

- Closes #issue

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12856)

### CODE REVIEW

**Review by dantengsky — APPROVED** [review]

**Comment by BohuTANG** [comment]
image

tpch benchmark many query failed.

**Comment by drmingdrmer** [comment]
> ```
> APIError: ResponseError with 500: {"error":{"code":"500","message":"ConnectionError: address: meta-service-2.meta-service.databend-system.svc.cluster.local:28003 source: tonic::transport::error::Error: transport error source: error trying to connect: tcp connect error: Connection refused (os error 111) source: tcp connect error: Connection refused (os error 111) source: Connection refused (os error 111)"}}
> ```
> 
> cc: @drmingdrmer

Just ignore it

**Comment by BohuTANG** [comment]
From the benchmark, there's a noticeable performance improvement:
image

Was this enhancement made by this PR?

**Comment by zhang2014** [comment]
> Was this enhancement made by this PR?

not sure. this may eliminate the time of executor hang. Let's merge main and rerun it.

**Comment by BohuTANG** [comment]
The recent benchmark results highlight a performance regression on XLARGE with hits dataset:
CleanShot 2023-10-14 at 10 47 58@2x

**Comment by BohuTANG** [comment]
Looks good now.

**Pull request merged**
