### PR TITLE
chore: improve logic test

### PR DESCRIPTION
**Pull request by ZeaLoVe**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

1. Silence logic test logs, change statements log level to debug, issue #6596 
2. Add ydb logic test cases, part of issue #5889

Fixes #issue

### CODE REVIEW

**Comment by ZeaLoVe** [comment]
cc @leiysky  many select test cases with planner_v2, please take a look.

**Comment by Xuanwo** [comment]
@ZeaLoVe Hi, `chore` intends to be small changes, I think this PR should not be `chore`...


Please consider changing this PR's type to `ci`.

**Comment by Xuanwo** [comment]
BTW, it could be better to split the improve into two PRs:

- One for improvement.
- One for adding new test suites.

**Comment by ZeaLoVe** [comment]
> BTW, it could be better to split the improvement into two PRs:
> 
> * One for improvement.
> * One for adding new test suites.
> 
> Especially for our logic test will fail after adding new test suites. We need more time to address the new suite.

ok, I wil close this and split to two pr

**Pull request closed without merging**
