### PR TITLE
feat(query): add call stats functions

### PR DESCRIPTION
**Pull request by everpcpc**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

## Changelog

- New Feature

## Related Issues

Fixes #issue

### CODE REVIEW

**Comment by BohuTANG** [comment]
Oops, `.github/actions/check/action.yml` Conflicting

**Comment by everpcpc** [comment]
ask @drmingdrmer for advice, if there are any needs to limit request to meta?

**Comment by drmingdrmer** [comment]
> ask @drmingdrmer for advice, are there any needs to limit request to meta?

Yes, if it's possible. The estimated max throughput is about 30,000 writes per second for now.

**Comment by everpcpc** [comment]
> Yes, if it's possible. The estimated max throughput is about 30,000 writes per second for now.

The stats call is just read, no write at all. Would that make any difference?

**Comment by drmingdrmer** [comment]
> > Yes, if it's possible. The estimated max throughput is about 30,000 writes per second for now.
> 
> The stats call is just read, no write at all. Would that make any difference?

A read does not need to replicate a raft-log or to persist anything on a disk. It would be cheaper.

If the total RPS is under 5,000 there should not be a concern.

**Comment by everpcpc** [comment]
> > > Yes, if it's possible. The estimated max throughput is about 30,000 writes per second for now.
> > 
> > 
> > The stats call is just read, no write at all. Would that make any difference?
> 
> A read does not need to replicate a raft-log or to persist anything on a disk. It would be cheaper.
> 
> If the total RPS is under 5,000 there should not be a concern.

thx~
currently the `list_tables` operation would result in a RPS of total table count, but we only need the table count, would a `list_id_value` or `list_keys` call different from common read calls?
Moreover, would it be ok for meta to provide some api for stats with grouping prefix (such as tenant id) ?

**Comment by drmingdrmer** [comment]
> Would a `list_id_value` or `list_keys` call different from common read calls? 

`list_id_value` can be implemented with a `prefix-list` RPC to metasrv.
`list_keys` can not be expressed with KVApi yet.

> Moreover, would it be ok for meta to provide some api for stats grouped by prefix (such as tenant id) ?

metasrv does not know what the delimiter is for an application, although traditionally it is a slash `/`.
And maintaining the counts of every prefix will result in unnecessary write-amplification.

Thus IMHO, `count by the prefix` should be implemented on the application side:

When creating/dropping/undropping/renaming a table, also update a counter record.

**Pull request merged**
