### PR TITLE
feat: Google Cloud Storage as storage backend for databend

### LINKED ISSUE #7023: Feature: Add Google Cloud Storage backend support for databend
**Summary**

Currently, Databend does not support the Google Cloud Storage service

### PR DESCRIPTION
**Pull request by ClSlaid**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

1. add GCS backend in common_storage
2. add environment variable support for GCS
3. some integrated tests for GCS

Related #7023 

Related #7151 

This PR does not introduce stage support for GCS.

### Demonstrations

- Running DataBend-Query on GCS:
DataBend Query showing
- Query with MySQL (MyCLI is a MySQL client with syntax highlighting):
Query with mycli
- Yes it's really on GCS, my proxy tells me :)
proxy image

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]
Bravo!

**Comment by BohuTANG** [comment]
Cool.
Then we can copy files from GCS?

**Comment by ClSlaid** [comment]
> Cool. Then we can copy files from GCS?

This should work in theory, I'll give it a try.

**Comment by Xuanwo** [comment]
> Then we can copy files from GCS?

This will be implemented in the following PRs.

**Comment by BohuTANG** [comment]
It would be great to add a `Google Cloud Storage` tab to the deploy in the documentation:
https://databend.rs/doc/deploy/deploying-databend

**Review by BohuTANG — APPROVED** [review]

**Comment by BohuTANG** [comment]
> It would be great to add a `Google Cloud Storage` tab to the deploy in the documentation: https://databend.rs/doc/deploy/deploying-databend

cc @soyeric128

**Comment by ClSlaid** [comment]
> > It would be great to add a `Google Cloud Storage` tab to the deploy in the documentation: https://databend.rs/doc/deploy/deploying-databend
> 
> cc @soyeric128

working on it.

**Pull request merged**
