### PR TITLE
add method get_databases to meta_api

### PR DESCRIPTION
**Pull request by dantengsky**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary
`meta_api`:

- new method `get_databases`
- new method `get_tables`
- rm method `get_database_meta`

## Changelog

- Improvement

## Related Issues

None

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
Oops, there are some conflicts with https://github.com/datafuselabs/databend/pull/2020

**Comment by dantengsky** [comment]
> Oops, there are some conflicts with #2020

that is ok，let me rebase it

**Comment by BohuTANG** [comment]
> > Oops, there are some conflicts with #2020
> 
> that is ok，let me rebase it

I rebase it from github cli.
I am not sure why it merged so quickly :thinking:

**Comment by dantengsky** [comment]
already merged？

**Comment by BohuTANG** [comment]
> already merged？

Reverted due to some errors, this patch need push again.
The bot merged before check it.

**Comment by dantengsky** [comment]
> > already merged？
> 
> Reverted due to some errors, this patch need push again. The bot merged before check it.

OK

**Comment by dantengsky** [comment]
> > already merged？
> 
> Reverted due to some errors, this patch need push again. The bot merged before check it.

pls ping me when master branch is ready

**Comment by BohuTANG** [comment]
> > > already merged？
> > 
> > 
> > Reverted due to some errors, this patch need push again. The bot merged before check it.
> 
> pls ping me when master branch is ready

The master reverted, it's ready now:)

**Comment by dantengsky** [comment]
nice

**Pull request merged**
