### PR TITLE
[meta/schema-api]: rename-table need to check table exist before returning OK

### PR DESCRIPTION
**Pull request by drmingdrmer**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Related Issues

### CODE REVIEW

**Comment by drmingdrmer** [comment]
Thanks to @TCeason for reminding me about this bug:DDD

**Comment by TCeason** [comment]
LGTM. By the way maybe we can delete the “if exists” token.

**Comment by drmingdrmer** [comment]
> LGTM. By the way maybe we can delete the “if exists” token.

delete it from where? 🤔

**Comment by TCeason** [comment]
> > LGTM. By the way maybe we can delete the “if exists” token.
> 
> delete it from where? 🤔

Like MySQL or Oracle rename table not support if exists.

**Comment by drmingdrmer** [comment]
> > > LGTM. By the way maybe we can delete the “if exists” token.
> > 
> > 
> > delete it from where? 🤔
> 
> Like MySQL or Oracle rename table not support if exists.

I do not know, forward this question to @BohuTANG  :DD

**Comment by BohuTANG** [comment]
I think it's Ok here. Let's merge!

**Pull request merged**
