### PR TITLE
feat(FlightSQL): should not use session ID as token

### LINKED ISSUE #11583: Feature(FlightSQL): should not use session ID as token.
not safe since other user can see it when `show processlist `

### PR DESCRIPTION
**Pull request by jun0315**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Encrypt session id with salt

Closes #11583

### CODE REVIEW

**Comment by sundy-li** [comment]
We need to consider the decoder.

session_id + salt  ---------- encode ------>  token; 

We save `token` as the key of ` pub sessions: Mutex<ExpiringMap<String, Arc<Session>>>,`

token  ---------- decode ------>   session_id

**Comment by jun0315** [comment]
Perhaps we can get the session-id through the session.

**Comment by youngsofun** [comment]
> Perhaps we can get the session-id through the session.

so token do not need to be related to session？just another uuid is enough？

**Comment by sundy-li** [comment]
I guess `uuid` is enough, no need any encoder.

**Comment by jun0315** [comment]
Ok, I will use `UUID`.

**Review by sundy-li — APPROVED** [review]

**Pull request merged**
