### PR TITLE
refactor(query): Migrate more new planners to be enabled

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Maked `UndropDatabase`, `Kill`, `UseDatabase` to be enabled in the new planners.

Related #6644

### CODE REVIEW

**Comment by sundy-li** [comment]
After this Pr.

We only left four Statements running on old planner.

```
  DfStatement::Query(_)
                | DfStatement::Explain(_)
                | DfStatement::InsertQuery(_)
                | DfStatement::Delete(_)
```

**Review by Xuanwo — APPROVED** [review]

**Review by BohuTANG — APPROVED** [review]
:+1:

**Comment by BohuTANG** [comment]
Dev MacOS / test_sqllogic_standalone_macos(optional)  always failed, please take a look @ZeaLoVe

**Review by PsiACE — APPROVED** [review]

**Comment by ZeaLoVe** [comment]
> Dev MacOS / test_sqllogic_standalone_macos(optional) always failed, please take a look @ZeaLoVe

flaky error, issue here https://github.com/datafuselabs/databend/issues/6614

**Pull request merged**
