### PR TITLE
feat(ee): Add OSS Server Side Encryption Support 

### PR DESCRIPTION
**Pull request by Xuanwo**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

This PR is based on https://github.com/datafuselabs/databend/pull/13343

Without sse (start succeed):

```shell
:( RUST_LOG=debug STORAGE_TYPE=oss STORAGE_OSS_BUCKET=test STORAGE_OSS_ENDPOINT_URL=https://oss-ap-northeast-1.aliyuncs.com STORAGE_OSS_ACCESS_KEY_ID=ak STORAGE_OSS_ACCESS_KEY_SECRET=sk ./scripts/ci/deploy/databend-query-standalone.sh
Start databend-query...
Databend Query

Version: v1.2.164-nightly-3b2d86c870(rust-1.72.0-nightly-2023-10-19T14:43:12.566094356Z)
```

With SSE but no valid key:

```shell
:( RUST_LOG=debug STORAGE_TYPE=oss STORAGE_OSS_SERVER_SIDE_ENCRYPTION=AES256 STORAGE_OSS_BUCKET=test STORAGE_OSS_ENDPOINT_URL=https://oss-ap-northeast-1.aliyuncs.com STORAGE_OSS_ACCESS_KEY_ID=ak STORAGE_OSS_ACCESS_KEY_SECRET=sk ./scripts/ci/deploy/databend-query-standalone.sh
Start databend-query...
Databend Query start failure, cause: LicenseKeyInvalid. Code: 1402, Text = use of storage_encryption requires an enterprise license. license key is not found for test_tenant.

<Backtrace disabled by default. Please use RUST_BACKTRACE=1 to enable> 

```

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13349)

### CODE REVIEW

**Comment by Xuanwo** [comment]
I assumed adding `server_side_encryption` to OSS would be compatible, but the test failed.

```shell
running 1 test
test user_stage::test_user_stage_oss_v13 ... FAILED

failures:

failures:
    user_stage::test_user_stage_oss_v13

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 92 filtered out; finished in 0.00s


--- STDERR:              common-proto-conv::it user_stage::test_user_stage_oss_v13 ---
thread 'user_stage::test_user_stage_oss_v13' panicked at 'assertion failed: `(left == right)`: loading test_user_stage_oss_v13 with version 61 program

Diff < left / right > :
 StageInfo {
     stage_name: "oss://my_bucket/data/files",
     stage_type: External,
     stage_params: StageParams {
         storage: Oss(
             StorageOssConfig {
                 endpoint_url: "https://oss-cn-litang.example.com/",
                 presign_endpoint_url: "",
                 bucket: "my_bucket",
                 root: "/data/files",
                 access_key_id: "******_id",
                 access_key_secret: "******ret",
                 ..
             },
         ),
     },
     file_format_params: Json(
         JsonFileFormatParams {
             compression: Bz2,
         },
     ),
     copy_options: CopyOptions {
         on_error: SkipFileNum(
             666,
         ),
         size_limit: 1038,
         max_files: 0,
         split_size: 0,
         purge: true,
         single: false,
         max_file_size: 0,
         disable_variant_check: false,
         return_failed_only: false,
     },
     comment: "test",
     number_of_files: 0,
     creator: None,
 }

', src/meta/proto-conv/tests/it/common.rs:71:5
```

@drmingdrmer, could you please check what happened?

**Comment by drmingdrmer** [comment]
@Xuanwo 
It looks like the color was lost when pasting stdout to the comment textarea. I can not see what's the diff is 🤔

**Comment by Xuanwo** [comment]
> It looks like the color was lost when pasting stdout to the comment textarea. I can not see what's the diff is 🤔

image

I can't see changes even with colorful output

**Comment by Xuanwo** [comment]
Ok, I got it. The `Debug` for struct matters.

**Comment by Xuanwo** [comment]
Our proto conv test is great! The root cause is we used to assign number 6 & 7 in old version. We can't use them anymore.

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 22 of 63 files at r1, 1 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13349)* status: 26 of 64 files reviewed, 1 unresolved discussion (waiting on @Xuanwo and @ZhiHanZ)

___
*[`src/meta/protos/proto/config.proto` line 80 at r4](https://reviewable.io/reviews/datafuselabs/databend/13349#-NhA3Ce6C2Ad1CWxM7G0:-NhA3Ce6C2Ad1CWxM7G1:beoi0b6) ([raw file](https://github.com/datafuselabs/databend/blob/f51f0b2977d01c13b4a994d65fd662949d0cf047/src/meta/protos/proto/config.proto#L80)):*
> ```proto
>   // So we should start from 8 now.
>   string server_side_encryption = 8;
>   string server_side_encryption_key_id = 9;
> ```

Oh I see these field are removed in this PR: https://github.com/datafuselabs/databend/pull/8135/files#diff-2f2a00a6d3c7fda557c512eb57a7f72b191a8bbed6f4c69eaa38e95fab0c5ef0

To provide compatibility, field index must be reserved after removing them:
https://protobuf.dev/programming-guides/proto3/#fieldreserved

**Comment by Xuanwo** [comment]
> To provide compatibility, field index must be reserved after removing them:
> https://protobuf.dev/programming-guides/proto3/#fieldreserved

Got it, I will add them back for compatibility

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 6 of 63 files at r1, 3 of 4 files at r2, 37 of 37 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13349)* status: all files reviewed, 1 unresolved discussion (waiting on @Xuanwo and @ZhiHanZ)

**Review by drmingdrmer — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13349)* status: 63 of 64 files reviewed, 2 unresolved discussions (waiting on @Xuanwo and @ZhiHanZ)

___
*[`src/meta/protos/proto/config.proto` line 80 at r6](https://reviewable.io/reviews/datafuselabs/databend/13349#-NhB6Prw3M0tjhVUDGCQ:-NhB6Prw3M0tjhVUDGCR:b-ra9esb) ([raw file](https://github.com/datafuselabs/databend/blob/2d6145d5be54fdbefa22be793c9bef5f0e1e0c33/src/meta/protos/proto/config.proto#L80)):*
> ```proto
>   //  We used to have role_arn (6) and oidc_token (7) but removed later, keep those index reserved.
>   //  string role_arn = 6;
>   //  string oidc_token = 7;
> ```

Use keyword `reserve` to reserve a field index:



_Suggestion:_
```proto
  //  string role_arn = 6;
  //  string oidc_token = 7;
  reserved 6, 7;
```

**Comment by Xuanwo** [comment]
> Use keyword `reserve` to reserve a field index:

Oh, I learnt something now today!

**Review by ZhiHanZ — APPROVED** [review]
LGTM, please add a document on enterprise feature page

**Comment by Xuanwo** [comment]
cc @drmingdrmer, `reserved` has been added, PTAL.

**Comment by Xuanwo** [comment]
Hi, @soyeric128, this PR adds two new config for OSS:

- `server_side_encryption`: Activate server-side encryption for OSS. Possible values are `AES256` and `KMS`. `AES256` refers to the use of an OSS-managed AES256 key for data encryption, while `KMS` uses the key specified in `server_side_encryption_key_id` for data encryption. 
- `server_side_encryption_key_id`: This is the server-side encryption key id for OSS, which only applies when `server_side_encryption` is set to "KMS".
 
Both configurations require a valid license that enables the `storage-encryption` feature.

Would you like to help add the docs?

**Pull request merged**
