### PR TITLE
[CI] migrate to dev container and self hosted CI

### PR DESCRIPTION
**Pull request by ZhiHanZ**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Use dev container for CI and migrate to new self hosted container 

## Changelog

- Build/Testing/CI

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
How about to use buildkite agent later?

**Comment by ZhiHanZ** [comment]
> How about to use buildkite agent later?

the true challenge is to allocate and monitor suffient  resource for CI which is indispensable for both buildkite and github self hosted action runner, here I am fine tuning on that..

**Comment by Xuanwo** [comment]
I'm thinking about running all tests and building inside containers on Github-hosted runners.

So we can avoid the Github env's effect and unify the same build env for both `x86-64` and `aarch`. There is no need for `cross` anymore which will also make our CI much simpler.

Another benefit is a developer can reproduce the same env inside CI.

**Comment by Xuanwo** [comment]
Also, ping @PsiACE for advice. Is there anything we must be done by Github Actions?

**Comment by PsiACE** [comment]
> Also, ping @PsiACE for advice. Is there anything we must be done by Github Actions?

I think it's great, it looks like we can clean up some of the complexity. The only question is, if we use containers, roughly how much time will it take to finish the build/will there be more OOM.

**Comment by Xuanwo** [comment]
Closed for https://github.com/datafuselabs/databend/pull/4630 get merged. Feel free to reopen if there are other things to address.

**Pull request closed without merging**
