### PR TITLE
feat(storages): `read_parquet` uses OpenDAL for all IO operations.

### PR DESCRIPTION
**Pull request by RinChanNOWWW**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

- replace `std::File` with `opendal` for all IO operations. (TODO(Another PR): use `opendal` to do "glob").
- optimize prewhere logic. (do `resort` before filter).
- fix scan progress collection.
- TODO(Another PR): support remote location and async operations.

Closes #issue

### CODE REVIEW

**Comment by Xuanwo** [comment]
only fs and hdfs implemented blocking api. Will we need to test s3 via blocking api too?

**Comment by RinChanNOWWW** [comment]
> only fs and hdfs implemented blocking api. Will we need to test s3 via blocking api too?

I plan to check if the backend supports blocking api and choose which api to use.

But I don't have figured out how to achieve this yet
(reading file meta data is only in sync functions now, maybe we need to use blocking api for these operations?) .

**Comment by RinChanNOWWW** [comment]
Have no complete idea about the remote location. Let's implement it later.

**Comment by BohuTANG** [comment]
> > only fs and hdfs implemented blocking api. Will we need to test s3 via blocking api too?
> 
> I plan to check if the backend supports blocking api and choose which api to use.
> 
> But I don't have figured out how to achieve this yet (reading file meta data is only in sync functions now, maybe we need to use blocking api for these operations?) .

Like this?
https://github.com/datafuselabs/databend/blob/923f3fab8491411a81222917c17a55675f3aa860/src/query/storages/fuse/src/fuse_table.rs#L180

**Comment by RinChanNOWWW** [comment]
Yes. Or we block the file meta data reading?

**Comment by Xuanwo** [comment]
> Let's implement it later.

LGTM, we can discussion the remote file support later.

**Review by Xuanwo — APPROVED** [review]

**Review by sundy-li — APPROVED** [review]

**Pull request merged**
