### PR TITLE
feat(processor): support max execute time settings

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

feat(processor): support max execute time settings

Parts of #6935

### CODE REVIEW

**Comment by zhang2014** [comment]
Cannot be limit sync processor, for example:
```
SELECT SLEEP(2);
```

**Comment by BohuTANG** [comment]
Need a stateless test to check it

**Comment by sundy-li** [comment]
I do think the `show settings` tests should be removed.

**Review by BohuTANG — APPROVED** [review]

**Comment by BohuTANG** [comment]
@soyeric128 for new settings documentation, thanks.

**Pull request merged**
