### PR TITLE
bug: fix interval_function flaky test

### LINKED ISSUE #5093: Flaky test: test_add_subtract_seconds
On my m1 mac laptop: c07e882756c1ea90955594d239e1c354545de521

It fails with:
```
RUST_TEST_THREADS=1 cargo test -p common-functions --test it
```

But it will pass with:
```
RUST_TEST_THREADS=1 cargo test -p common-functions --test it test_add_subtract_seconds
```

```
failures:

---- scalars::dates::interval_function::test_add_subtract_seconds stdout ----
Error: Code: 1069, displayText = Timestamp only ranges from 1000-01-01 00:00:00.000000 to 9999-12-31 23:59:59.999999.

   0: backtrace::backtrace::libunwind::trace
             at /Users/drdrxp/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/backtrace-0.3.64/src/backtrace/libunwind.rs:93:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/drdrxp/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/backtrace-0.3.64/src/backtrace/mod.rs:66:5
      backtrace::backtrace::trace
             at /Users/drdrxp/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/backtrace-0.3.64/src/backtrace/mod.rs:53:14
   1: backtrace::capture::Backtrace::create
             at /Users/drdrxp/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/backtrace-0.3.64/src/capture.rs:176:9
      backtrace::capture::Backtrace::new
             at /Users/drdrxp/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/backtrace-0.3.64/src/capture.rs:140:22
   2: common_exception::exception_code::<impl common_exception::exception::ErrorCode>::InvalidTimestamp::{{closure}}
             at /Users/drdrxp/xp/vcs/github.com/drmingdrmer/fuse-query/common/exception/src/exception_code.rs:37:109
   3: core::bool::<impl bool>::then
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/bool.rs:47:24
   4: common_exception::exception_code::<impl common_exception::exception::ErrorCode>::InvalidTimestamp
             at /Users/drdrxp/xp/vcs/github.com/drmingdrmer/fuse-query/common/exception/src/exception_code.rs:37:30
   5: common_datavalues::types::type_timestamp::check_timestamp
             at /Users/drdrxp/xp/vcs/github.com/drmingdrmer/fuse-query/common/datavalues/src/types/type_timestamp.rs:43:9
   6: <common_functions::scalars::dates::interval_function::IntervalFunction<L,R,O,F> as common_functions::scalars::function::Function>::eval
             at src/scalars/dates/interval_function.rs:166:25
   7: it::scalars::dates::interval_function::test_add_subtract_seconds
             at tests/it/scalars/dates/interval_function.rs:210:23
   8: it::scalars::dates::interval_function::test_add_subtract_seconds::{{closure}}
             at tests/it/scalars/dates/interval_function.rs:148:1
   9: core::ops::function::FnOnce::call_once
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/ops/function.rs:227:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/ops/function.rs:227:5
      test::__rust_begin_short_backtrace
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/test/src/lib.rs:574:5
  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/alloc/src/boxed.rs:1861:9
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panic.rs:137:14
      test::run_test_in_process
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/test/src/lib.rs:597:18
      test::run_test::run_test_inner::{{closure}}
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/test/src/lib.rs:491:39
  12: test::run_test::run_test_inner
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/test/src/lib.rs:529:13
  13: test::run_test
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/test/src/lib.rs:561:28
  14: test::run_tests
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/test/src/lib.rs:304:17
  15: test::console::run_tests_console
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/test/src/console.rs:301:5
  16: test::test_main
```

### PR DESCRIPTION
**Pull request by Veeupup**
Signed-off-by: Veeupup <code@tanweime.com>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

 flaky test

## Changelog

- Bug Fix
- Not for changelog (changelog entry is not required)

## Related Issues

Fixes #5093

### CODE REVIEW

**Review by sundy-li — APPROVED** [review]

**Comment by drmingdrmer** [comment]
Looks good to me, but why does it only pass when running a single test?

**Comment by drmingdrmer** [comment]
> @drmingdrmer because some undefined and unsafe cast happened when doing `static_cast` ... https://github.com/Veeupup/databend/blob/2a6aca31c11220fad859d041b7fe59d623617c46/common/datavalues/src/columns/series.rs#L38-L41

But... still.. why a single test case won't be affected by this?

**Comment by sundy-li** [comment]
> But... still.. why a single test case won't be affected by this?

`static_cast` will unsafe cast the pointer, maybe single test has different address which avoid this the problem. This unsafe will be fixed after #4868  we use `ColumnImpl` to replace `ColumnRef`.

**Comment by drmingdrmer** [comment]
> > But... still.. why a single test case won't be affected by this?
> 
> `static_cast` will unsafe cast the pointer, maybe single test has different address which avoid this problem. This unsafe will be fixed after #4868 we use `ColumnImpl` to replace `ColumnRef`.

Hmm... Interesting...

Thanks for the explanation!

**Pull request merged**
