### PR TITLE
ci: Move config files into .github instead

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

This PR will move configs into `.github` instead so that we have a much cleaner root directory.

## Changelog

- Build/Testing/CI

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
So like the idea to make the root directory clean, is there any github documents on this?

**Comment by Xuanwo** [comment]
> So like the idea to make the root directory clean, is there any github documents on this?

Most products support configs under `.github`, it's most like a common behavior instead of github's rule.

- mergify: https://docs.mergify.com/configuration/
- skywalking-eyes: https://github.com/apache/skywalking-eyes
- Codecov: https://docs.codecov.com/docs/codecov-yaml#can-i-name-the-file-codecovyml

**Comment by Xuanwo** [comment]
The branch was closed by wrong, reopened now.

**Comment by BohuTANG** [comment]
/lgtm

Nice shot :100:

**Pull request merged**
