### PR TITLE
feat: add owner field into show full tables

### LINKED ISSUE #14152: fix: owner field in the SHOW FULL TABLES statement
```
        for tbl in &database_tables {
            owner.push(
                tbl.get_table_info()
                    .meta
                    .owner
                    .as_ref()
                    .map(|v| v.owner_role_name.as_bytes().to_vec()),
            );
```

should be replaced with the ownership kv from meta

### PR DESCRIPTION
**Pull request by guojidan**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

_Briefly describe what this PR aims to solve. Include background context that will help reviewers understand the purpose of the PR._

Fixes #14152

## Tests

- [x] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14219)

### CODE REVIEW

**Comment by guojidan** [comment]
`SHOW FULL TABLES` contain `create_time` field, I do not know how to code `sqllogic-test`  😕

**Comment by Dousir9** [comment]
> `SHOW FULL TABLES` contain `create_time` field, I do not know how to code `sqllogic-test` 😕

A simple example: `tests/sqllogictests/suites/query/select.test`

**Comment by TCeason** [comment]
> ests/sqllogictests/suites/query/select.test

Try to modify this:

```
diff --git a/tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.sql b/tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.sql
index 1e49ac39cd..c0183b8a57 100644
--- a/tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.sql
+++ b/tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.sql
@@ -3,8 +3,11 @@ CREATE DATABASE db12_0002;
 USE db12_0002;
 
 CREATE TABLE t(c1 int);
+show full tables from db12_0002;
+
 DROP TABLE t;
 
 show tables history like 't';
 
 DROP database db12_0002;
+

```

then run this command on your local:

```shell
$ pwd
datafuse/tests
$ ./databend-test 12_0002_time_travel_show_tables_hist.sql
```

**Comment by TCeason** [comment]
> > SHOW FULL TABLES contain create_time field, I do not know how to code sqllogic-test 😕
> 
> Try to modify this:
> 
> ```
> diff --git a/tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.sql b/tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.sql
> index 1e49ac39cd..c0183b8a57 100644
> --- a/tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.sql
> +++ b/tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.sql
> @@ -3,8 +3,11 @@ CREATE DATABASE db12_0002;
>  USE db12_0002;
>  
>  CREATE TABLE t(c1 int);
> +show full tables from db12_0002;
> +
>  DROP TABLE t;
>  
>  show tables history like 't';
>  
>  DROP database db12_0002;
> +
> ```
> 
> then run this command on your local:
> 
> ```shell
> $ pwd
> datafuse/tests
> $ ./databend-test 12_0002_time_travel_show_tables_hist.sql
> ```

In my laptop, the result is:

+t	BASE TABLE	db12_0002	default	FUSE		yyyy-mm-dd HH:MM:SS.ssssss	0	0	0	0


So in your local, it should add owner fileds result.

**Comment by TCeason** [comment]
Now let's wait the ci passed. https://github.com/datafuselabs/databend/pull/14219/commits/88aea35159e911ab5b191ae181d61aa1a877a783

**Review by TCeason — APPROVED** [review]

**Comment by guojidan** [comment]
> > > SHOW FULL TABLES contain create_time field, I do not know how to code sqllogic-test 😕
> > 
> > 
> > Try to modify this:
> > ```
> > diff --git a/tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.sql b/tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.sql
> > index 1e49ac39cd..c0183b8a57 100644
> > --- a/tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.sql
> > +++ b/tests/suites/0_stateless/12_time_travel/12_0002_time_travel_show_tables_hist.sql
> > @@ -3,8 +3,11 @@ CREATE DATABASE db12_0002;
> >  USE db12_0002;
> >  
> >  CREATE TABLE t(c1 int);
> > +show full tables from db12_0002;
> > +
> >  DROP TABLE t;
> >  
> >  show tables history like 't';
> >  
> >  DROP database db12_0002;
> > +
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then run this command on your local:
> > ```shell
> > $ pwd
> > datafuse/tests
> > $ ./databend-test 12_0002_time_travel_show_tables_hist.sql
> > ```
> 
> On my laptop, the result is:
> 
> +t BASE TABLE db12_0002 default FUSE yyyy-mm-dd HH:MM:SS.ssssss 0 0 0 0
> 
> So in your local, it should add owner fileds result.

Wow, I got it

**Pull request merged**
