### PR TITLE
Use peotry to manage all python packages

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

This PR adds peotry to manage all python packages, so that we can avoid `python -m pip` while setting up.

Let's use `peotry install`!

Related https://github.com/datafuselabs/databend/pull/3901

Should be updated after https://github.com/datafuselabs/databend/pull/3896

## Changelog

- New Feature

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by PsiACE** [comment]
I think there are a few points that need attention.

1. we probably don't need to put it in the root directory? The python-related files will only be used for testing purposes.
2. also, is it really necessary to keep the lock file? If we specify a specific version.
3. please consider integrating it into our existing ci/docker. Then let's remove the python dependencies from the script.

**Comment by Xuanwo** [comment]
> 1. we probably don't need to put it in the root directory? The python-related files will only be used for testing purposes.

I think `poetry install` is much convenient than `cd xxxx && poetry install`. And I prefer to manage all python deps at once.

> 2. also, is it really necessary to keep the lock file? If we specify a specific version.

Yes, lock file is important and we need to track it.

Lock file is the key to reproducible build and keep us safe from things like `faker.js`.

> 3. please consider integrating it into our existing ci/docker. Then let's remove the python dependencies from the script.

Yes, but I prefer to split the work into several PRs.

In this one, we just discuss introducing the `poetry` itself and the version that we expect to pin.

And in the coming PRs, we will discover how to use `peotry` and how to refactor our dev setup scripts and so on.

**Comment by ariesdevil** [comment]
LGTM
If we can't avoid using python, I prefer using poetry:)

**Comment by BohuTANG** [comment]
> I think there are a few points that need attention.
> 
> 1. we probably don't need to put it in the root directory? The python-related files will only be used for testing purposes.

I still treat `poetry` as developent requeirement(only for our tests or a bit others), so agree with @PsiACE not put them in the root if it possible, to make the root directory as clean as possible.

`cd xxxx && poetry install` will in the setup.sh

> 2. also, is it really necessary to keep the lock file? If we specify a specific version.
> 3. please consider integrating it into our existing ci/docker. Then let's remove the python dependencies from the script.

**Comment by Xuanwo** [comment]
OK, let's move `pyproject.toml` into tests.

**Review by PsiACE — APPROVED** [review]
LGTM, let's do some subtraction next.

**Pull request merged**
