### PR TITLE
ci: cleanup after session finished

### PR DESCRIPTION
**Pull request by ZeaLoVe**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Considering that external datasets lack active deletion databases and tables. Add auto drop after a session is finished.
If a SQL starts with the command create, will record create type and name put into a set. Call drop if exists after the test is finished.

Fixes #issue

### CODE REVIEW

**Comment by ZeaLoVe** [comment]
Seems sometimes do not need auto cleanup, for example, fuse_compact, maybe make it optional, enable it by default?

**Comment by drmingdrmer** [comment]
- `main` branch is force pushed, update your working branch please: #7261

**Comment by Xuanwo** [comment]
@ZeaLoVe Please rebase this PR>

**Comment by ZeaLoVe** [comment]
> @ZeaLoVe Please rebase this PR. Merge can't resolve the problem mentioned in #7263

I choose close...

**Pull request closed without merging**
