### PR TITLE
fix(storage): disable table data cache in write operation

### LINKED ISSUE #13347: bug: compact oom with table mem cache table_data_deserialized_data_bytes = 1073741824
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.164-nightly

### What's Wrong?

use table cache 
```
[cache]
 table_data_deserialized_data_bytes = 1073741824 
```
load data use copy into quikly oom. 

disable table_data_deserialized_data_bytes is ok. 

### How to Reproduce?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by zhyass**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Disable table data cache in WRITE like COPY, DELETE, UPDATE, and REPLACE, and MERGE.

- Closes #13347

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13350)

### CODE REVIEW

**Comment by BohuTANG** [comment]
We can activate the block cache specifically for queries, while disabling it for other operations like COPY, DELETE, UPDATE, and REPLACE.

**Comment by wubx** [comment]
> We can activate the block cache specifically for queries, while disabling it for other operations like COPY, DELETE, UPDATE, and REPLACE, and MERGE.

The root cause is cache size is not under control.

The cache should be divided into two lists, hot and young, and new writes can be placed in young for LRU. The young area can account for 3/10 or 2/10 of the total cache, if the requests are repeatedly placed in the hot area within 1 second.

**Comment by BohuTANG** [comment]
@wubx It's not related to this, databend WRITE cluster always not same as READ cluster, so the COMPACT/RECLUSTER not need.

As cache, we are already LRU like you said.

**Review by BohuTANG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13350)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @dantengsky and @zhyass)

___
*[`src/query/ee/src/storages/fuse/operations/virtual_columns.rs` line 97 at r2](https://reviewable.io/reviews/datafuselabs/databend/13350#-Nh9cBis795Totuo5HMo:-Nh9cBis795Totuo5HMp:b-22mbj3) ([raw file](https://github.com/datafuselabs/databend/blob/de7a2737ec6bb0f24dcff22d96e8c5322a6f1463/src/query/ee/src/storages/fuse/operations/virtual_columns.rs#L97)):*
> ```XML
> 
>     let projection = Projection::Columns(field_indices);
>     let block_reader = fuse_table.create_block_reader(projection, false, ctx.clone(), true)?;
> ```

BTW, Make the `ctx` as the first param of `create_block_reader` in this PR?

**Comment by zhyass** [comment]
> > _[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13350)_ status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @dantengsky and @zhyass)

Thanks, has been modified.

**Comment by dantengsky** [comment]
@zhyass 

the population of `table_data_array_cache` also needs to be disabled:



https://github.com/datafuselabs/databend/blob/06a6e38779437d90a656e0d00be45399d60dc0bd/src/query/storages/fuse/src/io/read/block/block_reader_native_deserialize.rs#L166-L173



https://github.com/datafuselabs/databend/blob/06a6e38779437d90a656e0d00be45399d60dc0bd/src/query/storages/fuse/src/io/read/block/block_reader_parquet_deserialize.rs#L163-L170

**Review by dantengsky — APPROVED** [review]

**Pull request merged**
