### PR TITLE
feat: append only stream

### PR DESCRIPTION
**Pull request by zhyass**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

- [x] Add table option `change_tracking`
```sql
mysql> create table t(a int) cluster by(a) change_tracking=true;
Query OK, 0 rows affected (0.15 sec)

mysql> alter table t set options(change_tracking=false);
Query OK, 0 rows affected (0.05 sec)
```
- [x] tracking table read and write
```sql
mysql> insert into t values(1),(2);
Query OK, 2 rows affected (0.14 sec)

mysql> alter table t set options(change_tracking=true);
Query OK, 0 rows affected (0.17 sec)

mysql> insert into t values(3),(4);
Query OK, 2 rows affected (0.14 sec)

mysql> select * from t;
+------+
| a    |
+------+
|    1 |
|    2 |
|    3 |
|    4 |
+------+
4 rows in set (0.15 sec)
Read 4 rows, 18.00 B in 0.035 sec., 114.12 rows/sec., 513.55 B/sec.

mysql>  select _origin_version,_origin_block_id,_origin_block_row_num,a from t;
+-----------------+------------------+-----------------------+------+
| _origin_version | _origin_block_id | _origin_block_row_num | a    |
+-----------------+------------------+-----------------------+------+
|            NULL |             NULL |                  NULL |    1 |
|            NULL |             NULL |                  NULL |    2 |
|             324 |             NULL |                  NULL |    3 |
|             324 |             NULL |                  NULL |    4 |
+-----------------+------------------+-----------------------+------+
4 rows in set (0.17 sec)
Read 4 rows, 277.00 B in 0.026 sec., 155.77 rows/sec., 10.53 KiB/sec.

mysql> delete from t where a=3;
Query OK, 1 row affected (0.28 sec)

mysql> select _origin_version,_origin_block_id,_origin_block_row_num,a from t;
+-----------------+-----------------------------------------+-----------------------+------+
| _origin_version | _origin_block_id                        | _origin_block_row_num | a    |
+-----------------+-----------------------------------------+-----------------------+------+
|            NULL |                                    NULL |                  NULL |    1 |
|            NULL |                                    NULL |                  NULL |    2 |
|             324 | 131962390614217412475909862857956794283 |                     0 |    4 |
+-----------------+-----------------------------------------+-----------------------+------+
3 rows in set (0.16 sec)
Read 3 rows, 241.00 B in 0.025 sec., 121.19 rows/sec., 9.51 KiB/sec.

mysql> optimize table t compact;
Query OK, 3 rows affected (0.26 sec)

mysql> select _origin_version,_origin_block_id,_origin_block_row_num,a from t;
+-----------------+------------------------------------------+-----------------------+------+
| _origin_version | _origin_block_id                         | _origin_block_row_num | a    |
+-----------------+------------------------------------------+-----------------------+------+
|            NULL | -106146012413320482322914722827061169288 |                     0 |    1 |
|            NULL | -106146012413320482322914722827061169288 |                     1 |    2 |
|             324 |  131962390614217412475909862857956794283 |                     0 |    4 |
+-----------------+------------------------------------------+-----------------------+------+
3 rows in set (0.07 sec)
Read 3 rows, 112.00 B in 0.017 sec., 177.77 rows/sec., 6.48 KiB/sec.

mysql> update t set a=3 where _origin_version=324;
Query OK, 1 row affected (0.26 sec)

mysql> select _origin_version,_origin_block_id,_origin_block_row_num,a from t;
+-----------------+------------------------------------------+-----------------------+------+
| _origin_version | _origin_block_id                         | _origin_block_row_num | a    |
+-----------------+------------------------------------------+-----------------------+------+
|            NULL | -106146012413320482322914722827061169288 |                     0 |    1 |
|            NULL | -106146012413320482322914722827061169288 |                     1 |    2 |
|             324 |  131962390614217412475909862857956794283 |                     0 |    3 |
+-----------------+------------------------------------------+-----------------------+------+
3 rows in set (0.11 sec)
Read 3 rows, 112.00 B in 0.029 sec., 101.75 rows/sec., 3.71 KiB/sec.

mysql> insert into t values(5),(6);
Query OK, 2 rows affected (0.18 sec)

mysql> alter table t recluster;
Query OK, 5 rows affected (0.28 sec)

mysql> select _origin_version,_origin_block_id,_origin_block_row_num,a from t;
+-----------------+------------------------------------------+-----------------------+------+
| _origin_version | _origin_block_id                         | _origin_block_row_num | a    |
+-----------------+------------------------------------------+-----------------------+------+
|            NULL | -106146012413320482322914722827061169288 |                     0 |    1 |
|            NULL | -106146012413320482322914722827061169288 |                     1 |    2 |
|             324 |  131962390614217412475909862857956794283 |                     0 |    3 |
|             339 |  121890568986419126843086623591081426969 |                     0 |    5 |
|             339 |  121890568986419126843086623591081426969 |                     1 |    6 |
+-----------------+------------------------------------------+-----------------------+------+
5 rows in set (0.13 sec)
Read 5 rows, 184.00 B in 0.029 sec., 174.48 rows/sec., 6.27 KiB/sec.
```

- [x] create stream
```sql
CREATE STREAM [IF NOT EXISTS] [<database>.]<stream> 
  ON TABLE [<database>.]<table> 
    [<stream_point>] [COMMENT = '<string_literal>']
```
```sql
mysql> create stream if not exists s1 on table t comment='this is a stream';
Query OK, 0 rows affected (0.11 sec)

mysql> create stream s2 on table t at(stream => s1);
Query OK, 0 rows affected (0.18 sec)
```
- [x] drop stream 
```sql
DROP STREAM [IF EXISTS] [<database>.]<stream>
```

```sql
mysql> drop stream if exists s2;
Query OK, 0 rows affected (0.14 sec)
```

- [x] select stream
```sql
mysql> create table t(a int);
Query OK, 0 rows affected (0.07 sec)

mysql> insert into t values(1);
Query OK, 1 row affected (0.06 sec)

mysql> alter table t set options(change_tracking=true);
Query OK, 0 rows affected (0.06 sec)

mysql> create stream s on table t;
Query OK, 0 rows affected (0.04 sec)

mysql> insert into t values(2);
Query OK, 1 row affected (0.07 sec)

mysql> select * from s;
+------+
| a    |
+------+
|    2 |
+------+
1 row in set (0.07 sec)
Read 2 rows, 59.00 B in 0.032 sec., 61.82 rows/sec., 1.78 KiB/sec.

mysql> create stream s1 on table t;
Query OK, 0 rows affected (0.05 sec)

mysql> insert into t values(3);
Query OK, 1 row affected (0.06 sec)

mysql> select * from s;
+------+
| a    |
+------+
|    3 |
|    2 |
+------+
2 rows in set (0.07 sec)
Read 3 rows, 90.00 B in 0.029 sec., 104.22 rows/sec., 3.05 KiB/sec.

mysql> select * from s1;
+------+
| a    |
+------+
|    3 |
+------+
1 row in set (0.06 sec)
Read 1 rows, 31.00 B in 0.028 sec., 35.96 rows/sec., 1.09 KiB/sec.

mysql> optimize table t compact;
Query OK, 3 rows affected (0.10 sec)

mysql> select * from s1;
+------+
| a    |
+------+
|    3 |
+------+
1 row in set (0.06 sec)
Read 3 rows, 87.00 B in 0.030 sec., 101.64 rows/sec., 2.88 KiB/sec.

mysql> select * from s;
+------+
| a    |
+------+
|    2 |
|    3 |
+------+
2 rows in set (0.07 sec)
Read 3 rows, 87.00 B in 0.030 sec., 99.19 rows/sec., 2.81 KiB/sec.
```

- [x] consum stream
```sql
mysql> select * from s;
+------+
| a    |
+------+
|    3 |
|    2 |
+------+
2 rows in set (0.14 sec)
Read 2 rows, 62.00 B in 0.078 sec., 25.72 rows/sec., 797.25 B/sec.

mysql> create table t2(a int);
Query OK, 0 rows affected (0.19 sec)

mysql> insert into t2 select * from s;
Query OK, 2 rows affected (0.27 sec)

mysql> select * from s;
Empty set (0.27 sec)
Read 0 rows, 0.00 B in 0.100 sec., 0 rows/sec., 0.00 B/sec.

mysql> select * from t2;
+------+
| a    |
+------+
|    3 |
|    2 |
+------+
2 rows in set (0.06 sec)
Read 2 rows, 10.00 B in 0.014 sec., 142.88 rows/sec., 714.40 B/sec.
```
- [x] show streams
```sql
SHOW [FULL] STREAMS [FROM <database>]  [LIKE '<pattern>' | WHERE <expr>]

DESC|DESCRIBE STREAM [<database>.]<stream>
```

```
mysql> show streams;
+----------------------------+------+----------+---------+-----------+
| created_on                 | name | database | catalog | table_on  |
+----------------------------+------+----------+---------+-----------+
| 2023-11-20 14:50:42.442963 | s    | default  | default | default.t |
+----------------------------+------+----------+---------+-----------+
1 row in set (0.07 sec)
Read 1 rows, 249.00 B in 0.042 sec., 23.57 rows/sec., 5.73 KiB/sec.

mysql> drop table t;
Query OK, 0 rows affected (0.15 sec)

mysql> show full streams;
+----------------------------+------+----------+---------+-----------+-------+---------+-------------+-----------------------------------------------------+
| created_on                 | name | database | catalog | table_on  | owner | comment | mode        | invalid_reason                                      |
+----------------------------+------+----------+---------+-----------+-------+---------+-------------+-----------------------------------------------------+
| 2023-11-20 14:50:42.442963 | s    | default  | default | default.t | NULL  |         | append_only | UnknownTable. Code: 1025, Text = Unknown table 't'. |
+----------------------------+------+----------+---------+-----------+-------+---------+-------------+-----------------------------------------------------+
1 row in set (0.09 sec)
Read 1 rows, 249.00 B in 0.052 sec., 19.38 rows/sec., 4.71 KiB/sec.
```

- Closes #issue

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13602)

### CODE REVIEW

**Comment by BohuTANG** [comment]
Good PR summary 👍 , it would be great to add a case: 'merge into' from stream, for CDC.

**Review by dantengsky — APPROVED** [review]
:+1: LGTM

**Comment by dantengsky** [comment]
@BohuTANG  

This PR has also passed the other tests scenarios that @zhyass  and I came up with:

https://github.com/datafuse-extras/test-scripts/tree/main/change_tracking

**Comment by BohuTANG** [comment]
@zhyass  this pr is ready to merge?

**Pull request merged**
