### PR TITLE
add package purge subcommand for bendctl

### PR DESCRIPTION
**Pull request by linyihai**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

## Changelog

- New Feature

Add package purge subcommand for bendctl.

## Related Issues

Fixes [#issue3352](https://github.com/datafuselabs/databend/issues/3352)

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
`make lint` will make the rust happy :D

**Comment by PsiACE** [comment]
Hi, thanks for your contribution, we recently upgraded clap of bendctl and you need to merge the main branch.

also `clap::App` has been deprecated and we now `use clap::Command as App`

**Comment by linyihai** [comment]
ok



---Original---
From: "Chojan ***@***.***&gt;
Date: Fri, Feb 25, 2022 13:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [datafuselabs/databend] add package purge subcommand for bendctl (PR #4245)




 
Hi, thanks for your contribution, we recently upgraded clap of bendctl and you need to merge the main branch.
 
also clap::App has been deprecated and we now use clap::Command as App
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Review by PsiACE — APPROVED** [review]
LGTM, thanks

**Pull request merged**
