### PR TITLE
feat(rbac): Add secondary roles

### LINKED ISSUE #13544: feat: seperate primary role and secondary role
may looks like: https://docs.snowflake.com/en/sql-reference/sql/use-secondary-roles

- Make secondary roles default as ALL, so every roles' privileges take effect, when you create a database, it's owned by the CURRENT ROLE
- If the secondary roles are NONE, only the privileges of CURRENT ROLE take effect

### PR DESCRIPTION
**Pull request by flaneur2020**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

TODO:

- [x] revert the restricted_role to auth_role
- [x] add `secondary_roles` in session_ctx, and add `effective_roles` on checking privileges
- [x] allow pass secondary roles in the session state
- [x] return the updated role and secondary_roles in session state.
- [x] add SQL syntax about SET SECONDARY ROLES [ALL|NONE]
- [x] add stateless tests

test cases:

1) specify one role, set secondary_roles as None, all the role granted to the user have effects.
2) sepcify one role, set secondary_roles as [], only the current role and current role's related roles have effects.
3) specify one role, set secondary_roles as [role2], it will report an error about only ALL|NONE is supported yet.

more test cases may learned from: https://medium.com/@kar9475/snowflake-secondary-roles-usage-and-findings-8e026a20d146

fixes #13544

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13673)

### CODE REVIEW

**Comment by flaneur2020** [comment]
the stateless test requires a newer version of bendsql with https://github.com/datafuselabs/bendsql/pull/304 included

**Comment by BohuTANG** [comment]
Cool.
But GPT4 give more test cases for this PR, [Share link to Chat](https://chat.openai.com/share/37a9ce4d-2ea8-4903-989b-a393095ad1cb).

We can choose some of them:
```
#!/usr/bin/env bash

# Your existing setup code here...
# ...

# Test 7: Verify behavior when switching roles multiple times in a single session
# This test checks if the system correctly handles multiple role changes in the same session.
echo '-- test 7: switch roles multiple times in a single session'
echo "SET ROLE testrole1; INSERT INTO t20_0015_table1 VALUES (2); SET ROLE testrole2; INSERT INTO t20_0015_table2 VALUES (2);" | $TEST_USER_CONNECT

# Test 8: Attempt to access a table with no explicit privileges
# This test attempts to access a table without any explicitly granted privileges to see if the default behavior is secure.
echo '-- test 8: access table without explicit privileges'
echo "CREATE TABLE t20_0015_table3(c int not null)" | $BENDSQL_CLIENT_CONNECT
echo "INSERT INTO t20_0015_table3 VALUES (1);" | $TEST_USER_CONNECT || true

# Test 9: Check role persistence across different sessions
# This test creates a new session and checks if the role settings from the previous session persist, which they shouldn't.
echo '-- test 9: role persistence across sessions'
echo "SET ROLE testrole1; SELECT current_role();" | $TEST_USER_CONNECT
echo "SELECT current_role();" | $TEST_USER_CONNECT # Expected to not be testrole1

# Test 10: Validate behavior with nonexistent roles
# This test tries to set a role that doesn't exist to see if the system handles such cases gracefully.
echo '-- test 10: set a nonexistent role'
echo "SET ROLE nonexisting_role;" | $TEST_USER_CONNECT || true

# Test 11: Check for SQL injection vulnerability in role setting
# This test checks if the role-setting mechanism is vulnerable to SQL injection.
echo '-- test 11: SQL injection test in role setting'
INJECTION_TEST="testrole1; DROP TABLE t20_0015_table1;"
echo "SET ROLE '$INJECTION_TEST'" | $TEST_USER_CONNECT || true
echo "SELECT COUNT(*) FROM t20_0015_table1;" | $BENDSQL_CLIENT_CONNECT # Should not return an error if table is not dropped

# Test 12: Validate the revocation of privileges from a role
# This test revokes a privilege from a role and checks if the revocation is effective.
echo '-- test 12: revoke privileges and test access'
echo "REVOKE SELECT ON default.t20_0015_table1 FROM ROLE testrole1" | $BENDSQL_CLIENT_CONNECT
echo "SELECT * FROM t20_0015_table1;" | $TEST_USER_CONNECT || true

#!/usr/bin/env bash

# Your existing setup and environment variables...
# ...

# Test 13: Create and use a UDF with a specific role
# This test checks if a UDF can be created and used by a role with appropriate privileges.
echo '-- test 13: create and use a UDF with specific role'
echo "CREATE FUNCTION test_udf AS 'return x+1'" | $BENDSQL_CLIENT_CONNECT
echo "SET ROLE testrole1; SELECT test_udf(1);" | $TEST_USER_CONNECT || true

# Test 14: Attempt to use a UDF without necessary privileges
# This test tries to use a UDF without having the required privileges to see if access control is enforced.
echo '-- test 14: use a UDF without necessary privileges'
echo "SET ROLE testrole2; SELECT test_udf(1);" | $TEST_USER_CONNECT || true

# Test 15: Grant UDF privileges and then revoke them
# This test grants UDF usage privileges to a role, tests the access, and then revokes it to test access again.
echo '-- test 15: grant and revoke UDF privileges'
echo "GRANT USAGE ON UDF test_udf TO ROLE testrole2" | $BENDSQL_CLIENT_CONNECT
echo "SET ROLE testrole2; SELECT test_udf(1);" | $TEST_USER_CONNECT
echo "REVOKE USAGE ON UDF test_udf FROM ROLE testrole2" | $BENDSQL_CLIENT_CONNECT
echo "SET ROLE testrole2; SELECT test_udf(1);" | $TEST_USER_CONNECT || true

# Test 16: Check role behavior with transactional statements
# This test examines how role changes interact with transaction boundaries.
echo '-- test 16: role behavior within transactions'
echo "BEGIN; SET ROLE testrole1; INSERT INTO t20_0015_table1 VALUES (3); COMMIT;" | $TEST_USER_CONNECT
echo "BEGIN; SET ROLE testrole2; INSERT INTO t20_0015_table2 VALUES (3); ROLLBACK;" | $TEST_USER_CONNECT

# Test 17: Validate the behavior of dynamic role switching in complex queries
# This test changes roles in the middle of a complex query to check if the system dynamically adjusts privileges.
echo '-- test 17: dynamic role switching in complex queries'
echo "SET ROLE testrole1; SELECT * FROM t20_0015_table1 WHERE EXISTS (SET ROLE testrole2; SELECT * FROM t20_0015_table2);" | $TEST_USER_CONNECT || true

# Test 18: Check access control with chained role dependencies
# This test creates a chain of roles with dependencies and checks if privilege escalation or leakage occurs.
echo '-- test 18: chained role dependencies'
echo "CREATE ROLE testrole3; GRANT ROLE testrole2 TO testrole3; SET ROLE testrole3; INSERT INTO t20_0015_table2 VALUES (4);" | $TEST_USER_CONNECT || true

# Test 19: Test role revocation in an active session
# This test revokes a role in an active session and checks if the privileges are immediately updated.
echo '-- test 19: role revocation in an active session'
echo "SET ROLE testrole1; REVOKE ROLE testrole1 FROM testuser1; SELECT * FROM t20_0015_table1;" | $TEST_USER_CONNECT || true

# Test 20: Validate error messages for unauthorized actions
# This test performs unauthorized actions and checks if the system provides clear and informative error messages.
echo '-- test 20: validate error messages for unauthorized actions'
echo "SET ROLE testrole1; DELETE FROM t20_0015_table1;" | $TEST_USER_CONNECT || true

... ... 

```

**Comment by BohuTANG** [comment]
Cool.
But GPT4 give more test cases for this PR, [Share link to Chat](https://chat.openai.com/share/37a9ce4d-2ea8-4903-989b-a393095ad1cb).

We can choose some of them:
```
#!/usr/bin/env bash

# Your existing setup code here...
# ...

# Test 7: Verify behavior when switching roles multiple times in a single session
# This test checks if the system correctly handles multiple role changes in the same session.
echo '-- test 7: switch roles multiple times in a single session'
echo "SET ROLE testrole1; INSERT INTO t20_0015_table1 VALUES (2); SET ROLE testrole2; INSERT INTO t20_0015_table2 VALUES (2);" | $TEST_USER_CONNECT

# Test 8: Attempt to access a table with no explicit privileges
# This test attempts to access a table without any explicitly granted privileges to see if the default behavior is secure.
echo '-- test 8: access table without explicit privileges'
echo "CREATE TABLE t20_0015_table3(c int not null)" | $BENDSQL_CLIENT_CONNECT
echo "INSERT INTO t20_0015_table3 VALUES (1);" | $TEST_USER_CONNECT || true

# Test 9: Check role persistence across different sessions
# This test creates a new session and checks if the role settings from the previous session persist, which they shouldn't.
echo '-- test 9: role persistence across sessions'
echo "SET ROLE testrole1; SELECT current_role();" | $TEST_USER_CONNECT
echo "SELECT current_role();" | $TEST_USER_CONNECT # Expected to not be testrole1

# Test 10: Validate behavior with nonexistent roles
# This test tries to set a role that doesn't exist to see if the system handles such cases gracefully.
echo '-- test 10: set a nonexistent role'
echo "SET ROLE nonexisting_role;" | $TEST_USER_CONNECT || true

# Test 11: Check for SQL injection vulnerability in role setting
# This test checks if the role-setting mechanism is vulnerable to SQL injection.
echo '-- test 11: SQL injection test in role setting'
INJECTION_TEST="testrole1; DROP TABLE t20_0015_table1;"
echo "SET ROLE '$INJECTION_TEST'" | $TEST_USER_CONNECT || true
echo "SELECT COUNT(*) FROM t20_0015_table1;" | $BENDSQL_CLIENT_CONNECT # Should not return an error if table is not dropped

# Test 12: Validate the revocation of privileges from a role
# This test revokes a privilege from a role and checks if the revocation is effective.
echo '-- test 12: revoke privileges and test access'
echo "REVOKE SELECT ON default.t20_0015_table1 FROM ROLE testrole1" | $BENDSQL_CLIENT_CONNECT
echo "SELECT * FROM t20_0015_table1;" | $TEST_USER_CONNECT || true

#!/usr/bin/env bash

# Your existing setup and environment variables...
# ...

# Test 13: Create and use a UDF with a specific role
# This test checks if a UDF can be created and used by a role with appropriate privileges.
echo '-- test 13: create and use a UDF with specific role'
echo "CREATE FUNCTION test_udf AS 'return x+1'" | $BENDSQL_CLIENT_CONNECT
echo "SET ROLE testrole1; SELECT test_udf(1);" | $TEST_USER_CONNECT || true

# Test 14: Attempt to use a UDF without necessary privileges
# This test tries to use a UDF without having the required privileges to see if access control is enforced.
echo '-- test 14: use a UDF without necessary privileges'
echo "SET ROLE testrole2; SELECT test_udf(1);" | $TEST_USER_CONNECT || true

# Test 15: Grant UDF privileges and then revoke them
# This test grants UDF usage privileges to a role, tests the access, and then revokes it to test access again.
echo '-- test 15: grant and revoke UDF privileges'
echo "GRANT USAGE ON UDF test_udf TO ROLE testrole2" | $BENDSQL_CLIENT_CONNECT
echo "SET ROLE testrole2; SELECT test_udf(1);" | $TEST_USER_CONNECT
echo "REVOKE USAGE ON UDF test_udf FROM ROLE testrole2" | $BENDSQL_CLIENT_CONNECT
echo "SET ROLE testrole2; SELECT test_udf(1);" | $TEST_USER_CONNECT || true

# Test 16: Check role behavior with transactional statements
# This test examines how role changes interact with transaction boundaries.
echo '-- test 16: role behavior within transactions'
echo "BEGIN; SET ROLE testrole1; INSERT INTO t20_0015_table1 VALUES (3); COMMIT;" | $TEST_USER_CONNECT
echo "BEGIN; SET ROLE testrole2; INSERT INTO t20_0015_table2 VALUES (3); ROLLBACK;" | $TEST_USER_CONNECT

# Test 17: Validate the behavior of dynamic role switching in complex queries
# This test changes roles in the middle of a complex query to check if the system dynamically adjusts privileges.
echo '-- test 17: dynamic role switching in complex queries'
echo "SET ROLE testrole1; SELECT * FROM t20_0015_table1 WHERE EXISTS (SET ROLE testrole2; SELECT * FROM t20_0015_table2);" | $TEST_USER_CONNECT || true

# Test 18: Check access control with chained role dependencies
# This test creates a chain of roles with dependencies and checks if privilege escalation or leakage occurs.
echo '-- test 18: chained role dependencies'
echo "CREATE ROLE testrole3; GRANT ROLE testrole2 TO testrole3; SET ROLE testrole3; INSERT INTO t20_0015_table2 VALUES (4);" | $TEST_USER_CONNECT || true

# Test 19: Test role revocation in an active session
# This test revokes a role in an active session and checks if the privileges are immediately updated.
echo '-- test 19: role revocation in an active session'
echo "SET ROLE testrole1; REVOKE ROLE testrole1 FROM testuser1; SELECT * FROM t20_0015_table1;" | $TEST_USER_CONNECT || true

# Test 20: Validate error messages for unauthorized actions
# This test performs unauthorized actions and checks if the system provides clear and informative error messages.
echo '-- test 20: validate error messages for unauthorized actions'
echo "SET ROLE testrole1; DELETE FROM t20_0015_table1;" | $TEST_USER_CONNECT || true

... ... 

```

**Comment by flaneur2020** [comment]
neat suggestions! let me push these AI test cases into this PR quq

**Comment by flaneur2020** [comment]
@BohuTANG 

I added the following test cases:

1. set a non-exsited & non-granted role
2. set default role, then select current_role() in another session
3. test the inherited privileges

this test files mainly targets the `SET ROLE` statement. we also have a plan to have some rework on the existing test cases, so we can add some other test cases from the API suggested list into proper files.

**Review by BohuTANG — APPROVED** [review]

**Pull request merged**
