### PR TITLE
feat: remove XML input format.

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

- Fixes https://github.com/datafuselabs/databend/issues/13460

1.  this issue has been there for a long time, and no one seems to be using XML as far as I know.
2.  to be able to read exists XML related objects in meta , I keep the EnumItems  `FileFormatParams::XML`, as shown below, 
    -   user can still `show file formats`(important), and `show stages`(important),  and `desc stage `
    -  can drop them for cleaning up.  (after all user done with this, there is no problem with  `list file formats`)
    -  but reading from the old stage with xml format will raise error (can not avoid).   
4.  try to read data (query state, copy into table) or create new object  (stage, file format) with xml will lead to error too (can not avoid)
 

## checks for all realted usages

 step1: create objects on old server

```
create file format xml1 type = xml;
create stage s1 file_format=(type=xml);
create stage s2 file_format=(format_name='xml1');

```

 step2: try used them on new server 

```
root@localhost:8000/default> select * from @s1;
error: APIError: ResponseError with 1002: The file format in the query stage is not supported. Currently supported formats are: Parquet, NDJson, CSV, and TSV. Provided format: 'TYPE = XML COMPRESSION = None ROW_TAG = 'row''.


root@localhost:8000/default> select * from @s2;
error: APIError: ResponseError with 1002: The file format in the query stage is not supported. Currently supported formats are: Parquet, NDJson, CSV, and TSV. Provided format: 'TYPE = XML COMPRESSION = None ROW_TAG = 'row''.

root@localhost:8000/default> show file formats;

SHOW FILE formats

┌────────────────────────────────────────────────────────┐
│  name  │                 format_options                │
│ String │                     String                    │
├────────┼───────────────────────────────────────────────┤
│ xml1   │ TYPE = XML COMPRESSION = None ROW_TAG = 'row' │
└────────────────────────────────────────────────────────┘

```

step3: drop them on new server

```
root@localhost:8000/default> drop stage s1;
root@localhost:8000/default> drop file format xml1;
```

step4: use xml directly on new server

```
1 | create file format xml2 type = xml
  | ------                         ^^^ unexpected `xml`, expecting <QuotedString>, `TSV`, `CSV`, `NDJSON`, `PARQUET`, or `JSON`

root@localhost:8000/default> create stage s1 file_format=(format_name=xml1);
error: APIError: ResponseError with 1005: error: 
  --> SQL:1:42
  |
1 | create stage s1 file_format=(format_name=xml1)
  | ------                                   ^^^^ unexpected `xml1`, expecting <QuotedString


root@localhost:8000/default> copy into @s1 from (select 1) file_format=(type=csv);
root@localhost:8000/default> select * from @s1(file_format=>'xml');
error: APIError: ResponseError with 2508: Unsupported file format type: Xml

```

## Tests

- [ ] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [x] No Test  - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [x] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15540)

### CODE REVIEW

**Review by drmingdrmer — COMMENTED** [review]
Not quite sure if the compatibility will be held after these changes.

> Reviewed 13 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15540#-:-NxzC33x04ZP8jIQKb5P:b-rm982z)* status: 13 of 21 files reviewed, 2 unresolved discussions (waiting on @youngsofun)

___
*[`src/meta/app/src/principal/file_format.rs` line 110 at r1](https://reviewable.io/reviews/datafuselabs/databend/15540#-NxzBR3VAxhzH_VxozDk:-NxzBR3VAxhzH_VxozDl:b-kd1dqg) ([raw file](https://github.com/datafuselabs/databend/blob/600f3eacf7aefc8f8fa71a19c1e72657b322d456/src/meta/app/src/principal/file_format.rs#L110)):*
> ```XML
>         let typ = reader.take_type()?;
>         let params = match typ {
>             StageFileFormatType::Xml => {
> ```

I'm not entirely certain where this method is utilized, but I suspect that removing an enum variant might make it impossible to read data that already exists. This could lead to compatibility issues with data serialized under the previous schema. It's crucial to carefully consider the implications of such changes on existing systems.
___
*[`src/query/formats/src/field_decoder/separated_text.rs` line 104 at r1](https://reviewable.io/reviews/datafuselabs/databend/15540#-NxzBuTo62x1IAYCQFWN:-NxzBuTo62x1IAYCQFWO:b1vg804) ([raw file](https://github.com/datafuselabs/databend/blob/600f3eacf7aefc8f8fa71a19c1e72657b322d456/src/query/formats/src/field_decoder/separated_text.rs#L104)):*
> ```XML
>                 true_bytes: TRUE_BYTES_NUM.as_bytes().to_vec(),
>                 false_bytes: FALSE_BYTES_NUM.as_bytes().to_vec(),
>                 nan_bytes: NAN_BYTES_LOWER.as_bytes().to_vec(),
> ```

The same. Is there any compatibility test that covers these part of changes?

**Comment by youngsofun** [comment]
@drmingdrmer  

Thanks!

Just as you said, for compatibility I do not delete the XML enum item.  pleas see the  summary for detail.

I also checked the 2 places you pointed out, It seems no problem to me.

**Comment by drmingdrmer** [comment]
> @drmingdrmer
> 
> Thanks!
> 
> Just as you said, for compatibility I do not delete the XML enum item. pleas see the summary for detail.
> 
> I also checked the 2 places you pointed out, It seems no problem to me.
> 
> in this way, no need to change the meta code?

If I got it correctly, it will emit error if encountered `XML` type. Unless it assumes no `XML` type is used in existing data. If this assumption is true, the error should be emitted earlier: by `reader.take_type()?`, not by `try_from_reader()`

In this commit, it will still return an `XML` type:

image

But in `try_from_reader`, variant `XML` will emit an error:

image

And finally result in an `Incompatible` error:

image

**Comment by youngsofun** [comment]
@drmingdrmer 

you are right,  this will happen if the object is written before 2023-04-05:

```
    (32, "2023-04-05: Add: file_format.proto/FileFormatParams", ),
```

**Comment by youngsofun** [comment]
@drmingdrmer 

let me try restoring it https://github.com/datafuselabs/databend/pull/15540

**Review by sundy-li — APPROVED** [review]

**Comment by drmingdrmer** [comment]
> @drmingdrmer
> 
> you are right, this will happen if the object is written on a old server before 2023-04-05:
> 
> ```
>     (32, "2023-04-05: Add: file_format.proto/FileFormatParams", ),
> ```

If there are no longer data with version=32 deployed, we can remove this compatibility support 🤔

**Comment by youngsofun** [comment]
> > @drmingdrmer
> 
> > 
> 
> > you are right, this will happen if the object is written on a old server before 2023-04-05:
> 
> > 
> 
> > ```
> 
> >     (32, "2023-04-05: Add: file_format.proto/FileFormatParams", ),
> 
> > ```
> 
> 
> 
> If there are no longer data with version=32 deployed, we can remove this compatibility support 🤔 
> 
> 
> 
> 

not sure

**Comment by youngsofun** [comment]
@drmingdrmer is this OK with you?

**Comment by drmingdrmer** [comment]
> @drmingdrmer is this OK with you?

Either way is Ok to me:)

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 7 of 21 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15540)* status: all files reviewed, 2 unresolved discussions (waiting on @youngsofun)

**Pull request merged**
