### PR TITLE
[fix]: resolve ulimit error in makefile

### LINKED ISSUE #2551: [fix] failed to run make test in wsl2
**Summary**

failed to run the make test in wsl2
Description for this bug.

**How to reproduce**
run make test in wsl2

**Error message and/or stacktrace**

ulimit -c 1024 bash ./scripts/ci/ci-run-unit-tests.sh
/bin/sh: 1: ulimit: too many arguments
make: *** [Makefile:64：unit-test]

**Additional context**

### PR DESCRIPTION
**Pull request by sunisdown**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

fix `ulimit: too many arguments` 

## Changelog

- Bug Fix

## Related Issues

Fixes #2551

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by sunisdown** [comment]
@zhang2014   @PsiACE  please do not merge the PR. It's not stable in different OS. I need to test it more.

**Comment by zhang2014** [comment]
> @zhang2014 @PsiACE please do not merge the PR. It's not stable in different OS. I need to test it more.

Let's convert it to draft until it's ready to be reviewed again : )

**Comment by sunisdown** [comment]
@zhang2014 @PsiACE  updated

**Review by PsiACE — APPROVED** [review]

**Pull request merged**
