### PR TITLE
feat: implement task suggestion for background service

### PR DESCRIPTION
**Pull request by ZhiHanZ**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

1. enable manual execution of background job
2. add `call admin$suggested_background_tasks` command to show all suggested actions for background service
3. add api `/v1/suggestions` on http query port and support to query the api under management mode.
4. change field on meta app to audit for action trigger

 Closes #issu

### CODE REVIEW

**Comment by BohuTANG** [comment]
askbend:summary

**Comment by BohuTANG** [comment]
## PR Summary(By [llmchain.rs](https://github.com/shafishlabs/llmchain.rs)):
* **Dependency Updates**: Updated versions of `typetag` and `syn` crates, and removed `parking_lot` dependency.
* **Background Job Manual Trigger**: Added a new field `manual_trigger` to `BackgroundTaskInfo` and `BackgroundJobParams` structs, and implemented `FromToProto` trait for `ManualTriggerParams`. Added a new shell script to run test suite for DatabendQuery in standalone mode with MinIO as the backend.
* **Background Compaction Config**: Added new fields `enable_compaction` and `target_tables` to `BackgroundCompactionConfig` struct, and modified related functions and implementations.
* **Management Suggestions**: Added a new module `management_suggestions` and an enum `Suggestion` to it.
* **Background Service**: Modified related functions and implementations to use `SuggestedBackgroundTasksProcedure` instead of `Planner` and `InterpreterFactory`, and added support for manual trigger params. Added a new file `suggested_background_compaction_tasks.rs` to get suggested compaction tasks for tables.
* **HTTP Server**: Added a new endpoint to handle GET requests to `/suggestions`, and defined a new struct `SuggestionsResponse` and a handler function `list_suggestions`.
* **Query Context**: Added a new enum `Origin` with variants `Default`, `HttpHandler`, and `BuiltInProcedure`, and a new field `origin` to `QueryContext` struct.
* **Test Cases**: Added new test scripts and result files to test background job trigger and related functionalities.

**Comment by flaneur2020** [comment]
i guess the endpoint `/v1/suggestions` is a bit too general, how about `/v1/suggested-background-tasks` ?

**Review by flaneur2020 — APPROVED** [review]

**Comment by drmingdrmer** [comment]
### PR summary(by Claude):

 Woah that's a lot of changes. The summary points look good though here are my suggestions:

1. * **Extract common SQL**: Extracted common SQL logic into a background procedure so it can be reused.
This avoids duplicating SQL execution logic and makes future changes easier.

2. * **Track suggested background tasks**: Added logic to track suggested background compaction tasks and make them available via an HTTP endpoint. This provides visibility into tables that may benefit from compaction.  

3. * **Trigger background jobs manually**: Added ability to manually trigger background jobs from an API call. This ensures tasks are run promptly without waiting for the scheduled time.

4. * **Filter background jobs**: Background jobs can now filter target tables from a config instead of querying all tables. This improves performance and control.

5. * **Add table and DB information**: Background task suggestions now include table statistics and database information for context.

How's that? Let me know if you have any other questions.

**Review by drmingdrmer — APPROVED** [review]

**Pull request merged**
