### PR TITLE
[ Doc ] Documentation for run databend-cluster under kubernetes

### LINKED ISSUE #4493: Deploy Databend distributed clusters based on Kubernetes
**Summary**

How to depoly Databend cluster based on Kubernetes.

### PR DESCRIPTION
**Pull request by ZhiHanZ**
…s with minio as object storage

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Add sample kubernetes configuration yaml for deploy databend on private kubernetes with minio as object storage

## Changelog

- Build/Testing/CI
- Documentation

## Related Issues

Fixes #4493 

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Review by BohuTANG — APPROVED** [review]
Nice work!

**Review by everpcpc — APPROVED** [review]

**Comment by TCeason** [comment]
Some typo errs :

> NOTICE: please make sure that the localhost port 3308 is available.

NOTICE: Please make sure that the localhost port 3308 is available.


> The distributed query works, the cluster will efficient transfer data through `flight_api_address`.

The distributed query works, the cluster will efficiently transfer data through `flight_api_address`.

**Comment by BohuTANG** [comment]
error: ts/kubernetes/meta-standalone.yaml:97:22: [error] no new line character at the end of file (new-line-at-end-of-file)


Need make lint

**Comment by flaneur2020** [comment]
cool

**Review by flaneur2020 — APPROVED** [review]

**Pull request merged**
