### PR TITLE
refactor:  adjsut file format options.

### PR DESCRIPTION
**Pull request by youngsofun**
## Summary
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

### breaking changes for newly added feature.  
for stricter type checking:  Databend will by default report error when trying to load csv empty or json null to not nullable columns

1. change default of CSV `EMPTY_FIELD_AS` from `FIELD_DEFAULT` to `NULL`.  including  empty caused by `error_on_column_count_mismatch=true`.
2. change default of NDJSON `NULL_FIELD_AS` from `FIELD_DEFAULT` to `NULL`.
3. remove `TYPE_DEFAULT` (I guess not used for now)

if the original COPY failed after this patch, there are 2 solutions:

1.  change relate field type of table from non-nullable to nullable (preferred)
2. add option ` EMPTY_FIELD_AS |  NULL_FIELD_AS = FIELD_DEFAULT` when copy

### other refinement:

1. prefer ident (like `NULL`)  to string literal  (like `'NULL'`)  for enum values like EMPTY_FIELD_AS | NULL_FIELD_AS | MISSING_FIELD_AS.
3. Fix Display of FileFormatParams. 
5. test compatibility for CsvFileFormatParams instead of FileFormatParam. fix https://github.com/datafuselabs/databend/issues/14332#event-11493608393

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [x] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [x] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14335)

### CODE REVIEW

**Review by drmingdrmer — CHANGES_REQUESTED** [review]
> Reviewed 1 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14335)* status: 1 of 21 files reviewed, 1 unresolved discussion (waiting on @andylokandy, @sundy-li, and @youngsofun)

___
*[`src/meta/proto-conv/tests/it/v064_ndjson_format_params.rs` line 36 at r1](https://reviewable.io/reviews/datafuselabs/databend/14335#-NoMffc4AiViJwviACDS:-NoMffc4AiViJwviACDT:b-fs0rv4) ([raw file](https://github.com/datafuselabs/databend/blob/a92759cce4d89b86f02980a3d17e58d24c63d585/src/meta/proto-conv/tests/it/v064_ndjson_format_params.rs#L36)):*
> ```XML
>         8, 1, 18, 13, 70, 73, 69, 76, 68, 95, 68, 69, 70, 65, 85, 76, 84, 26, 13, 70, 73, 69, 76,
>         68, 95, 68, 69, 70, 65, 85, 76, 84, 160, 6, 64, 168, 6, 24,
>     ];
> ```

Never change the message built with a previous version of program. Only add new test to ensure compatibility.
These messages are kept to ensure a new version of program being able to load old version message.

https://github.com/datafuselabs/databend/blob/04349323a92e6cf58f0cd6c8fb3effe052b36e6c/src/meta/proto-conv/src/util.rs#L107-L112



_Code quote:_
```XML
    let nd_json_file_format_params_v64 = vec![
        8, 1, 18, 13, 70, 73, 69, 76, 68, 95, 68, 69, 70, 65, 85, 76, 84, 26, 13, 70, 73, 69, 76,
        68, 95, 68, 69, 70, 65, 85, 76, 84, 160, 6, 64, 168, 6, 24,
    ];
```

**Comment by youngsofun** [comment]
@drmingdrmer 
the change of v64 is to fix https://github.com/datafuselabs/databend/issues/14332#event-11493608393.
so this is not needed?  or I should add a new test for each wrong case?

**Comment by drmingdrmer** [comment]
> @drmingdrmer the change of v64 is to fix [#14332 (comment)](https://github.com/datafuselabs/databend/issues/14332#event-11493608393). so this is not needed ( just pay attention from now on)? or I should add a new test for each wrong case?


I strongly advise against modifying an existing serialized message. It is not immediately apparent whether compatibility will be maintained after such a change.

If the intention is to resolve issue #14332, I suggest submitting a separate pull request dedicated to this fix. Additionally, please ensure to accompany it with a new test case to verify the change.

**Comment by youngsofun** [comment]
> > @drmingdrmer the change of v64 is to fix [#14332 (comment)](https://github.com/datafuselabs/databend/issues/14332#event-11493608393). so this is not needed ( just pay attention from now on)? or I should add a new test for each wrong case?
> 
> I strongly advise against modifying an existing serialized message. It is not immediately apparent whether compatibility will be maintained after such a change.
> 
> If the intention is to resolve issue #14332, I suggest submitting a separate pull request dedicated to this fix. Additionally, please ensure to accompany it with a new test case to verify the change.

the test for v64 is reverted. please review again.

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 2 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14335)* status: 3 of 21 files reviewed, 1 unresolved discussion (waiting on @andylokandy, @sundy-li, and @youngsofun)

**Pull request merged**
