### PR TITLE
ci: Fix binary in target not found by docker

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

Fix issue #3467 

## Changelog

- Build/Testing/CI

### CODE REVIEW

**Comment by Xuanwo** [comment]
Sorry for closing PR by mistake.

**Comment by Xuanwo** [comment]
cc @PsiACE for review.

**Comment by Xuanwo** [comment]
@mergify update

**Review by PsiACE — APPROVED** [review]
It is possible to remove `Build perf-tools`. But I'm not sure it will solve the issue.

**Comment by Xuanwo** [comment]
I don't know why test_stateless_cluster (macos-11, x86_64-apple-darwin) https://github.com/datafuselabs/databend/runs/4530086984?check_suite_focus=true failed, looks like not related to this PR.

**Comment by Xuanwo** [comment]
> It is possible to remove `Build perf-tools`. But I'm not sure it will solve the issue.

Oh, they are not related. The real change is to remove the `.dockerignore` which ignores all files under `target`.

**Pull request merged**
