### PR TITLE
chore(query): display error name

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

chore(query): display error name

```
mysql> select 123zxcvsdfsd from xxx;
ERROR 1105 (HY000): UnknownTable. Code: 1025, Text = error:
  --> SQL:1:26
  |
1 | select 123zxcvsdfsd from xxx
  |                          ^^^ Unknown table 'xxx'
```

- Closes #issue

### CODE REVIEW

**Review by BohuTANG — APPROVED** [review]

**Comment by BohuTANG** [comment]
```
--- /runner/_work/databend/databend/tests/suites/1_stateful/00_copy/00_0011_distributed_copy_into_table_exection_test.result	2023-07-05 04:39:08.524255491 +0000
+++ /runner/_work/databend/databend/tests/suites/1_stateful/00_copy/00_0011_distributed_copy_into_table_exection_test.stdout	2023-07-05 04:41:27.274689860 +0000
@@ -28,6 +28,6 @@
 105	hammer	14oz carpenter's hammer
 24
 null
-ERROR 1105 (HY000) at line 1: BadBytes. Code: 1046, Text = expect 3 fields, only found 2 , split sample_2_columns.csv(77 bytes), row=0=0+0, offset=0=0+0, options=Csv(CsvFileFormatParams { compression: None, headers: 0, field_delimiter: ",", record_delimiter: "\n", nan_display: "NaN", escape: "", quote: "\"" }), schema=[TableField { name: "id", default_expr: None, data_type: Number(Int32), column_id: 0, computed_expr: None }, TableField { name: "name", default_expr: None, data_type: String, column_id: 1, computed_expr: None }, TableField { name: 

+ERROR 1105 (HY000) at line 1: BadBytes. Code: 1046, Text = expect 3 fields, only found 2 , split sample_2_columns.csv(77 bytes), row=0=0+0, offset=0=0+0, options=Csv(CsvFileFormatParams { compression: None, headers: 0, field_delimiter: ",", record_delimiter: "\n", nan_display: "NaN", escape: "", quote: "\"" }), schema=[TableField { name: "id", default_expr: None, data_type: Number(Int32), column_id: 0, computed_expr: None }, TableField { name: "name", default_expr: None, data_type: String, column_id: 1, computed_expr: None }, TableFiel
 24
 5
```

**Comment by zhang2014** [comment]
> ```
> --- /runner/_work/databend/databend/tests/suites/1_stateful/00_copy/00_0011_distributed_copy_into_table_exection_test.result	2023-07-05 04:39:08.524255491 +0000
> +++ /runner/_work/databend/databend/tests/suites/1_stateful/00_copy/00_0011_distributed_copy_into_table_exection_test.stdout	2023-07-05 04:41:27.274689860 +0000
> @@ -28,6 +28,6 @@
>  105	hammer	14oz carpenter's hammer
>  24
>  null
> -ERROR 1105 (HY000) at line 1: BadBytes. Code: 1046, Text = expect 3 fields, only found 2 , split sample_2_columns.csv(77 bytes), row=0=0+0, offset=0=0+0, options=Csv(CsvFileFormatParams { compression: None, headers: 0, field_delimiter: ",", record_delimiter: "\n", nan_display: "NaN", escape: "", quote: "\"" }), schema=[TableField { name: "id", default_expr: None, data_type: Number(Int32), column_id: 0, computed_expr: None }, TableField { name: "name", default_expr: None, data_type: String, column_id: 1, computed_expr: None }, TableField { name: 
> 
> +ERROR 1105 (HY000) at line 1: BadBytes. Code: 1046, Text = expect 3 fields, only found 2 , split sample_2_columns.csv(77 bytes), row=0=0+0, offset=0=0+0, options=Csv(CsvFileFormatParams { compression: None, headers: 0, field_delimiter: ",", record_delimiter: "\n", nan_display: "NaN", escape: "", quote: "\"" }), schema=[TableField { name: "id", default_expr: None, data_type: Number(Int32), column_id: 0, computed_expr: None }, TableField { name: "name", default_expr: None, data_type: String, column_id: 1, computed_expr: None }, TableFiel
>  24
>  5
> ```

I have fixed and push it. but github didn't sync : (

**Comment by BohuTANG** [comment]
> I have fixed and push it. but github didn't sync : (

I have found this in my another repo, it looks strange.
Any suggestions? @everpcpc

**Comment by BohuTANG** [comment]
unit test:
```
failures:

---- schema_api_impl::test_meta_embedded stdout ----
thread 'schema_api_impl::test_meta_embedded' panicked at 'assertion failed: `(left == right)`
  left: `"Code: 2302, Text = Table 'tb2' already exists."`,
 right: `"TableAlreadyExists. Code: 2302, Text = Table 'tb2' already exists."`', /workspace/src/meta/api/src/schema_api_test_suite.rs:1479:13
stack backtrace:
   0:     0x55aea2df4541 - trace
```

**Pull request merged**
