### PR TITLE
federated query:show collation, show charset, timediff func

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

add federated query 

## Changelog

- New Feature

## Related Issues

Fixes #5835 #5851

### CODE REVIEW

**Review by BohuTANG — APPROVED** [review]

**Comment by TCeason** [comment]
I will fix the ci err.

**Comment by BohuTANG** [comment]
```
test parser::test_statements_in_legacy_suites ... FAILED
failures:
---- parser::test_statements_in_legacy_suites stdout ----
thread 'parser::test_statements_in_legacy_suites' panicked at 'Parser error should not exist in integration suites. Please add parser error cases to `common/ast/tests/it/parser.rs`: Code: 1005, displayText = error: 
  --> SQL:7:6
  |
4 | -- mydumper
5 | SET SQL_LOG_BIN=0;
6 | --charset and collation
7 | SHOW CHARSET;
  |      ^^^^^^^ expected `DATABASES`, `SCHEMAS`, `CREATE`, `TABLES`, `TABLE`, `SETTINGS`, or 5 more ...
```

https://github.com/datafuselabs/databend/runs/6813487398?check_suite_focus=true#step:3:1417

**Comment by TCeason** [comment]
> ```
> test parser::test_statements_in_legacy_suites ... FAILED
> failures:
> ---- parser::test_statements_in_legacy_suites stdout ----
> thread 'parser::test_statements_in_legacy_suites' panicked at 'Parser error should not exist in integration suites. Please add parser error cases to `common/ast/tests/it/parser.rs`: Code: 1005, displayText = error: 
>   --> SQL:7:6
>   |
> 4 | -- mydumper
> 5 | SET SQL_LOG_BIN=0;
> 6 | --charset and collation
> 7 | SHOW CHARSET;
>   |      ^^^^^^^ expected `DATABASES`, `SCHEMAS`, `CREATE`, `TABLES`, `TABLE`, `SETTINGS`, or 5 more ...
> ```
> 
> 
>      
>   
> 
> https://github.com/datafuselabs/databend/runs/6813487398?check_suite_focus=true#step:3:1417

Ok, we need let it support planner v2

**Comment by Xuanwo** [comment]
@mergify update

**Pull request merged**
