### PR TITLE
Feature: add DeleteByPrefix API in txn::op

### PR DESCRIPTION
**Pull request by lichuang**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Feature: add DeleteByPrefix API in txn::op

## Changelog

- New Feature

## Related Issues

Fixes [#issue 5929](https://github.com/datafuselabs/databend/issues/5929)

### CODE REVIEW

**Review by junnplus — APPROVED** [review]
Nice feature, I guess it's very useful for batch deletion of same prefix keys

**Comment by BohuTANG** [comment]
@ZeaLoVe Logic test failed, please take a look :)

**Comment by ZeaLoVe** [comment]
284EZtdjWo
cc @youngsofun  in Linux the case is success, but mac failed

**Comment by youngsofun** [comment]
@ZeaLoVe @BohuTANG maybe flaky cause by a potential  bug of HTTP handler in slow mac CI.  if not seen again I suggest just rerun for it,  because if it is HTTP handle it may fail other query .  I will try to  find the bug.

**Review by drmingdrmer — APPROVED** [review]
Cool~

**Pull request merged**
