### PR TITLE
[bench] build the SessionManager from the default config

### PR DESCRIPTION
**Pull request by PsiACE**
Signed-off-by: Chojan Shang <psiace@outlook.com>

I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

build the SessionManager from the default config, eliminate possible warnings and decouple from `SessionManagerBuilder`.

## Changelog

- Not for changelog (changelog entry is not required)

## Related Issues

Related #1866

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
Hi @PsiACE ,
Why move testing purposes function to `query/src/sessions/sessions_builder.rs`?

**Comment by PsiACE** [comment]
> Hi @PsiACE , Why move testing purposes function to `query/src/sessions/sessions_builder.rs`?

On the one hand, it is also used in bench, which always prompts a warning in vscode, and this move eliminates this problem.

On the other hand, this way, we can easily move the tests dir to tests/it to suit the new testing style.

Although it appears to be for testing purposes only, it makes sense to provide such a hack.

**Comment by BohuTANG** [comment]
I think `SessionManagerBuilder` is only for test, and some hacks in it like:
```
  pub fn create() -> SessionManagerBuilder {
        SessionManagerBuilder::inner_create(Config::default())
            .log_dir_with_relative("../tests/data/logs") -- here
    }
```
It is not a normal function, if we want to build the normal `SessionManager` we should use:
`SessionManager::from_conf` instead of `SessionManagerBuilder`

**Pull request merged**
