### PR TITLE
[bendctl] continue #2530 on the package subcommands

### PR DESCRIPTION
**Pull request by flaneur2020**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

this PR continue the work from #2530 on the package commands.

- make the package subcommands impl the Command trait
- change the return value of `about()` to `&'static str`, removes duplicated description string in the `about` fn and the clap definition 

## Changelog

- Improvement

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
LGTM.
But perhaps #2545  needs to be review&merged first :)

**Comment by BohuTANG** [comment]
Conflict files need resolved after #2545

**Comment by flaneur2020** [comment]
@BohuTANG thank you, i've merged the upstream and resolved the conflicts qwq

**Comment by ZhiHanZ** [comment]
great job, there is several refactors need to be done in bendctl
1. status.rs should separate local runtime trait relevant structures to comply with upcoming cluster runtime
2. generic functions, such as getter methods., download, unpack, and retry those things could be separated to another util package, currently it reside in package mode.

**Comment by ZhiHanZ** [comment]
Plus, similar to kubectl, there is a lot of examples in long help/about message, I think we should also incorporate examples into bendctl help message

**Comment by BohuTANG** [comment]
> great job, there is several refactors need to be done in bendctl
> 
> 1. status.rs should separate local runtime trait relevant structures to comply with upcoming cluster runtime
> 2. generic functions, such as getter methods., download, unpack, and retry those things could be separated to another util package, currently it reside in package mode.

We can issue them and  do it in other servals patches later , I think this patch is good to merge.
@ZhiHanZ  What do you think?

**Comment by ZhiHanZ** [comment]
\lgtm

**Review by ZhiHanZ — APPROVED** [review]

**Pull request merged**
