### PR TITLE
query(pipeline): support abort pipeline

### LINKED ISSUE #6173: Feature: support graceful abort insert query
**Summary**

Description for this feature.

- [ ] support graceful abort insert query
- [ ] show abort error messages to the client

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

support abort pipelines from context

```
databend > select count() from test;
+-------------+
| count()     |
+-------------+
| 13107200000 |
+-------------+
1 row in set (0.026 sec)

databend > insert into test select number from test;
^CCtrl-C -- query killed. Continuing normally.
ERROR 1152 (08S01): Code: 1043, displayText = Aborted query, because the server is shutting down or the query was killed (while in processor thread 31).
 
databend > select sum(number) from test;
^CCtrl-C -- query killed. Continuing normally.
ERROR 1152 (08S01): Code: 1043, displayText = Aborted query, because the server is shutting down or the query was killed (while in processor thread 31).


databend > show processlist;
+--------------------------------------+-------+-----------------+------+-------+----------+------------------+--------------+------------------------+-------------------------+-------------------------+--------------------------+---------------------+
| id                                   | type  | host            | user | state | database | extra_info       | memory_usage | dal_metrics_read_bytes | dal_metrics_write_bytes | scan_progress_read_rows | scan_progress_read_bytes | mysql_connection_id |
+--------------------------------------+-------+-----------------+------+-------+----------+------------------+--------------+------------------------+-------------------------+-------------------------+--------------------------+---------------------+
| e7427070-2b88-4bcb-81aa-465ab6c5613c | MySQL | 127.0.0.1:44500 | root | Query | default  | show processlist |            0 |                      0 |                       0 |                       0 |                        0 |                   9 |
+--------------------------------------+-------+-----------------+------+-------+----------+------------------+--------------+------------------------+-------------------------+-------------------------+--------------------------+---------------------+
1 row in set (0.020 sec)

databend > select count() from test;
+-------------+
| count()     |
+-------------+
| 13107200000 |
+-------------+
1 row in set (0.022 sec)
```

## Changelog
 
- Improvement
 
## Related Issues

Fixes  #6173

### CODE REVIEW

**Review by zhang2014 — APPROVED** [review]

**Review by Xuanwo — APPROVED** [review]

**Comment by sundy-li** [comment]
@youngsofun  Do you know the reason for failed unit tests?  May need your help.

**Comment by youngsofun** [comment]
```
  let async_runtime = ctx.get_storage_runtime();
            let executor = PipelineCompleteExecutor::try_create(async_runtime, pipeline)?;

  self.ctx
      .get_shared()
      .add_pipeline_executor(executor.get_inner());
```

seems executor and ctx forms a cycle reference

**Comment by BohuTANG** [comment]
@mergify update

**Comment by BohuTANG** [comment]
Re-run the test and servers::http::http_query_handlers::test_http_session failed again.

**Pull request merged**
