### PR TITLE
refactor: split common-meta-store

### PR DESCRIPTION
**Pull request by PsiACE**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

After this split:

- `query/common/meta` will be available as a common crate named `common-meta-store`

Related #6180

### CODE REVIEW

**Comment by PsiACE** [comment]
It seems that it lacks some tests and could be added if necessary.

**Comment by Xuanwo** [comment]
This crate provide very litter APIs, how about merging within meta?

**Review by drmingdrmer — APPROVED** [review]
LGTM

**Comment by PsiACE** [comment]
> This crate provide very litter APIs, how about merging within meta?

But which meta would be better for us to move it to? It looks like it's just a thin layer and the other meta components have clearer boundaries.

**Comment by drmingdrmer** [comment]
> This crate provide very litter APIs, how about merging within meta?

Not very sure about it. there may be dependency issues if moving it to an existent common/meta/* crate.

**Pull request merged**
