### PR TITLE
feat(planner): Push filter to sort

### LINKED ISSUE #10248: Feature(planner): Add rule to push filter under sort
**Summary**

Description for this feature.

ref: https://github.com/datafuselabs/databend/pull/10240#issuecomment-1445792205

### PR DESCRIPTION
**Pull request by johnhaxx7**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Ditto 

Closes #10248

### CODE REVIEW

**Comment by johnhaxx7** [comment]
@leiysky , @sundy-li  PTAL, thanks!

**Comment by johnhaxx7** [comment]
@leiysky , @sundy-li , PTAL

I was browsing heuristic rules again, and didn't find push filter to limit and merge limit, if it makes sense. I'll pick up those next. 

Query like this can be optimized as well:

```
mysql> explain select * from (select * from numbers(10) limit 3) limit 2;
+-------------------------------------------------------+
| explain                                               |
+-------------------------------------------------------+
| Limit                                                 |
| ├── limit: 2                                          |
| ├── offset: 0                                         |
| ├── estimated rows: 2.00                              |
| └── Limit                                             |
|     ├── limit: 3                                      |
|     ├── offset: 0                                     |
|     ├── estimated rows: 3.00                          |
|     └── TableScan                                     |
|         ├── table: default.system.numbers             |
|         ├── read rows: 3                              |
|         ├── read bytes: 24                            |
|         ├── partitions total: 1                       |
|         ├── partitions scanned: 1                     |
|         ├── push downs: [filters: [], limit: 3]       |
|         └── estimated rows: 10.00                     |
+-------------------------------------------------------+
```

**Comment by johnhaxx7** [comment]
ping on this, thanks!

**Review by sundy-li — APPROVED** [review]

**Comment by johnhaxx7** [comment]
thank you!

**Comment by johnhaxx7** [comment]
@mergify update

**Comment by johnhaxx7** [comment]
@mergify refresh

**Pull request merged**
