### PR TITLE
website: Migrate site to docusaurus

### PR DESCRIPTION
**Pull request by Xuanwo**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

This PR is a part of https://github.com/datafuselabs/databend/issues/3209

Please review this PR here: https://databend.vercel.app/

## Migrate plan

For now, I think there should be three stages:

image

### Stage 1

Stage before this PR gets merged.

At stage 1, we need to:

- [x] Fix markdown format
- [x] Fix social media and resource links (as @PsiACE said)
- [x] Figure out how to use docusaurus and add them into docs.
- [x] Catch up all changes to current docs (**heavy work here**)

### Stage 2

This PR getting merged means we already changed the databend website framework. However, until we change the `databend.rs` DNS to vercel, this change will not take effect.

- People will still see the site built by MkDocs hosted at `gh-pages`
- All changes to docs will not show up until we get into next stage.

At stage 2, we need to:

- Mirror the current design. (**I need help**)
- Figure out how to organize content (as @PsiACE said)

### Stage 3

The final stage. After DNS is changed, the site will be online and replace the current site.

At stage 3, we need to:

- Have a front-end design (as @BohuTANG said)

## Changelog

- Documentation

### CODE REVIEW

**Comment by Xuanwo** [comment]
In order to make this PR works correctly, I need the repo maintainer to config the vercel correctly.

**Comment by BohuTANG** [comment]
Thank you @Xuanwo .
It might make sense to wait with this PR until we have a front-end design, I've temporarily converted it to draft first.

**Review by PsiACE — COMMENTED** [review]
Thanks for the quick.

- The corresponding social media and resource links need to be updated.
- It looks like the RFCs can't be expanded, I wish it could be like Development.
- It looks like the content needs to be organised and re-filed to ensure that users can find what they want.

Also, how should we configure vercel.

**Comment by Xuanwo** [comment]
Hi, I'm thinking about the migration plan.

For now, I think there should be three stages:

image

## Stage 1

Stage before this PR gets merged.

At stage 1, we need to:

- Fix markdown format
- Fix social media and resource links (as @PsiACE said)
- Figure out how to use docusaurus and add them into docs.
- Catch up all changes to current docs (heavy work here)

## Stage 2

This PR getting merged means we already changed the databend website framework. However, until we change the `databend.rs` DNS to vercel, this change will not take effect.

- People will still see the site built by MkDocs hosted at `gh-pages`
- All changes to docs will not show up until we get into next stage.

At stage 2, we need to:

- Have a front-end design (as @BohuTANG said)
- Figure out how to organize content (as @PsiACE said)

## Stage 3

The final stage. After DNS is changed, the site will be online and replace the current site.

---

Is this plan looks good to you? @BohuTANG @PsiACE 

I prefer to make stage 1 as short as possible so that we don't need to speed too much time on syncing docs change.

**Comment by PsiACE** [comment]
> At stage 2, People will still see the site built by MkDocs hosted at gh-pages

It looks like mkdocs will miss the documentation update.

**Comment by Xuanwo** [comment]
> It looks like mkdocs will miss the documentation update.

Yep.

It's a trade-off. And it depends on how long we will keep in stage 2.

Either we sync changes between two website frameworks manually, or we just stop updates for MkDocs for the whole stage 2.

**Comment by PsiACE** [comment]
> Either we sync changes between two website frameworks manually, or we just stop updates for MkDocs for the whole stage 2.

We can stop updates for MkDocs. However, to reduce the wait, I recommend only figuring out how to organize content in stage 2 . The front-end design can be deferred to stage 4. Stage 2 will have only necessary and minor front-end modifications.

**Comment by Xuanwo** [comment]
> However, to reduce the wait, I recommend only figuring out how to organize content in stage 2 . The front-end design can be deferred to stage 4. Stage 2 will have only necessary and minor front-end modifications.

Makes sense.

**Comment by Xuanwo** [comment]
@PsiACE `rfcs` and `development` belong to different folders, so it's a bit tricky to make rfcs also expand under development. How about re-organizing the content in stage 2? Maybe we can put rfcs under development?

Except this issue, all comments (in stage 1) are resolved.

**Comment by PsiACE** [comment]
> Maybe we can put rfcs under development?
We can do this first.
> How about re-organizing the content in stage 2? 
Of course, we need to reconsider how to arrange it at stage 2.

**Comment by Xuanwo** [comment]
> We can do this first.

Done.

**Comment by Xuanwo** [comment]
This PR is synced with the latest commit at https://github.com/datafuselabs/databend/commit/9382849edf79f13e641c6f934dd2f61da2ff6d15 and finished all job defined in stage 1.

PTAL @PsiACE

**Review by PsiACE — APPROVED** [review]
It looks finished. I would approve of merging this PR first and then moving on to Stage 2.

cc @BohuTANG , What do you think about it?

**Comment by Xuanwo** [comment]
@BohuTANG PTAL

**Comment by BohuTANG** [comment]
Myabe we should remove `blog` menu until we have blogs

**Pull request merged**
