### PR TITLE
[deps] try to bump most deps

### PR DESCRIPTION
**Pull request by PsiACE**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

**main changes**

clap v3.0.0
sysinfo v0.22
azure-sdk rev-b5bf36b

## Changelog

- Build/Testing/CI
- Not for changelog (changelog entry is not required)

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by PsiACE** [comment]
arrow2 has had some relatively major changes. 

clickhuse_driver still needs some simple checks. ref https://github.com/datafuse-extras/clickhouse_driver/pull/4

so they will not appear in this PR.

**Comment by BohuTANG** [comment]
Does our CI can do the batch update?

**Comment by PsiACE** [comment]
> Does our CI can do the batch update?

It's hard, they can't update the dependency of having broken changes.

The options that I currently find workable are.

1. automatically update some of the dependencies by ci
2. manually update dependencies that have broken changes
3. periodically clean up the dependency tree (Monthly)

**Pull request merged**
