### PR TITLE
[metasrv]fix: list_databases return all tenants' databases

### LINKED ISSUE #3875: tenant not work in embedded meta
Use branch: https://github.com/datafuselabs/databend/pull/3867

1. Build:
```
make build-debug
```
2. Start with management mode:
```
./target/debug/databend-query --management-mode
```

3. Client
```
 mysql -uroot -h127.0.0.1  -P3307

mysql> SUDO USE TENANT 'tenant2';
Query OK, 0 rows affected (0.01 sec)
Read 0 rows, 0 B in 0.003 sec., 0 rows/sec., 0 B/sec.

mysql> CREATE DATABASE tenant2_db;
Query OK, 0 rows affected (0.36 sec)
Read 0 rows, 0 B in 0.349 sec., 0 rows/sec., 0 B/sec.

mysql> show databases;
+------------+
| Database   |
+------------+
| default    |
| system     |
| tenant2_db |
+------------+


mysql> SUDO USE TENANT 'tenant3';
Query OK, 0 rows affected (0.02 sec)
Read 0 rows, 0 B in 0.003 sec., 0 rows/sec., 0 B/sec.

mysql> show databases;
+------------+
| Database   |
+------------+
| default    |
| system     |
| tenant2_db |  -- tenant3 should not see it
+------------+

```

### PR DESCRIPTION
**Pull request by ariesdevil**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Fix bug that `list_databases` return all tenants' databases.

## Changelog

- Bug Fix

## Related Issues

Fixes #3875 

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Review by drmingdrmer — APPROVED** [review]
LGTM:D

**Review by BohuTANG — APPROVED** [review]
LGTM

**Review by drmingdrmer — APPROVED** [review]
Good again...

**Review by drmingdrmer — APPROVED** [review]

**Comment by drmingdrmer** [comment]
The priority queue is disabled in a free subscription...

**Comment by BohuTANG** [comment]
@mergify update

**Pull request merged**
