### PR TITLE
Add arithmetic support for interval type

### PR DESCRIPTION
**Pull request by junli1026**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

Add arithemetic support for interval type
>      Date16  [+|-] Interval
>      Date32  [+|-] Interval
>      DateTime32 [+|-] Interval

## Changelog

- New Feature

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

### CODE REVIEW

**Comment by sundy-li** [comment]
Hello, this implementation looks good but seems it's not efficient.

1. `try_get` is slow inside the loop.
2. There are lots of errors try return inside the loop.
3. There are lots of `match` inside the loop.

These will cause many branch predictions which make the function work slowly.

Do you have any plan to make it faster?

If the IntervalType is DayTime, seems we can use `array.apply` to apply arithmetic op in seconds with casting it into NativeTime.


```
mach interval_type {
    DataType::IntervalType(DayTime) => {
       //date  apply to seconds and +/- seconds
       
       //date32   apply to seconds and +/- seconds
       
       //datetime32  apply to seconds and +/- seconds
    
    }


  DataType::IntervalType(YearMonth) => {
       //date apply to NativeTime and +/- year month
         
       //date32  apply to NativeTime and +/- year month
       
       //datetime32  apply to NativeTime +/- plus year month
     
    }
}

```

**Comment by junli1026** [comment]
> Hello, this implementation looks good but seems it's not efficient.
> 
>     1. `try_get` is slow inside the loop.
> 
>     2. There are lots of errors try return inside the loop.
> 
>     3. There are lots of `match` inside the loop.
> 
> 
> These will cause many branch predictions which make the function work slowly.
> 
> Do you have any plan to make it faster?
> 
> If the IntervalType is DayTime, seems we can use `array.apply` to apply arithmetic op in seconds with casting it into NativeTime.
> 
> ```
> mach interval_type {
>     DataType::IntervalType(DayTime) => {
>        //date  apply to seconds and +/- seconds
>        
>        //date32   apply to seconds and +/- seconds
>        
>        //datetime32  apply to seconds and +/- seconds
>     
>     }
> 
> 
>   DataType::IntervalType(YearMonth) => {
>        //date apply to NativeTime and +/- year month
>          
>        //date32  apply to NativeTime and +/- year month
>        
>        //datetime32  apply to NativeTime +/- plus year month
>      
>     }
> }
> ```

Sure, will address. A quick question, do we have SIMD support for bit operation like left shift (<<) or right shift ?  (Maybe they can be achieved by Module or Multiple, but they are slower).   Because the DayTime is a 64bit, it may help if we have SIMD for left shift or right shift.

**Comment by sundy-li** [comment]
> Because the DayTime is a 64bit, it may help if we have SIMD for left shift or right shift.

We can use `array.i64().apply(|v| v << shift )`,  since the inner logic is very simple,  it'll be auto vectorized.

**Comment by sundy-li** [comment]
Some comments:

1. Can we refactor the function `interval_to_day_time` to store milliseconds as i64? Thus we don't need to do any shift operation.

2. If we use  `into_nonull_iter`, we should combine the bitmap of both arrays, there is no method named `combine_validities`, or we can introduce `pub fn binary<T, D, F>` from `arrow2`.

**Comment by junli1026** [comment]
>     1. Can we refactor the function `interval_to_day_time` to store milliseconds as i64? Thus we don't need to do any shift operation.

Sure. In this case we still need to to the division from milliseconds to seconds for DateTime, and from milliseconds to days for Date, right ? 

`
Current we have 
for Date
   val / 0x1_0000_0000 => days
for DateTime
   val / 0x1_0000_0000 * seconds_per_days => seconds 

After the change:
   for Date
      val / milliseconds_per_day => days
   for DateTime
      val / 1000 => seconds 
`
So that we save one multiplication operation, is that what you mean ?

**Comment by sundy-li** [comment]
> So that we save one multiplication operation, is that what you mean ?

Yes, this is not the reason related to performance, but aimed to be more clear to us.

And we can add alias functions to work with arithmetic with interval, such as `addDays`, `substractMonths`.

Did you check the implementation of ClickHouse?  I think you can check it because it did a great job.

Refer:

https://github.com/ClickHouse/ClickHouse/blob/dfbb1ffec0dd38b2480c16264b409d4fef6bfa1a/src/Functions/FunctionBinaryArithmetic.h#L999-L1014

https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionBinaryArithmetic.h#L608-L657

**Comment by junli1026** [comment]
> > So that we save one multiplication operation, is that what you mean ?
> 
> Yes, this is not the reason related to performance, but aimed to be more clear to us.
> 
> And we can add alias functions to work with arithmetic with interval, such as `addDays`, `substractMonths`.
> 
> Did you check the implementation of ClickHouse? I think you can check it because it did a great job.
> 
> Refer:
> 
> https://github.com/ClickHouse/ClickHouse/blob/dfbb1ffec0dd38b2480c16264b409d4fef6bfa1a/src/Functions/FunctionBinaryArithmetic.h#L999-L1014
> 
> https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionBinaryArithmetic.h#L608-L657

Thanks. maybe we can add a file named as "interval_function.rs" in the /sralars/dates folder, and reuse the function such as addDays, substractMonths both place.

**Comment by junli1026** [comment]
Hi @sundy-li  I am going to add the addYear/addMonth functions in another PR. If you are fine with this one, could you approve it ? Just don't want to make the PR too big.

**Review by sundy-li — APPROVED** [review]
LGTM

**Pull request merged**
