### PR TITLE
feat(storage): distributed execution of recluster

### PR DESCRIPTION
**Pull request by zhyass**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

`enable_distributed_recluster`: Enable distributed execution of table recluster, default is 0.

```
> set global enable_distributed_recluster=1;

SET
  GLOBAL enable_distributed_recluster = 1

0 row read in 0.601 sec. Processed 0 row, 0 B (0 row/s, 0 B/s)

> alter table test_order recluster final;

ALTER TABLE
  test_order recluster final

202563631 rows written in 431.972 sec. Processed 202.56 million rows, 115.82 GiB (468.93 thousand rows/s, 274.56 MiB/s)

>select * from clustering_information('zzq','test_order');

SELECT
  *
FROM
  clustering_information('zzq', 'test_order')

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│    cluster_key    │ total_block_count │ constant_block_count │ unclustered_block_count │ average_overlaps │ average_depth │   block_depth_histogram  │
│       String      │       UInt64      │        UInt64        │          UInt64         │      Float64     │    Float64    │          Variant         │
├───────────────────┼───────────────────┼──────────────────────┼─────────────────────────┼──────────────────┼───────────────┼──────────────────────────┤
│ (id, insert_time) │               529 │                   91 │                       0 │          15.8261 │       16.8261 │ {"00001":437,"00128":92} │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
1 row read in 1.334 sec. Processed 1 row, 448 B (0.75 row/s, 335 B/s)
```

```
> set global enable_distributed_recluster=0;

SET
  GLOBAL enable_distributed_recluster = 0

0 row read in 0.601 sec. Processed 0 row, 0 B (0 row/s, 0 B/s)

> alter table test_order recluster final;

ALTER TABLE
  test_order recluster final

222679181 rows written in 939.860 sec. Processed 222.68 million rows, 129.19 GiB (236.93 thousand rows/s, 140.76 MiB/s)

> select * from clustering_information('zzq','test_order');

SELECT
  *
FROM
  clustering_information('zzq', 'test_order')

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│    cluster_key    │ total_block_count │ constant_block_count │ unclustered_block_count │ average_overlaps │ average_depth │   block_depth_histogram  │
│       String      │       UInt64      │        UInt64        │          UInt64         │      Float64     │    Float64    │          Variant         │
├───────────────────┼───────────────────┼──────────────────────┼─────────────────────────┼──────────────────┼───────────────┼──────────────────────────┤
│ (id, insert_time) │               543 │                   80 │                       0 │          11.9337 │       12.9337 │ {"00001":462,"00128":81} │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
1 row read in 1.886 sec. Processed 1 row, 448 B (0.03 row/s, 12 B/s)
```

- Closes #issue

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13048)

### CODE REVIEW

**Comment by zhyass** [comment]
Get hang, when executing a distributed recluster(32 Gb).
```
export BUILD_PROFILE=release
./scripts/ci/deploy/databend-query-cluster-3-nodes.sh
```
```sql
drop table if exists test_order all;
drop table if exists random_source all;
create table test_order (
    id bigint,
    id1 bigint,
    id2 bigint,
    id3 bigint,
    id4 bigint,
    id5 bigint,
    id6 bigint,
    id7 bigint,
    
    s1 varchar,
    s2 varchar,
    s3 varchar,
    s4 varchar,
    s5 varchar,
    s6 varchar,
    s7 varchar,
    s8 varchar,
    s9 varchar,
    s10 varchar,
    s11 varchar,
    s12 varchar,
    s13 varchar,
    
    d1 DECIMAL(20, 8),
    d2 DECIMAL(20, 8),
    d3 DECIMAL(20, 8),
    d4 DECIMAL(20, 8),
    d5 DECIMAL(20, 8),
    d6 DECIMAL(30, 8),
    d7 DECIMAL(30, 8),
    d8 DECIMAL(30, 8),
    d9 DECIMAL(30, 8),
    d10 DECIMAL(30, 8),
    
    insert_time datetime,
    insert_time1 datetime,
    insert_time2 datetime,
    insert_time3 datetime,
    
    i int
) CLUSTER BY(id,insert_time);

create table random_source (
    id bigint,
    id1 bigint,
    id2 bigint,
    id3 bigint,
    id4 bigint,
    id5 bigint,
    id6 bigint,
    id7 bigint,
    
    s1 varchar,
    s2 varchar,
    s3 varchar,
    s4 varchar,
    s5 varchar,
    s6 varchar,
    s7 varchar,
    s8 varchar,
    s9 varchar,
    s10 varchar,
    s11 varchar,
    s12 varchar,
    s13 varchar,
    
    d1 DECIMAL(20, 8),
    d2 DECIMAL(20, 8),
    d3 DECIMAL(20, 8),
    d4 DECIMAL(20, 8),
    d5 DECIMAL(20, 8),
    d6 DECIMAL(30, 8),
    d7 DECIMAL(30, 8),
    d8 DECIMAL(30, 8),
    d9 DECIMAL(30, 8),
    d10 DECIMAL(30, 8),
    
    insert_time datetime,
    insert_time1 datetime,
    insert_time2 datetime,
    insert_time3 datetime,
    
    i int
) Engine = Random;

insert into test_order select * from random_source limit 25000000;

insert into test_order select * from random_source limit 25000000;

insert into test_order select * from random_source limit 25000000;

insert into test_order select * from random_source limit 25000000;

set global enable_distributed_recluster=1;

set global recluster_block_size=3120455953;

alter table test_order recluster final;
```
Get hang:
```
mysql> show processlist;
+--------------------------------------+-------+-----------------+------+---------+----------+----------------------------------------+--------------+-----------------+------------------+-------------------------+--------------------------+---------------------+------+----------------------------------------------------------+
| id                                   | type  | host            | user | command | database | extra_info                             | memory_usage | data_read_bytes | data_write_bytes | scan_progress_read_rows | scan_progress_read_bytes | mysql_connection_id | time | status                                                   |
+--------------------------------------+-------+-----------------+------+---------+----------+----------------------------------------+--------------+-----------------+------------------+-------------------------+--------------------------+---------------------+------+----------------------------------------------------------+
| 79d8778a-d730-4a3d-95ea-01887b50652e | MySQL | 127.0.0.1:41636 | root | Query   | default  | ALTER TABLE test_order RECLUSTER FINAL |    985515485 |               0 |                0 |               222660350 |              98256944302 |                   9 |  227 | commit mutation success after 0 retries, which took 5 ms |
| 0d01ebcb-49bc-438b-91d0-cd2f2136e804 | MySQL | 127.0.0.1:54584 | root | Query   | default  | SHOW PROCESSLIST                       |         1108 |               0 |                0 |                       0 |                       64 |                  10 |    0 | executing pipeline                                       |
+--------------------------------------+-------+-----------------+------+---------+----------+----------------------------------------+--------------+-----------------+------------------+-------------------------+--------------------------+---------------------+------+----------------------------------------------------------+
2 rows in set (0.06 sec)
Read 2 rows, 698.00 B in 0.038 sec., 52.35 rows/sec., 17.84 KiB/sec.
```

**Comment by zhyass** [comment]
Sometimes, get the follow error
```
mysql> alter table test_order recluster final;
ERROR 1105 (HY000): Unimplemented. Code: 1002, Text = ExchangeSource is unimplemented.

mysql> show processlist;
+--------------------------------------+-------+-----------------+------+---------+----------+----------------------------------------+--------------+-----------------+------------------+-------------------------+--------------------------+---------------------+------+-----------------------------------+
| id                                   | type  | host            | user | command | database | extra_info                             | memory_usage | data_read_bytes | data_write_bytes | scan_progress_read_rows | scan_progress_read_bytes | mysql_connection_id | time | status                            |
+--------------------------------------+-------+-----------------+------+---------+----------+----------------------------------------+--------------+-----------------+------------------+-------------------------+--------------------------+---------------------+------+-----------------------------------+
| 6058be02-4377-4d1c-a23a-1c029fa41c34 | MySQL | [127.0.0.1:50264](http://127.0.0.1:50264/) | root | Query   | default  | SHOW PROCESSLIST                       |            0 |               0 |                0 |                       0 |                       64 |                   9 |    0 | executing pipeline                |
| cac6ca06-e8dd-4c0b-9d97-d50ef28eabf0 | MySQL | [127.0.0.1:39336](http://127.0.0.1:39336/) | root | Query   | default  | ALTER TABLE test_order RECLUSTER FINAL |    170913195 |               0 |                0 |               201431680 |              87719141667 |                   9 |  416 | recluster: begin to run recluster |
+--------------------------------------+-------+-----------------+------+---------+----------+----------------------------------------+--------------+-----------------+------------------+-------------------------+--------------------------+---------------------+------+-----------------------------------+
2 rows in set (0.01 sec)
Read 2 rows, 677.00 B in 0.007 sec., 295.71 rows/sec., 97.75 KiB/sec.
```
```
2023-10-17T07:00:00.660028Z ERROR databend_query::servers::mysql::writers::query_result_writer: src/query/service/src/servers/mysql/writers/[query_result_writer.rs:309](http://query_result_writer.rs:309/) OnQuery Error: Unimplemented. Code: 1002, Text = ExchangeSource is unimplemented.

   0: common_exception::exception_backtrace::capture
             at src/common/exception/src/[exception_backtrace.rs:72](http://exception_backtrace.rs:72/):17
   1: common_exception::exception_code::<impl common_exception::exception::ErrorCode>::Unimplemented
             at src/common/exception/src/[exception_code.rs:35](http://exception_code.rs:35/):30
   2: databend_query::api::rpc::exchange::exchange_manager::QueryCoordinator::subscribe_fragment
             at src/query/service/src/api/rpc/exchange/[exchange_manager.rs:638](http://exchange_manager.rs:638/):13
   3: databend_query::api::rpc::exchange::exchange_manager::DataExchangeManager::get_fragment_source
             at src/query/service/src/api/rpc/exchange/[exchange_manager.rs:396](http://exchange_manager.rs:396/):17
   4: databend_query::pipelines::pipeline_builder::PipelineBuilder::build_exchange_source
             at src/query/service/src/pipelines/[pipeline_builder.rs:2172](http://pipeline_builder.rs:2172/):25
   5: databend_query::pipelines::pipeline_builder::PipelineBuilder::build_pipeline
             at src/query/service/src/pipelines/[pipeline_builder.rs:264](http://pipeline_builder.rs:264/):53
   6: databend_query::pipelines::pipeline_builder::PipelineBuilder::build_recluster_sink
             at src/query/service/src/pipelines/[pipeline_builder.rs:936](http://pipeline_builder.rs:936/):9
      databend_query::pipelines::pipeline_builder::PipelineBuilder::build_pipeline
             at src/query/service/src/pipelines/[pipeline_builder.rs:298](http://pipeline_builder.rs:298/):17
   7: databend_query::pipelines::pipeline_builder::PipelineBuilder::finalize
             at src/query/service/src/pipelines/[pipeline_builder.rs:229](http://pipeline_builder.rs:229/):9
   8: databend_query::api::rpc::exchange::exchange_manager::FragmentCoordinator::prepare_pipeline
             at src/query/service/src/api/rpc/exchange/[exchange_manager.rs:816](http://exchange_manager.rs:816/):44
   9: databend_query::api::rpc::exchange::exchange_manager::QueryCoordinator::prepare_pipeline
             at src/query/service/src/api/rpc/exchange/[exchange_manager.rs:578](http://exchange_manager.rs:578/):17
      databend_query::api::rpc::exchange::exchange_manager::DataExchangeManager::init_query_fragments_plan
             at src/query/service/src/api/rpc/exchange/[exchange_manager.rs:204](http://exchange_manager.rs:204/):17
  10: databend_query::api::rpc::exchange::exchange_manager::DataExchangeManager::commit_actions::{{closure}}::{{closure}}
             at src/query/service/src/api/rpc/exchange/[exchange_manager.rs:292](http://exchange_manager.rs:292/):9
      <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[framed.rs:49](http://framed.rs:49/):27
      async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:184](http://frame.rs:184/):17
      std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/[local.rs:270](http://local.rs:270/):16
      std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/[local.rs:246](http://local.rs:246/):9
  11: async_backtrace::frame::active_frame::with
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:81](http://frame.rs:81/):9
      async_backtrace::frame::Frame::in_scope
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:180](http://frame.rs:180/):13
      <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[framed.rs:49](http://framed.rs:49/):9
      databend_query::api::rpc::exchange::exchange_manager::DataExchangeManager::commit_actions::{{closure}}
             at src/query/service/src/api/rpc/exchange/[exchange_manager.rs:264](http://exchange_manager.rs:264/):5
      databend_query::schedulers::scheduler::build_distributed_pipeline::{{closure}}::{{closure}}
             at src/query/service/src/schedulers/[scheduler.rs:112](http://scheduler.rs:112/):10
      <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[framed.rs:49](http://framed.rs:49/):27
      async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:184](http://frame.rs:184/):17
      std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/[local.rs:270](http://local.rs:270/):16
      std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/[local.rs:246](http://local.rs:246/):9
  12: async_backtrace::frame::active_frame::with
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:81](http://frame.rs:81/):9
      async_backtrace::frame::Frame::in_scope
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:180](http://frame.rs:180/):13
      <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[framed.rs:49](http://framed.rs:49/):9
      databend_query::schedulers::scheduler::build_distributed_pipeline::{{closure}}
             at src/query/service/src/schedulers/[scheduler.rs:96](http://scheduler.rs:96/):1
      databend_query::schedulers::scheduler::build_query_pipeline_without_render_result_set::{{closure}}::{{closure}}
             at src/query/service/src/schedulers/[scheduler.rs:69](http://scheduler.rs:69/):65
      <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[framed.rs:49](http://framed.rs:49/):27
      async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:184](http://frame.rs:184/):17
      std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/[local.rs:270](http://local.rs:270/):16
      std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/[local.rs:246](http://local.rs:246/):9
  13: async_backtrace::frame::active_frame::with
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:81](http://frame.rs:81/):9
      async_backtrace::frame::Frame::in_scope
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:180](http://frame.rs:180/):13
      <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[framed.rs:49](http://framed.rs:49/):9
      databend_query::schedulers::scheduler::build_query_pipeline_without_render_result_set::{{closure}}
             at src/query/service/src/schedulers/[scheduler.rs:55](http://scheduler.rs:55/):1
  14: <databend_query::interpreters::interpreter_table_recluster::ReclusterTableInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute2::{{closure}}::{{closure}}
             at src/query/service/src/interpreters/[interpreter_table_recluster.rs:165](http://interpreter_table_recluster.rs:165/):22
      <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[framed.rs:49](http://framed.rs:49/):27
      async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:184](http://frame.rs:184/):17
      std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/[local.rs:270](http://local.rs:270/):16
      std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/[local.rs:246](http://local.rs:246/):9
  15: async_backtrace::frame::active_frame::with
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:81](http://frame.rs:81/):9
      async_backtrace::frame::Frame::in_scope
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:180](http://frame.rs:180/):13
      <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[framed.rs:49](http://framed.rs:49/):9
      <databend_query::interpreters::interpreter_table_recluster::ReclusterTableInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute2::{{closure}}
             at src/query/service/src/interpreters/[interpreter_table_recluster.rs:69](http://interpreter_table_recluster.rs:69/):5
  16: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/[future.rs:125](http://future.rs:125/):9
      databend_query::interpreters::interpreter::Interpreter::execute::{{closure}}::{{closure}}
             at src/query/service/src/interpreters/[interpreter.rs:55](http://interpreter.rs:55/):51
      <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[framed.rs:49](http://framed.rs:49/):27
      async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:184](http://frame.rs:184/):17
      std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/[local.rs:270](http://local.rs:270/):16
      std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/[local.rs:246](http://local.rs:246/):9
  17: async_backtrace::frame::active_frame::with
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:81](http://frame.rs:81/):9
      async_backtrace::frame::Frame::in_scope
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:180](http://frame.rs:180/):13
      <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[framed.rs:49](http://framed.rs:49/):9
      databend_query::interpreters::interpreter::Interpreter::execute::{{closure}}
             at src/query/service/src/interpreters/[interpreter.rs:45](http://interpreter.rs:45/):5
  18: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/[future.rs:125](http://future.rs:125/):9
      databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorkerBase::exec_query::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at src/query/service/src/servers/mysql/[mysql_interactive_worker.rs:395](http://mysql_interactive_worker.rs:395/):76
      <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/minitrace-0.5.1/src/[future.rs:121](http://future.rs:121/):19
  19: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[framed.rs:49](http://framed.rs:49/):27
      async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:184](http://frame.rs:184/):17
      std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/[local.rs:270](http://local.rs:270/):16
      std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/[local.rs:246](http://local.rs:246/):9
  20: async_backtrace::frame::active_frame::with
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:81](http://frame.rs:81/):9
      async_backtrace::frame::Frame::in_scope
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[frame.rs:180](http://frame.rs:180/):13
      <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/async-backtrace-0.2.5/src/[framed.rs:49](http://framed.rs:49/):9
      tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/[core.rs:223](http://core.rs:223/):17
      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/loom/std/[unsafe_cell.rs:14](http://unsafe_cell.rs:14/):9
  21: tokio::runtime::task::core::Core<T,S>::poll
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/[core.rs:212](http://core.rs:212/):13
  22: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/[harness.rs:476](http://harness.rs:476/):19
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/[unwind_safe.rs:271](http://unwind_safe.rs:271/):9
  23: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/[panicking.rs:500](http://panicking.rs:500/):40
      std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/[panicking.rs:464](http://panicking.rs:464/):19
  24: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/[panic.rs:142](http://panic.rs:142/):14
      tokio::runtime::task::harness::poll_future
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/[harness.rs:464](http://harness.rs:464/):18
  25: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/[harness.rs:198](http://harness.rs:198/):27
  26: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/[harness.rs:152](http://harness.rs:152/):15
  27: tokio::runtime::task::raw::RawTask::poll
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/[raw.rs:200](http://raw.rs:200/):18
      tokio::runtime::task::LocalNotified<S>::run
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/[mod.rs:394](http://mod.rs:394/):9
      tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/[worker.rs:487](http://worker.rs:487/):21
      tokio::runtime::coop::with_budget
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/[coop.rs:107](http://coop.rs:107/):5
      tokio::runtime::coop::budget
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/[coop.rs:73](http://coop.rs:73/):5
      tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/[worker.rs:463](http://worker.rs:463/):9
  28: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/[worker.rs:426](http://worker.rs:426/):24
      tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/[worker.rs:406](http://worker.rs:406/):17
      tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/macros/[scoped_tls.rs:61](http://scoped_tls.rs:61/):9
  29: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/[worker.rs:403](http://worker.rs:403/):5
  30: tokio::runtime::scheduler::multi_thread::worker::block_in_place::{{closure}}::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/[worker.rs:343](http://worker.rs:343/):41
      <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/[task.rs:42](http://task.rs:42/):21
  31: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/[core.rs:223](http://core.rs:223/):17
      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/loom/std/[unsafe_cell.rs:14](http://unsafe_cell.rs:14/):9
  32: tokio::runtime::task::core::Core<T,S>::poll
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/[core.rs:212](http://core.rs:212/):13
  33: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/nuan/.cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/[harness.rs:476](http://harness.rs:476/):19
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/[unwind_safe.rs:271](http://unwind_safe.rs:271/):9
  34: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/[panicking.rs:500](http://panicking.rs:500/):40
      std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/[panicking.rs:464](http://panicking.rs:464/):19
  35: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/librar
```

**Comment by dantengsky** [comment]
@zhyass  the following logic test failed.

Tests relying on `system.metrics` may cause flaky results. Consider replacing or just removing the assertion?

https://github.com/datafuselabs/databend/actions/runs/6556258359/job/17806132271?pr=13048#step:4:171

~~~
Completed Http test for file: tests/sqllogictests/suites/mode/cluster/distributed_copy_into_table.test ✅ (258.495184432s)
Test finished, fail fast enabled, 1 out of 567 records failed to run
0: query result mismatch:
[SQL] select count()>1 from system.metrics where metric='fuse_recluster_block_nums_to_read_total'
[Diff] (-expected|+actual)
-   1
+   0
at tests/sqllogictests/suites/mode/cluster/distributed_recluster.sql:25
Error: SelfError("sqllogictest failed")

~~~

**Comment by zhyass** [comment]
> @zhyass the following logic test failed.
> 
Thanks, the flaky test has been removed.

**Review by sundy-li — APPROVED** [review]

**Review by zhang2014 — APPROVED** [review]

**Review by dantengsky — APPROVED** [review]

**Pull request merged**
