### PR TITLE
ISSUE-2909: Add interpreter interceptor for metrics intercepte

### LINKED ISSUE #2909: Add a interceptor for the interpreters wrapping query log operation
# Summary

interpreter_interceptor.rs:
1. Returns Interpreter trait

### PR DESCRIPTION
**Pull request by BohuTANG**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

1. This PR introduces a new `InterceptorInterpreter` for interceptor all the `Interpreter` trait object, this is use for query_log #2868.

```
let stream = interceptor.execute(....);
stream.iter() ...
interceptor.finish() -- we will write metrics to query_log
```
2. Enable interpreter_select_test.rs 

## Changelog

- Improvement

## Related Issues

Fixes #2909

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by sundy-li** [comment]
Git have conflicts.

**Comment by BohuTANG** [comment]
> Git has conflicts.

Thank you sundy.
Updated

**Comment by sundy-li** [comment]
LGTM.

But I did not see any place to call fn `finish`. Shall we add calling finish in http/clickhouse/mysql servers in this PR?

**Comment by BohuTANG** [comment]
> LGTM.
> 
> But I did not see any place to call fn `finish`. Shall we add calling finish in http/clickhouse/mysql servers in this PR?

Not yet, should after #2868

**Pull request merged**
