### PR TITLE
feat(sqllogictests): Add no-fail-fast support

### PR DESCRIPTION
**Pull request by xudong963**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Closes #issue

### CODE REVIEW

**Comment by Xuanwo** [comment]
Please add a args for this. We want CI to fail fast so they can exit more quick.

**Comment by xudong963** [comment]
> Please add an args for this. We want CI to fail fast so they can exit more quick.
> 
> For example:
> 
> ```
> > cargo test --help
>     --no-fail-fast              Run all tests regardless of failure
> ```

Make sense. cc @zhang2014 @sundy-li  Any thoughts?

**Comment by Xuanwo** [comment]
We can change the workflow files if we have special needs during refactor. And change it back before merging.

**Review by sundy-li — APPROVED** [review]

**Comment by sundy-li** [comment]
>  We want CI to fail fast so they can exit more quickly.
Ok in online ci.

In local dev, we can pass this arg to have all errors.

**Review by Xuanwo — APPROVED** [review]

**Pull request merged**
