### PR TITLE
change default password type to DoubleSha1Password

### LINKED ISSUE #4326: create user can not login
```
mysql -h127.0.0.1 -P3307 -uroot
create user 'wubx'@'%' identified by 'databend';
grant all privileges on *.* to 'wubx';
```

The account wubx can't login to Databend.

Maybe relevance https://github.com/datafuselabs/databend/issues/4179

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

change default  password type to DoubleSha1Password,  so user create without specifying auth type can login with mysql client.

## Related Issues

Fixes #4326

part of 
https://github.com/datafuselabs/databend/issues/4351

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by youngsofun** [comment]
seems not related to this pr:

```
09_0008_fuse_optimize_table:                                            2022-03-08T04:24:38.462201Z  INFO databend_query::servers::mysql::mysql_handler: MySQL connection coming: Ok(127.0.0.1:50483)
2022-03-08T04:24:38.47[1318](https://github.com/datafuselabs/databend/runs/5459431198?check_suite_focus=true#step:3:1318)Z  INFO databend_query::catalogs::impls::database_catalog: Drop database from req:DropDatabaseReq { if_exists: true, tenant: "test_tenant", db: "db_09_0008" }
2022-03-08T04:24:38.479975Z  INFO databend_query::catalogs::impls::database_catalog: Create database from req:CreateDatabaseReq { if_not_exists: false, tenant: "test_tenant", db: "db_09_0008", meta: DatabaseMeta { engine: "", engine_options: {}, options: {}, created_on: 2022-03-08T04:24:38.478927Z } }
2022-03-08T04:24:38.481588Z ERROR databend_query::catalogs::impls::mutable_catalog: db name: db_09_0008, engine: 
2022-03-08T04:24:38.509506Z  INFO databend_query::catalogs::impls::database_catalog: Create table from req:CreateTableReq { if_not_exists: false, tenant: "test_tenant", db: "db_09_0008", table: "t", table_meta: TableMeta { schema: DataSchema { fields: [DataField { name: "a", data_type: UInt64, nullable: true }], metadata: {} }, engine: "FUSE", engine_options: {}, options: {"database_id": "29"}, created_on: 2022-03-08T04:24:38.507962Z } }
2022-03-08T04:24:38.510151Z  INFO common_meta_raft_store::state_machine::sm_meta_api_impl: create table: db_09_0008: "t"
2022-03-08T04:24:38.835933Z  INFO databend_query::catalogs::impls::database_catalog: Create table from req:CreateTableReq { if_not_exists: false, tenant: "test_tenant", db: "db_09_0008", table: "m", table_meta: TableMeta { schema: DataSchema { fields: [DataField { name: "a", data_type: UInt64, nullable: true }], metadata: {} }, engine: "Memory", engine_options: {}, options: {}, created_on: 2022-03-08T04:24:38.834858Z } }
2022-03-08T04:24:38.836580Z  INFO common_meta_raft_store::state_machine::sm_meta_api_impl: create table: db_09_0008: "m"
2022-03-08T04:24:38.885623Z  INFO databend_query::catalogs::impls::database_catalog: Drop table from req:DropTableReq { if_exists: false, tenant: "test_tenant", db: "db_09_0008", table: "m" }
2022-03-08T04:24:38.895752Z  INFO databend_query::catalogs::impls::database_catalog: Create table from req:CreateTableReq { if_not_exists: false, tenant: "test_tenant", db: "db_09_0008", table: "m", table_meta: TableMeta { schema: DataSchema { fields: [DataField { name: "a", data_type: UInt64, nullable: true }], metadata: {} }, engine: "Fuse", engine_options: {}, options: {"database_id": "29"}, created_on: 2022-03-08T04:24:38.894166Z } }
2022-03-08T04:24:38.896314Z  INFO common_meta_raft_store::state_machine::sm_meta_api_impl: create table: db_09_0008: "m"
2022-03-08T04:24:39.106051Z  INFO databend_query::catalogs::impls::database_catalog: Drop table from req:DropTableReq { if_exists: false, tenant: "test_tenant", db: "db_09_0008", table: "m" }
2022-03-08T04:24:39.109604Z ERROR databend_query::servers::mysql::writers::query_result_writer: OnQuery Error: Code: 1002, displayText = EOF while parsing a value at line 1 column 0.

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: common_exception::exception::ErrorCode::from_std_error
   3: common_exception::exception_into::<impl core::convert::From<serde_json::error::Error> for common_exception::exception::ErrorCode>::from
   4: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
   5: databend_query::storages::fuse::io::meta_readers::<impl databend_query::storages::fuse::cache::local_cache::Loader<V> for T>::load::{{closure}}
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
   8: databend_query::storages::fuse::cache::local_cache::CachedReader<V,L>::load::{{closure}}
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: databend_query::storages::fuse::cache::local_cache::CachedReader<V,L>::read::{{closure}}
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: databend_query::storages::fuse::io::meta_readers::<impl databend_query::storages::fuse::cache::local_cache::CachedReader<databend_query::storages::fuse::meta::snapshot::TableSnapshot,&databend_query::sessions::query_ctx::QueryContext>>::read_snapshot_history::{{closure}}
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: databend_query::storages::fuse::operations::optimize::<impl databend_query::storages::fuse::fuse_table::FuseTable>::do_optimize::{{closure}}
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <databend_query::storages::fuse::fuse_table::FuseTable as databend_query::storages::storage_table::Table>::optimize::{{closure}}
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: <core::pin::Pin<P> as core::future::future::Future>::poll
  19: <databend_query::interpreters::interpreter_table_drop::DropTableInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute::{{closure}}
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  21: <core::pin::Pin<P> as core::future::future::Future>::poll
  22: <databend_query::interpreters::interpreter_factory_interceptor::InterceptorInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute::{{closure}}
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  24: <core::pin::Pin<P> as core::future::future::Future>::poll
  25: databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorkerBase<W>::exec_query::{{closure}}::{{closure}}::{{closure}}
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  27: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
  28: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  29: tokio::runtime::task::core::CoreStage<T>::poll
  30: tokio::runtime::task::harness::poll_future::{{closure}}
  31: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  32: std::panicking::try::do_call
  33: ___rust_try
  34: std::panicking::try
  35: std::panic::catch_unwind
  36: tokio::runtime::task::harness::poll_future
  37: tokio::runtime::task::harness::Harness<T,S>::poll_inner
  38: tokio::runtime::task::harness::Harness<T,S>::poll
  39: tokio::runtime::task::raw::poll
  40: tokio::runtime::task::raw::RawTask::poll
  41: tokio::runtime::task::LocalNotified<S>::run
  42: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
  43: tokio::coop::with_budget::{{closure}}
  44: std::thread::local::LocalKey<T>::try_with
  45: std::thread::local::LocalKey<T>::with
  46: tokio::runtime::thread_pool::worker::Context::run_task
  47: tokio::runtime::thread_pool::worker::Context::run
  48: tokio::runtime::thread_pool::worker::run::{{closure}}
  49: tokio::macros::scoped_tls::ScopedKey<T>::set
  50: tokio::runtime::thread_pool::worker::run
  51: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
  52: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  53: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
  54: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  55: tokio::runtime::task::core::CoreStage<T>::poll
  56: tokio::runtime::task::harness::poll_future::{{closure}}
  57: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  58: std::panicking::try::do_call
  59: ___rust_try
  60: std::panicking::try
  61: std::panic::catch_unwind
  62: tokio::runtime::task::harness::poll_future
  63: tokio::runtime::task::harness::Harness<T,S>::poll_inner
  64: tokio::runtime::task::harness::Harness<T,S>::poll
  65: tokio::runtime::task::raw::poll
  66: tokio::runtime::task::raw::RawTask::poll
  67: tokio::runtime::task::UnownedTask<S>::run
  68: tokio::runtime::blocking::pool::Task::run
  69: tokio::runtime::blocking::pool::Inner::run
  70: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
  71: std::sys_common::backtrace::__rust_begin_short_backtrace
  72: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
  73: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  74: std::panicking::try::do_call
  75: ___rust_try
  76: std::panicking::try
  77: std::panic::catch_unwind
  78: std::thread::Builder::spawn_unchecked_::{{closure}}
  79: core::ops::function::FnOnce::call_once{{vtable.shim}}
  80: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/8769f4ef2fe1efddd1f072485f97f568e7328f79/library/alloc/src/boxed.rs:1854:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/8769f4ef2fe1efddd1f072485f97f568e7328f79/library/alloc/src/boxed.rs:1854:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/8769f4ef2fe1efddd1f072485f97f568e7328f79/library/std/src/sys/unix/thread.rs:108:17
  81: __pthread_start

2022-03-08T04:24:39.118831Z  INFO databend_query::catalogs::impls::database_catalog: Drop table from req:DropTableReq { if_exists: false, tenant: "test_tenant", db: "db_09_0008", table: "t" }
2022-03-08T04:24:39.[1357](https://github.com/datafuselabs/databend/runs/5459431198?check_suite_focus=true#step:3:1357)39Z  INFO databend_query::catalogs::impls::database_catalog: Drop database from req:DropDatabaseReq { if_exists: false, tenant: "test_tenant", db: "db_09_0008" }
[ FAIL ] - result differs with:
--- /Users/runner/work/databend/databend/tests/suites/0_stateless/09_fuse_engine/09_0008_fuse_optimize_table.result	2022-03-08 04:19:49.000000000 +0000
+++ /Users/runner/work/databend/databend/tests/suites/0_stateless/09_fuse_engine/09_0008_fuse_optimize_table.stdout	2022-03-08 04:24:39.000000000 +0000
@@ -17,3 +17,4 @@
 8
 9
 10
+ERROR 1105 (HY000) at line 56: Code: 1002, displayText = EOF while parsing a value at line 1 column 0.

09_0009_remote_explain:                                                 2022-03-08T04:24:39.228184Z  INFO databend_query::servers::mysql::mysql_handler: MySQL connection coming: Ok(127.0.0.1:50484)
2022-03-08T04:24:39.237
```

**Comment by BohuTANG** [comment]
> https://github.com/datafuselabs/databend/runs/5459431198?check_suite_focus=true
> 
> seems not related to this pr:
> 
> ```
> 09_0008_fuse_optimize_table:                                            2022-03-08T04:24:38.462201Z  INFO databend_query::servers::mysql::mysql_handler: MySQL connection coming: Ok(127.0.0.1:50483)
> 2022-03-08T04:24:38.47[1318](https://github.com/datafuselabs/databend/runs/5459431198?check_suite_focus=true#step:3:1318)Z  INFO databend_query::catalogs::impls::database_catalog: Drop database from req:DropDatabaseReq { if_exists: true, tenant: "test_tenant", db: "db_09_0008" }
> 2022-03-08T04:24:38.479975Z  INFO databend_query::catalogs::impls::database_catalog: Create database from req:CreateDatabaseReq { if_not_exists: false, tenant: "test_tenant", db: "db_09_0008", meta: DatabaseMeta { engine: "", engine_options: {}, options: {}, created_on: 2022-03-08T04:24:38.478927Z } }
> 2022-03-08T04:24:38.481588Z ERROR databend_query::catalogs::impls::mutable_catalog: db name: db_09_0008, engine: 
> 2022-03-08T04:24:38.509506Z  INFO databend_query::catalogs::impls::database_catalog: Create table from req:CreateTableReq { if_not_exists: false, tenant: "test_tenant", db: "db_09_0008", table: "t", table_meta: TableMeta { schema: DataSchema { fields: [DataField { name: "a", data_type: UInt64, nullable: true }], metadata: {} }, engine: "FUSE", engine_options: {}, options: {"database_id": "29"}, created_on: 2022-03-08T04:24:38.507962Z } }
> 2022-03-08T04:24:38.510151Z  INFO common_meta_raft_store::state_machine::sm_meta_api_impl: create table: db_09_0008: "t"
> 2022-03-08T04:24:38.835933Z  INFO databend_query::catalogs::impls::database_catalog: Create table from req:CreateTableReq { if_not_exists: false, tenant: "test_tenant", db: "db_09_0008", table: "m", table_meta: TableMeta { schema: DataSchema { fields: [DataField { name: "a", data_type: UInt64, nullable: true }], metadata: {} }, engine: "Memory", engine_options: {}, options: {}, created_on: 2022-03-08T04:24:38.834858Z } }
> 2022-03-08T04:24:38.836580Z  INFO common_meta_raft_store::state_machine::sm_meta_api_impl: create table: db_09_0008: "m"
> 2022-03-08T04:24:38.885623Z  INFO databend_query::catalogs::impls::database_catalog: Drop table from req:DropTableReq { if_exists: false, tenant: "test_tenant", db: "db_09_0008", table: "m" }
> 2022-03-08T04:24:38.895752Z  INFO databend_query::catalogs::impls::database_catalog: Create table from req:CreateTableReq { if_not_exists: false, tenant: "test_tenant", db: "db_09_0008", table: "m", table_meta: TableMeta { schema: DataSchema { fields: [DataField { name: "a", data_type: UInt64, nullable: true }], metadata: {} }, engine: "Fuse", engine_options: {}, options: {"database_id": "29"}, created_on: 2022-03-08T04:24:38.894166Z } }
> 2022-03-08T04:24:38.896314Z  INFO common_meta_raft_store::state_machine::sm_meta_api_impl: create table: db_09_0008: "m"
> 2022-03-08T04:24:39.106051Z  INFO databend_query::catalogs::impls::database_catalog: Drop table from req:DropTableReq { if_exists: false, tenant: "test_tenant", db: "db_09_0008", table: "m" }
> 2022-03-08T04:24:39.109604Z ERROR databend_query::servers::mysql::writers::query_result_writer: OnQuery Error: Code: 1002, displayText = EOF while parsing a value at line 1 column 0.
> 
>    0: backtrace::backtrace::trace
>    1: backtrace::capture::Backtrace::new
>    2: common_exception::exception::ErrorCode::from_std_error
>    3: common_exception::exception_into::<impl core::convert::From<serde_json::error::Error> for common_exception::exception::ErrorCode>::from
>    4: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
>    5: databend_query::storages::fuse::io::meta_readers::<impl databend_query::storages::fuse::cache::local_cache::Loader<V> for T>::load::{{closure}}
>    6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>    7: <core::pin::Pin<P> as core::future::future::Future>::poll
>    8: databend_query::storages::fuse::cache::local_cache::CachedReader<V,L>::load::{{closure}}
>    9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>   10: databend_query::storages::fuse::cache::local_cache::CachedReader<V,L>::read::{{closure}}
>   11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>   12: databend_query::storages::fuse::io::meta_readers::<impl databend_query::storages::fuse::cache::local_cache::CachedReader<databend_query::storages::fuse::meta::snapshot::TableSnapshot,&databend_query::sessions::query_ctx::QueryContext>>::read_snapshot_history::{{closure}}
>   13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>   14: databend_query::storages::fuse::operations::optimize::<impl databend_query::storages::fuse::fuse_table::FuseTable>::do_optimize::{{closure}}
>   15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>   16: <databend_query::storages::fuse::fuse_table::FuseTable as databend_query::storages::storage_table::Table>::optimize::{{closure}}
>   17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>   18: <core::pin::Pin<P> as core::future::future::Future>::poll
>   19: <databend_query::interpreters::interpreter_table_drop::DropTableInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute::{{closure}}
>   20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>   21: <core::pin::Pin<P> as core::future::future::Future>::poll
>   22: <databend_query::interpreters::interpreter_factory_interceptor::InterceptorInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute::{{closure}}
>   23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>   24: <core::pin::Pin<P> as core::future::future::Future>::poll
>   25: databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorkerBase<W>::exec_query::{{closure}}::{{closure}}::{{closure}}
>   26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>   27: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
>   28: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
>   29: tokio::runtime::task::core::CoreStage<T>::poll
>   30: tokio::runtime::task::harness::poll_future::{{closure}}
>   31: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
>   32: std::panicking::try::do_call
>   33: ___rust_try
>   34: std::panicking::try
>   35: std::panic::catch_unwind
>   36: tokio::runtime::task::harness::poll_future
>   37: tokio::runtime::task::harness::Harness<T,S>::poll_inner
>   38: tokio::runtime::task::harness::Harness<T,S>::poll
>   39: tokio::runtime::task::raw::poll
>   40: tokio::runtime::task::raw::RawTask::poll
>   41: tokio::runtime::task::LocalNotified<S>::run
>   42: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
>   43: tokio::coop::with_budget::{{closure}}
>   44: std::thread::local::LocalKey<T>::try_with
>   45: std::thread::local::LocalKey<T>::with
>   46: tokio::runtime::thread_pool::worker::Context::run_task
>   47: tokio::runtime::thread_pool::worker::Context::run
>   48: tokio::runtime::thread_pool::worker::run::{{closure}}
>   49: tokio::macros::scoped_tls::ScopedKey<T>::set
>   50: tokio::runtime::thread_pool::worker::run
>   51: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
>   52: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
>   53: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
>   54: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
>   55: tokio::runtime::task::core::CoreStage<T>::poll
>   56: tokio::runtime::task::harness::poll_future::{{closure}}
>   57: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
>   58: std::panicking::try::do_call
>   59: ___rust_try
>   60: std::panicking::try
>   61: std::panic::catch_unwind
>   62: tokio::runtime::task::harness::poll_future
>   63: tokio::runtime::task::harness::Harness<T,S>::poll_inner
>   64: tokio::runtime::task::harness::Harness<T,S>::poll
>   65: tokio::runtime::task::raw::poll
>   66: tokio::runtime::task::raw::RawTask::poll
>   67: tokio::runtime::task::UnownedTask<S>::run
>   68: tokio::runtime::blocking::pool::Task::run
>   69: tokio::runtime::blocking::pool::Inner::run
>   70: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
>   71: std::sys_common::backtrace::__rust_begin_short_backtrace
>   72: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
>   73: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
>   74: std::panicking::try::do_call
>   75: ___rust_try
>   76: std::panicking::try
>   77: std::panic::catch_unwind
>   78: std::thread::Builder::spawn_unchecked_::{{closure}}
>   79: core::ops::function::FnOnce::call_once{{vtable.shim}}
>   80: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
>              at /rustc/8769f4ef2fe1efddd1f072485f97f568e7328f79/library/alloc/src/boxed.rs:1854:9
>       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
>              at /rustc/8769f4ef2fe1efddd1f072485f97f568e7328f79/library/alloc/src/boxed.rs:1854:9
>       std::sys::unix::thread::Thread::new::thread_start
>              at /rustc/8769f4ef2fe1efddd1f072485f97f568e7328f79/library/std/src/sys/unix/thread.rs:108:17
>   81: __pthread_start
> 
> 2022-03-08T04:24:39.118831Z  INFO databend_query::catalogs::impls::database_catalog: Drop table from req:DropTableReq { if_exists: false, tenant: "test_tenant", db: "db_09_0008", table: "t" }
> 2022-03-08T04:24:39.[1357](https://github.com/datafuselabs/databend/runs/5459431198?check_suite_focus=true#step:3:1357)39Z  INFO databend_query::catalogs::impls::database_catalog: Drop database from req:DropDatabaseReq { if_exists: false, tenant: "test_tenant", db: "db_09_0008" }
> [ FAIL ] - result differs with:
> --- /Users/runner/work/databend/databend/tests/suites/0_stateless/09_fuse_engine/09_0008_fuse_optimize_table.result	2022-03-08 04:19:49.000000000 +0000
> +++ /Users/runner/work/databend/databend/tests/suites/0_stateless/09_fuse_engine/09_0008_fuse_optimize_table.stdout	2022-03-08 04:24:39.000000000 +0000
> @@ -17,3 +17,4 @@
>  8
>  9
>  10
> +ERROR 1105 (HY000) at line 56: Code: 1002, displayText = EOF while parsing a value at line 1 column 0.
> 
> 09_0009_remote_explain:                                                 2022-03-08T04:24:39.228184Z  INFO databend_query::servers::mysql::mysql_handler: MySQL connection coming: Ok(127.0.0.1:50484)
> 2022-03-08T04:24:39.237
> ```

cc @dantengsky

**Comment by dantengsky** [comment]
> https://github.com/datafuselabs/databend/runs/5459431198?check_suite_focus=true
> seems not related to this pr:

yeah, encounter a similar flaky test in PR #4356 minutes ago, also in the apple/darwin platform. 

digging into it, at the same time, please re-run them

**Pull request merged**
