### PR TITLE
[common/meta/sled-store] feature: txn-tree: add update_and_fetch()

### PR DESCRIPTION
**Pull request by drmingdrmer**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Changelog

- New Feature

## Related Issues

### CODE REVIEW

**Review by ariesdevil — APPROVED** [review]
LGTM

**Comment by ariesdevil** [comment]
Sorry for my previous PR lack of tests, maybe we can make these as good-first-issue:)
But the good-first-issues of metasrv does not seem to arouse the interest of others :(

**Comment by drmingdrmer** [comment]
> Sorry for my previous PR lack of tests, maybe we can make these as good-first-issue:) But the good-first-issues of metasrv does not seem to arouse the interest of others :(

It's our duty to make opportunities for people to participate.
And it's also our duty to get them done if people are more interested in other part than metasrv.

**Comment by ariesdevil** [comment]
Yup, good-first-issues should have deadline.

**Pull request merged**
