### PR TITLE
chore(ast): Fix typo and code cleanup

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

chore(ast): Fix typo and code cleanup

## Changelog

- Bug Fix

### CODE REVIEW

**Comment by BohuTANG** [comment]
Hmm, will conflicts with https://github.com/datafuselabs/databend/pull/5230

**Comment by Xuanwo** [comment]
> Hmm, will conflicts with #5230

Thanks for the information. I will rebase this PR after #5230 get merged.

**Comment by andylokandy** [comment]
@Xuanwo for convenience I've just merged your changes into the pull request. sorry for stealing your work :laughing:.

**Comment by Xuanwo** [comment]
This PR has been merged into https://github.com/datafuselabs/databend/pull/5230, closing now.

**Pull request closed without merging**
