### PR TITLE
feat(query): support parser `copy into distributed`

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

 support parser `copy into distributed`

Part of #8594

### CODE REVIEW

**Comment by sundy-li** [comment]
I think `distributed` should not be an option , it'll enabled by default in cluster deployment.

**Comment by Xuanwo** [comment]
Hello, why we need a new option to make COPY distributed? Can you elaborate more details?

**Comment by TCeason** [comment]
> I think `distributed` should not be an option , it'll enabled by default in cluster deployment.

Good idea. Will close this pr.

**Comment by TCeason** [comment]
> Hello, why we need a new option to make COPY distributed? Can you elaborate more details?

Base idea is in there:

https://github.com/datafuselabs/databend/issues/8594#issue-1432471562

But now, I think as a default set enable on cluster mode is better.

**Pull request closed without merging**
