### PR TITLE
fix: compact_segment_bug

### PR DESCRIPTION
**Pull request by JackTan25**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

- Closes #issue

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12207)

### CODE REVIEW

**Comment by JackTan25** [comment]
https://github.com/datafuselabs/databend/pull/12207/files#diff-46625998da2d3923cca903cd6ec42cee1114e9440cfcb0652255ec9c8b358da5L55 I think row_idx won't over 100w, need 20bits, so this modify is good. cc @sundy-li @dantengsky

**Comment by sundy-li** [comment]
> I think row_idx won't over 100w

```
pub const DEFAULT_BLOCK_MAX_ROWS: usize = 1000 * 1000;
```

This may be incorrect if there is large block with more than 100w rows.

**Comment by JackTan25** [comment]
> > I think row_idx won't over 100w
> 
> ```
> pub const DEFAULT_BLOCK_MAX_ROWS: usize = 1000 * 1000;
> ```
> 
> This may be incorrect if there is a large block with more than 100w rows.

I think I should limit the row_per_block option when create table?

**Comment by sundy-li** [comment]
maybe we should expand the row_id type to int128.

**Comment by JackTan25** [comment]
> maybe we should expand the row_id type to int128.

this costs deeply, can we accept the memory size? If so I will try it.

**Review by sundy-li — APPROVED** [review]

**Comment by JackTan25** [comment]
if use u128, I need to modify many codes, add a new UInt128 type, should we? cc @sundy-li

**Comment by JackTan25** [comment]
> > I think I should limit the row_per_block option when create table?
> 
> Let's have this limit for now.

I think so.

**Pull request merged**
