### PR TITLE
feat: add `is_attach` column to `system.tables` and disable index creation for attache tables

### PR DESCRIPTION
**Pull request by dantengsky**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

add `is_attach` column to `system.tables` and disable index creation for attache tables

- fixes: #16163
- fixes: #16164

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16166)

### CODE REVIEW

**Review by TCeason — APPROVED** [review]
system table part is LGTM.

Add col may influence jdbc? Please check it @hantmac

**Review by b41sh — APPROVED** [review]
LGTM

**Comment by dantengsky** [comment]
@hantmac  please take a look, thanks

**Comment by hantmac** [comment]
No affect to jdbc. LGTM.

**Pull request merged**
