### PR TITLE
feat(query): support drop cluster key

### LINKED ISSUE #5834: Feature: Support drop cluster key
**Summary**

```
ALTER TABLE <name> DROP CLUSTER KEY
```

### PR DESCRIPTION
**Pull request by zhyass**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

```
ALTER TABLE <name> DROP CLUSTER KEY
```

## Changelog

- New Feature

## Related Issues

Fixes #5834

### CODE REVIEW

**Review by dantengsky — APPROVED** [review]
LGTM

**Comment by BohuTANG** [comment]
This PR needs a doc, cc @soyeric128

**Comment by zhyass** [comment]
> Hi @BohuTANG and @zhyass
> 
> Could you pls review the draft attached for this feature? Thanks.

Thanks for your contribution. 
I have some ideas to discuss. 
- The cluster key can be listed as a separate group title, just like table and database.  And contains some subtitles, such as alter cluster key, drop cluster key.

**Comment by soyeric128** [comment]
Hi @zhyass 
Do we also support "alter cluster key"? I couldn't find it in the current documentation.  If so, could you pls help provide more information about it ? such as syntax, example... so I can add them as well.

**Comment by zhyass** [comment]
> 

Please refer to this pr:
https://github.com/datafuselabs/databend/pull/5718

**Comment by zhyass** [comment]
Yes,  we can refer to the samples of snowflake. After https://github.com/datafuselabs/databend/pull/5994 is merged, we can run `select * from system.tables where name ='t'` to display the cluster key.

**Comment by soyeric128** [comment]
@zhyass pls review this PR: https://github.com/datafuselabs/databend/pull/6009

**Pull request merged**
