### PR TITLE
fix: Fix flaky test of fuse compat read

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Fix https://github.com/datafuselabs/databend/issues/7626

I'm not familiar with this logic, but it seem to make sense to remove the trailing `0`:

```sql
statement ok
INSERT INTO fuse_compat_table VALUES(
        0,
        127,
        3267,
        2147483647,
        9223372036854775807,
        3.4,
        1.7,
        '9999-12-31',
        '1991-01-01 00:00:00',
        'varchar',
        parse_json('[1,2,3,["a","b","c"]]'),
        parse_json('{"a":1,"b":{"c":2}}'),
        parse_json('[1,{"a":1,"b":{"c":2}}]')
);

statement query T
select c_timestamp FROM fuse_compat_table;

----
1991-01-01 00:00:00
```

Cc @TCeason, is this related to the MySQL connector's update?
~~Cc @drmingdrmer to confirm that this PR is right.~~

### CODE REVIEW

**Comment by TCeason** [comment]
> Cc @TCeason, is this related to the MySQL connector's update?

Need to merge the newest main branch.

**Comment by Xuanwo** [comment]
@mergify update

**Comment by Xuanwo** [comment]
Mysql native client output:

```shell
MySQL [(none)]> select c_timestamp FROM fuse_compat_table;
+----------------------------+
| c_timestamp                |
+----------------------------+
| 1991-01-01 00:00:00.000000 |
+----------------------------+
1 row in set (0.046 sec)
```

**Comment by Xuanwo** [comment]
I realized the root cause of this problem.

Our logic test has migrated to `datafuselabs/build-tool:sqllogic`, but `fuse-compat` not updated.

Cc @everpcpc

**Comment by Xuanwo** [comment]
I tried to update `fuse-compat`, @everpcpc please help review~

**Review by everpcpc — APPROVED** [review]

**Review by drmingdrmer — APPROVED** [review]
nice...

**Pull request merged**
