### PR TITLE
Use mysql-connector-python instead of deprecated mysql-connector

### PR DESCRIPTION
**Pull request by ariesdevil**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Use mysql-connector-python instead of deprecated mysql-connector
ref: https://pypi.org/project/mysql-connector/

## Changelog

- Build/Testing/CI

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Review by PsiACE — APPROVED** [review]
LGTM

**Comment by BohuTANG** [comment]
Weird, `error: could not compile `common-functions` https://github.com/datafuselabs/databend/runs/4858522398?check_suite_focus=true

**Comment by Xuanwo** [comment]
I trigger a rurun to make sure it's not an env related issue.

**Comment by ariesdevil** [comment]
Still failed...

**Comment by Xuanwo** [comment]
Let me take a look on what happened here.

**Comment by Xuanwo** [comment]
Can't reproduced by my side. `rustc` has been `kill -9`, it's highly possible that `rustc` meets OOM. No matter why, it's not caused by this PR.

**Review by Xuanwo — APPROVED** [review]

**Pull request merged**
