### PR TITLE
feat(metrics): Add metrics about IO

### LINKED ISSUE #6458: Feature: add metrics about IO
**Summary**

- rows scanned/write
- s3 bytes recv/send

### PR DESCRIPTION
**Pull request by e1ijah1**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

- Add metrics for rows scanned/write.
- Add metrics for bytes scanned/write.
- Add metrics for s3 bytes recv/send.

Fixes #6458

### CODE REVIEW

**Comment by Xuanwo** [comment]
Please mark this PR as `draft` instead of adding `[WIP]` in title.

**Comment by drmingdrmer** [comment]
- `main` branch is force pushed, update your working branch please: #7261

**Comment by drmingdrmer** [comment]
- `main` branch is force pushed, update your working branch please: #7261

**Comment by drmingdrmer** [comment]
`main` branch is force pushed(**again** `:(`, to cleanup big object in history), update your working branch please: [To everybody: main branch is force pushed. #7263](https://github.com/datafuselabs/databend/issues/7263)

**Comment by Xuanwo** [comment]
cc @ZhiHanZ for reviewing

**Comment by e1ijah1** [comment]
Maybe S3 metrics should be recorded in OpenDal?

**Comment by Xuanwo** [comment]
> Maybe S3 metrics should be recorded in OpenDal?

Yes.

OpenDAL supports metrics via [Metrics Layer](https://opendal.databend.rs/opendal/layers/struct.MetricsLayer.html), it will track all underlying IO metrics.

And databend should track metrics around table and databases.

**Comment by Xuanwo** [comment]
As described in https://github.com/datafuselabs/databend/pull/7216#issuecomment-1226739311, we don't need this PR anymore.

@e1ijah1 Thanks for your contribution. Hoping we can meet again!

**Pull request closed without merging**
