### PR TITLE
Make date32 physical type to be int32

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

- To be compatible with ClickHouse's [Date32](https://clickhouse.com/docs/en/sql-reference/data-types/date32/), it supports negative numbers.

- Add new aliases for SQL datatypes:
   "DATE16" => Ok(DataType::Date16),
    "DATE32" => Ok(DataType::Date32),
    "DATETIME" => Ok(DataType::DateTime32(None)),
    "DATETIME32" => Ok(DataType::DateTime32(None)),

## Changelog

related cc @ygf11  @dust1  @junli1026 

- Improvement

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Review by zhang2014 — CHANGES_REQUESTED** [review]
unit test failure need to fix.

**Comment by ygf11** [comment]
https://github.com/datafuselabs/databend/blob/f43dcb8f8cffe437bf47f30737db6a1033f30772/common/functions/src/scalars/dates/number_function.rs#L227-L233


@sundy-li  For functions in number_function file, we need fix  constant path for date32  and add more tests :smile:?

**Comment by ygf11** [comment]
https://github.com/datafuselabs/databend/blob/dddc5614e5c7bab14386e5f1ad3bd30d1f80858b/common/functions/src/scalars/dates/number_function.rs#L227-L232
@sundy-li It seem date32 still make 0 as '1970-1-1' after this pr, so for number functions we just need to fix the constant path which use as_u64 for date32?

**Comment by sundy-li** [comment]
> @sundy-li It seem date32 still make 0 as '1970-1-1' after this pr, so for number functions we just need to fix the constant path which use as_u64 for date32?

This does not matter, because the numbers_function in date/datetime have specific numberic return types.

```
pub type ToYYYYMMFunction = NumberFunction<ToYYYYMM, u32>;
pub type ToYYYYMMDDFunction = NumberFunction<ToYYYYMMDD, u32>;
pub type ToYYYYMMDDhhmmssFunction = NumberFunction<ToYYYYMMDDhhmmss, u64>;

pub type ToStartOfISOYearFunction = NumberFunction<ToStartOfISOYear, u16>;
pub type ToStartOfYearFunction = NumberFunction<ToStartOfYear, u16>;
pub type ToStartOfQuarterFunction = NumberFunction<ToStartOfQuarter, u16>;
pub type ToStartOfMonthFunction = NumberFunction<ToStartOfMonth, u16>;

```

**Comment by ygf11** [comment]
> This does not matter, because the numbers_function in date/datetime have specific numberic return types.

I mean that as the physical data type of date32 is `i32` now, we can using `as_i64` instead of `as_u64`  to extract value in constant path.
https://github.com/datafuselabs/databend/blob/dddc5614e5c7bab14386e5f1ad3bd30d1f80858b/common/functions/src/scalars/dates/number_function.rs#L229

**Pull request merged**
