### PR TITLE
[metasrv] refactor: rename metasrv to kvsrv since it actual does not provide meta APIs but just kv APIs

### PR DESCRIPTION
**Pull request by drmingdrmer**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Changelog

- Improvement

## Related Issues

### CODE REVIEW

**Comment by BohuTANG** [comment]
@drmingdrmer 
Would you mind merge https://github.com/datafuselabs/databend/pull/1971 first?
This patch may conflicts after that merged.

**Comment by drmingdrmer** [comment]
> @drmingdrmer
> Would you mind merge #1971 first?
> This patch may conflicts after that merged.

No at all. Changes in this PR are simple and obvious. The conflicts would be much easier to solve.

**Comment by drmingdrmer** [comment]
- Revert to draft . Wait until #1971 being merged.

**Review by dantengsky — APPROVED** [review]
LGTM

**Pull request merged**
