### PR TITLE
feat(mysql handler): return "NaN"/"Infinity" instead of 'nan'/'inf'

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

originally proposed by  @sandflee  https://github.com/datafuselabs/databend/pull/8929#issuecomment-1326221921

discussed in https://github.com/datafuselabs/databend/discussions/8941

### CODE REVIEW

**Review by TCeason — APPROVED** [review]

**Review by sundy-li — APPROVED** [review]

**Comment by BohuTANG** [comment]
There is a test failed relate to this PR:
```
--- /runner/_work/databend/databend/tests/suites/1_stateful/00_copy/00_0002_copy_from_fs_location.result	2022-11-29 06:12:24.292176608 +0000
+++ /runner/_work/databend/databend/tests/suites/1_stateful/00_copy/00_0002_copy_from_fs_location.stdout	2022-11-29 06:15:48.724594517 +0000
@@ -5,4 +5,4 @@
 199	2020.0	769
 199	2020.0	769
 199	2020.0	769
-199	2020.0	769
+198	2020.0	765
```

**Comment by youngsofun** [comment]
not repeatable on my Mac,  CI rerun succeeded

**Comment by youngsofun** [comment]
I will dive into it if it fails again.

**Comment by youngsofun** [comment]
@mergify update

**Pull request merged**
