### PR TITLE
refactor: add minitrace to common_tracing

### PR DESCRIPTION
**Pull request by andylokandy**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

- Add tracing config
- Add minitrace infrastructure to common_tracing

Part of https://github.com/datafuselabs/databend/pull/12169

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12222)

### CODE REVIEW

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 6 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12222)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @andylokandy, @ariesdevil, @PsiACE, and @Xuanwo)

___
*[`src/common/tracing/src/lib.rs` line 58 at r2](https://reviewable.io/reviews/datafuselabs/databend/12222#-NaKXePqDM-nHT4h3YF6:-NaKXePqDM-nHT4h3YF7:b-wtout1) ([raw file](https://github.com/datafuselabs/databend/blob/8a4d9355ac62b1490c3ceab02a622a025a574415/src/common/tracing/src/lib.rs#L58)):*
> ```XML
>     let full_name = std::any::type_name::<F>();
>     full_name.rsplit("::").next().unwrap()
> }
> ```

Where is `closure_name` used?

**Review by andylokandy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12222)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @ariesdevil, @drmingdrmer, @PsiACE, and @Xuanwo)

___
*[`src/common/tracing/src/lib.rs` line 58 at r2](https://reviewable.io/reviews/datafuselabs/databend/12222#-NaKXePqDM-nHT4h3YF6:-NaK_t1k3gsxMa_asQbh:b6e7o8y) ([raw file](https://github.com/datafuselabs/databend/blob/8a4d9355ac62b1490c3ceab02a622a025a574415/src/common/tracing/src/lib.rs#L58)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

Where is `closure_name` used?
</blockquote></details>

it's used by test harness.

**Review by drmingdrmer — APPROVED** [review]
Tidy and clean!

The updated log/tracing module looks like having a better defined structure compared to the previous version.
:lgtm:

> Reviewed 4 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12222#-:-NaLpn7H3ievkQiLq8Wf:boegdkq)* status: all files reviewed, 2 unresolved discussions (waiting on @andylokandy, @ariesdevil, @PsiACE, and @Xuanwo)

___
*[`src/common/tracing/src/lib.rs` line 58 at r2](https://reviewable.io/reviews/datafuselabs/databend/12222#-NaKXePqDM-nHT4h3YF6:-NaLpct47Ijl6Z39JyfM:bxvhtb4) ([raw file](https://github.com/datafuselabs/databend/blob/8a4d9355ac62b1490c3ceab02a622a025a574415/src/common/tracing/src/lib.rs#L58)):*
<details><summary><i>Previously, andylokandy (Andy Lok) wrote…</i></summary><blockquote>

it's used by test harness.
</blockquote></details>

Did not get it. how is this fn called?
___
*[`src/common/tracing/src/minitrace.rs` line 189 at r2](https://reviewable.io/reviews/datafuselabs/databend/12222#-NaLnaIR0MHYLgYmRy94:-NaLnaIR0MHYLgYmRy95:b4swq79) ([raw file](https://github.com/datafuselabs/databend/blob/8a4d9355ac62b1490c3ceab02a622a025a574415/src/common/tracing/src/minitrace.rs#L189)):*
> ```XML
> }
> 
> fn formmater(
> ```

typo `formmater -> formatter`

**Review by PsiACE — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12222)* status: all files reviewed, 2 unresolved discussions (waiting on @andylokandy, @ariesdevil, and @Xuanwo)

**Review by andylokandy — COMMENTED** [review]
> Reviewed 7 of 10 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12222)* status: all files reviewed, 1 unresolved discussion (waiting on @ariesdevil, @drmingdrmer, and @Xuanwo)

___
*[`src/common/tracing/src/lib.rs` line 58 at r2](https://reviewable.io/reviews/datafuselabs/databend/12222#-NaKXePqDM-nHT4h3YF6:-NaM95Yd0MPk4KZOOyLS:b-pl68ss) ([raw file](https://github.com/datafuselabs/databend/blob/8a4d9355ac62b1490c3ceab02a622a025a574415/src/common/tracing/src/lib.rs#L58)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

Did not get it. how is this fn called?
</blockquote></details>

https://github.com/datafuselabs/databend/blob/3d59d4ee64ffdd5c3a7f83e855ecc6c6c0bd84e5/src/meta/sled-store/tests/it/testing/mod.rs#L57

**Pull request merged**
