### PR TITLE
chore(deps): upstream first

### LINKED ISSUE #6968: upstream-first: Switch `async-trait` to upstream

### LINKED ISSUE #6969: upstream-first: Switch `cargo-license` to upstream

### PR DESCRIPTION
**Pull request by PsiACE**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

- async-trait-fn 0.1.0
- cargo license 0.5.1

Fixes #6968 
Fixes #6969

### CODE REVIEW

**Comment by PsiACE** [comment]
async-trait-fn is only introduced where needed, although we can replace all async-trait if necessary

**Review by Xuanwo — APPROVED** [review]
Great!

**Comment by PsiACE** [comment]
work fine

```
MySQL [(none)]> SELECT * FROM system.credits LIMIT 20;
+---------------------------+---------+---------------------------+
| name                      | version | license                   |
+---------------------------+---------+---------------------------+
| addr2line                 | 0.17.0  | Apache-2.0 OR MIT         |
| adler                     | 1.0.2   | 0BSD OR Apache-2.0 OR MIT |
| ahash                     | 0.7.6   | Apache-2.0 OR MIT         |
| aho-corasick              | 0.7.18  | MIT OR Unlicense          |
| alloc-no-stdlib           | 2.0.3   | BSD-3-Clause              |
| alloc-stdlib              | 0.2.1   | BSD-3-Clause              |
| android_system_properties | 0.1.4   | Apache-2.0 OR MIT         |
| ansi_term                 | 0.12.1  | MIT                       |
| anyerror                  | 0.1.6   | Apache-2.0                |
| anyhow                    | 1.0.61  | Apache-2.0 OR MIT         |
| approx                    | 0.5.1   | Apache-2.0                |
| arc-swap                  | 1.5.1   | Apache-2.0 OR MIT         |
| array-init-cursor         | 0.2.0   | Apache-2.0 OR MIT         |
| arrayref                  | 0.3.6   | BSD-2-Clause              |
| arrayvec                  | 0.4.12  | Apache-2.0 OR MIT         |
| arrayvec                  | 0.5.2   | Apache-2.0 OR MIT         |
| arrayvec                  | 0.7.2   | Apache-2.0 OR MIT         |
| arrow-format              | 0.7.0   | Apache-2.0                |
| arrow2                    | 0.12.0  | Apache-2.0                |
| as-slice                  | 0.1.5   | Apache-2.0 OR MIT         |
+---------------------------+---------+---------------------------+
20 rows in set (0.004 sec)

MySQL [(none)]> SELECT count(*) FROM system.credits;
+----------+
| COUNT(*) |
+----------+
|      658 |
+----------+
1 row in set (0.004 sec)
```

**Review by BohuTANG — APPROVED** [review]
:100:

**Pull request merged**
