### PR TITLE
feat(query): improve select query order+limit performance under planner v2

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

when pipeline build sort push limit

Fixes #issue

### CODE REVIEW

**Comment by TCeason** [comment]
test failed.

```
--- /runner/_work/databend/databend/tests/suites/1_stateful/04_mini_dataset/04_0001_mini_hits.result	2022-08-26 11:38:49.158876641 +0000
+++ /runner/_work/databend/databend/tests/suites/1_stateful/04_mini_dataset/04_0001_mini_hits.stdout	2022-08-26 11:44:43.898159472 +0000
@@ -156,9 +156,9 @@
 usb на юбился ворожение русскую
 usb на юбился ворожение русскую
 ведомосквы с ляйсан баллы
+ведомосквы с ляйсан баллы
 армянск
 армянск
-ведомосквы с ляйсан баллы
 ====== SQL26 ======
 /topic,6 на карта
 /topic,6 на карта


Having 1 errors! 18 tests passed.                     0 tests skipped.
The failure tests:
    /runner/_work/databend/databend/tests/suites/1_stateful/04_mini_dataset/04_0001_mini_hits.sh
```

Because 
```
let indices: PrimitiveArray<u32> =
            arrow_sort::lexsort_to_indices_impl(&order_arrays, limit, &build_compare)?;
```

**Comment by sundy-li** [comment]
Why do we got differ results ?

**Comment by TCeason** [comment]
> ```rust
> lexsort_to_indices_impl
> ```

As far as I can confirm, arrow_sort::lexsort_to_indices_impl modify the data.

* if limit is None it will return all sort data.

* if limit is Some() it will return part data but when I print the indices the data's sort already changed.

```
[
    "+------------------+---------------------------------+",
    "| 4                | 39                              |",
    "+------------------+---------------------------------+",
    "| 1373832005000000 | армянск                         |",
    "| 1373832005000000 | армянск                         |",
    "| 1373832006000000 | коптимиквидвич фаршироксин      |",
    "| 1373832007000000 | коптимиквидвич фаршироксин      |",
    "| 1373832029000000 | usb на юбился ворожение русскую |",
    "| 1373832029000000 | usb на юбился ворожение русскую |",
    "| 1373832033000000 | ведомосквы с ляйсан баллы       |",
    "| 1373832036000000 | ведомосквы с ляйсан баллы       |",
    "| 1373832036000000 | армянск                         |",
    "| 1373832036000000 | армянск                         |",
    "+------------------+---------------------------------+",
]

```

So record on pr.

**Comment by sundy-li** [comment]
Maybe this is a bug, you can dig into it.

**Comment by TCeason** [comment]
> Maybe this is a bug, you can dig into it.

Np. 😉

**Comment by sundy-li** [comment]
It's not a bug, because the limit sort is unstable sort. You can modify the Q25 to:

```
SELECT SearchPhrase FROM hits WHERE SearchPhrase <> '' ORDER BY EventTime, SearchPhrase  LIMIT 10;
```
and the results to make it stable enough.

**Comment by sundy-li** [comment]
@mergify update

**Review by sundy-li — APPROVED** [review]

**Review by leiysky — APPROVED** [review]

**Comment by RinChanNOWWW** [comment]
Unfortunately, I couldn't approve PRs yet.

**Comment by BohuTANG** [comment]
> Unfortunately, I couldn't approve PRs yet.

I think you are ok now

**Pull request merged**
