### PR TITLE
Fix the documents avgIf to avg_if

### PR DESCRIPTION
**Pull request by hanyisong**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

##Summary
Change the document function avgIf to avg_if

### CODE REVIEW

**Comment by BohuTANG** [comment]
Thanks for your contribution!

**Comment by Xuanwo** [comment]
Hi, thanks for contributing!

There is something we should take care about:

- Please don't rename the file path into Chinese, as we rely on the file path to generate correct docs.

**Comment by Xuanwo** [comment]
ping @BohuTANG, please roll this PR back.

image

**Comment by Xuanwo** [comment]
Addressed by https://github.com/datafuselabs/databend/pull/5494

**Pull request merged**
