### PR TITLE
fix(query): Fix values source `skip_to_next_row`

### LINKED ISSUE #6569: `value_source_v2` shoud sync with `value_source`
`value_source_v2` shoud sync with `value_source`? In this transitional stage, all changes in `value_source` may be lost in `value_source_v2`. 

How can we guarantee it sync?

cc @sundy-li

_Originally posted by @fkuner in https://github.com/datafuselabs/databend/issues/6565#issuecomment-1181216624_

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

1.  Fix values source `skip_to_next_row` escape flag bug.
2. Uniform `DateTime` & `Timestamp` in the new parser.

Fixes #6569

### CODE REVIEW

**Review by andylokandy — APPROVED** [review]

**Review by fkuner — APPROVED** [review]

**Comment by BohuTANG** [comment]
After this PR, `DATETIME` is not an alias for `TIMESTAMP` in v2?

**Comment by sundy-li** [comment]
> After this PR, `DATETIME` is not an alias for `TIMESTAMP` in v2?

Before this PR, DATETIME is not an alias for TIMESTAMP.

After it is the same.

**Comment by BohuTANG** [comment]
> > After this PR, `DATETIME` is not an alias for `TIMESTAMP` in v2?
> 
> Before this PR, DATETIME is not an alias for TIMESTAMP.

Oh, our document needs an update: https://databend.rs/doc/reference/data-types/data-type-time-date-types
Btw, `Dev MacOS / test_stateless_cluster_macos` always failed, not sure related to this PR.

> After it is the same.

**Comment by sundy-li** [comment]
> Our document needs an update(updated)

It's the same as document, but In planner V2, we forgot to follow the document. This pr is a fix for that.

> test_stateless_cluster_macos

Seems like a flaky test, I will try to rerun multi times to confirm.

**Pull request merged**
