### PR TITLE
bugfix: http_query fail.

### LINKED ISSUE #2767: [flaky test] servers::http::v1::http_query_handlers_test::test_simple_sql
**Summary**

```bash
---- servers::http::v1::http_query_handlers_test::test_simple_sql stdout ----
thread 'servers::http::v1::http_query_handlers_test::test_simple_sql' panicked at 'internal error: entered unreachable code', query/src/servers/http/v1/query/execute_state.rs:73:27
```

see: https://github.com/datafuselabs/databend/runs/4197693711?check_suite_focus=true#step:5:890

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

bug fix: /v1/query may fail,  reason: state mistakenly relying on tokio schedule order.

## Related Issues

Fixes #2767 

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
Oops, conflict~
But this PR can be backport some improvements from PR https://github.com/datafuselabs/databend/pull/2777

**Comment by youngsofun** [comment]
> Oops, conflict~ But this PR can be backport some improvements from PR #2777

thank you!

and there are unwraps in statment.rs, I will refactor it to based on mod v1/query soon.

**Comment by youngsofun** [comment]
>  and there are unwraps in statment.rs, I will refactor it to based on mod v1/query soon.

before that, I am working on a better and stable JSON format because it will be used by cli/plaground.

**Pull request merged**
