### PR TITLE
Remove dal mod 

### LINKED ISSUE #4145: `common-dal` is unused, we can remove it.
lgtm, and the common-dal is unused, we can remove it.

_Originally posted by @PsiACE in https://github.com/datafuselabs/databend/pull/4142#pullrequestreview-881338928_

### PR DESCRIPTION
**Pull request by wangzhen11aaa**
Signed-off-by: wang.zhen <wangzhenaaa7@gmail.com>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Remove dal mod.

Effects:
   Cargo.lock,
   Cargo.toml,
   dal(data access layer for remote storage),
   etc,

## Changelog

- Improvement

## Related Issues

Fixes #4145

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by wangzhen11aaa** [comment]
That's weird. All CI tests passed, while Unit tests gave no.
@Xuanwo

**Comment by BohuTANG** [comment]
> That's weird. All CI tests passed, while Unit tests gave no. @Xuanwo

The failure test is not related to this patch :)

**Comment by wangzhen11aaa** [comment]
@Xuanwo A little confused about this error. 

> > That's weird. All CI tests passed, while Unit tests gave no. @Xuanwo
> 
> The failure test is not related to this patch :)


---- servers::http::http_query_handlers::test_http_handler_tls_server stdout ----
Error: Code: 1045, displayText = Address already in use (os error 98).

How does this error emerge in the master (stable/runnable) branch?

**Comment by BohuTANG** [comment]
@wangzhen11aaa 
Hi, thank you for the PR, looks great to me, but there is a question about the PR title:
`also named common-dal in Cargo.toml dependencies` here is mean?
From my understand, we only remove the dal mod, not do others.

**Comment by BohuTANG** [comment]
> @Xuanwo A little confused about this error.
> 
> > > That's weird. All CI tests passed, while Unit tests gave no. @Xuanwo
> > 
> > 
> > The failure test is not related to this patch :)
> 
> ---- servers::http::http_query_handlers::test_http_handler_tls_server stdout ---- Error: Code: 1045, displayText = Address already in use (os error 98).
> 
> How does this error emerge in the master (stable/runnable) branch? How do we fix this?

Looks a flaky test here, please ignore it.

**Comment by wangzhen11aaa** [comment]
> common-dal

You are right. I will fix the title. 👍🏻

**Pull request merged**
