### PR TITLE
try fix the CI error about protoc

### LINKED ISSUE #3208: CI failed on protoc
**Summary**

like: https://github.com/datafuselabs/databend/runs/4392215697?check_suite_focus=true

```
Run actions-rs/cargo@v1
/home/runner/.cargo/bin/cargo clippy --tests -- -D warnings
    Updating git submodule `https://github.com/apache/arrow-testing`
    Updating git submodule `https://github.com/apache/parquet-testing`
   Compiling common-macros v0.1.0 (/home/runner/work/databend/databend/common/macros)
   Compiling tikv-jemalloc-sys v0.4.2+5.2.1-patched.2
   Compiling curl-sys v0.4.51+curl-7.80.0
    Checking common-cache v0.1.0 (/home/runner/work/databend/databend/common/cache)
    Checking common-infallible v0.1.0 (/home/runner/work/databend/databend/common/infallible)
    Checking async-raft v0.6.1 (https://github.com/datafuse-extras/async-raft?tag=v0.6.2-alpha.14.1#5086c8b3)
   Compiling common-meta-flight v0.1.0 (/home/runner/work/databend/databend/common/meta/flight)
   Compiling common-building v0.1.0 (/home/runner/work/databend/databend/common/building)
error: failed to run custom build command for `common-meta-flight v0.1.0 (/home/runner/work/databend/databend/common/meta/flight)`

Caused by:
  process didn't exit successfully: `/home/runner/work/databend/databend/target/debug/build/common-meta-flight-491817349f4c9c57/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=/home/runner/work/databend/databend/common/meta/flight/proto/metaflight.proto

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: NotFound, error: "failed to invoke protoc (hint: https://docs.rs/prost-build/#sourcing-protoc): No such file or directory (os error 2)" }', common/meta/flight/build.rs:34:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```

### PR DESCRIPTION
**Pull request by flaneur2020**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

the CI seems break in the main branch, error message:

```
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: NotFound, error: "failed to invoke protoc (hint: https://docs.rs/prost-build/#sourcing-protoc): No such file or directory (os error 2)" }', common/meta/flight/build.rs:34:10
```

the cause might be something changed in the CI base image?

this PR is a quick-and-dirty fix on the CI break to avoid blocking the other pull requests, we'd better find out the root cause of this CI break.

## Changelog

- Bug Fix

## Related Issues

Fixes #3208

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by Xuanwo** [comment]
Looks strange. I didn't find any changes that related to `protoc`.

**Comment by flaneur2020** [comment]
> Looks strange. I didn't find any changes that related to `protoc`.

yes, still not sure about the root cause :(

**Comment by Xuanwo** [comment]
`metaflight.proto` is not changed since two months ago.

In fact, this `build.rs` should not be run. Maybe it's related to the rust cache?

**Comment by flaneur2020** [comment]
> `metaflight.proto` is not changed since two months ago.
> 
> In fact, this `build.rs` should not be run. Maybe it's related to the rust cache?

the cache is suspicious! 🤔

**Pull request merged**
