### PR TITLE
fix(query): unify features for opendal

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

fix(query): unify features for opendal

Closes #issue

### CODE REVIEW

**Comment by zhang2014** [comment]
When we do not enable trust-dns by default, the following code will be used to resolve the dns, which may cause the thread to hang and cannot be destroyed.


```rust
let fut = async move {
            match runtime
                .spawn_blocking(move || {
                    // hyper will set port externally, so the port here is
                    // just used to construct a correct query.
                    //
                    // Ref: <https://github.com/hyperium/hyper/blob/4d89adce6122af1650165337d9d814314e7ee409/src/client/connect/http.rs#L322-L359>
                    (name.as_str(), 0).to_socket_addrs().map(|iter| {
                        let res: Vec<_> = iter.collect();
                        // Insert into cache if resolved succeeded.
                        cache.insert(name.as_str(), res.clone());
                        res
                    })
                })
                .await
            {
                Ok(v) => v.map(|v| Box::new(v.into_iter()) as reqwest::dns::Addrs),
                Err(err) => Err(io::Error::new(
                    io::ErrorKind::Other,
                    format!("spawn dns resolving task failed: {err:?}"),
                )),
            }
            .map_err(|err| Box::new(err) as Box<_>)
        };
```

**Comment by zhang2014** [comment]
before:
```
│       │       ├── opendal feature "default"
│       │       │   ├── opendal v0.29.0
│       │       │   └── opendal feature "rustls"
│       │       │       ├── opendal v0.29.0 (*)
│       │       │       ├── opendal feature "default" (*)
│       │       │       ├── opendal feature "layers-metrics"
│       │       │       │   └── opendal v0.29.0 (*)
│       │       │       ├── opendal feature "layers-tracing"
│       │       │       │   └── opendal v0.29.0 (*)
│       │       │       ├── opendal feature "services-ipfs"
│       │       │       │   └── opendal v0.29.0 (*)
│       │       │       ├── opendal feature "services-moka"
│       │       │       │   └── opendal v0.29.0 (*)
│       │       │       ├── opendal feature "services-redis"
│       │       │       │   └── opendal v0.29.0 (*)
│       │       │       ├── opendal feature "trust-dns"
│       │       │       │   ├── opendal v0.29.0 (*)
├── opendal feature "default" (*)
├── opendal feature "default" (*)
├── opendal feature "default" (*)
├── opendal feature "layers-metrics" (*)
├── opendal feature "layers-tracing" (*)
│       ├── opendal feature "default" (*)
│       ├── opendal feature "default" (*)
│       ├── opendal feature "default" (*)
├── opendal feature "default" (*)
├── opendal feature "default" (*)
├── opendal feature "default" (*)
├── opendal feature "default" (*)
├── opendal feature "layers-metrics" (*)
├── opendal feature "layers-tracing" (*)
│   │   ├── opendal feature "default" (*)
│   │   ├── opendal feature "layers-metrics" (*)
│   │   ├── opendal feature "layers-tracing" (*)
        ├── opendal feature "default" (*)
```

after
```
│       │       ├── opendal feature "default"
│       │       │   ├── opendal v0.29.0
│       │       │   └── opendal feature "rustls"
│       │       │       ├── opendal v0.29.0 (*)
│       │       ├── opendal feature "layers-metrics"
│       │       │   └── opendal v0.29.0 (*)
│       │       ├── opendal feature "layers-tracing"
│       │       │   └── opendal v0.29.0 (*)
│       │       ├── opendal feature "services-ipfs"
│       │       │   └── opendal v0.29.0 (*)
│       │       ├── opendal feature "services-moka"
│       │       │   └── opendal v0.29.0 (*)
│       │       ├── opendal feature "services-redis"
│       │       │   └── opendal v0.29.0 (*)
│       │       ├── opendal feature "trust-dns"
│       │       │   ├── opendal v0.29.0 (*)
│       │       │       ├── opendal feature "default" (*)
│       │       │       ├── opendal feature "layers-metrics" (*)
│       │       │       ├── opendal feature "layers-tracing" (*)
│       │       │       ├── opendal feature "services-ipfs" (*)
│       │       │       ├── opendal feature "services-moka" (*)
│       │       │       ├── opendal feature "services-redis" (*)
│       │       │       ├── opendal feature "trust-dns" (*)
├── opendal feature "default" (*)
├── opendal feature "layers-metrics" (*)
├── opendal feature "layers-tracing" (*)
├── opendal feature "services-ipfs" (*)
├── opendal feature "services-moka" (*)
├── opendal feature "services-redis" (*)
├── opendal feature "trust-dns" (*)
├── opendal feature "default" (*)
├── opendal feature "layers-metrics" (*)
├── opendal feature "layers-tracing" (*)
├── opendal feature "services-ipfs" (*)
├── opendal feature "services-moka" (*)
├── opendal feature "services-redis" (*)
├── opendal feature "trust-dns" (*)
├── opendal feature "default" (*)
├── opendal feature "layers-metrics" (*)
├── opendal feature "layers-tracing" (*)
├── opendal feature "services-ipfs" (*)
├── opendal feature "services-moka" (*)
├── opendal feature "services-redis" (*)
├── opendal feature "trust-dns" (*)
│       ├── opendal feature "default" (*)
│       ├── opendal feature "layers-metrics" (*)
│       ├── opendal feature "layers-tracing" (*)
│       ├── opendal feature "services-ipfs" (*)
│       ├── opendal feature "services-moka" (*)
│       ├── opendal feature "services-redis" (*)
│       ├── opendal feature "trust-dns" (*)
│       ├── opendal feature "default" (*)
│       ├── opendal feature "layers-metrics" (*)
│       ├── opendal feature "layers-tracing" (*)
│       ├── opendal feature "services-ipfs" (*)
│       ├── opendal feature "services-moka" (*)
│       ├── opendal feature "services-redis" (*)
│       ├── opendal feature "trust-dns" (*)
│       ├── opendal feature "default" (*)
│       ├── opendal feature "layers-metrics" (*)
│       ├── opendal feature "layers-tracing" (*)
│       ├── opendal feature "services-ipfs" (*)
│       ├── opendal feature "services-moka" (*)
│       ├── opendal feature "services-redis" (*)
│       ├── opendal feature "trust-dns" (*)
├── opendal feature "default" (*)
├── opendal feature "layers-metrics" (*)
├── opendal feature "layers-tracing" (*)
├── opendal feature "services-ipfs" (*)
├── opendal feature "services-moka" (*)
├── opendal feature "services-redis" (*)
├── opendal feature "trust-dns" (*)
├── opendal feature "default" (*)
├── opendal feature "layers-metrics" (*)
├── opendal feature "layers-tracing" (*)
├── opendal feature "services-ipfs" (*)
├── opendal feature "services-moka" (*)
├── opendal feature "services-redis" (*)
├── opendal feature "trust-dns" (*)
├── opendal feature "default" (*)
├── opendal feature "layers-metrics" (*)
├── opendal feature "layers-tracing" (*)
├── opendal feature "services-ipfs" (*)
├── opendal feature "services-moka" (*)
├── opendal feature "services-redis" (*)
├── opendal feature "trust-dns" (*)
├── opendal feature "default" (*)
├── opendal feature "layers-metrics" (*)
├── opendal feature "layers-tracing" (*)
├── opendal feature "services-ipfs" (*)
├── opendal feature "services-moka" (*)
├── opendal feature "services-redis" (*)
├── opendal feature "trust-dns" (*)
│   │   ├── opendal feature "default" (*)
│   │   ├── opendal feature "layers-metrics" (*)
│   │   ├── opendal feature "layers-tracing" (*)
│   │   ├── opendal feature "services-ipfs" (*)
│   │   ├── opendal feature "services-moka" (*)
│   │   ├── opendal feature "services-redis" (*)
│   │   ├── opendal feature "trust-dns" (*)
        ├── opendal feature "default" (*)
        ├── opendal feature "layers-metrics" (*)
        ├── opendal feature "layers-tracing" (*)
        ├── opendal feature "services-ipfs" (*)
        ├── opendal feature "services-moka" (*)
        ├── opendal feature "services-redis" (*)
        ├── opendal feature "trust-dns" (*)
```

**Review by dantengsky — APPROVED** [review]

**Comment by Xuanwo** [comment]
This pull request is of satisfactory quality to be merged.

However, I have a question regarding the cargo building process. As far as I am aware, cargo should include all the features in the final binary, but it seems that this feature is not being passed through. 

@PsiACE, could you kindly clarify?

**Review by PsiACE — APPROVED** [review]

**Comment by PsiACE** [comment]
> @PsiACE, could you kindly clarify?

The version "2" resolver avoids unifying features in a few situations where that unification can be unwanted.

**Review by sundy-li — APPROVED** [review]

**Pull request merged**
