### PR TITLE
unify crate Bincode repo

### LINKED ISSUE #4357: Question: two version of crate Bincode used
**Summary**

Currently, there are two different versions of crate `bincode` used, shall we pick just one version of them?

one in query:

https://github.com/datafuselabs/databend/blob/45d9bd7cd70afbe1d19f6ba93a78a0950a1d7d03/query/Cargo.toml#L67

the other one in common-io:

https://github.com/datafuselabs/databend/blob/45d9bd7cd70afbe1d19f6ba93a78a0950a1d7d03/common/io/Cargo.toml#L20

### PR DESCRIPTION
**Pull request by dantengsky**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

unify crate `bincode`'s repo to`git = "https://github.com/datafuse-extras/bincode", rev = "fd3f9ff" `

## Changelog

- Other 
- Not for changelog (changelog entry is not required)

## Related Issues

Fixes #4357

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Review by sundy-li — APPROVED** [review]

**Comment by BohuTANG** [comment]
PR is Draft, does it ready for merge? @dantengsky

**Comment by dantengsky** [comment]
> PR is Draft, does it ready for merge? @dantengsky

oops, forget to convert the status. yes, it is ready for merge.

**Comment by Xuanwo** [comment]
What changes we have applied for bincode? Is it possible to send it back upstream? Keeping `upstream first` will help reduce our maintenance burden.

**Pull request merged**
