### PR TITLE
[Build] Fix `make docker`

### LINKED ISSUE #4123: bug: make docker may not work properly
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

https://github.com/datafuselabs/databend/tree/f40e411ed1117aea8b1aa83e3f14fe289b84419e

### What's Wrong?

After forking and cloning the repo to my laptop, I tried building from source and running in docker.
```bash
make build-release
make docker
```
and then run it
```bash
docker run --init --rm -p 11451:3307 -p 9000:9000 -p 8001:8001 datafuselabs/databend-query
```
However, it logged:
```text
docker run --init --rm -p 11451:3307 -p 9000:9000 -p 8001:8001 datafuselabs/databend-query:latest
# /databend-meta: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
# /databend-query: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
Try connect:
```bash
mysql -h 127.0.0.1 -P 11451 -u root                      
# ERROR 2013 (HY000): Lost connection to server at 'handshake: reading initial communication packet', system error: 11

clickhouse client --host 127.0.0.1 --port 9000
# ClickHouse client version 21.12.3.32 (official build).
# Connecting to 127.0.0.1:9000 as user default.
# Code: 210. DB::NetException: Connection reset by peer, while reading from socket (127.0.0.1:9000). (NETWORK_ERROR)

curl --location --request POST '127.0.0.1:8001/v1/statement/' --header 'Content-Type: text/plain' --data-raw 'SELECT avg(number) FROM numbers(1000000000)'
# curl: (56) Recv failure: connection reset by peer.

```

### What You Expected?

`databend-query` was healthily pumped up and running in docker, as same as `datafuselabs/databend:latest` pulled from dockerhub.
图片

Try to connect:
> `clickhouse` client is still unusable.
图片

### How to Reproduce?

Exactly as I described in `What's Wrong?`

### Anything Else?

Though knowing little about docker, after looking up `databend/docker/Dockerfile` and `dockerhub`, I consider `debian:buster` the one be to blame.
```dockerfile
# databend/docker/Dockerfile
FROM debian:buster
```
However, [`rootfs.manifest`](https://github.com/debuerreotype/docker-debian-artifacts/blob/de5fb2efd50a009baa2aaccd2b7874ec728bd7a9/buster/rootfs.manifest) of `debian:buster` contains nothing like `openssl` or `libssl`, this might be the cause.

Knowing nowhere to get the dockerfile of `datafuselabs/databend`, I don't know why `datafuselabs/databend` could work properly, neither...

```text
system: Arch Linux x86_64
kernel: Linux 5.15.19-1-lts
CPU: AMD Ryzen 7 5800H
rust toolchain: nightly 2022-02-07
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by ClSlaid**
Signed-off-by: ClSlaid <cailue@bupt.edu.cn>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

This PR fixes problem occurred in `make docker` described in #4123
docker run container
MySQL client connect successfully

## Changelog

- Bug Fix
- Build/Testing/CI

1. Changed `make docker`'s base image to `ubuntu:22.04`.
2. Add missing `tenant_id` in `docker/databend-query-docker.toml`.

## Related Issues

Fixes #4123

## Test Plan

Manual test:

```bash
# set up
docker pull datafuselabs/databend:latest
git clone git@github.com:datafuselabs/databend
cd databend
make build-release
make docker

# compare behaviour of following docker container
# datafuselabs/databend:latest
# datafuselabs/databend-query:latest
```

### CODE REVIEW

**Comment by ClSlaid** [comment]
@ZhiHanZ PTAL

**Comment by ZhiHanZ** [comment]
LGTM， nice work @ClSlaid !

**Comment by Xuanwo** [comment]
It's wired that macos-11 built failed, I re-triggered it.

**Review by Xuanwo — APPROVED** [review]
Nice job! And nice issue&PR description!

**Review by ZhiHanZ — APPROVED** [review]

**Pull request merged**
