### PR TITLE
chore(storage): use max_threads instead of max_storage_io_requests

### PR DESCRIPTION
**Pull request by zhyass**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

- Closes #issue

### CODE REVIEW

**Review by dantengsky — APPROVED** [review]

**Comment by dantengsky** [comment]
> local cloud cloud
> 
> ## ClickBench Report
> * **hits**: https://repo.databend.rs/benchmark/clickbench/pr/12089/5553457598/hits.html
> * **tpch**: https://repo.databend.rs/benchmark/clickbench/pr/12089/5553457598/tpch.html

the result looks weird, changes in this PR should not have significant impact on these benchmarks

**Comment by BohuTANG** [comment]
Trigger the bench again and let's check it again.

**Comment by BohuTANG** [comment]
Weird, the benchmark looks affected.

**Comment by dantengsky** [comment]
> Weird, the benchmark looks affected.

same feelings, if I understand this PR correctly, only three table functions, gc, analyze table and table compactions should be affected (which are definitely not used in perf).

@zhyass  any comments?

**Comment by zhyass** [comment]
> same feelings, if I understand this PR correctly, only three table functions, gc, analyze table and table compactions should be affected (which are definitely not used in perf).

Yes, it doesn't seem to have effect on the select. I suspect that some pr after 1.0.20-nightly is causing the problem?

**Comment by dantengsky** [comment]
@BohuTANG  

this PR vs Release@v1.2.**22**-nightly shows NO significant performance degradation

> ## ClickBench Report
> * **hits**: https://repo.databend.rs/benchmark/clickbench/pr/12089/5557153990/hits.html
> * **tpch**: https://repo.databend.rs/benchmark/clickbench/pr/12089/5557153990/tpch.html



The previous "weird" perf is based on Release@v1.2.**20**-nightly

## ClickBench Report
* **hits**: https://repo.databend.rs/benchmark/clickbench/pr/12089/5554826470/hits.html
* **tpch**: https://repo.databend.rs/benchmark/clickbench/pr/12089/5554826470/tpch.html

**Pull request merged**
