### PR TITLE
fix(metrics): fix query_scan_io* collect in select query

### LINKED ISSUE #12037: bug: incorrect value of  metrics `query_scan_io_bytes`
**Summary**

how to reproduce:

~~~
mysql> create table t as select * from numbers(1000);
Query OK, 1000 rows affected (0.14 sec)

mysql> truncate table system.metrics;
Query OK, 0 rows affected (0.02 sec)

mysql> select * from t ignore_result;
Empty set (0.07 sec)
Read 1000 rows, 7.81 KiB in 0.012 sec., 86.59 thousand rows/sec., 676.52 KiB/sec.

mysql> select * from system.metrics where metric like 'query_scan_io_bytes%';
+---------------------+---------+--------------------------------------------------------------------------------------------+-------+
| metric              | kind    | labels                                                                                     | value |
+---------------------+---------+--------------------------------------------------------------------------------------------+-------+
| query_scan_io_bytes | counter | {"kind":"TruncateTable","handler":"MySQL","cluster":"test_cluster","tenant":"test_tenant"} | 0.0   |
| query_scan_io_bytes | counter | {"handler":"MySQL","tenant":"test_tenant","kind":"CreateTable","cluster":"test_cluster"}   | 0.0   |
| query_scan_io_bytes | counter | {"kind":"Query","tenant":"test_tenant","cluster":"test_cluster","handler":"MySQL"}         | 0.0   |
+---------------------+---------+--------------------------------------------------------------------------------------------+-------+
3 rows in set (0.03 sec)
Read 96 rows, 10.46 KiB in 0.010 sec., 9.7 thousand rows/sec., 1.03 MiB/sec.
~~~

the value of metric `query_scan_io_bytes` is not supposed to be 0.

A rough debug shows that while gathering the metrics of the current ctx, the length of `Vec<Arc<StorageMetrics>>` is zero, which seems to be buggy.
 

https://github.com/datafuselabs/databend/blob/f19c2ac6d90aeefa94881118ad93960937d0fcc6/src/query/service/src/sessions/query_ctx_shared.rs#L215-L221

### PR DESCRIPTION
**Pull request by akoshchiy**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

- Closes #12037

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12454)

### CODE REVIEW

**Comment by dantengsky** [comment]
thanks! 

but seems value of metric `query_scan_io_bytes` is still not as expected:

did I miss something?


test.sql

~~~
select version();
drop table if exists t;
create table t as select * from numbers(1000);
truncate table system.metrics;
select * from t ignore_result;
select * from system.metrics where metric like 'query_scan_io_bytes%';
~~~

~~~
$ mysql -uroot -h127.0.0.1 -P3307  < test.sql
version()
8.0.26-v1.2.61-nightly-4436b2746c4f13e4e8f3a37a0f5202fbdb2823a4(rust-1.72.0-nightly-2023-08-14T09:13:39.009250324Z)
node	metric	kind	labels	value
O8vvTF1QP85qCQWc8rEjw7	query_scan_io_bytes	counter	{"handler":"MySQL","cluster":"test_cluster","kind":"TruncateTable","tenant":"test_tenant"}	  0.0
O8vvTF1QP85qCQWc8rEjw7	query_scan_io_bytes	counter	{"tenant":"test_tenant","handler":"MySQL","cluster":"test_cluster","kind":"CreateTable"}	0.0
O8vvTF1QP85qCQWc8rEjw7	query_scan_io_bytes	counter	{"handler":"MySQL","tenant":"test_tenant","cluster":"test_cluster","kind":"DropTable"}	  0.0
O8vvTF1QP85qCQWc8rEjw7	query_scan_io_bytes	counter	{"cluster":"test_cluster","kind":"Query","tenant":"test_tenant","handler":"MySQL"}	  0.0
~~~

**Comment by akoshchiy** [comment]
Yeah, I've got the same result :( 
I will deal with it.

**Comment by akoshchiy** [comment]
I think, the data was cached after table creation.
```
root@localhost> create table t as select * from numbers(1000);
1000 rows affected in (0.112 sec)

root@localhost> select * from system.caches;

SELECT
  *
FROM
  system.caches

┌──────────────────────────────────────────────────────────────────────────────┐
│          node          │              name              │ num_items │  size  │
│         String         │             String             │   UInt64  │ UInt64 │
├────────────────────────┼────────────────────────────────┼───────────┼────────┤
│ DRMIopJJCIjyXj6R4K0EC4 │ table_snapshot_cache           │         1 │      1 │
│ DRMIopJJCIjyXj6R4K0EC4 │ table_snapshot_statistic_cache │         0 │      0 │
│ DRMIopJJCIjyXj6R4K0EC4 │ segment_info_cache             │         1 │    545 │
│ DRMIopJJCIjyXj6R4K0EC4 │ bloom_index_filter_cache       │         0 │      0 │
│ DRMIopJJCIjyXj6R4K0EC4 │ bloom_index_meta_cache         │         0 │      0 │
│ DRMIopJJCIjyXj6R4K0EC4 │ prune_partitions_cache         │         0 │      0 │
│ DRMIopJJCIjyXj6R4K0EC4 │ file_meta_data_cache           │         0 │      0 │
└──────────────────────────────────────────────────────────────────────────────┘
7 rows in 0.032 sec. Processed 7 rows, 7B (218.3 rows/s, 16.75 KiB/s)
```

It will work after restarting databend-query, when the cache is empty.
```
root@localhost> select * from system.caches;

SELECT
  *
FROM
  system.caches

┌──────────────────────────────────────────────────────────────────────────────┐
│          node          │              name              │ num_items │  size  │
│         String         │             String             │   UInt64  │ UInt64 │
├────────────────────────┼────────────────────────────────┼───────────┼────────┤
│ axlEKiDDBpQ26gXeQt3Em2 │ table_snapshot_cache           │         0 │      0 │
│ axlEKiDDBpQ26gXeQt3Em2 │ table_snapshot_statistic_cache │         0 │      0 │
│ axlEKiDDBpQ26gXeQt3Em2 │ segment_info_cache             │         0 │      0 │
│ axlEKiDDBpQ26gXeQt3Em2 │ bloom_index_filter_cache       │         0 │      0 │
│ axlEKiDDBpQ26gXeQt3Em2 │ bloom_index_meta_cache         │         0 │      0 │
│ axlEKiDDBpQ26gXeQt3Em2 │ prune_partitions_cache         │         0 │      0 │
│ axlEKiDDBpQ26gXeQt3Em2 │ file_meta_data_cache           │         0 │      0 │
└──────────────────────────────────────────────────────────────────────────────┘
7 rows in 0.169 sec. Processed 7 rows, 7B (41.54 rows/s, 3.19 KiB/s)

root@localhost> select * from system.metrics where metric like 'query_scan_io%';

SELECT
  *
FROM
  system.metrics
WHERE
  metric LIKE 'query_scan_io%'

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│          node          │        metric       │   kind  │                                         labels                                         │  value │
│         String         │        String       │  String │                                         String                                         │ String │
├────────────────────────┼─────────────────────┼─────────┼────────────────────────────────────────────────────────────────────────────────────────┼────────┤
│ axlEKiDDBpQ26gXeQt3Em2 │ query_scan_io_bytes │ counter │ {"cluster":"test_cluster","handler":"HTTPQuery","kind":"Query","tenant":"test_tenant"} │ 0.0    │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
1 row in 0.056 sec. Processed 42 rows, 42B (748.65 rows/s, 109.25 KiB/s)

root@localhost> select * from t ignore_result;

SELECT
  *
FROM
  t ignore_result

0 row in 0.054 sec. Processed 1 thousand rows, 1000B (18.57 thousand rows/s, 34.14 KiB/s)

root@localhost> select * from system.metrics where metric like 'query_scan_io%';

SELECT
  *
FROM
  system.metrics
WHERE
  metric LIKE 'query_scan_io%'

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│          node          │        metric       │   kind  │                                         labels                                         │  value │
│         String         │        String       │  String │                                         String                                         │ String │
├────────────────────────┼─────────────────────┼─────────┼────────────────────────────────────────────────────────────────────────────────────────┼────────┤
│ axlEKiDDBpQ26gXeQt3Em2 │ query_scan_io_bytes │ counter │ {"handler":"HTTPQuery","tenant":"test_tenant","kind":"Query","cluster":"test_cluster"} │ 462.0  │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
1 row in 0.038 sec. Processed 60 rows, 60B (1.58 thousand rows/s, 211.03 KiB/s)

```

**Comment by akoshchiy** [comment]
@dantengsky what do you think? It seems legit.

**Comment by BohuTANG** [comment]
Thanks for the contribution.
There are a conflicting file need to fix.

**Comment by akoshchiy** [comment]
I see some failed tests, could we restart it? I'm not sure, that the problem is in that pr.

**Review by sundy-li — APPROVED** [review]

**Comment by dantengsky** [comment]
@akoshchiy 

I sincerely apologize for the late response.

> I think, the data was cached after table creation.

Agree, the issue https://github.com/datafuselabs/databend/pull/12454  is partially caused by the caching of table metadata, but table data is **not cached** by default, and reading them should affect the `query_scan_io_bytes`,  which is confusing.

 After some investigation, I found there might be more flaws in the current way of collecting `query_scan_io_bytes`:
 
 - The "interceptor" which collects the `query_scan_io_bytes` seems only work for **async** io operations
   
https://github.com/datafuselabs/databend/blob/f3bb848c424d411e193d8f747ecf30c36c2aada7/src/common/storage/src/common_metrics/storage_metrics.rs#L243-L253

   if local `fs`  is configured as the storage backend (the typical setting for local dev), **synchronous** io will be used. 
   

- Even worse, the instances of `Table` that read the table data (not the table metadata) seem not to be tracked properly

   I think that is the reason for
    
    > It will work after evicting the cache (here I've just restarted databend-query).
    
    Stmt `create table t as select * from numbers(1000)` will cache the table meta of `t` during execution.
    
    The subsequent query `select * from t ignore_result` fetches all the table meta from the cache, although the query also read data from disk, the relevant io metrics were not kept properly.

   After restart, the table metadata cache is cleared, and the io of reading table metadata is kept as the value of metric `query_scan_io_bytes`.
   

Let's merge this PR first, and fix the above issues in other PR(s).

Thanks!

**Review by dantengsky — APPROVED** [review]

**Pull request merged**
