### PR TITLE
feat(query): add optimize rule rule_eliminate_groupby

### LINKED ISSUE #9611: Feature: Add rule_eliminate_groupby
**Summary**

Description for this feature.

Query with `group by a, b, f(a,b)` could be rewritten to `group by a,b`, this could save GroupKey space in hashmap.

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Query with group by a, b, f(a,b) could be rewritten to group by a,b, this could save GroupKey space in hashmap.

Closes #9611

### CODE REVIEW

**Comment by sundy-li** [comment]
Need a stateless test.

**Comment by leiysky** [comment]
I'm afraid this rule cannot work as you expected, since the group by expressions will be evaluated by a `EvalScalar` operator and then referenced in `Aggregate` operator with `BoundColumnRef`.

For example:
```
mysql> explain select count(*) from numbers(10) group by number, number+1;
+----------------------------------------------------------------------+
| explain                                                              |
+----------------------------------------------------------------------+
| EvalScalar                                                           |
| ├── expressions: [COUNT(*) (#3)]                                     |
| ├── estimated rows: 10.00                                            |
| └── AggregateFinal                                                   |
|     ├── group by: [number, (number + 1)]                             |
|     ├── aggregate functions: [count()]                               |
|     ├── estimated rows: 10.00                                        |
|     └── AggregatePartial                                             |
|         ├── group by: [number, (number + 1)]                         |
|         ├── aggregate functions: [count()]                           |
|         ├── estimated rows: 10.00                                    |
|         └── EvalScalar                                               |
|             ├── expressions: [plus(numbers.number (#0), 1_u8)]       |
|             ├── estimated rows: 10.00                                |
|             └── TableScan                                            |
|                 ├── table: default.system.numbers                    |
|                 ├── read rows: 10                                    |
|                 ├── read bytes: 80                                   |
|                 ├── partitions total: 1                              |
|                 ├── partitions scanned: 1                            |
|                 ├── push downs: [filters: [], limit: NONE]           |
|                 └── estimated rows: 10.00                            |
+----------------------------------------------------------------------+
22 rows in set (0.06 sec)
Read 0 rows, 0.00 B in 0.006 sec., 0 rows/sec., 0.00 B/sec.
```

And this optimization should be based on the functional dependency, which we have the plan to implement recently #7438.

**Comment by sundy-li** [comment]
Can we move the child `EvalScalar`: `number + 1` to his parent if we do not have `functional dependency optimization` now?

**Comment by leiysky** [comment]
> Can we move the child `EvalScalar`: `number + 1` to his parent if we do not have `functional dependency optimization` now?

It will be a big modification, I'd rather implement the functional dependency now to resolve the issue.

**Pull request closed without merging**
