### PR TITLE
[functions/xxhash] add xxhash32 and xxhash64

### PR DESCRIPTION
**Pull request by PsiACE**
Signed-off-by: Chojan Shang <psiace@outlook.com>

I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

- [x] add xxhash32 and xxhash64
- [x] add unit tests
- [x] add stateless tests
- [x] add docs

Tips: Due to the different versions of xxhash used by different databases, the results may not be consistent.

## Changelog

- New Feature
- Need Documentation (Need to add documentation to https://databend.rs)

## Related Issues

Fixes #issue

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by PsiACE** [comment]
The current implementation of siphash includes date types, but it might be better to rewrite it with string2number.

**Comment by PsiACE** [comment]
emmm, wait #3563 .

The current results are the same as the xxhash v0.8.1 results and may differ from those of other databases.

**Comment by sundy-li** [comment]
@mergifiy  update

**Review by sundy-li — APPROVED** [review]

**Review by Xuanwo — APPROVED** [review]

**Comment by Xuanwo** [comment]
@mergify update

**Pull request merged**
