### PR TITLE
chore: add the switch of enable_cbo

### PR DESCRIPTION
**Pull request by xudong963**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Add the switch of enable_cbo

Fixes #issue

### CODE REVIEW

**Review by sundy-li — APPROVED** [review]

**Comment by TCeason** [comment]
Maybe you could add a brief introduction to the system-settings.md

**Comment by xudong963** [comment]
> Maybe you could add a brief introduction to the system-settings.md

Currently, we do not intend to make it visible to users, just used for debug.

**Comment by BohuTANG** [comment]
test_sqllogic_base_cluster_linux always failed in this PR :/

**Review by leiysky — APPROVED** [review]

**Comment by BohuTANG** [comment]
```
Following failed statements:
---------------------------------------------
Runner: mysql
ErrorType: statement query get result not equal to expected
Message: 
 Expected:
enable_async_insert 0 0 SESSION Whether the client open async insert mode, default value: 0 UInt64
enable_new_processor_framework 1 1 SESSION Enable new processor framework if value != 0, default value: 1 UInt64
enable_planner_v2 1 1 SESSION Enable planner v2 by setting this variable to 1, default value: 1 UInt64
 Actual:
enable_async_insert  0  0  SESSION  Whether the client open async insert mode, default value: 0  UInt64
enable_cbo  1  1  SESSION  If enable cost based optimization, default value: 1  UInt64
enable_new_processor_framework  1  1  SESSION  Enable new processor framework if value != 0, default value: 1  UInt64
enable_planner_v2  1  1  SESSION  Enable planner v2 by setting this variable to 1, default value: 1  UInt64
 Statement:
Parsed Statement
    at_line: 34,
    s_type: Statement: query, type: TTTTTT, query_type: TTTTTT, retry: False,
    suite_name: base/06_show/06_0003_show_settings,
    text:
        SHOW SETTINGS LIKE 'enable%';
    results: [(<re.Match object; span=(0, 4), match='----'>, 40, 'enable_async_insert 0 0 SESSION Whether the client open async insert mode, default value: 0 UInt64\nenable_new_processor_framework 1 1 SESSION Enable new processor framework if value != 0, default value: 1 UInt64\nenable_planner_v2 1 1 SESSION Enable planner v2 by setting this variable to 1, default value: 1 UInt64')],
    runs_on: {'mysql'},
```

**Pull request merged**
