### PR TITLE
website: Use yarn instead of npm to fix #3283

### LINKED ISSUE #3283: Build website failure
**Summary**

CC: @Xuanwo 

```
:> npm start

Compiled with problems:X

ERROR in ./docs/cli/images/bendctl-how-to-use.gif (./node_modules/url-loader/dist/cjs.js?limit=10000&name=assets/images/[name]-[hash].[ext]&fallback=file-loader!./docs/cli/images/bendctl-how-to-use.gif)

Module build failed: Error: Unknown keyword formatMinimum
    at get (/Users/winter/Source/databend/website/databend/node_modules/_ajv-keywords@5.1.0@ajv-keywords/dist/index.js:25:15)
    at ajvKeywords (/Users/winter/Source/databend/website/databend/node_modules/_ajv-keywords@5.1.0@ajv-keywords/dist/index.js:10:13)
    at Object.<anonymous> (/Users/winter/Source/databend/website/databend/node_modules/schema-utils/dist/validate.js:58:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/winter/Source/databend/website/databend/node_modules/schema-utils/dist/index.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)


ERROR in ./docs/development/images/profiling-flamegraph.png (./node_modules/url-loader/dist/cjs.js?limit=10000&name=assets/images/[name]-[hash].[ext]&fallback=file-loader!./docs/development/images/profiling-flamegraph.png)

Module build failed: Error: Unknown keyword formatMinimum
    at get (/Users/winter/Source/databend/website/databend/node_modules/_ajv-keywords@5.1.0@ajv-keywords/dist/index.js:25:15)
    at ajvKeywords (/Users/winter/Source/databend/website/databend/node_modules/_ajv-keywords@5.1.0@ajv-keywords/dist/index.js:10:13)
    at Object.<anonymous> (/Users/winter/Source/databend/website/databend/node_modules/schema-utils/dist/validate.js:58:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/winter/Source/databend/website/databend/node_modules/schema-utils/dist/index.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

Read https://github.com/facebook/docusaurus/issues/6073#issuecomment-989630651 for detailed explanations.

## Changelog

- Documentation

## Related Issues

Fixes #3283

### CODE REVIEW

**Comment by Josh-Cena** [comment]
FYI, you can just remove the `@svgr/webpack`, `file-loader`, and `url-loader` dependencies completely from your package.json. That was a dirty hack we used to make the project work in Yarn PnP which (a) you aren't using and (b) will be properly fixed in the next release this week. Probably would make the package manager less confused

**Comment by Xuanwo** [comment]
Thanks for your advice!

**Review by PsiACE — APPROVED** [review]
LGTM

**Pull request merged**
