### PR TITLE
fix(insert): server panic when exceeds max active sessions

### LINKED ISSUE #5844: bug: server panic when exceed max_active_sessions in async insert mode
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

bf596a382ac3d3f4b1dad004faaffd4d5bfa60ee

### What's Wrong?

https://github.com/datafuselabs/databend/pull/5567#issuecomment-1149339319

### How to Reproduce?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by fkuner**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

1. bug fix: delete processing entry
2. bug fix: return err when server panic

cc @BohuTANG 

## Changelog

- Bug Fix

## Related Issues

Fixes #5844 

https://github.com/datafuselabs/databend/pull/5567#issuecomment-1149339319

### CODE REVIEW

**Comment by b41sh** [comment]
Almost ok for me, it's better to add some unit tests.

**Review by sundy-li — APPROVED** [review]

**Comment by fkuner** [comment]
> 1. entry

Good idea. Now the client can control the `enable_async_insert`, so we can add more stateless-test.

**Comment by fkuner** [comment]
> Almost ok for me, it's better to add some unit tests.

Good idea. Now the client can control the `enable_async_insert`, so we can add more stateless-test.

**Comment by fkuner** [comment]
I wll add a new pr to cover all test cases about `async-insert`.

**Pull request merged**
