### PR TITLE
chore(ci): link with mold in build-tool

### LINKED ISSUE #4180: [Feature][CI] replace CI's linker with `mold`
**Summary**
I learned about [`mold`](https://github.com/rui314/mold) the linker from this [tweet](https://twitter.com/lichuang/status/1493156835477852163) and it turned out to be much faster and consumes much less memory than `gold`.

Here are my laptop's configurations:
```text
CPU: AMD Ryzen 7 5800H
Hard Drive: Zhitai PC005 SSD
System: Arch Linux
Kernel: Linux 5.15.22-1-lts x86_64
RAM: 13GB
rust toolchain: x86_64_unknown_linux_gnu nightly v1.60.0
```
time result:
```bash
cd databend && cargo clean

# with mold
/bin/time -v cargo test
# Command exited with non-zero status 101
#        Command being timed: "cargo test"
#        User time (seconds): 2182.67
#        System time (seconds): 160.52
#        Percent of CPU this job got: 657%
#        Elapsed (wall clock) time (h:mm:ss or m:ss): 5:56.15
#        Average shared text size (kbytes): 0
#        Average unshared data size (kbytes): 0
#        Average stack size (kbytes): 0
#        Average total size (kbytes): 0
#        Maximum resident set size (kbytes): 4888048
#        Average resident set size (kbytes): 0
#        Major (requiring I/O) page faults: 50383
#        Minor (reclaiming a frame) page faults: 41360989
#        Voluntary context switches: 352776
#        Involuntary context switches: 321932
#        Swaps: 0
#        File system inputs: 6283912
#        File system outputs: 21923208
#        Socket messages sent: 0
#        Socket messages received: 0
#        Signals delivered: 0
#        Page size (bytes): 4096
#        Exit status: 101

# with gold
cargo clean && /bin/time -v cargo test
# eating up too much swap memory, drawing down it's time benchmark

# Command exited with non-zero status 101
#        Command being timed: "cargo test"
#        User time (seconds): 2723.20
#        System time (seconds): 432.94
#        Percent of CPU this job got: 432%
#        Elapsed (wall clock) time (h:mm:ss or m:ss): 12:09.36
#        Average shared text size (kbytes): 0
#        Average unshared data size (kbytes): 0
#        Average stack size (kbytes): 0
#        Average total size (kbytes): 0
#        Maximum resident set size (kbytes): 4213836
#        Average resident set size (kbytes): 0
#        Major (requiring I/O) page faults: 5896400
#        Minor (reclaiming a frame) page faults: 74752048
#        Voluntary context switches: 6994245
#        Involuntary context switches: 306750
#        Swaps: 0
#        File system inputs: 214730184
#        File system outputs: 59830592
#        Socket messages sent: 0
#        Socket messages received: 0
#        Signals delivered: 0
#        Page size (bytes): 4096
#        Exit status: 101
```

Almost 60% reduction of time usage and 90% reduction of maximum memory consumption.

### PR DESCRIPTION
**Pull request by everpcpc**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

link with mold for debug linux gnu

### with mold

on x86_64-unknown-linux-gnu
```
 Finished dev [unoptimized + debuginfo] target(s) in 3m 26s

String dump of section '.comment':
  [     0]  GCC: (Debian 10.2.1-6) 10.2.1 20210110
  [    27]  mold 1.1.1 (c1af9c97e763a1d521889191a83b27bd6c43b351; compatible with GNU ld)
  [    75]  clang version 13.0.0
```

on aarch64-unknown-linux-gnu
```
Finished dev [unoptimized + debuginfo] target(s) in 3m 38s

String dump of section '.comment':
  [     0]  GCC: (Debian 10.2.1-6) 10.2.1 20210110
  [    27]  mold 1.1.1 (c1af9c97e763a1d521889191a83b27bd6c43b351; compatible with GNU ld)
  [    75]  GCC: (crosstool-NG ) 5.2.0
```

### without mold

on x86_64-unknown-linux-gnu
```
Finished dev [unoptimized + debuginfo] target(s) in 5m 53s

String dump of section '.comment':
  [     0]  GCC: (Debian 10.2.1-6) 10.2.1 20210110
  [    27]  clang version 13.0.0
```

on aarch64-unknown-linux-gnu
```
Finished dev [unoptimized + debuginfo] target(s) in 5m 11s

String dump of section '.comment':
  [     0]  GCC: (Debian 10.2.1-6) 10.2.1 20210110
  [    27]  GCC: (crosstool-NG ) 5.2.0
```

## Changelog

- Build/Testing/CI

## Related Issues

Fixes #4180

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Review by PsiACE — APPROVED** [review]

**Review by Xuanwo — APPROVED** [review]

**Comment by Xuanwo** [comment]
@ClSlaid used to work on the same issue https://github.com/datafuselabs/databend/pull/4196, invited for a review, and thanks for his hard work!

**Comment by ClSlaid** [comment]
The PR seems to work by replacing the GNU `Gold` with `mold`. It's good but, will it also replace the builder for `aarch64-linux-unknown-gnu`? @Xuanwo

**Comment by everpcpc** [comment]
> The PR seems to work by replacing the GNU `Gold` with `mold`. It's good but, will it also replace the builder for `aarch64-linux-unknown-gnu`? @Xuanwo

Yes, it will replace ld under `x86-64` and `aarch64`.
They both working with the mold binary release:
```
mold: supported targets: elf32-i386 elf64-x86-64 elf64-littleaarch64
mold: supported emulations: elf_i386 elf_x86_64 aarch64linux aarch64elf
```

**Review by ClSlaid — COMMENTED** [review]
It's nice and clear, looks good to me.

**Pull request merged**
