### PR TITLE
dal2: Implement fs support

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Part of https://github.com/datafuselabs/databend/issues/3677

## Changelog

- New Feature

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by BohuTANG** [comment]
Oops, there are some Conflicting need resolved :/

**Comment by Xuanwo** [comment]
> Oops, there are some Conflicting need resolved :/

I will resolve the conflicting after PR approved.

Ping @dantengsky and @Veeupup to take a look, thanks!

**Comment by Veeupup** [comment]
/LGTM
the code looks very clear!

**Comment by dantengsky** [comment]
> Ping @dantengsky and @Veeupup to take a look, thanks!
LGTM : )

**Pull request merged**
