### PR TITLE
chore(query): enable max threads for sort transform

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Closes #issue

### CODE REVIEW

**Review by zhang2014 — APPROVED** [review]

**Review by Xuanwo — APPROVED** [review]

**Review by RinChanNOWWW — APPROVED** [review]

**Comment by RinChanNOWWW** [comment]
Can change arrow2 to 95e117d3f0bb69c52617d2e0b1a9564492b063a0 to fix the `null_first` bug.

**Comment by BohuTANG** [comment]
```
logictest.LogicError: Runner: clickhouse
ErrorType: statement query get result not equal to expected
Message: 
 Expected:
Query default                                                                   
 Actual:
Idle  default
Query  default
Query  default
Query  default                      
 Statement:
Parsed Statement
    at_line: 1,
    s_type: Statement: query, type: TT, query_type: TT, retry: False,
    suite_name: base/03_dml/03_0011_select_from_system_processes,
    text:
        select command, database from system.processes;
    results: [(<re.Match object; span=(0, 4), match='----'>, 5, 'Query default')],
    runs_on: {'mysql', 'clickhouse', 'http'},
 Start Line: 5, Result Label: 
```

**Comment by sundy-li** [comment]
> select command, database from system.processes;
That's really strange, I still have no idea why it affected this query.

**Comment by BohuTANG** [comment]
The new version of the arrow has some broken.

**Comment by BohuTANG** [comment]
This test always failed in cluster mode, it's strange:
``
Runner: mysql
ErrorType: statement query get result not equal to expected
Message: 
 Expected:
Query default                                                                   
 Actual:
Idle  default
Query  default                                                    
 Statement:
Parsed Statement
    at_line: 1,
    s_type: Statement: query, type: TT, query_type: TT, retry: False,
    suite_name: base/03_dml/03_0011_select_from_system_processes,
    text:
        select command, database from system.processes;
    results: [(<re.Match object; span=(0, 4), match='----'>, 5, 'Query default')],
    runs_on: {'http', 'clickhouse', 'mysql'},
 Start Line: 5, Result Label: `
``

**Comment by BohuTANG** [comment]
Let's merge first. If it still fails let's skip it and address it then.

**Pull request merged**
