### PR TITLE
docs: add vacuum table doc

### PR DESCRIPTION
**Pull request by lichuang**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary
docs: add vacuum table doc

Closes #issue

### CODE REVIEW

**Comment by soyeric128** [comment]
Screenshot 2023-05-10 at 5 36 23 PM

- How do i apply a license so that i can run the command?
- What is difference between "vacuum table t retain 0 hours" and "optimize table t purge all"?
- "vacuum table" does NOT purge the latest snapshots of a table, right?

**Comment by BohuTANG** [comment]
@soyeric128 Set Enterprise license key doc is in https://github.com/datafuselabs/databend/pull/11395 not merged yet, but we can reference from it.

**Comment by soyeric128** [comment]
> @soyeric128 Set Enterprise license key doc is in #11395 not merged yet, but we can reference from it.

Ok, i will work on this branch after i get a chance to try it out.

**Comment by BohuTANG** [comment]
Now we support the enterprise feature banner: https://github.com/datafuselabs/databend/pull/11434

image


cc@soyeric128

**Review by BohuTANG — APPROVED** [review]

**Pull request merged**
