### PR TITLE
Improve Unknown database error message

### LINKED ISSUE #4249: enhance database not exist error message
**Summary**

```
mysql> create table test.test;
ERROR 1105 (HY000): Code: 1003, displayText = test.
...
mysql> create database test;
Query OK, 0 rows affected (0.01 sec)
Read 0 rows, 0 B in 0.004 sec., 0 rows/sec., 0 B/sec.
mysql> create table test.test(id int);
Query OK, 0 rows affected (0.01 sec)
Read 0 rows, 0 B in 0.009 sec., 0 rows/sec., 0 B/sec.
```

verson:
mysql> select version();
+-------------------------------------------------------------------------------------+
| version()                                                                           |
+-------------------------------------------------------------------------------------+
| DatabendQuery v-0.1.0-9a31fe4-simd(1.60.0-nightly-2022-02-24T16:35:27.533355+00:00) |
+-------------------------------------------------------------------------------------+
1 row in set (0.02 sec)
Read 1 rows, 1 B in 0.006 sec., 179.61 rows/sec., 179.61 B/sec.

### PR DESCRIPTION
**Pull request by july2993**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary
Improve Unknown database error message

Before this pr:
mysql> create table test.test;
ERROR 1105 (HY000): Code: 1003, displayText = test.

After this pr:
mysql> create table test.test(id int);
ERROR 1105 (HY000): Code: 1003, displayText = Unknown database 'test'.
## Changelog

- Improvement

## Related Issues

Fixes #4249 

## Test Plan
start up services by running up.sh

<details>
  <summary>Click to expand up.sh!</summary>

```sh
cat - > "/tmp/db-meta.toml" <<EOF
log_dir = "metadata/_logs"
admin_api_address = "127.0.0.1:8101"
grpc_api_address = "127.0.0.1:9101"

[raft_config]
id = 1
single = true
raft_dir = "metadata/datas"
EOF



cat - > "/tmp/db-query.toml" <<EOF
[log]
log_level = "INFO"
log_dir = "benddata/_logs"

[query]
# For admin RESET API.
admin_api_address = "127.0.0.1:8001"

# Metrics.
metric_api_address = "127.0.0.1:7071"

# Cluster flight RPC.
flight_api_address = "127.0.0.1:9091"

#

# Query MySQL Handler.
mysql_handler_host = "127.0.0.1"
mysql_handler_port = 3307

# Query ClickHouse Handler.
clickhouse_handler_host = "127.0.0.1"
clickhouse_handler_port = 9001

# Query HTTP Handler.
http_handler_host = "127.0.0.1"
http_handler_port = 8081

tenant_id = "tenant1"
cluster_id = "cluster1"

[meta]
# databend-meta grpc api address.
meta_address = "127.0.0.1:9101"
meta_username = "root"
meta_password = "root"

[storage]
# disk|s3
storage_type = "disk"

[storage.disk]
data_path = "bendata/datas"

[storage.s3]

[storage.azure_storage_blob]
EOF

stop_services() {
    killall -9 databend-meta || true
    killall -9 databend-query || true
}

trap stop_services EXIT

./target/debug/databend-meta -c /tmp/db-meta.toml > meta.log 2>&1 &

sleep 4
./target/debug/databend-query -c /tmp/db-query.toml > query.log 2>&1 &


while true;
do
    sleep 1
done
```

</details>

try create table:
```
mysql -h127.0.0.1 -uroot -P3307
mysql> create table test.test(id int);
ERROR 1105 (HY000): Code: 1003, displayText = Unknown database 'test'.
```

### CODE REVIEW

**Review by BohuTANG — APPROVED** [review]
Nice work!
Thank you @july2993 !

**Comment by BohuTANG** [comment]
```
failures:

---- sql::plan_parser::test_plan_parser stdout ----
thread 'sql::plan_parser::test_plan_parser' panicked at 'assertion failed: `(left == right)`: insert-simple

Diff < left / right > :
<"Code: 1025, displayText = Unknown table: 't'."
>"Code: 1025, displayText = Unknown table 't'."

```

**Comment by BohuTANG** [comment]
```
failures:

---- sql::statements::statement_copy::test_statement_copy stdout ----
thread 'sql::statements::statement_copy::test_statement_copy' panicked at 'assertion failed: `(left == right)`
  left: `"Code: 1025, displayText = Unknown table: 'mytable'."`,
 right: `"Code: 1025, displayText = Unknown table 'mytable'."`: copy-external-table-not-found-error', 
```

To check the unit test locally, we can run:
```
make unit-test
```

**Comment by july2993** [comment]
> statements

Thinks. I run it before, but it seems do not run this case locally in my env(searching `test_statement_copy` find nothing in the output).

also, there are some other case failures(seems unrelate to this pr):
```
test meta_node::meta_node_all::test_meta_node_snapshot_replication ... FAILED
test grpc::metasrv_grpc_api::test_restart ... ok
test meta_node::meta_node_all::test_meta_node_add_database ... FAILED
test store::test_meta_store_current_snapshot ... ok
test meta_node::meta_node_all::test_meta_node_write_to_local_leader ... FAILED
test store::test_meta_store_restart ... ok
test grpc::metasrv_grpc_kv_api_restart_cluster::test_kv_api_restart_cluster_token_expired ... ok
test grpc::metasrv_grpc_kv_api_restart_cluster::test_kv_api_restart_cluster_write_read ... ok
test store::test_impl_raft_storage ... ok
test grpc::metasrv_grpc_kv_api::test_metasrv_kv_api ... ok
test meta_node::meta_node_kv_api::test_meta_node_kv_api has been running for over 60 seconds
test store::test_meta_store_install_snapshot has been running for over 60 seconds
test meta_node::meta_node_kv_api::test_meta_node_kv_api ... ok
test store::test_meta_store_install_snapshot ... ok

failures:

---- meta_node::meta_node_all::test_meta_node_snapshot_replication stdout ----
Error: timeout after 10s when non-voter replicated all logs .last_log_index -> Some(15) latest: Metrics{id:1,Learner, term:1, last_log:None, last_applied:None, leader:Some(0), membership:{log_id:0-0 membership:[{1}]}, snapshot:None, replication:
thread 'meta_node::meta_node_all::test_meta_node_snapshot_replication' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/8769f4ef2fe1efddd1f072485f97f568e7328f79/library/test/src/lib.rs:187:5

---- meta_node::meta_node_all::test_meta_node_add_database stdout ----
Error: timeout after 10s when  .last_applied -> Some(7) latest: Metrics{id:1,Follower, term:1, last_log:Some(7), last_applied:Some(LogId { term: 1, index: 6 }), leader:Some(0), membership:{log_id:1-7 membership:[{0, 1, 2}]}, snapshot:None, replication:
thread 'meta_node::meta_node_all::test_meta_node_add_database' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/8769f4ef2fe1efddd1f072485f97f568e7328f79/library/test/src/lib.rs:187:5

---- meta_node::meta_node_all::test_meta_node_write_to_local_leader stdout ----
Error: raft stopped
thread 'meta_node::meta_node_all::test_meta_node_write_to_local_leader' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/8769f4ef2fe1efddd1f072485f97f568e7328f79/library/test/src/lib.rs:187:5


failures:
    meta_node::meta_node_all::test_meta_node_add_database
    meta_node::meta_node_all::test_meta_node_snapshot_replication
    meta_node::meta_node_all::test_meta_node_write_to_local_leader

test result: FAILED. 47 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 77.26s
```

**Comment by lichuang** [comment]
LGTM

**Pull request merged**
