### PR TITLE
refactor: enable chunked reading of hive table

### PR DESCRIPTION
**Pull request by dantengsky**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

enable chunked reading of hive table. coauthored by @sandflee 
  

Fixes #issue

### CODE REVIEW

**Comment by sandflee** [comment]
is it to resolve high sys cpu problem?

**Comment by dantengsky** [comment]
> is it to resolve high sys cpu problem?

yeah, trying it. but refactories committed so far are unlikely able to solve the high sys cpu problem yet ;(

**Comment by sandflee** [comment]
a big step, I'll try to test this pr on our cluster tomorrow :)

**Comment by dantengsky** [comment]
> a big step, I'll try to test this pr on our cluster tomorrow :)
cc @sandflee 
Thanks for the performance testing, and the data you've provided. They are very enlightening.
Let's evaluate this patch again after PR #7300 is merged.

btw, would you please share with us your patched version (the branch) of this PR (which enabled chunked-deserialization of page group)?

I'd like to merge it with this PR.

**Comment by BohuTANG** [comment]
@sandflee 
Please take a review when you have time, Thanks.

**Comment by sandflee** [comment]
totally LGTM except one minor change.

**Review by BohuTANG — APPROVED** [review]

**Pull request merged**
