### PR TITLE
feat: store result cache as parquet file.

### PR DESCRIPTION
**Pull request by RinChanNOWWW**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Tracking in #10010

### CODE REVIEW

**Review by ariesdevil — APPROVED** [review]
Great!

**Review by sundy-li — APPROVED** [review]

**Comment by BohuTANG** [comment]
@mergify update

**Comment by BohuTANG** [comment]
@mergify update

**Comment by BohuTANG** [comment]
The Dev Linux / check CI failure was solved by https://github.com/datafuselabs/databend/pull/10190

**Pull request merged**
