### PR TITLE
fix(functions): optimize error message

### PR DESCRIPTION
**Pull request by hantmac**
Signed-off-by: hantmc <hantmac@outlook.com>

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Optimize error message.

## Changelog

- Improvement

## Related Issues

Fixes [#issue](https://github.com/datafuselabs/databend/issues/5635)

### CODE REVIEW

**Comment by hantmac** [comment]
Why I accept so many same notifications sent by mergify bot 😅

**Comment by Xuanwo** [comment]
> Why I accept so many same notifications sent by mergify bot sweat_smile

I don't know either. I have hidden them.

**Comment by Xuanwo** [comment]
Please also update unit tests:

```shell
---- users::user_mgr::test_user_manager_with_root_user stdout ----
thread 'users::user_mgr::test_user_manager_with_root_user' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<Code: 2201, displayText = only accept root from localhost, current: 'root'@'otherhost'.
>Code: 2201, displayText = only accept root from localhost 'root'@'otherhost'.
```

**Review by Xuanwo — APPROVED** [review]
Thanks for contribution!

**Pull request merged**
