### PR TITLE
chore: remove the static filter for merge into

### PR DESCRIPTION
**Pull request by JackTan25**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

Summary about this PR
* 1. I just add more comments and tests for cluster table, it's to prevent people from modifying the 
logic in the future.
* 2. remove static filter
- Closes #issue
#14014 

## Tests
- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14011)

### CODE REVIEW

**Comment by JackTan25** [comment]
wait https://github.com/datafuselabs/databend/issues/14014 to fix. cc @SkyFan2002  @dantengsky

**Comment by JackTan25** [comment]
@SkyFan2002 will remove static filter in the future. But let's fix this firstly.

**Review by dantengsky — DISMISSED** [review]

**Comment by JackTan25** [comment]
let me test cloud and check wizard cc @dantengsky @SkyFan2002

**Comment by BohuTANG** [comment]
Conflicting files
src/query/service/src/interpreters/interpreter_merge_into_static_filter.rs

**Comment by JackTan25** [comment]
The merge into wizard test result can see in https://github.com/datafuselabs/databend/pull/13950 (it removes static filter, but the pr is waiting this pr).

**Comment by BohuTANG** [comment]
This PR is important for the MERGEINTO performance, I modify the PR title to make it more sense.

**Comment by BohuTANG** [comment]
@dantengsky @JackTan25 
Can we don't remove the static filter(due to the performance) and design the new runtime filter? When new runtime filter is ready then remove the static filter.

**Comment by JackTan25** [comment]
> @dantengsky @JackTan25
> Can we don't remove the static filter(due to the performance) and design the new runtime filter? When new runtime filter is ready then remove the static filter.

we will dive into a trouble (the static filter implementation is hack, it can't pass the tests for this pr, maybe I can overcome these, but I'm not sure there could be many potential cases, however it can process some normal cases that we need for now).It's up to you, cc @dantengsky

**Review by dantengsky — DISMISSED** [review]

**Comment by dantengsky** [comment]
re-opened at https://github.com/datafuselabs/databend/pull/14092

**Pull request closed without merging**
