### PR TITLE
docs: use comma to separate connection parameters

### PR DESCRIPTION
**Pull request by soyeric128**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

I made a test with the latest version of Databend for what should be used to separate connection parameters. The following are my test results (on a local databend with MinIO), based on which I would suggest SPACES (instead of commas) for all scenarios:

- [**OK**]: COPY INTO books FROM 's3://databend/books.csv' CONNECTION = (ENDPOINT_URL = 'http://localhost:9000/' ACCESS_KEY_ID = 'ROOTUSER' SECRET_ACCESS_KEY = 'CHANGEME123' region = 'us-west-2') FILE_FORMAT = (type = CSV);

- [**ERROR**]: COPY INTO books FROM 's3://databend/books.csv' CONNECTION = (ENDPOINT_URL = 'http://localhost:9000/', ACCESS_KEY_ID = 'ROOTUSER', SECRET_ACCESS_KEY = 'CHANGEME123', region = 'us-west-2') FILE_FORMAT = (type = CSV);

- [**OK**]: CREATE STAGE my_minio_stage URL = 's3://databend' CONNECTION = (ENDPOINT_URL = 'http://localhost:9000/' ACCESS_KEY_ID = 'ROOTUSER' SECRET_ACCESS_KEY = 'CHANGEME123' region = 'us-west-2');

- [**ERROR**]: CREATE STAGE my_minio_stage URL = 's3://databend' CONNECTION = (ENDPOINT_URL = 'http://localhost:9000/', ACCESS_KEY_ID = 'ROOTUSER', SECRET_ACCESS_KEY = 'CHANGEME123', region = 'us-west-2');

- [**OK**]: SELECT $1 FROM 's3://databend' ( access_key_id => 'ROOTUSER', secret_access_key => 'CHANGEME123', endpoint_url => 'http://localhost:9000/', region => 'us-west-2', file_format => 'csv', files => ('books.csv'));

- [**OK**]: SELECT $1 FROM 's3://databend' ( access_key_id => 'ROOTUSER' secret_access_key => 'CHANGEME123' endpoint_url => 'http://localhost:9000/' region => 'us-west-2' file_format => 'csv' files => ('books.csv'));

- Closes #issue

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13055)

### CODE REVIEW

**Comment by youngsofun** [comment]
need some discuss： https://github.com/datafuselabs/databend/pull/12885

**Comment by youngsofun** [comment]
> As discussed , `commas` is more easy to use, let's keep it.

```
[ERROR]: COPY INTO books FROM 's3://databend/books.csv' CONNECTION = (ENDPOINT_URL = 'http://localhost:9000/', ACCESS_KEY_ID = 'ROOTUSER', SECRET_ACCESS_KEY = 'CHANGEME123', region = 'us-west-2') FILE_FORMAT = (type = CSV);
```

need to update code first.

**Comment by BohuTANG** [comment]
> > As discussed , `commas` is more easy to use, let's keep it.
> 
> ```
> [ERROR]: COPY INTO books FROM 's3://databend/books.csv' CONNECTION = (ENDPOINT_URL = 'http://localhost:9000/', ACCESS_KEY_ID = 'ROOTUSER', SECRET_ACCESS_KEY = 'CHANGEME123', region = 'us-west-2') FILE_FORMAT = (type = CSV);
> ```
> 
> need to update code first.

cc @andylokandy

**Comment by soyeric128** [comment]
> > As discussed , `commas` is more easy to use, let's keep it.
> 
> ```
> [ERROR]: COPY INTO books FROM 's3://databend/books.csv' CONNECTION = (ENDPOINT_URL = 'http://localhost:9000/', ACCESS_KEY_ID = 'ROOTUSER', SECRET_ACCESS_KEY = 'CHANGEME123', region = 'us-west-2') FILE_FORMAT = (type = CSV);
> ```
> 
> need to update code first.

Please let me know when the code work is complete.

**Comment by BohuTANG** [comment]
@soyeric128  We can continue this now

**Comment by soyeric128** [comment]
As I just tested with Databend 8.0.26-v1.2.148-nightly-6367d6e6a7(rust-1.72.0-nightly-2023-10-09T04:30:07.869462000Z), the following statements with commas now work perfectly:

COPY INTO books FROM 's3://databend/books.csv' CONNECTION = (ENDPOINT_URL = 'http://localhost:9000/', ACCESS_KEY_ID = 'ROOTUSER', SECRET_ACCESS_KEY = 'CHANGEME123', region = 'us-west-2') FILE_FORMAT = (type = CSV);

CREATE STAGE my_minio_stage URL = 's3://databend' CONNECTION = (ENDPOINT_URL = 'http://localhost:9000/', ACCESS_KEY_ID = 'ROOTUSER', SECRET_ACCESS_KEY = 'CHANGEME123', region = 'us-west-2');

**Review by BohuTANG — APPROVED** [review]
LGTM

**Pull request merged**
