### PR TITLE
refactor(query): improve performances for group by queries

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

- [x] use `build_keys_iter` to save allocators, this can improve group by single string query about 20%.
	e.g.  `select BrowserLanguage, sum(URLHash) from hits group by BrowserLanguage`	

- [x] Remove `HashMethodSingleString`, because it's already covered by `HashMethodSerializer`
- [x] Improve performance in  `HashMethodSerializer` about 10% ~ 30% in ontime dataset
- [x] Aovid extra allocation in  `HashMethodSerializer`  & `HashMethodFixedKeys` if there is only one non-nullable key.

Related #6367

### CODE REVIEW

**Comment by Xuanwo** [comment]
@sundy-li I have updated the title, welcome change it if doesn't meet your original idea.

**Comment by sundy-li** [comment]
Ontime results:

case | old | new
-- | -- | --
Q1 | 166.0 ms | 162.0 ms
Q2 | 236.9 ms | 234.0 ms
Q3 | 398.4 ms | 377.5 ms
Q4 | 5.0 ms | 5.5 ms
Q5 | 5.3 ms | 5.5 ms
Q6 | 484.1 ms | 387.1 ms
Q7 | 462.9 ms | 365.0 ms
Q8 | 549.5 ms | 517.1 ms
Q9 | 305.9 ms | 273.9 ms
Q10 | 467.9 ms | 475.5 ms
Q11 | 473.3 ms | 475.0 ms
Q12 | 4.535 s | 3.874 s
Q13 | 1.752 s | 1.460 s
Q14 | 5.2 ms | 5.3 ms
Q15 | 3.5 ms | 3.7 ms

</byte-sheet-html-origin>

Keep going to improve.

**Review by fkuner — COMMENTED** [review]
LGTM

**Review by fkuner — APPROVED** [review]

**Comment by sundy-li** [comment]
Failed tests are not related.

**Review by zhang2014 — APPROVED** [review]

**Pull request merged**
