### PR TITLE
chore(functions): make array get return null if out of bounds happens

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

chore(functions): make array get return null if out of bounds happens

## Changelog

 
- Improvement
 

## Related Issues

Fixes #issue

### CODE REVIEW

**Comment by b41sh** [comment]
LGTM

**Comment by BohuTANG** [comment]
CI failure:
```
--- /workspace/tests/suites/0_stateless/03_dml/03_0023_insert_into_array.result	2022-05-12 08:10:10.605451094 +0000
+++ /workspace/tests/suites/0_stateless/03_dml/03_0023_insert_into_array.stdout	2022-05-12 08:14:28.444629247 +0000
@@ -1,3 +1,4 @@
+ERROR 1105 (HY000) at line 140: Code: 1054, displayText = Expected server error code: 1006 but got: Ok..
 ==Array(UInt8)==
 1	[1, 2, 3]
 2	[254, 255]
```

https://github.com/datafuselabs/databend/runs/6402109779?check_suite_focus=true#step:3:424

**Comment by b41sh** [comment]
> 

this test case is ok now.
```sql
CREATE TABLE IF NOT EXISTS t15(id Int, arr Array(String) Null) Engine = Memory;

INSERT INTO t15 (id, arr) VALUES(1, ['aa', 'bb']), (2, ['cc', 'dd']), (3, null), (4, ['ee', 'ff']);

select * from t15;
select arr[0], arr[1] from t15; -- {ErrorCode 1006}
```

**Comment by BohuTANG** [comment]
@mergify update

**Comment by BohuTANG** [comment]
@mergify update

**Pull request merged**
