### PR TITLE
refactor: make block meta easier to be cloned

### PR DESCRIPTION
**Pull request by dantengsky**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

After reading `SegmentInfo` from storage,  block meta is owned by an `Arc<SegmentInfo>` (which may be cached). 
For situations that need block metas only, like pruning, we have no choice but to clone the block meta, which hurts the performance.

In this PR, changes SegmentInfo from

~~~
pub struct SegmentInfo {
   ....
    pub blocks: Vec<BlockMeta>,
   ....
}
~~~

to

~~~
pub struct SegmentInfo {
   ....
    pub blocks: Vec<Arc<BlockMeta>>,
   ....
}
~~~

and refactor related components accordingly.

Fixes #issue

### CODE REVIEW

**Comment by Xuanwo** [comment]
`BlockMeta` itself is cheap to be cloned. How about move `col_stats` & `col_metas` to `Arc<HashMap>` instead?

**Comment by dantengsky** [comment]
> `BlockMeta` itself is cheap to be cloned. 

according to @sundy-li 's profiling,  cloning of `BlockMeta` do hurt performance and highly likely hurts badly for the large tables.

> How about move `col_stats` & `col_metas` to `Arc<HashMap>` instead?

sounds reasonable to me. let's do the refactor if profiling identifies them to be bottlenecks.

**Comment by Xuanwo** [comment]
> cloning of `BlockMeta` do hurt performance and highly likely hurts badly for the large tables.

Yep. Most cost happened at the clone for hasmap.

**Review by sundy-li — APPROVED** [review]

**Comment by sundy-li** [comment]
It works

**Comment by BohuTANG** [comment]
Because we clone BlockMeta so the hashmap is cloned, and with this PR it will avoid.

**Review by BohuTANG — APPROVED** [review]

**Pull request merged**
