### PR TITLE
feat: Implement Default for CatalogInfo

### PR DESCRIPTION
**Pull request by Xuanwo**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

feat: Implement Default for CatalogInfo

## Tests

- [x] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [x] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15844)

### CODE REVIEW

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15844)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BohuTANG)

**Comment by Xuanwo** [comment]
Oh, I see. The commit is gone.

**Comment by Xuanwo** [comment]
Should fix by https://github.com/datafuselabs/databend/pull/15846

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15844)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BohuTANG)

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15844)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BohuTANG)

**Pull request merged**
