### PR TITLE
docs: Add language for code blocks

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

Add language hint for code blocks.

## Changelog

- Documentation

## Related Issues

Fixes https://github.com/datafuselabs/databend/discussions/3099#discussioncomment-1857559

### CODE REVIEW

**Comment by BohuTANG** [comment]
https://databend-git-fix-highlight-databend.vercel.app/user/sql-statement/aggregate-functions/aggregate-argmax

Some sql code block broken

**Comment by Xuanwo** [comment]
> https://databend-git-fix-highlight-databend.vercel.app/user/sql-statement/aggregate-functions/aggregate-argmax
> 
> Some sql code block broken

Fixed.

**Review by sundy-li — APPROVED** [review]

**Comment by sundy-li** [comment]
@Xuanwo  We should avoid pushing branches upstream. Better to make it in your forked repo.

**Comment by Xuanwo** [comment]
> @Xuanwo We should avoid pushing branches upstream. Better to make it in your forked repo.

Oh, it's a mistake. I will avoid it.

**Pull request merged**
