### PR TITLE
chore(query): fix table create time

### LINKED ISSUE #5996: table create time always  1970-01-01 00:00:00.000
**Summary**

```
mysql> select * from system.tables;
+--------------------+---------------+--------------------+-------------------------------+------------+----------+-----------+----------------------+------------+
| database           | name          | engine             | created_on                    | dropped_on | num_rows | data_size | data_compressed_size | index_size |
+--------------------+---------------+--------------------+-------------------------------+------------+----------+-----------+----------------------+------------+
| system             | roles         | SystemRoles        | 1970-01-01 00:00:00.000 +0000 | NULL       |     NULL |      NULL |                 NULL |       NULL |
| system             | tracing       | SystemTracing      | 1970-01-01 00:00:00.000 +0000 | NULL       |     NULL |      NULL |                 NULL |       NULL |
...
| default            | ck            | FUSE               | 1970-01-01 00:00:00.000 +0000 | NULL       |        0 |         0 |                    0 |       NULL |
| default            | objects_test1 | Fuse               | 1970-01-01 00:00:00.000 +0000 | NULL       |        0 |         0 |                    0 |       NULL |
| default            | tb2           | Fuse               | 1970-01-01 00:00:00.000 +0000 | NULL       |        7 |       156 |                 1225 |       NULL |
+--------------------+---------------+--------------------+-------------------------------+------------+----------+-----------+----------------------+------------+

```

cc @drmingdrmer @lichuang 

related issue:

https://github.com/databendcloud/databend-cloud-platform/issues/1365#issuecomment-1155930135

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Fixes #5996

### CODE REVIEW

**Comment by BohuTANG** [comment]
@mergify update

**Review by dantengsky — APPROVED** [review]
LGTM

**Comment by dantengsky** [comment]
oops...

stateless test case `./suites/gen/01_system/01_0001_system_tables`  and  ut `interpreters::interpreter_show_tab_stat::test_show_tab_stat_interpreter` should be adjusted thought

**Comment by BohuTANG** [comment]
10_0000_python_mysql_driver:                                            [ FAIL ] - return code 1
[402](https://github.com/datafuselabs/databend/runs/7211918068?check_suite_focus=true#step:3:413)
, result:
[403](https://github.com/datafuselabs/databend/runs/7211918068?check_suite_focus=true#step:3:414)
[404](https://github.com/datafuselabs/databend/runs/7211918068?check_suite_focus=true#step:3:415)
Traceback (most recent call last):
[405](https://github.com/datafuselabs/databend/runs/7211918068?check_suite_focus=true#step:3:416)
  File "/workspace/tests/suites/0_stateless/10_drivers/10_0000_python_mysql_driver.py", line 43, in <module>
[406](https://github.com/datafuselabs/databend/runs/7211918068?check_suite_focus=true#step:3:417)
    assert res == [('t1', 'BASE TABLE', 'db1', 'Fuse',
[407](https://github.com/datafuselabs/databend/runs/7211918068?check_suite_focus=true#step:3:418)
AssertionError: [('t1', 'BASE TABLE', 'db1', 'Fuse', '2022-07-06 10:22:21.478 +0000', 2, 296, 1816, None)]

**Comment by ZeaLoVe** [comment]
> select * from system.databases where name not like '%sys%' order by name;

means  sql ：select * from system.databases where name not like '%sys%' order by name;    get result showtabstat not in expect. Maybe the former test case need drop database showtabstat .

**Comment by BohuTANG** [comment]
The failures seem not related to this pr, please have a confirmation, so we can merge it  @sundy-li

**Comment by sundy-li** [comment]
> Maybe the former test case need drop database showtabstat .

I don't know where we missed dropping database `showtabstat`.

**Comment by sundy-li** [comment]
Related to sqlachemy, cc @youngsofun  

```
2022-07-07T12:35:59.970323Z  INFO databend_query::servers::http::clickhouse_handler: receive clickhouse http post, (query + body) = DROP DATABASE IF EXISTS showtabstat; FORMAT TabSeparatedWithNamesAndTypes
```

**Comment by ZeaLoVe** [comment]
> Related to sqlachemy, cc @youngsofun
> 
> ```
> 2022-07-07T12:35:59.970323Z  INFO databend_query::servers::http::clickhouse_handler: receive clickhouse http post, (query + body) = DROP DATABASE IF EXISTS showtabstat; FORMAT TabSeparatedWithNamesAndTypes
> ```

`WARNING:log:
Parsed Statement
    at_line: 19,
    s_type: Statement: query, type: skipped, query_type: skipped, retry: False,
    suite_name: gen/06_show/06_0008_show_table_status,
    text:
        SHOW TABLE STATUS;
    results: [None],
    runs_on: {'mysql', 'http'}, statement is skipped
INFO:log:Batch execute, suite name:gen/06_show/06_0009_show_schemas in file ./suites/gen/06_show/06_0009_show_schemas
INFO:log:executing statement, type ok
`
statement query skipped has bug，the following statament in file will be skipped。 Change to statement ok here，I will fix it later.

**Comment by sundy-li** [comment]
@mergfiy update

**Review by BohuTANG — APPROVED** [review]

**Pull request merged**
