### PR TITLE
feat(query):  add StageFileFormatType::Tsv.

### PR DESCRIPTION
**Pull request by youngsofun**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Fixes https://github.com/datafuselabs/databend/issues/6555

### CODE REVIEW

**Comment by youngsofun** [comment]
```
  running "/usr/local/bin/aarch64-linux-musl-cc" "src/smoke.c" "-o" "/dev/null" "-lz"
  running: "/usr/local/bin/aarch64-linux-musl-cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src/zlib" "-fvisibility=hidden" "-DSTDC" "-D_LARGEFILE64_SOURCE" "-D_POSIX_SOURCE" "-o" "/workspace/target/debug/build/libz-sys-89ae92780d381752/out/lib/src/zlib/adler32.o" "-c" "src/zlib/adler32.c"
  cargo:warning=aarch64-linux-musl-cc: error: unrecognized command line option ‘-m64’
  exit status: 1
  running: "/usr/local/bin/aarch64-linux-musl-cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src/zlib" "-fvisibility=hidden" "-DSTDC" "-D_LARGEFILE64_SOURCE" "-D_POSIX_SOURCE" "-o" "/workspace/target/debug/build/libz-sys-89ae92780d381752/out/lib/src/zlib/compress.o" "-c" "src/zlib/compress.c"
  cargo:warning=aarch64-linux-musl-cc: error: unrecognized command line option ‘-m64’
  exit status: 1
  --- stderr
  src/smoke.c:1:10: fatal error: zlib.h: No such file or directory
      1 | #include <zlib.h>
        |          ^~~~~~~~
  compilation terminated.
  error occurred: Command "/usr/local/bin/aarch64-linux-musl-cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src/zlib" "-fvisibility=hidden" "-DSTDC" "-D_LARGEFILE64_SOURCE" "-D_POSIX_SOURCE" "-o" "/workspace/target/debug/build/libz-sys-89ae92780d381752/out/lib/src/zlib/adler32.o" "-c" "src/zlib/adler32.c" with args "aarch64-linux-musl-cc" did not execute successfully (status code exit status: 1).

```

**Comment by BohuTANG** [comment]
It would be better to have a stateful test for the tsv format, what do you think? @youngsofun

**Comment by youngsofun** [comment]
OK I was going to but find tsv itself need some fix

i can add a simple tsv first

**Review by Xuanwo — APPROVED** [review]
Great!

**Review by BohuTANG — APPROVED** [review]

**Pull request merged**
