### PR TITLE
fix(datatypes): fix datetime from negative micro timestamp bug

### LINKED ISSUE #5346: Returns error when creating a table on not support keyword
**Summary**

```
mysql> create table t1(a INT auto_increment);
Query OK, 0 rows affected (0.07 sec)
Read 0 rows, 0.00 B in 0.023 sec., 0 rows/sec., 0.00 B/sec.
```

`auto_increment` should return an error to the client.

### LINKED ISSUE #5397: bug: convert from negative timestamp panics
**Summary**

```
select '1022-05-16 03:25:02.868894'::TIMESTAMP;
```

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

1. Fix bug of Timestamp value convert from negative micro timestamp
2. Throw exceptions if column option is not supported

## Changelog

 
- Bug Fix
 

## Related Issues

Fixes #5397
Fixes #5346

### CODE REVIEW

**Review by Veeupup — APPROVED** [review]
LGTM!

**Review by BohuTANG — APPROVED** [review]

**Comment by fkuner** [comment]
LGTM

**Comment by fkuner** [comment]
hava a question about `select '1022-05-16 03:25:02.868894'::TIMESTAMP;`

why the micro second is negative?

**Comment by sundy-li** [comment]
You will know if you query`select 0::TIMESTAMP`.

**Comment by fkuner** [comment]
Get it.

**Pull request merged**
