### PR TITLE
Datavalues2: date: today yesterday and tomorrow

### LINKED ISSUE #3970: datavalues2 && date functions

### PR DESCRIPTION
**Pull request by LiuYuHui**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Migrate some date functions into datavalues2

## Changelog

- New Feature

## Related Issues

Fixes #3970 

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by Veeupup** [comment]
/LGTM 
thank you : D !  @LiuYuHui

**Comment by Veeupup** [comment]
@LiuYuHui  it seems unit test not pass, maybe you can check it.

**Comment by PsiACE** [comment]
In stateless test:

```
 --- /home/runner/work/databend/databend/tests/suites/0_stateless/11_0001_show_functions.result	2022-01-26 13:24:31.493804554 +0000
+++ /home/runner/work/databend/databend/tests/suites/0_stateless/11_0001_show_functions.stdout	2022-01-26 13:28:05.755838253 +0000
@@ -1,8 +1,6 @@
-today	1	0		
 todayofmonth	1	0		
 todayofweek	1	0		
 todayofyear	1	0		
-today	1	0		
 todayofmonth	1	0		
 todayofweek	1	0		
 todayofyear	1	0	
```

**Comment by sundy-li** [comment]
@LiuYuHui 

Try to modify `registered_names` in https://github.com/datafuselabs/databend/blob/bf372ee302df756d20c839c3e75e2104a2538d8b/common/functions/src/scalars/function_factory.rs   to chain the names of Function2Factory.

**Pull request merged**
