### PR TITLE
feat(planner): [WIP] Push limit down further

### LINKED ISSUE #6865: Feature: LIMIT push down for new planner
In some cases, it's possible to push the `LIMIT` operator down to reduce the data to be processed.

Besides, `LIMIT` hint of `ReadDataSource` will affect the behavior of `Random` table engine.

### PR DESCRIPTION
**Pull request by AngleNet**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Push limit down over sort, outer join, project, scan.

Fixes #6865

### CODE REVIEW

**Comment by sundy-li** [comment]
@AngleNet  How is it going? We are waiting for this optimizer now.

**Comment by AngleNet** [comment]
I think it is almost there and still need to fix CI failures. I think you could take it over. I really want to finish this, however I do not have much time to working on this at a regular pace.

**Comment by sundy-li** [comment]
> I think it is almost there and still need to fix CI failures. I think you could take it over. I really want to finish this, however I do not have much time to working on this at a regular pace.

Ok, @TCeason will help to finish the ci tests.

**Comment by drmingdrmer** [comment]
- `main` branch is force pushed, update your working branch please: #7261

**Comment by TCeason** [comment]
Close this pr and will finish in https://github.com/datafuselabs/databend/pull/7273. Thanks for AngleNet's contribution. Waiting for your new pr.

Be smooth sailing in life :) :+1:

**Pull request closed without merging**
