### PR TITLE
chore(ci): add label with pr title

### PR DESCRIPTION
**Pull request by everpcpc**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Using GitHub Actions instead of `Mergify` to add labels could avoid trigging additional CI workflow.

- Closes #issue

### CODE REVIEW

**Comment by BohuTANG** [comment]
askbend:summary

**Comment by BohuTANG** [comment]
## PR Summary(By [llmchain.rs](https://github.com/shafishlabs/llmchain.rs)):
* **Modify Mergify.yml**
The `pull_request_rules` section has been modified by commenting out various rules related to PR conflicts, description, semantic check, and labeling on different types of PRs.

* **Extract Information from PR Title**
Added code to extract information from the pull request title and assign labels accordingly using a switch statement.

* **Add Labels to PR**
Added code to add labels to pull requests using GitHub REST API. 

These changes modify the rules and add functionality to automatically label pull requests based on their type and title.

**Comment by everpcpc** [comment]
askbend:summary

**Comment by BohuTANG** [comment]
## PR Summary(By [llmchain.rs](https://github.com/shafishlabs/llmchain.rs)):
* **Disable Mergify Rules**
The Mergify rules for PR conflicts, CLA check, semantic PR check, and labeling have been commented out in the .github/mergify.yml file.

* **Add Python Bindings Workflow**
A new workflow file for Python bindings has been added in .github/workflows/bindings_python.yml. It includes a job to publish to PyPI and a condition to check if the event is not a pull request. The parameter name `skip-existing` has been changed to `skip_existing`.

* **Modify PR Validation Script**
The script to validate the pull request title has been modified in .github/workflows/pr.yml. A switch case has been added to assign labels based on the pull request type, and a new step has been added to add labels to the pull request.

* **Delete Benchmark Script**
The benchmark script benchmark_cloud.sh in benchmark/clickbench has been modified to remove a line that drops the warehouse and to create a warehouse with a cache size parameter.

**Review by Xuanwo — APPROVED** [review]
Cool!

**Pull request merged**
