### PR TITLE
[query] Add config for enable/disable github table engine

### PR DESCRIPTION
**Pull request by Junnplus**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

- Add `table_engine_github_enabled` config.
- Uniform env config for table engine.

## Changelog

- New Feature

## Related Issues

Fixes [#issue](https://github.com/datafuselabs/databend/issues/3205)

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Comment by sundy-li** [comment]
How about grouping these enable/disable as a group config? 

Such as  `struct Features` ?

**Comment by zhang2014** [comment]
Why don't we use conditional compilation? such as: `cargo features`

**Comment by BohuTANG** [comment]
> Why don't we use conditional compilation? such as: `cargo features`

Good idea.

**Comment by Junnplus** [comment]
@zhang2014 @BohuTANG Do we need to support in this pr, or open an issue to discuss?

**Comment by zhang2014** [comment]
Maybe we can merge this PR and then implement it in another pr? CC: @BohuTANG

**Pull request merged**
